### ISSUE TITLE
seaweed s3 list_buckets

### ISSUE THREAD

**Issue by dorsany** [chrislusf/seaweedfs#1064]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
I'm using s3 gateway and python boto3 and while trying to list all buckets I'm getting the error:
```
>>> kwrgs =  {'endpoint_url': 'http://seaweedfs-s3.default.svc.cluster.local:8333', 'aws_access_key_id': 'accessKey1', 'aws_secret_access_key': 'secretKey1'}
>>> import boto3
>>> cli = boto3.client('s3', **kwrgs)
>>> cli.list_buckets()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InternalError) when calling the ListBuckets operation (reached max retries: 4): We encountered an internal error, please try again.
```

I Found only Errors in the s3 gateway:
```
I0916 09:49:36 1 config.go:25] Reading security.toml from
I0916 09:49:36 1 config.go:28] Reading : Config File "security" Not Found in "[/ /root/.seaweedfs /etc/seaweedfs]"
I0916 09:49:36 1 s3.go:92] Start Seaweed S3 API Server 30GB 1.43 at http port 8333
I0916 09:50:58 1 filer_util.go:89] read directory: directory:"/buckets" limit:2147483647
I0916 09:51:18 1 s3api_handlers.go:78] status 500 application/xml: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Resource>/</Resource><RequestId>1568627478252701334</RequestId></Error>
I0916 09:51:19 1 filer_util.go:89] read directory: directory:"/buckets" limit:2147483647
I0916 09:51:39 1 s3api_handlers.go:78] status 500 application/xml: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Resource>/</Resource><RequestId>1568627499203098406</RequestId></Error>
I0916 09:51:40 1 filer_util.go:89] read directory: directory:"/buckets" limit:2147483647
I0916 09:52:00 1 s3api_handlers.go:78] status 500 application/xml: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Resource>/</Resource><RequestId>1568627520693419381</RequestId></Error>
I0916 09:52:02 1 filer_util.go:89] read directory: directory:"/buckets" limit:2147483647
I0916 09:52:22 1 s3api_handlers.go:78] status 500 application/xml: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Resource>/</Resource><RequestId>1568627542703114894</RequestId></Error>
I0916 09:52:30 1 filer_util.go:89] read directory: directory:"/buckets" limit:2147483647
I0916 09:52:50 1 s3api_handlers.go:78] status 500 application/xml: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Resource>/</Resource><RequestId>1568627570429772055</RequestId></Error
```

FYI :
The ```weed shell``` can return the ```colletion.list``` and ```fs.tree``` without any issue
The s3cmd can't list buckets too
put file is working: ```cli.put_object(Bucket='test', Key='test', Body='test')```. output:
```
{'ResponseMetadata': {'RequestId': '1568620869872887033', 'HostId': '', 'HTTPStatusCode': 200, 'HTTPHeaders': {'accept-ranges': 'bytes', 'etag': '"098f6bcd4621d373cade4e832627b4f6"', 'x-amz-request-id': '1568620869872887033', 'date': 'Mon, 16 Sep 2019 08:01:09 GMT', 'content-length': '0'}, 'RetryAttempts': 0}, 'ETag': '"098f6bcd4621d373cade4e832627b4f6"'}
```

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount":
```
/usr/bin/weed -v=4 s3 -port=8333 -filer.dir.buckets=/buckets -filer=seaweedfs-filer.default:8888

/usr/bin/weed -v=4 master -port=9333 -mdir=/data -ip.bind=0.0.0.0 -volumeSizeLimitMB=30000 -defaultReplication=000 -ip=seaweedfs-master-0.seaweedfs-master -peers=seaweedfs-master-0.seaweedfs-master:9333

/usr/bin/weed -v=4 volume -port=8080 -dir=/data -max=1000 -ip.bind=0.0.0.0 -read.redirect=true -ip=10.244.83.158 -mserver=seaweedfs-master-0.seaweedfs-master:9333

/usr/bin/weed -v=4 filer -port=8888 -dirListLimit=100000 -ip=10.244.83.155 -master=seaweedfs-master-0.seaweedfs-master:9333

```
- OS version: ```Ubuntu 18.04.2 LTS```
- output of `weed version`: ```version 30GB 1.43 linux amd64```
- if using filer, show the content of `filer.toml`

```
# A sample TOML config file for SeaweedFS filer store
# Used with "weed filer" or "weed server -filer"

[memory]
# local in memory, mostly for testing purpose
enabled = false

[leveldb]
# local on disk, mostly for simple single-machine setup, fairly scalable
enabled = false
dir = "/data"                                   # directory to store level db files

[leveldb2]
# local on disk, mostly for simple single-machine setup, fairly scalable
enabled = true
dir = "/data/filerldb2"                                 # directory to store level db 2 files

####################################################
# multiple filers on shared storage, fairly scalable
####################################################

[mysql]
# CREATE TABLE IF NOT EXISTS filemeta (
#   dirhash     BIGINT         COMMENT 'first 64 bits of MD5 hash value of directory field',
#   name        VARCHAR(1000)  COMMENT 'directory or file name',
#   directory   TEXT           COMMENT 'full path to parent directory',
#   meta        BLOB,
#   PRIMARY KEY (dirhash, name)
# ) DEFAULT CHARSET=utf8;

enabled = false
hostname = "localhost"
port = 3306
username = "root"
password = ""
database = ""              # create or use an existing database
connection_max_idle = 2
connection_max_open = 100

[postgres]
# CREATE TABLE IF NOT EXISTS filemeta (
#   dirhash     BIGINT,
#   name        VARCHAR(65535),
#   directory   VARCHAR(65535),
#   meta        bytea,
#   PRIMARY KEY (dirhash, name)
# );
enabled = false
hostname = "localhost"
port = 5432
username = "postgres"
password = ""
database = ""              # create or use an existing database
sslmode = "disable"
connection_max_idle = 100
connection_max_open = 100

[cassandra]
# CREATE TABLE filemeta (
#    directory varchar,
#    name varchar,
#    meta blob,
#    PRIMARY KEY (directory, name)
# ) WITH CLUSTERING ORDER BY (name ASC);
enabled = false
keyspace="seaweedfs"
hosts=[
        "localhost:9042",
]

[redis]
enabled = false
address  = "localhost:6379"
password = ""
db = 0

[redis_cluster]
enabled = false
addresses = [
    "localhost:30001",
    "localhost:30002",
    "localhost:30003",
    "localhost:30004",
    "localhost:30005",
    "localhost:30006",
]
```

**Expected behavior**
List all buckets when has only 1 bucket using python boto3

**Comment by chrislusf** [comment]
My local is working fine.

```
$ aws --endpoint-url http://localhost:8333 s3 ls
Unable to locate credentials. You can configure credentials by running "aws configure".
$ aws configure
AWS Access Key ID [None]: any
AWS Secret Access Key [None]: any
Default region name [None]: us-east-1
Default output format [None]:
$ aws configure set default.s3.signature_version s3v4
$ aws --endpoint-url http://localhost:8333 s3 ls
$ aws --endpoint-url http://localhost:8333 s3 mb s3://newbucket3
make_bucket: newbucket3
$ aws --endpoint-url http://localhost:8333 s3 ls
2019-09-16 08:05:47 newbucket3
$ python
Python 2.7.16 (default, Mar  4 2019, 09:01:38)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named boto3
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>> exit()
$ pip install boto3
Collecting boto3
  Downloading https://pypi.uberinternal.com/packages/16/e4/91e772079f1a5f48262da2d47136eb96a14348f320a96382ecff3aaaf7c9/boto3-1.9.228-py2.py3-none-any.whl (128kB)
    100% |████████████████████████████████| 133kB 480kB/s
Collecting botocore<1.13.0,>=1.12.228 (from boto3)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://pypi.uberinternal.com/packages/f7/5c/b66a2241e5030c491f982c6b9646c008559aa7cd7f4448f643e8ed9f15e5/botocore-1.12.228-py2.py3-none-any.whl (5.7MB)
    100% |████████████████████████████████| 5.7MB 258kB/s
Collecting jmespath<1.0.0,>=0.7.1 (from boto3)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://pypi.uberinternal.com/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Collecting s3transfer<0.3.0,>=0.2.0 (from boto3)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://pypi.uberinternal.com/packages/16/8a/1fc3dba0c4923c2a76e1ff0d52b305c44606da63f718d14d3231e21c51b0/s3transfer-0.2.1-py2.py3-none-any.whl (70kB)
    100% |████████████████████████████████| 71kB 344kB/s
Collecting docutils<0.16,>=0.10 (from botocore<1.13.0,>=1.12.228->boto3)
  Downloading https://pypi.uberinternal.com/packages/3a/dc/bf2b15d1fa15a6f7a9e77a61b74ecbbae7258558fcda8ffc9a6638a6b327/docutils-0.15.2-py2-none-any.whl (548kB)
    100% |████████████████████████████████| 552kB 1.9MB/s
Requirement already satisfied: python-dateutil<3.0.0,>=2.1; python_version >= "2.7" in /usr/local/lib/python2.7/site-packages/python_dateutil-2.8.0-py2.7.egg (from botocore<1.13.0,>=1.12.228->boto3)
Requirement already satisfied: urllib3<1.26,>=1.20; python_version == "2.7" in /usr/local/lib/python2.7/site-packages (from botocore<1.13.0,>=1.12.228->boto3)
Collecting futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" (from s3transfer<0.3.0,>=0.2.0->boto3)
  Downloading https://pypi.uberinternal.com/packages/d8/a6/f46ae3f1da0cd4361c344888f59ec2f5785e69c872e175a748ef6071cdb5/futures-3.3.0-py2-none-any.whl
Requirement already satisfied: six>=1.5 in /usr/local/lib/python2.7/site-packages (from python-dateutil<3.0.0,>=2.1; python_version >= "2.7"->botocore<1.13.0,>=1.12.228->boto3)
Installing collected packages: docutils, jmespath, botocore, futures, s3transfer, boto3
Successfully installed boto3-1.9.228 botocore-1.12.228 docutils-0.15.2 futures-3.3.0 jmespath-0.9.4 s3transfer-0.2.1
$ python
Python 2.7.16 (default, Mar  4 2019, 09:01:38)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> kwrgs =  {'endpoint_url': 'http://localhost:8333', 'aws_access_key_id': 'accessKey1', 'aws_secret_access_key': 'secretKey1'}
>>> cli = boto3.client('s3', **kwrgs)
>>> cli.list_buckets()
{u'Owner': {u'DisplayName': '', u'ID': ''}, u'Buckets': [{u'CreationDate': datetime.datetime(2019, 9, 16, 8, 5, 47, tzinfo=tzoffset(None, -25200)), u'Name': 'newbucket3'}], 'ResponseMetadata': {'HTTPStatusCode': 200, 'RetryAttempts': 0, 'HostId': '', 'RequestId': '1568646520764307000', 'HTTPHeaders': {'date': 'Mon, 16 Sep 2019 15:08:40 GMT', 'transfer-encoding': 'chunked', 'accept-ranges': 'bytes', 'x-amz-request-id': '1568646520764307000', 'content-type': 'application/xml'}}}
```

**Comment by chrislusf** [comment]
I could not tell yet, and added one line of log. in https://github.com/chrislusf/seaweedfs/compare/ad3efbb19796...20ae55943758

Is it possible for you to build and test it out?

**Comment by dorsany** [comment]
This is the error after using the ```weed``` from the commit above:
```
# /usr/bin/weed -v=4 s3 \
>         -port=8333 \
>         -filer.dir.buckets=/buckets \
>         -filer=seaweedfs-filer.${NAMESPACE}:8888
I0916 21:45:19    41 config.go:25] Reading security.toml from
I0916 21:45:19    41 config.go:28] Reading : Config File "security" Not Found in "[/ /root/.seaweedfs /etc/seaweedfs]"
I0916 21:45:19    41 s3.go:92] Start Seaweed S3 API Server 30GB 1.43 at http port 8333
I0916 21:47:35    41 filer_util.go:91] read directory: directory:"/buckets" limit:2147483647
I0916 21:47:55    41 filer_util.go:94] read directory directory:"/buckets" limit:2147483647 : rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 10.100.169.207:18888: i/o timeout"
I0916 21:47:55    41 s3api_handlers.go:78] status 500 application/xml: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Resource>/</Resource><RequestId>1568670475682473758</RequestId></Error>
I0916 21:47:56    41 filer_util.go:91] read directory: directory:"/buckets" limit:2147483647
I0916 21:48:16    41 filer_util.go:94] read directory directory:"/buckets" limit:2147483647 : rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 10.100.169.207:18888: i/o timeout"
I0916 21:48:16    41 s3api_handlers.go:78] status 500 application/xml: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Resource>/</Resource><RequestId>1568670496253963492</RequestId></Error>
I0916 21:48:17    41 filer_util.go:91] read directory: directory:"/buckets" limit:2147483647
I0916 21:48:37    41 filer_util.go:94] read directory directory:"/buckets" limit:2147483647 : rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 10.100.169.207:18888: i/o timeout"
I0916 21:48:37    41 s3api_handlers.go:78] status 500 application/xml: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Resource>/</Resource><RequestId>1568670517598209468</RequestId></Error>
I0916 21:48:40    41 filer_util.go:91] read directory: directory:"/buckets" limit:2147483647
I0916 21:49:00    41 filer_util.go:94] read directory directory:"/buckets" limit:2147483647 : rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 10.100.169.207:18888: i/o timeout"
I0916 21:49:00    41 s3api_handlers.go:78] status 500 application/xml: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Resource>/</Resource><RequestId>1568670540693922394</RequestId></Error>
```

From The error is seems that the s3 gateway doesn't has connectivity to the filer 

but ```ping``` is working from s3 to filer
```
# ping seaweedfs-filer-0.seaweedfs-filer
PING seaweedfs-filer-0.seaweedfs-filer (10.244.14.107): 56 data bytes
64 bytes from 10.244.14.107: seq=0 ttl=64 time=0.100 ms
```
also ports are open:
```
# nc -zv seaweedfs-filer-0.seaweedfs-filer 8888
seaweedfs-filer-0.seaweedfs-filer (10.244.14.107:8888) open

# nc -zv seaweedfs-filer-0.seaweedfs-filer 18888
seaweedfs-filer-0.seaweedfs-filer (10.244.14.107:18888) open
```

also ```wget``` for port ```8888```:
```
# wget seaweedfs-filer-0.seaweedfs-filer:8888
Connecting to seaweedfs-filer-0.seaweedfs-filer:8888 (10.244.14.107:8888)
index.html           100% |*************************************************************************|  2337  0:00:00 ETA
```
but not for port ```18888```:
```
# wget seaweedfs-filer-0.seaweedfs-filer:18888
Connecting to seaweedfs-filer-0.seaweedfs-filer:18888 (10.244.14.107:18888)
wget: error getting response: Connection reset by peer
```

```netstat``` in filer:
```
# netstat -plntu
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 10.244.14.107:8888      0.0.0.0:*               LISTEN      1/weed
tcp        0      0 :::18888                :::*                    LISTEN      1/weed
```

any idea?

**Comment by dorsany** [comment]
Found the problem. related to issue that the grpc ports especially 18888 was blocked. After fix it also the list buckets worked(and not just put). It will be amazing if we will be able to get this information from the log error because i/o error can be a bit confusing
