### ISSUE TITLE
ec.balance not working

### ISSUE THREAD

**Issue by steven2612** [chrislusf/seaweedfs#1111]
**Describe the bug**
After recompiling the weed binary with the actual snapshot the binary fixes the last issues (problem with redirect, problem with some ec encoded files)
but now i could see some of the ec.shards are not distributed in the right way (5 volume servers).
for example volume 59:
```
bm6: 59		3146776576 Bytes	[0 1 2 3]	06 Nov 19 11:08 +0100
bm8: 59		3146776576 Bytes	[0 1 2 3 4 5 6 7 8 9 10]	06 Nov 19 11:06 +0100
bm9: 59		3146776576 Bytes	[4]	06 Nov 19 11:08 +0100
bm2: 59		3146776576 Bytes	[11 12 13]	06 Nov 19 10:29 +0100
bm7: 59		3146776576 Bytes	[5 6 7]	06 Nov 19 11:08 +0100
```

i dont know why those shards had been created this way (when doing ec.encode all volume servers had been up and those should be distributed equally) but i wanted to fix it with weed shell - ec.balance -force

but ec.balance -force only says:
```
balanceEcVolumes collections 1
balanceEcVolumes collection 
balanceEcVolumes 
bm7:8280 has 1 overlimit, moving ec shard 15.4
bm7:8280 has 1 overlimit, moving ec shard 60.6
bm2:8280 has 2 overlimit, moving ec shard 56.0
bm2:8280 has 1 overlimit, moving ec shard 56.1
bm6:8280 has 1 overlimit, moving ec shard 59.0
```
and seems to be doing nothing.

weed master is also configured to do:
```
[master.maintenance]
# periodically run these scripts are the same as running them from 'weed shell'
scripts = """
  ec.encode -fullPercent=95 -quietFor=1h
  ec.rebuild -force
  ec.balance -force
  volume.balance -force
"""
sleep_minutes = 17          # sleep minutes between each script execution
```
is balancing maybe running currently in the background ? how to check this ? i did not see anything in the logfiles ...

**System Setup**
weed version: version 30GB 1.44 linux amd64
but as stated recompiled with the latest git snapshot
OS Version - mixed Ubuntu Server 14.04 and 18.04

**Expected behavior**
- doing a rebalance
- some sort of status message if something is running in the background - either in `weed shell` or in the web status screen - or in both ;)

additionally ec.rebuild says:
error: disk space is not enough
but on all (weed) disks there is plenty of storage free - or is here another path used - for example /tmp ?

**Comment by chrislusf** [comment]
Hard to tell. Need more info.

**Comment by steven2612** [comment]
hard to tell which informations will help you ...

i just did one more test - isolated as example volume 59 - and run locally master + 5 volumes

this is what i get when running weed shell ec.balance:

```
weed shell -master localhost:9500                                                                                                     
I1110 12:43:18 32615 config.go:28] Reading : Config File "security" Not Found in "[/mfs/weedtest /root/.seaweedfs /etc/seaweedfs]"
> volume.balance
> ec.balance
balanceEcVolumes collections 1
balanceEcVolumes collection 
balanceEcVolumes 
ec shard 59.0 has 2 copies, keeping 127.0.0.1:9506
ec shard 59.1 has 2 copies, keeping 127.0.0.1:9506
ec shard 59.2 has 2 copies, keeping 127.0.0.1:9506
ec shard 59.3 has 2 copies, keeping 127.0.0.1:9506
ec shard 59.4 has 2 copies, keeping 127.0.0.1:9509
ec shard 59.5 has 2 copies, keeping 127.0.0.1:9507
ec shard 59.6 has 2 copies, keeping 127.0.0.1:9507
ec shard 59.7 has 2 copies, keeping 127.0.0.1:9507
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1531c44]

goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/shell.doBalanceEcShardsAcrossRacks(0x2230240, 0xc000042068, 0xc00034e460, 0x0, 0x0, 0x3b, 0xc0003638c0, 0x5, 0x8, 0xc00035f260, ...)
        /mfs/src/github/seaweedfs/weed/shell/command_ec_balance.go:270 +0x714
github.com/chrislusf/seaweedfs/weed/shell.balanceEcShardsAcrossRacks(0x2230240, 0xc000042068, 0xc00034e460, 0xc000458480, 0x5, 0x8, 0xc00035f260, 0x0, 0x0, 0x0, ...)
        /mfs/src/github/seaweedfs/weed/shell/command_ec_balance.go:235 +0x13e
github.com/chrislusf/seaweedfs/weed/shell.balanceEcVolumes(0xc00034e460, 0x0, 0x0, 0xc000458480, 0x5, 0x8, 0xc00035f260, 0x0, 0x0, 0x0)
        /mfs/src/github/seaweedfs/weed/shell/command_ec_balance.go:173 +0x2c7
github.com/chrislusf/seaweedfs/weed/shell.(*commandEcBalance).Do(0x3451d00, 0x3451d00, 0x0, 0x0, 0xc00034e460, 0x21f03c0, 0xc000010018, 0xa, 0x0)
        /mfs/src/github/seaweedfs/weed/shell/command_ec_balance.go:131 +0x5f8
github.com/chrislusf/seaweedfs/weed/shell.RunShell(0xc000367e80, 0x21ef320, 0xc0005f8128, 0x1e72ee6, 0x9, 0x22b8, 0x1e72ef4, 0x1)
        /mfs/src/github/seaweedfs/weed/shell/shell_liner.go:70 +0x5c0
github.com/chrislusf/seaweedfs/weed/command.runShell(0x3305b80, 0xc00003c130, 0x0, 0x0, 0x0)
        /mfs/src/github/seaweedfs/weed/command/shell.go:46 +0x23e
main.main()
        /mfs/src/github/seaweedfs/weed/weed.go:66 +0x2f9
```

next i will test with official 1.44 client if i can reproduce this ...

**Comment by chrislusf** [comment]
Added a fix for the nil exception.

You may need to run `ec.balance -force` several times to achieve balance. See the command_ec_balace.go code for details.

**Comment by steven2612** [comment]
but `ec.balance -force` seems to do nothing - it prints out the message and 
immediately returns. no entry in logfile.
but now i let it run a few hours without doing anything and it nearly distributes evenly.
only 59.ec04 is double (bm8 and bm9)
log says:
master:
`I1110 15:10:29 19756 master_server.go:224] error: balance across racks collection  ec shards: copy 59.[4] 127.0.0.1:9509 => 127.0.0.1:9508 : rpc error: code = Unknown desc = VolumeEcShardsCopy volume 59: failed to copy bm8/59.ecj file: receiving bm8/59.ecj: rpc error: code = Unknown desc = CopyFile not found ec volume id 59`
bm8:
```
I1110 13:27:53 31512 store_ec.go:85] UnmountEcShards 59.0
I1110 13:27:53 31512 store_ec.go:85] UnmountEcShards 59.1
I1110 13:27:53 31512 store_ec.go:85] UnmountEcShards 59.2
I1110 13:27:53 31512 store_ec.go:85] UnmountEcShards 59.3
I1110 13:27:53 31512 store_ec.go:85] UnmountEcShards 59.4
I1110 13:27:53 31512 store_ec.go:85] UnmountEcShards 59.5
I1110 13:27:53 31512 store_ec.go:85] UnmountEcShards 59.6
I1110 13:27:53 31512 store_ec.go:85] UnmountEcShards 59.7
I1110 13:27:53 31512 store_ec.go:85] UnmountEcShards 59.8
I1110 13:27:53 31512 store_ec.go:85] UnmountEcShards 59.9
I1110 13:27:53 31512 store_ec.go:85] UnmountEcShards 59.10
I1110 13:27:53 31512 volume_grpc_copy.go:147] writing to bm8/59.ec04
I1110 13:30:09 31512 volume_grpc_copy.go:147] writing to bm8/59.ecx
I1110 13:30:13 31512 volume_grpc_copy.go:147] writing to bm8/59.ecj
I1110 13:30:13 31512 volume_grpc_copy.go:147] writing to bm8/59.ec04
I1110 13:32:13 31512 volume_grpc_copy.go:147] writing to bm8/59.ecx
I1110 13:32:14 31512 volume_grpc_copy.go:147] writing to bm8/59.ecj
I1110 13:43:19 31512 volume_grpc_copy.go:147] writing to bm8/59.ec04
I1110 13:45:17 31512 volume_grpc_copy.go:147] writing to bm8/59.ecx
I1110 13:45:18 31512 volume_grpc_copy.go:147] writing to bm8/59.ecj
I1110 14:00:19 31512 volume_grpc_copy.go:147] writing to bm8/59.ec04
I1110 14:02:39 31512 volume_grpc_copy.go:147] writing to bm8/59.ecx
I1110 14:02:40 31512 volume_grpc_copy.go:147] writing to bm8/59.ecj
I1110 14:17:19 31512 volume_grpc_copy.go:147] writing to bm8/59.ec04
I1110 14:19:22 31512 volume_grpc_copy.go:147] writing to bm8/59.ecx
I1110 14:19:23 31512 volume_grpc_copy.go:147] writing to bm8/59.ecj
I1110 14:34:19 31512 volume_grpc_copy.go:147] writing to bm8/59.ec04
I1110 14:36:25 31512 volume_grpc_copy.go:147] writing to bm8/59.ecx
I1110 14:36:25 31512 volume_grpc_copy.go:147] writing to bm8/59.ecj
I1110 14:51:19 31512 volume_grpc_copy.go:147] writing to bm8/59.ec04
I1110 14:53:32 31512 volume_grpc_copy.go:147] writing to bm8/59.ecx
I1110 14:53:36 31512 volume_grpc_copy.go:147] writing to bm8/59.ecj
I1110 15:08:19 31512 volume_grpc_copy.go:147] writing to bm8/59.ec04
I1110 15:10:29 31512 volume_grpc_copy.go:147] writing to bm8/59.ecx
I1110 15:10:29 31512 volume_grpc_copy.go:147] writing to bm8/59.ecj
I1110 15:25:19 31512 volume_grpc_copy.go:147] writing to bm8/59.ec00
I1110 15:28:42 31512 volume_grpc_copy.go:147] writing to bm8/59.ecx
I1110 15:28:44 31512 volume_grpc_copy.go:147] writing to bm8/59.ecj
I1110 15:28:44 31512 store_ec.go:51] MountEcShards 59.0
```
bm9:
```
I1110 12:35:19 19783 volume_grpc_copy.go:147] writing to bm9/59.ec00
I1110 12:38:54 19783 volume_grpc_copy.go:147] writing to bm9/59.ec01
I1110 12:41:44 19783 volume_grpc_copy.go:147] writing to bm9/59.ec02
I1110 12:44:19 19783 volume_grpc_copy.go:147] writing to bm9/59.ec03
I1110 12:47:13 19783 volume_grpc_copy.go:147] writing to bm9/59.ec05
I1110 12:50:17 19783 volume_grpc_copy.go:147] writing to bm9/59.ec06
I1110 12:52:58 19783 volume_grpc_copy.go:147] writing to bm9/59.ec07
I1110 12:55:30 19783 volume_grpc_copy.go:147] writing to bm9/59.ec11
I1110 12:58:19 19783 volume_grpc_copy.go:147] writing to bm9/59.ec12
I1110 13:01:22 19783 volume_grpc_copy.go:147] writing to bm9/59.ec13
I1110 13:27:49 19783 store_ec.go:51] MountEcShards 59.8
I1110 13:27:49 19783 store_ec.go:51] MountEcShards 59.9
I1110 13:27:49 19783 store_ec.go:51] MountEcShards 59.10
```
ec.balance -force
```
balanceEcVolumes collections 1
balanceEcVolumes collection 
balanceEcVolumes 
127.0.0.1:9509 has 1 overlimit, moving ec shard 59.4
```
returns and doing nothing

next i will try your fix and the original 1.44 weed executable

**Comment by steven2612** [comment]
original 1.44 weed executable:
```
weed shell -master localhost:9500
> ec.balance
balanceEcVolumes collections 1
balanceEcVolumes collection 
balanceEcVolumes 
ec shard 59.4 has 2 copies, keeping 127.0.0.1:9508
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1189c44]

goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/shell.doBalanceEcShardsAcrossRacks(0x1ca82e0, 0xc0000ec000, 0xc000492190, 0x0, 0x0, 0x3b, 0xc0001d7d40, 0x5, 0x8, 0xc0004b7950, ...)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/shell/command_ec_balance.go:270 +0x714
github.com/chrislusf/seaweedfs/weed/shell.balanceEcShardsAcrossRacks(0x1ca82e0, 0xc0000ec000, 0xc000492190, 0xc0001d7a40, 0x5, 0x8, 0xc0004b7950, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/shell/command_ec_balance.go:235 +0x13e
github.com/chrislusf/seaweedfs/weed/shell.balanceEcVolumes(0xc000492190, 0x0, 0x0, 0xc0001d7a40, 0x5, 0x8, 0xc0004b7950, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/shell/command_ec_balance.go:173 +0x2c7
github.com/chrislusf/seaweedfs/weed/shell.(*commandEcBalance).Do(0x297fe70, 0x297fe70, 0x0, 0x0, 0xc000492190, 0x1c76840, 0xc0000ca008, 0xa, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/shell/command_ec_balance.go:131 +0x5f8
github.com/chrislusf/seaweedfs/weed/shell.RunShell(0xc000082d80, 0x1c757e0, 0xc00000e2e8, 0x194d5a4, 0x9, 0x22b8, 0x1945366, 0x1)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/shell/shell_liner.go:70 +0x5c0
github.com/chrislusf/seaweedfs/weed/command.runShell(0x294c800, 0xc0000d0070, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/shell.go:38 +0x133
main.main()
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/weed.go:66 +0x2f9

weed shell -master localhost:9500
> ec.balance -force
balanceEcVolumes collections 1
balanceEcVolumes collection 
balanceEcVolumes 
ec shard 59.4 has 2 copies, keeping 127.0.0.1:9508
unmount 59.[4] from 127.0.0.1:9509
delete 59.[4] from 127.0.0.1:9509
```

so except the panic without "-force" it works fine

i will do one more test with the original distribution of ec shards and then compile the new version with your fix

**Comment by steven2612** [comment]
ok, with original 1.44 executable and original distribution - ec.balance gives the error shown in the last post. ec-balance -force distributes most of the shards, but one which keeps duplicate on two shards. ec.balance and ec.balance-force says
`127.0.0.1:9506 has 1 overlimit, moving ec shard 59.0 `
but does nothing, even when calling multiple times.

version 9c2f3b1 seems to fix the panic but does not change anything with not balancing ec shards correct.

what infos would help to fix this ?

**Comment by chrislusf** [comment]
It is hard to reproduce here.

Looks you get to this line https://github.com/chrislusf/seaweedfs/blob/master/weed/shell/command_ec_balance.go#L354
but has some problem inside pickOneEcNodeAndMoveOneShard() function. You can try to do some println and see what is the problem.

**Comment by steven2612** [comment]
i am trying my best ;) never coded with go before ...

i added some printf:
```
bm7:8280 has 1 overlimit, moving ec shard 60.6
possible nodes bm9:8280 bm6:8280 bm7:8280 bm2:8280 
test bm7:8280 bm9:8280 13
cont 3 - 3 >= 1
test bm7:8280 bm6:8280 13
cont 3 - 3 >= 1
test bm7:8280 bm7:8280 12
cont 1 - same node
test bm7:8280 bm2:8280 11
cont 3 - 3 >= 1
```
it seems, there is missing a node - in this case bm8
because all conditions are not met (would only be true on the missing node) it skips all nodes and do not move at all.

i am currently trying to find out why one node is missing
in web topology all nodes are present

**Comment by steven2612** [comment]
ok checking deduplication (added more debug):
volume.list gives:
```
        ec volume id:60 collection: shards:[3 4 5]
        ec volume id:60 collection: shards:[0 1 2]
        ec volume id:60 collection: shards:[6 7 8 12 13]
        ec volume id:60 collection: shards:[6 7 8]
        ec volume id:60 collection: shards:[9 10 11]
```
but ec.balance does:
dedupl vol 60
```
ec shard 60.0 has 1 copies
ec shard 60.1 has 1 copies
ec shard 60.2 has 1 copies
ec shard 60.3 has 1 copies
ec shard 60.4 has 1 copies
ec shard 60.5 has 1 copies
ec shard 60.6 has 1 copies
ec shard 60.7 has 1 copies
ec shard 60.8 has 1 copies
ec shard 60.9 has 1 copies
ec shard 60.10 has 1 copies
ec shard 60.11 has 1 copies
ec shard 60.12 has 1 copies
ec shard 60.13 has 1 copies
```
so ec.balance does not delete duplicate shards, because it's only 1 copy, which is not true ...

**Comment by chrislusf** [comment]
please show your code also

**Comment by steven2612** [comment]
ok, i added more debug with deduplication:
```
bm6:8280 shardid: 0
bm6:8280 shardid: 1
bm6:8280 shardid: 2
bm9:8280 shardid: 9
bm9:8280 shardid: 10
bm9:8280 shardid: 11
bm7:8280 shardid: 6
bm7:8280 shardid: 7
bm7:8280 shardid: 8
bm7:8280 shardid: 12
bm7:8280 shardid: 13
bm2:8280 shardid: 3
bm2:8280 shardid: 4
bm2:8280 shardid: 5
```
here is missing bm8:8280 too, so the calculations are wrong.
so the main problem seems to be bm8 is missing in all calculations.
i dont know (yet) why here bm8 is missing, but with volume.list it shows up normal.

yes i can give you the code, but i only added some printf in the file you mentioned ...
https://static.buchmedia.at/command_ec_balance.go

**Comment by chrislusf** [comment]
What is "shows up normal"?

Seems for volume "60", there are no shard on bm8. This logic is fine for dedup.

**Comment by steven2612** [comment]
No, as stated before on bm8 are 3 shards:
see https://static.buchmedia.at/volume.list
```
  DataCenter bm1 volume:80/165 active:80 free:45
    Rack r1 volume:80/165 active:80 free:45
      DataNode bm2:8280 volume:16/33 active:16 free:9
       ec volume id:60 collection: shards:[3 4 5]
...
     DataNode bm6:8280 volume:16/33 active:16 free:9
      ec volume id:60 collection: shards:[0 1 2]
...
    DataNode bm7:8280 volume:16/33 active:16 free:9
       ec volume id:60 collection: shards:[6 7 8 12 13]
...
     DataNode bm8:8280 volume:16/33 active:16 free:8
       ec volume id:60 collection: shards:[6 7 8]
...
     DataNode bm9:8280 volume:16/33 active:16 free:9
       ec volume id:60 collection: shards:[9 10 11]

```

**Comment by steven2612** [comment]
ok .. now narrowed to `func collectEcNodes`:
```
// find out all volume servers with one slot left.
	eachDataNode(resp.TopologyInfo, func(dc string, rack RackId, dn *master_pb.DataNodeInfo) {
		if selectedDataCenter != "" && selectedDataCenter != dc {
			return
		}
	    fmt.Printf("eachdn %s %d\n",dn.Id,countFreeShardSlots(dn))
		if freeEcSlots := countFreeShardSlots(dn); freeEcSlots > 0 {
			ecNodes = append(ecNodes, &EcNode{
				info:       dn,
				dc:         dc,
				rack:       rack,
				freeEcSlot: int(freeEcSlots),
			})
			totalFreeEcSlots += freeEcSlots
		}
	})
```
this gives:
```
eachdn bm7:8280 12
eachdn bm2:8280 11
eachdn bm9:8280 13
eachdn bm8:8280 -1
eachdn bm6:8280 13
```
so its clear bm8 is skipped and allEcNodes does not include bm8 any more ..
i think this is because you dont want to move a ec shard to a node which has no ec slots available.
but for deleting duplicate shards this is bad, because shards are missing for the calculations ...

**Comment by chrislusf** [comment]
Thanks for the debugging! Maybe help to printout details for countShards() for bm8. And "volume.list" info for bm8.

**Comment by chrislusf** [comment]
added a fix. please check it out.

**Comment by steven2612** [comment]
yes, now countFreeShardSlots seems to be correct.

but i think - for doing the deduplication you should not skip volume servers which have no free ec slots
so i think there should be another function to get `allEcNodes` for:
`if err := deleteDuplicatedEcShards(ctx, commandEnv, allEcNodes, collection, applyBalancing);`
than for:
`if err := balanceEcShardsAcrossRacks(ctx, commandEnv, allEcNodes, racks, collection, applyBalancing);
`and
`if err := balanceEcShardsWithinRacks(ctx, commandEnv, allEcNodes, racks, collection, applyBalancing);`

**Comment by chrislusf** [comment]
the last fix also removed "freeEcSlots > 0" checking.

**Comment by steven2612** [comment]
ah .. ok .. seems to have overlooked this ;)

**Comment by steven2612** [comment]
ok, now deduplication works (in some suboptimal way) but moving volumes does not work. i will add debug info to see why.

as for deduplication - now i have:
```
        ec volume id:59 collection: shards:[11 12 13]
        ec volume id:59 collection: shards:[0 1 2 3]
        ec volume id:59 collection: shards:[7]
        ec volume id:59 collection: shards:[5 6 8 9 10]
        ec volume id:59 collection: shards:[4]
```

so it deleted the duplicated shards on those servers which have less shards. so now its needed to rebalance - better would be deduplication already deletes those shards where more shards are used so a even balancing is archived without need to move anything between servers ...

**Comment by chrislusf** [comment]
It's hard to balance under multiple constraints. 

Here you need to run multiple times to achieve balance.

**Comment by chrislusf** [comment]
Added one more fix for deduplication more on fuller nodes.

**Comment by steven2612** [comment]
i think i have found the problem:
averageShardsPerEcNode is double calculated
here a fix (with debug printf)
```
diff --git a/weed/shell/command_ec_balance.go b/weed/shell/command_ec_balance.go
index 9a70412c..3229f65a 100644
--- a/weed/shell/command_ec_balance.go
+++ b/weed/shell/command_ec_balance.go
@@ -440,20 +440,25 @@ func doBalanceEcRack(ctx context.Context, commandEnv *CommandEnv, ecRack *EcRack
        return nil
 }
 
-func pickOneEcNodeAndMoveOneShard(ctx context.Context, commandEnv *CommandEnv, expectedTotalEcShards int, existingLocation *EcNode, collection string, vid needle.VolumeId, shardId erasure_coding.ShardId, possibleDestinationEcNodes []*EcNode, applyBalancing bool) error {
+func pickOneEcNodeAndMoveOneShard(ctx context.Context, commandEnv *CommandEnv, averageShardsPerEcNode int, existingLocation *EcNode, collection string, vid needle.VolumeId, shardId erasure_coding.ShardId, possibleDestinationEcNodes []*EcNode, applyBalancing bool) error {
 
        sortEcNodesByFreeslotsDecending(possibleDestinationEcNodes)
-       averageShardsPerEcNode := ceilDivide(expectedTotalEcShards, len(possibleDestinationEcNodes))
+       //averageShardsPerEcNode := ceilDivide(expectedTotalEcShards, len(possibleDestinationEcNodes))
+  //fmt.Printf("avg %d %d %d\n",expectedTotalEcShards, len(possibleDestinationEcNodes), averageShardsPerEcNode)
 
        for _, destEcNode := range possibleDestinationEcNodes {
+               fmt.Printf("%s check move ec shard %d.%d to %s\n", existingLocation.info.Id, vid, shardId, destEcNode.info.Id)
                if destEcNode.info.Id == existingLocation.info.Id {
+                 fmt.Printf("con1 - same node\n")
                        continue
                }
 
                if destEcNode.freeEcSlot <= 0 {
+                 fmt.Printf("con2 - not free\n")
                        continue
                }
                if findEcVolumeShards(destEcNode, vid).ShardIdCount() >= averageShardsPerEcNode {
+                 fmt.Printf("con3 - %d %d\n",findEcVolumeShards(destEcNode, vid).ShardIdCount(),averageShardsPerEcNode)
                        continue
                }

```

**Comment by chrislusf** [comment]
cool!!! Added this fix!

**Comment by steven2612** [comment]
thanks for the quick fixing of all those problems !
i think this issue could be closed ...

but .. could you answer me one question from above ?

how should i max volumes calculate ?
currently i have 1TB for the volume server - so i did 1TB/30GB = 33 volumes is this the intended calculation ?

**Comment by chrislusf** [comment]
correct. Maybe allow one or two volume size, 30~60GB, because of compaction.
