### ISSUE TITLE
weed panic

### ISSUE THREAD

**Issue by roflmao** [chrislusf/seaweedfs#1184]
**Describe the bug**
Some hours after upgrading from 1.45 to 1.50 i had a panic:

```
Jan 21 14:09:09 photol-108 weed[31469]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 21 14:09:09 photol-108 weed[31469]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xa25d69]
Jan 21 14:09:09 photol-108 weed[31469]: goroutine 351366 [running]:
Jan 21 14:09:09 photol-108 weed[31469]: github.com/chrislusf/seaweedfs/weed/storage/needle.ReadNeedleBlob(0x0, 0x0, 0x8, 0x3000c4581, 0xc1ad191d60, 0x1, 0xc09ee0f658, 0x4fd8ec, 0xc2659b2000)
Jan 21 14:09:09 photol-108 weed[31469]:         /src/github.com/chrislusf/seaweedfs/weed/storage/needle/needle_read_write.go:158 +0x79
Jan 21 14:09:09 photol-108 weed[31469]: github.com/chrislusf/seaweedfs/weed/storage/needle.(*Needle).ReadData(0xc09ee0f780, 0x0, 0x0, 0x8, 0x3000c4581, 0xc1a691fef0, 0x0)
Jan 21 14:09:09 photol-108 weed[31469]:         /src/github.com/chrislusf/seaweedfs/weed/storage/needle/needle_read_write.go:195 +0x54
Jan 21 14:09:09 photol-108 weed[31469]: github.com/chrislusf/seaweedfs/weed/storage.(*Volume).copyDataBasedOnIndexFile.func1(0x3bb7dae5, 0xc458101000000, 0x4, 0xc4581)
Jan 21 14:09:09 photol-108 weed[31469]:         /src/github.com/chrislusf/seaweedfs/weed/storage/volume_vacuum.go:386 +0x17b
Jan 21 14:09:09 photol-108 weed[31469]: github.com/chrislusf/seaweedfs/weed/storage/needle_map.(*MemDb).AscendingVisit(0xc01195a588, 0xc09ee0f928, 0x8, 0x8)
Jan 21 14:09:09 photol-108 weed[31469]:         /src/github.com/chrislusf/seaweedfs/weed/storage/needle_map/memdb.go:73 +0x163
Jan 21 14:09:09 photol-108 weed[31469]: github.com/chrislusf/seaweedfs/weed/storage.(*Volume).copyDataBasedOnIndexFile(0xc17faacc30, 0xc067995200, 0x2e, 0xc067995260, 0x2e, 0x0, 0x0, 0x0)
Jan 21 14:09:09 photol-108 weed[31469]:         /src/github.com/chrislusf/seaweedfs/weed/storage/volume_vacuum.go:377 +0x298
Jan 21 14:09:09 photol-108 weed[31469]: github.com/chrislusf/seaweedfs/weed/storage.(*Volume).Compact2(0xc17faacc30, 0x0, 0x0, 0x0)
Jan 21 14:09:09 photol-108 weed[31469]:         /src/github.com/chrislusf/seaweedfs/weed/storage/volume_vacuum.go:75 +0x2b8
Jan 21 14:09:09 photol-108 weed[31469]: github.com/chrislusf/seaweedfs/weed/storage.(*Store).CompactVolume(0xc000488180, 0x20b5, 0x0, 0x3200000, 0x1dbb2e0, 0x1e3c620)
Jan 21 14:09:09 photol-108 weed[31469]:         /src/github.com/chrislusf/seaweedfs/weed/storage/store_vacuum.go:19 +0x54
Jan 21 14:09:09 photol-108 weed[31469]: github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).VacuumVolumeCompact(0xc0003d46e0, 0x217aa60, 0xc1d0119560, 0xc3b80202f0, 0xc0003d46e0, 0xc1d0119470, 0x1b68520)
Jan 21 14:09:09 photol-108 weed[31469]:         /src/github.com/chrislusf/seaweedfs/weed/server/volume_grpc_vacuum.go:31 +0x81
Jan 21 14:09:09 photol-108 weed[31469]: github.com/chrislusf/seaweedfs/weed/pb/volume_server_pb._VolumeServer_VacuumVolumeCompact_Handler(0x1e3c620, 0xc0003d46e0, 0x217aa60, 0xc1d0119560, 0xc0c8686000, 0x0, 0x0, 0x0, 0xc3b80202e8, 0x3)
Jan 21 14:09:09 photol-108 weed[31469]:         /src/github.com/chrislusf/seaweedfs/weed/pb/volume_server_pb/volume_server.pb.go:2673 +0x23e
Jan 21 14:09:09 photol-108 weed[31469]: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00035a2c0, 0x218c860, 0xc01413b080, 0xc0e7f97400, 0xc2c37b8ab0, 0x347d810, 0x0, 0x0, 0x0)
Jan 21 14:09:09 photol-108 weed[31469]:         /root/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:995 +0x485
Jan 21 14:09:09 photol-108 weed[31469]: google.golang.org/grpc.(*Server).handleStream(0xc00035a2c0, 0x218c860, 0xc01413b080, 0xc0e7f97400, 0x0)
Jan 21 14:09:09 photol-108 weed[31469]:         /root/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:1275 +0xe02
Jan 21 14:09:09 photol-108 weed[31469]: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc1803ea5a0, 0xc00035a2c0, 0x218c860, 0xc01413b080, 0xc0e7f97400)
Jan 21 14:09:09 photol-108 weed[31469]:         /root/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:710 +0x9f
Jan 21 14:09:09 photol-108 weed[31469]: created by google.golang.org/grpc.(*Server).serveStreams.func1
Jan 21 14:09:09 photol-108 weed[31469]:         /root/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:708 +0xa1
```

**System Setup**
```
-  /usr/local/bin/weed -logtostderr master -mdir=/mnt/data01/meta -ip=10.1.21.18 -defaultReplication=010 -volumePreallocate -volumeSizeLimitMB 30000 -pulseSeconds 10 -peers=10.1.21.17:9333,10.1.21.18:9333,10.1.21.19:9333
-  /usr/local/bin/weed -logtostderr -v=1 volume -compactionMBps=50 -port=8080 -mserver=10.1.21.17:9333,10.1.21.18:9333,10.1.21.19:9333 -dir=/mnt/data01/data,/mnt/data02/data -index leveldb -max 3866,3866 -ip 10.1.21.18 -rack photol-108
- version 30GB 1.50 linux amd64
- Ubuntu 16.04
```

**Additional context**
Running force gc at 0.10

**Comment by roflmao** [comment]
volume server log: https://gist.githubusercontent.com/roflmao/011d048e776daa293aaaffc0fd50d108/raw/58e06ebf08a1c7c9ffda0e52dc7c69a1a2179027/gistfile1.txt

**Comment by chrislusf** [comment]
Is it possible there are multiple concurrent compactions going on?

**Comment by roflmao** [comment]
There might have been a double http request for forcing gc: 
```curl "http://localhost:9333/vol/vacuum?garbageThreshold=0.1"```'

It isnt synchronous i guess even if it returns when finished?

**Comment by chrislusf** [comment]
The `curl "http://localhost:9333/vol/vacuum?garbageThreshold=0.1"` is a synchronous call.

1.52 release has a fix to address the panic.

**Comment by roflmao** [comment]
Great, thanks!
