### ISSUE TITLE
panic: assertion failed: leader.elected.at.same.term.0

### ISSUE THREAD

**Issue by Dmole** [chrislusf/seaweedfs#1186]
**Describe the bug**
`panic: assertion failed: leader.elected.at.same.term.0`

**System Setup**
```
> ./weed server -master.port=9333 -volume.port=808 -dir=/opt/seaweedfs-data -ip=${IP} -filer -master.peers=${IP}:9333,${IP2}:9333,${IP3}:9333

> hostnamectl | grep Operating
  Operating System: Ubuntu 18.04.3 LTS

> ./weed version
version 30GB 1.51 linux amd64
```

**Expected behavior**
An Admin friendly error message instead of a stack trace.

**Additional context**
```
I0125 02:37:38 22656 config.go:27] Reading : Config File "security" Not Found in "[/opt /root/.seaweedfs /etc/seaweedfs]"
I0125 02:37:38 22656 config.go:27] Reading : Config File "master" Not Found in "[/opt /root/.seaweedfs /etc/seaweedfs]"
I0125 02:37:38 22656 file_util.go:20] Folder /opt/seaweedfs-data Permission: -rwxr-xr-x
I0125 02:37:38 22656 master_server.go:102] Volume Size Limit is 30000 MB
I0125 02:37:38 22656 master_server.go:188] adminScripts:
I0125 02:37:38 22656 master.go:112] Start Seaweed Master 30GB 1.51 at 0.0.0.0:9333
I0125 02:37:38 22656 raft_server.go:44] Starting RaftServer with 192.168.0.124:9333
I0125 02:37:38 22656 file_util.go:20] Folder /opt/seaweedfs-data Permission: -rwxr-xr-x
I0125 02:37:38 22656 raft_server.go:48] Peers Change: [] => [192.168.0.124:9333 :9333 192.168.0.150:9333]
I0125 02:37:38 22656 disk_location.go:108] Store started on dir: /opt/seaweedfs-data with 0 volumes max 7
I0125 02:37:38 22656 disk_location.go:111] Store started on dir: /opt/seaweedfs-data with 0 ec shards
I0125 02:37:38 22656 volume.go:277] Start Seaweed volume server 30GB 1.51 at 0.0.0.0:808
I0125 02:37:38 22656 volume_grpc_client_to_master.go:25] Volume server start with seed master nodes: [192.168.0.124:9333 :9333 192.168.0.150:9333]
I0125 02:37:38 22656 volume_grpc_client_to_master.go:66] SendHeartbeat to 192.168.0.124:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.0.124:19333: connect: connection refused"
I0125 02:37:38 22656 volume_grpc_client_to_master.go:46] heartbeat error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.0.124:19333: connect: connection refused"
I0125 02:37:38 22656 raft_server.go:71] Initializing new cluster
I0125 02:37:38 22656 raft_server.go:84] current cluster leader: 192.168.0.124:9333
I0125 02:37:38 22656 master_server.go:143] [ 192.168.0.124:9333 ] I am the leader!
I0125 02:37:38 22656 master.go:136] Start Seaweed Master 30GB 1.51 grpc server at 0.0.0.0:19333
I0125 02:37:38 22656 master_grpc_server.go:206] + client master192.168.0.124:47360
panic: assertion failed: leader.elected.at.same.term.0


goroutine 50 [running]:
github.com/chrislusf/raft._assert(...)
	/home/travis/gopath/pkg/mod/github.com/chrislusf/raft@v0.0.0-20190225081310-10d6e2182d92/util.go:60
github.com/chrislusf/raft.(*server).processAppendEntriesRequest(0xc000483560, 0xc0000bc7d0, 0xc0000bc7d0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/chrislusf/raft@v0.0.0-20190225081310-10d6e2182d92/server.go:981 +0x9a3
github.com/chrislusf/raft.(*server).leaderLoop(0xc000483560)
	/home/travis/gopath/pkg/mod/github.com/chrislusf/raft@v0.0.0-20190225081310-10d6e2182d92/server.go:882 +0x430
github.com/chrislusf/raft.(*server).loop(0xc000483560)
	/home/travis/gopath/pkg/mod/github.com/chrislusf/raft@v0.0.0-20190225081310-10d6e2182d92/server.go:609 +0x1fd
github.com/chrislusf/raft.(*server).Start.func1(0xc000483560)
	/home/travis/gopath/pkg/mod/github.com/chrislusf/raft@v0.0.0-20190225081310-10d6e2182d92/server.go:470 +0x64
created by github.com/chrislusf/raft.(*server).Start
	/home/travis/gopath/pkg/mod/github.com/chrislusf/raft@v0.0.0-20190225081310-10d6e2182d92/server.go:468 +0x1a8
```

**Comment by chrislusf** [comment]
try to clear up /opt/seaweedfs-data when running from the same directory again and with a different master settings.

**Comment by Dmole** [comment]
/opt/seaweedfs-data was empty.

what different master settings?

**Comment by chrislusf** [comment]
Is it running with just one server?

**Comment by Dmole** [comment]
Yes; I was going to start the others after I got one working.

**Comment by Dmole** [comment]
sorry chrislusf, on re-testing I think /opt/seaweedfs-data was not empty.
Can we get a better error message?

**Comment by chrislusf** [comment]
I could not reproduce this by running locally:
```
$ weed server -master.port=9333 -volume.port=8080 -dir=./x -ip=127.0.0.1 \
  -filer -master.peers=127.0.0.1:9333,127.0.0.2:9333,127.0.0.3:9333
I0126 20:58:45  6801 file_util.go:20] Folder ./x Permission: -rwxr-xr-x
I0126 20:58:45  6801 file_util.go:20] Folder ./x Permission: -rwxr-xr-x
I0126 20:58:45  6801 s3_backend.go:51] created backend storage s3.default for region us-west-1 bucket seaweedfs.test
I0126 20:58:45  6801 master_server.go:102] Volume Size Limit is 30000 MB
I0126 20:58:45  6801 disk_location.go:108] Store started on dir: ./x with 0 volumes max 7
I0126 20:58:45  6801 master_server.go:188] adminScripts:
I0126 20:58:45  6801 master.go:112] Start Seaweed Master 30GB 1.51 at 0.0.0.0:9333
I0126 20:58:45  6801 disk_location.go:111] Store started on dir: ./x with 0 ec shards
I0126 20:58:45  6801 volume_grpc_client_to_master.go:25] Volume server start with seed master nodes: [127.0.0.1:9333 127.0.0.2:9333 127.0.0.3:9333]
I0126 20:58:45  6801 raft_server.go:44] Starting RaftServer with 127.0.0.1:9333
I0126 20:58:45  6801 raft_server.go:48] Peers Change: [] => [127.0.0.1:9333 127.0.0.2:9333 127.0.0.3:9333]
I0126 20:58:45  6801 volume.go:277] Start Seaweed volume server 30GB 1.51 at 0.0.0.0:8080
I0126 20:58:45  6801 volume_grpc_client_to_master.go:66] SendHeartbeat to 127.0.0.1:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: connect: connection refused"
I0126 20:58:45  6801 volume_grpc_client_to_master.go:46] heartbeat error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:19333: connect: connection refused"
I0126 20:58:45  6801 raft_server.go:71] Initializing new cluster
I0126 20:58:45  6801 raft_server.go:84] current cluster leader: 127.0.0.1:9333
I0126 20:58:45  6801 master_server.go:143] [ 127.0.0.1:9333 ] I am the leader!
I0126 20:58:45  6801 master.go:136] Start Seaweed Master 30GB 1.51 grpc server at 0.0.0.0:19333
I0126 20:58:45  6801 master_grpc_server.go:206] + client master127.0.0.1:56491
I0126 20:58:46  6801 master_grpc_server.go:206] + client filer127.0.0.1:56491
I0126 20:58:46  6801 config.go:27] Reading : Config File "notification" Not Found in "[/Users/chris/tmp /Users/chris/.seaweedfs /etc/seaweedfs]"
I0126 20:58:46  6801 leveldb2_store.go:39] filer store leveldb2 dir: ./filer_ldb2
I0126 20:58:46  6801 file_util.go:20] Folder ./filer_ldb2 Permission: -rwxr-xr-x
I0126 20:58:46  6801 configuration.go:26] Configure filer for leveldb2
I0126 20:58:46  6801 filer.go:133] Start Seaweed Filer 30GB 1.51 at 0.0.0.0:8888
I0126 20:59:10  6801 volume_grpc_client_to_master.go:66] SendHeartbeat to 127.0.0.2:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.2:19333: i/o timeout"
I0126 20:59:10  6801 volume_grpc_client_to_master.go:46] heartbeat error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.2:19333: i/o timeout"
I0126 20:59:35  6801 volume_grpc_client_to_master.go:66] SendHeartbeat to 127.0.0.3:9333: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.3:19333: i/o timeout"
I0126 20:59:35  6801 volume_grpc_client_to_master.go:46] heartbeat error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.3:19333: i/o timeout"
I0126 20:59:35  6801 master_server.go:140] state change: &{typ:stateChange source:0xc0005a4120 value:follower prevValue:leader}
I0126 20:59:40  6801 master_server.go:140] state change: &{typ:stateChange source:0xc0005a4120 value:candidate prevValue:follower}
I0126 20:59:40  6801 volume_grpc_client_to_master.go:69] Heartbeat to: 127.0.0.1:9333
I0126 20:59:40  6801 node.go:255] topo adds child DefaultDataCenter
I0126 20:59:40  6801 node.go:255] topo:DefaultDataCenter adds child DefaultRack
I0126 20:59:40  6801 node.go:255] topo:DefaultDataCenter:DefaultRack adds child 127.0.0.1:8080
I0126 20:59:40  6801 master_grpc_server.go:78] added volume server 127.0.0.1:8080
```

**Comment by chrislusf** [comment]
Tried multiple combinations and still could not reproduce.

**Comment by Dmole** [comment]
I also can't reproduce... I have chrony installed now because ceph complained about it.
feel free to close this issue.
