### ISSUE TITLE
Error message provides faulty instructions and a 404 link

### ISSUE THREAD

**Issue by Dmole** [chrislusf/seaweedfs#1187]
**Describe the bug**
1. a 404 link.
2. config=notification does not make filer.toml.
3. both toml files are in current directory why are they not loaded?

**System Setup**
```
> ./weed master -mdir="$TMP" -defaultReplication=001 -ip="${IP}" -peers=${IP1}:9333,${IP2}:9333,${IP3}:9333 > weed_master.log 2>&1 &
> sleep 2
> ./weed volume -dir="$TMP" -ip="${IP}" -port=8081 -mserver=${IP1}:9333,${IP2}:9333,${IP3}:9333 > weed_volume.log 2>&1 &
> sleep 2
> ./weed filer -defaultReplicaPlacement=001 -ip="${IP}" -master=${IP1}:9333,${IP2}:9333,${IP3}:9333 weed_filer.log 2>&1 &
> sleep 2
> ./weed mount -dir="$MOUNT" -replication=001 -filer="${IP}:8888" > weed_mount.log 2>&1 &

> hostnamectl | grep Operating
  Operating System: Ubuntu 18.04.3 LTS

> ./weed version
version 30GB 1.51 linux amd64

> find / -iname filer.toml # no pre existing file
```

**Expected behavior**
A clear and concise description of what is required.

**Additional context**
```
> ./weed scaffold -config=replication -output=.
> ./weed scaffold -config=filer -output=.
> ./weed filer.replicate
I0127 18:05:03 25618 config.go:27] Reading : Config File "security" Not Found in "[/opt /root/.seaweedfs /etc/seaweedfs]"
I0127 18:05:03 25618 config.go:27] Reading : Config File "notification" Not Found in "[/opt /root/.seaweedfs /etc/seaweedfs]"
F0127 18:05:03 25618 config.go:29] Failed to load notification.toml file from current directory, or $HOME/.seaweedfs/, or /etc/seaweedfs/

Please follow this example and add a filer.toml file to current directory, or $HOME/.seaweedfs/, or /etc/seaweedfs/:
    https://github.com/chrislusf/seaweedfs/blob/master/weed/notification.toml

Or use this command to generate the default toml file
    weed scaffold -config=notification -output=.


goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0xc000496b00, 0xc0000d4000, 0x1b8, 0x341)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0xb8
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x33179c0, 0xc000000003, 0xc000485f80, 0x31b7aa8, 0x9, 0x1d, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:718 +0x351
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x33179c0, 0x3, 0x1f24ac8, 0x177, 0xc0005edbe0, 0x3, 0x3)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:656 +0x14b
github.com/chrislusf/seaweedfs/weed/glog.Fatalf(...)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:1149
github.com/chrislusf/seaweedfs/weed/util.LoadConfiguration(0x1e968c1, 0xc, 0x1, 0xc000344d01)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/util/config.go:29 +0x3ae
github.com/chrislusf/seaweedfs/weed/command.runFilerReplicate(0x32e5ca0, 0xc00000c090, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/filer_replication.go:41 +0x8c
main.main()
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/weed.go:66 +0x2f9

> ls -1 *.toml
filer.toml
replication.toml
```

Side question: [How do I get the mount points to sync?](https://seaweedfs.slack.com/archives/C9MGUC1UG/p1580053555005400)

**Comment by chrislusf** [comment]
1. need to generate `notification.toml`, used by `weed filer` to emit file change notifications.
2. need to generate `replication.toml`, used by `weed replicate`, to receive the notifications, and replicate data to the destination.

There are client side cache for `weed mount`. One file change would not be instantly visible until the file is closed. So do not expect instantaneous synchronization.

**Comment by Dmole** [comment]
Are you going to fix that 404 link?
https://github.com/chrislusf/seaweedfs/blob/master/weed/notification.toml

**Comment by chrislusf** [comment]
`weed filer.replicate` would replicate the file to another seaweedfs cluster, or s3/azure/google_cloud_storage.
