### ISSUE TITLE
master leader election

### ISSUE THREAD

**Issue by cesar-blog** [chrislusf/seaweedfs#1191]
**Describe the bug**
master leader election problem.

**System Setup**

weed-version：0.76

```
192.168.15.31:
nohup ./weed master -mdir=./master_dir/ -port=9333 -defaultReplication=100   -peers=192.168.15.31:9333,192.168.15.32:9333,192.168.15.33:9333 -ip=192.168.15.31 -volumePreallocate=true  >> ./master_dir/server_sfs.log &
 
nohup ./weed volume  -dir=./rack1_volume_dir/ -port=8091  -max=30  -mserver=192.168.15.31:9333 -dataCenter=dc1 -ip=192.168.15.31 -rack=rk1  -idleTimeout=3600 >> ./rack1_volume_dir/volume_sfs.log &
 
nohup ./weed filer -dir=./filer_dir/ -port=8888 -ip=192.168.15.31 -master=192.168.15.31:9333  -maxMB=10 -defaultReplicaPlacement=100  >> ./filer_dir/f.log &
 
192.168.15.32:
          
nohup ./weed master -mdir=./master_dir/ -port=9333 -defaultReplication=100   -peers=192.168.15.31:9333,192.168.15.32:9333,192.168.15.33:9333 -ip=192.168.15.32   -volumePreallocate=true  >> ./master_dir/server_sfs.log &
 
 
nohup ./weed volume  -dir=./rack1_volume_dir/ -port=8091  -max=30  -mserver=192.168.15.32:9333 -dataCenter=dc1 -ip=192.168.15.32 -rack=rk1   -idleTimeout=3600 >> ./rack1_volume_dir/volume_sfs.log &
 
192.168.15.33:
          
nohup ./weed master -mdir=./master_dir/ -port=9333 -defaultReplication=100   -peers=192.168.15.31:9333,192.168.15.32:9333,192.168.15.33:9333 -ip=192.168.15.33   -volumePreallocate=true >> ./master_dir/server_sfs.log &
 
 
nohup ./weed volume  -dir=./rack2_volume_dir/ -port=8091  -max=100  -mserver=192.168.15.33:9333 -dataCenter=dc2 -ip=192.168.15.33 -rack=rk1 -idleTimeout=3600 >> ./rack2_volume_dir/volume_sfs.log &
 
```

**Screenshots**
192.168.15.31 master_log：

```
I0201 17:25:05 20683 file_util.go:20] Folder /home/weed/master_dir Permission: -rwxr-xr-x
I0201 17:25:05 20683 master_server.go:62] Volume Size Limit is 30000 MB
I0201 17:25:05 20683 master.go:87] Start Seaweed Master 0.76 at 0.0.0.0:9333
I0201 17:25:06 20683 raft_server.go:78] Joining cluster: 192.168.15.31:9333,192.168.15.32:9333,192.168.15.33:9333
I0201 17:25:06 20683 raft_server.go:166] Attempting to connect to: http://192.168.15.32:9333/cluster/join
2020/02/01 17:25:09 http: panic serving 192.168.31.194:34768: runtime error: invalid memory address or nil pointer dereference
goroutine 53 [running]:
net/http.(*conn).serve.func1(0x19e683c0)
	/home/travis/.gimme/versions/go/src/net/http/server.go:1693 +0x9f
panic(0x8673240, 0x8ac5d40)
	/home/travis/.gimme/versions/go/src/runtime/panic.go:489 +0x1c6
github.com/chrislusf/seaweedfs/weed/server.(*MasterServer).uiStatusHandler(0x19cfc000, 0x8a8e400, 0x19d46a20, 0x19d32380)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/server/master_server_handlers_ui.go:24 +0xce
github.com/chrislusf/seaweedfs/weed/server.(*MasterServer).(github.com/chrislusf/seaweedfs/weed/server.uiStatusHandler)-fm(0x8a8e400, 0x19d46a20, 0x19d32380)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/server/master_server.go:66 +0x38
net/http.HandlerFunc.ServeHTTP(0x19c446c8, 0x8a8e400, 0x19d46a20, 0x19d32380)
	/home/travis/.gimme/versions/go/src/net/http/server.go:1914 +0x34
github.com/gorilla/mux.(*Router).ServeHTTP(0x19c40510, 0x8a8e400, 0x19d46a20, 0x19d32380)
	/home/travis/gopath/src/github.com/gorilla/mux/mux.go:114 +0xa8
net/http.serverHandler.ServeHTTP(0x19c86200, 0x8a8e400, 0x19d46a20, 0x19d32280)
	/home/travis/.gimme/versions/go/src/net/http/server.go:2595 +0x8e
net/http.(*conn).serve(0x19e683c0, 0x8a8ede0, 0x19e51ea0)
	/home/travis/.gimme/versions/go/src/net/http/server.go:1797 +0x5d1
created by net/http.(*Server).Serve
	/home/travis/.gimme/versions/go/src/net/http/server.go:2696 +0x1f6
```

192.168.15.32 master_log：

```
I0201 17:20:26 30412 raft_server_handlers.go:16] Processing incoming join. Current Leader  Self 192.168.15.32:9333 Peers map[192.168.15.31:9333:0x1b31a000 192.168.15.33:9333:0x1b31a060]
I0201 17:20:26 30412 raft_server_handlers.go:20] Command:{"name":"192.168.15.31:9333","connectionString":"http://192.168.15.31:9333"}
I0201 17:20:26 30412 raft_server_handlers.go:27] join command from Name 192.168.15.31:9333 Connection http://192.168.15.31:9333
I0201 17:20:26 30412 raft_server_handlers.go:50] Error: Leader Unknown
I0201 17:20:27 30412 raft_server_handlers.go:16] Processing incoming join. Current Leader  Self 192.168.15.32:9333 Peers map[192.168.15.31:9333:0x1c207620 192.168.15.33:9333:0x1c207680]
I0201 17:20:27 30412 raft_server_handlers.go:20] Command:{"name":"192.168.15.31:9333","connectionString":"http://192.168.15.31:9333"}
I0201 17:20:27 30412 raft_server_handlers.go:27] join command from Name 192.168.15.31:9333 Connection http://192.168.15.31:9333
I0201 17:20:27 30412 raft_server_handlers.go:50] Error: Leader Unknown
I0201 17:20:28 30412 raft_server_handlers.go:16] Processing incoming join. Current Leader  Self 192.168.15.32:9333 Peers map[192.168.15.31:9333:0x1c1eb4a0 192.168.15.33:9333:0x1c1eb500]
I0201 17:20:28 30412 raft_server_handlers.go:20] Command:{"name":"192.168.15.31:9333","connectionString":"http://192.168.15.31:9333"}
I0201 17:20:28 30412 raft_server_handlers.go:27] join command from Name 192.168.15.31:9333 Connection http://192.168.15.31:9333
I0201 17:20:28 30412 raft_server_handlers.go:50] Error: Leader Unknown
I0201 17:20:29 30412 raft_server_handlers.go:16] Processing incoming join. Current Leader  Self 192.168.15.32:9333 Peers map[192.168.15.31:9333:0x1c2076e0 192.168.15.33:9333:0x1c207740]
I0201 17:20:29 30412 raft_server_handlers.go:20] Command:{"name":"192.168.15.31:9333","connectionString":"http://192.168.15.31:9333"}
I0201 17:20:29 30412 raft_server_handlers.go:27] join command from Name 192.168.15.31:9333 Connection http://192.168.15.31:9333
I0201 17:20:29 30412 raft_server_handlers.go:50] Error: Leader Unknown
I0201 17:20:30 30412 raft_server_handlers.go:16] Processing incoming join. Current Leader  Self 192.168.15.32:9333 Peers map[192.168.15.31:9333:0x1b8ca000 192.168.15.33:9333:0x1b8ca060]
I0201 17:20:30 30412 raft_server_handlers.go:20] Command:{"name":"192.168.15.31:9333","connectionString":"http://192.168.15.31:9333"}
I0201 17:20:30 30412 raft_server_handlers.go:27] join command from Name 192.168.15.31:9333 Connection http://192.168.15.31:9333
I0201 17:20:30 30412 raft_server_handlers.go:50] Error: Leader Unknown
I0201 17:21:02 16063 file_util.go:20] Folder /home/weed/master_dir Permission: -rwxr-xr-x
I0201 17:21:02 16063 master_server.go:62] Volume Size Limit is 30000 MB
I0201 17:21:02 16063 master.go:87] Start Seaweed Master 0.76 at 0.0.0.0:9333
I0201 17:21:02 16063 raft_server.go:78] Joining cluster: 192.168.15.31:9333,192.168.15.32:9333,192.168.15.33:9333
I0201 17:21:03 16063 raft_server.go:166] Attempting to connect to: http://192.168.15.31:9333/cluster/join
I0201 17:21:03 16063 raft_server.go:211] Post returned status:  200 
I0201 17:21:03 16063 master_server.go:98] [ 192.168.15.32:9333 ] 192.168.15.31:9333 is the leader.
```

192.168.15.33 master_log：

```
I0201 17:39:03  7005 file_util.go:20] Folder /home/weed/master_dir Permission: -rwxr-xr-x
I0201 17:39:03  7005 master_server.go:62] Volume Size Limit is 30000 MB
I0201 17:39:03  7005 master.go:87] Start Seaweed Master 0.76 at 0.0.0.0:9333
I0201 17:39:04  7005 raft_server.go:78] Joining cluster: 192.168.15.31:9333,192.168.15.32:9333,192.168.15.33:9333
I0201 17:39:04  7005 raft_server.go:166] Attempting to connect to: http://192.168.15.31:9333/cluster/join
I0201 17:39:06  7005 raft_server.go:211] Post returned status:  200 
I0201 17:39:06  7005 master_server.go:98] [ 192.168.15.33:9333 ] 192.168.15.31:9333 is the leader.
```

**Additional context**

**Comment by chrislusf** [comment]
Is the master at 192.168.15.31 still running after 2020/02/01 17:25:09 ?

**Comment by chrislusf** [comment]
updates?

**Comment by chrislusf** [comment]
close because of no updates.
