### ISSUE TITLE
1.70/FUSE3: failed "mount" leaves directory in broken state [BUG]

### ISSUE THREAD

**Issue by onlyjob** [chrislusf/seaweedfs#1258]
When "mount" command fails (e.g. due to unavailable filer), the mount directory is left in the unusable broken state:

```
$ ./weed mount -dir=/mnt/weed

This is SeaweedFS version 8000GB 1.70 linux amd64
mount point owner uid=1000 gid=1000 mode=drwxr-xr-x
2020-04-03 17:40:21.855824 I | mount helper error: fusermount: unsafe option suid ignored
F0403 17:40:21 34096 mount_std.go:151] get filer localhost:18888 configuration: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:18888: connect: connection refused"
goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0xc00003b800, 0xc000218140, 0xe5, 0x13d)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0xb8
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x2a8d1e0, 0xc000000003, 0xc0002121c0, 0x29c64bc, 0xc, 0x97, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:718 +0x351
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printDepth(0x2a8d1e0, 0x3, 0x1, 0xc00065fcf0, 0x1, 0x1)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:647 +0x129
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).print(...)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:638
github.com/chrislusf/seaweedfs/weed/glog.Fatal(...)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:1129
github.com/chrislusf/seaweedfs/weed/command.RunMount(0x2a8ce60, 0x12, 0x8)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/mount_std.go:151 +0x91f
github.com/chrislusf/seaweedfs/weed/command.runMount(0x2a76aa0, 0xc000192170, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/mount_std.go:38 +0x141
main.main()
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/weed.go:66 +0x2f9
```

Now after failed attempt to mount, `/mnt/weed` is left in the broken state:

```
$ stat /mnt/weed
stat: cannot stat '/mnt/weed': Transport endpoint is not connected
```

The remedy is to umount manually: `fusermount -u /mnt/weed`.

__Failed `mount` should fail cleanly.__

**Comment by chrislusf** [comment]
Nice suggestion! Added a fix for this.

**Comment by onlyjob** [comment]
Awesome! Many thanks for lightning-fast fixing. :)
