### ISSUE TITLE
Some files are corrupted when I copy from local to weed mount directory and Vice versa.

### ISSUE THREAD

**Issue by Jevi06** [chrislusf/seaweedfs#1260]
**Describe the bug**
Files like vides and images corrupted when I copy from lcoal to weed mount dir and vice versa.
I encountered this problem in a kubernetes cluster first ,but its reproduceable in host machine ,so I describe the steps out of cluster as blow.

**System Setup**
- CentOS Linux release 7.7.1908 (Core)
- Kernel: Linux 3.10.0-957.el7.x86_64
- Weed  version 30GB 1.70 linux amd64(1.55 also)
- Fuse: fuse-2.9.2-11.el7.x86_64
- Weed setup command
  `./weed server -filer=true -ip="0.0.0.0"  -dir=/root/ljh/tmp/vol`
  `./weed mount -filer=localhost:8888 -dir=/root/ljh/tmp/base`

**Problem**
After base system setup like above,just do `cp` opteration from local to mounted dir(`/root/ljh/tmp/base`).Now md5sum values are different between origin file and that one copyed to filer.
If you copy that file from mounted dir to local,the thrid  md5sum value generated.The end of the file is truncated if you copy out from mounted dir. I use beyond4compare to get this result.

**Expected behavior**
File keep the same after copy in / out from filer.

**Screenshots**
I use md5sum for file checking.

**Additional context**
I have tested this problem on other machine which booted with Ubuntu and Centos7 ,they work as expected.

**Comment by Jevi06** [comment]
Its a strange problem ,cause it work as expected on other nodes,the same deploy steps,the same seaweedfs version but not the same result.
The different spec between nodes is os and kernel version,so it is probably caused by them. I have checked the disk,that is normal,but no clue for solve it .

**Comment by chrislusf** [comment]
I do not have a way to reproduce the env. Any specific commands?

```
docker$ docker run --rm -it --network seaweedfs_default --device /dev/fuse --cap-add SYS_ADMIN --entrypoint /bin/sh chrislusf/seaweedfs:1.70
/ # apk add fuse git tmux
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/12) Installing fuse-common (3.9.0-r0)
(2/12) Installing fuse (2.9.8-r2)
(3/12) Installing ca-certificates (20191127-r1)
(4/12) Installing nghttp2-libs (1.40.0-r0)
(5/12) Installing libcurl (7.67.0-r0)
(6/12) Installing expat (2.2.9-r1)
(7/12) Installing pcre2 (10.34-r1)
(8/12) Installing git (2.24.1-r0)
(9/12) Installing ncurses-terminfo-base (6.1_p20200118-r2)
(10/12) Installing libevent (2.1.11-r0)
(11/12) Installing ncurses-libs (6.1_p20200118-r2)
(12/12) Installing tmux (3.0a-r1)
Executing busybox-1.31.1-r9.trigger
Executing ca-certificates-20191127-r1.trigger
OK: 24 MiB in 26 packages
/ # cat /etc/*-release
3.11.5
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.11.5
PRETTY_NAME="Alpine Linux v3.11"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
/ #
```

**Comment by chrislusf** [comment]
I am able to create a docker image. Here are my steps:

1. Change `docker/Dockerfile.local` to `FROM centos:centos7.7.1908 AS final` on the first line, and then `make dev`.
2. yum install fuse

**Comment by Jevi06** [comment]
> I am able to create a docker image similar to your env. Here are my steps:
> 
> 1. Change `docker/Dockerfile.local` to `FROM centos:centos7.7.1908 AS final` on the first line, and then `make dev`.
> 2. docker run --rm -it --network seaweedfs_default --device /dev/fuse --cap-add SYS_ADMIN --entrypoint /bin/sh chrislusf/seaweedfs:local
> 
> Then
> 
> 1. yum install fuse
> 2. yum install tmux
> 
> In one window
> 
> ```
> [root@0d23a8fc36b8 /]# mkdir /mnt/seaweedfs
> [root@0d23a8fc36b8 /]# weed mount -filer filer:8888 -dir /mnt/seaweedfs
> This is SeaweedFS version 30GB 1.70 linux amd64
> mount point owner uid=0 gid=0 mode=drwxr-xr-x
> current uid=0 gid=0
> ```
> 
> In another window
> 
> ```
> [root@0d23a8fc36b8 /]# mkdir /mnt/seaweedfs/tt/
> [root@0d23a8fc36b8 /]# cp f.mp4 /mnt/seaweedfs/tt/
> [root@0d23a8fc36b8 /]# diff f.mp4 /mnt/seaweedfs/tt/
> [root@0d23a8fc36b8 /]# cmp f.mp4 /mnt/seaweedfs/tt/f.mp4
> ```
> 
> The f.mp4 is downloaded from youtube

`cmp`'s output is one thing that confused me...,
I will use ur steps for testing

**Comment by Jevi06** [comment]
```docker-compose -f local-dev-compose.yml -p seaweedfs up
Recreating seaweedfs_master_1 ... done
Recreating seaweedfs_volume_1 ... 

ERROR: for seaweedfs_volume_1  a bytes-like object is required, not 'str'

ERROR: for volume  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 261, in _raise_for_status
  File "site-packages/requests/models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/e97543c55bb41469257204050bf543d1eb3df2ba10de38af5f486a6aa9ea0388/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compose/service.py", line 625, in start_container
  File "compose/container.py", line 241, in start
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 1095, in start
  File "site-packages/docker/api/client.py", line 263, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'driver failed programming external connectivity on endpoint seaweedfs_volume_1 (390e045bc4322af2c6fbb25f9b8dca71d7f4d29cad9b08b9209a85df8812edbe): Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 128, in perform_command
  File "compose/cli/main.py", line 1107, in up
  File "compose/cli/main.py", line 1103, in up
  File "compose/project.py", line 570, in up
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/project.py", line 556, in do
  File "compose/service.py", line 563, in execute_convergence_plan
  File "compose/service.py", line 490, in _execute_convergence_recreate
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/service.py", line 483, in recreate
  File "compose/service.py", line 602, in recreate_container
  File "compose/service.py", line 627, in start_container
TypeError: a bytes-like object is required, not 'str'
[22390] Failed to execute script docker-compose
make: *** [dev] Error 255
```

**Comment by Jevi06** [comment]
```python
> Recreating seaweedfs_master_1 ... done
> Recreating seaweedfs_volume_1 ... 
> 
> ERROR: for seaweedfs_volume_1  a bytes-like object is required, not 'str'
> 
> ERROR: for volume  a bytes-like object is required, not 'str'
> Traceback (most recent call last):
>   File "site-packages/docker/api/client.py", line 261, in _raise_for_status
>   File "site-packages/requests/models.py", line 940, in raise_for_status
> requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/e97543c55bb41469257204050bf543d1eb3df2ba10de38af5f486a6aa9ea0388/start
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "compose/service.py", line 625, in start_container
>   File "compose/container.py", line 241, in start
>   File "site-packages/docker/utils/decorators.py", line 19, in wrapped
>   File "site-packages/docker/api/container.py", line 1095, in start
>   File "site-packages/docker/api/client.py", line 263, in _raise_for_status
>   File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
> docker.errors.APIError: 500 Server Error: Internal Server Error ("b'driver failed programming external connectivity on endpoint seaweedfs_volume_1 (390e045bc4322af2c6fbb25f9b8dca71d7f4d29cad9b08b9209a85df8812edbe): Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use'")
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "bin/docker-compose", line 6, in <module>
>   File "compose/cli/main.py", line 72, in main
>   File "compose/cli/main.py", line 128, in perform_command
>   File "compose/cli/main.py", line 1107, in up
>   File "compose/cli/main.py", line 1103, in up
>   File "compose/project.py", line 570, in up
>   File "compose/parallel.py", line 112, in parallel_execute
>   File "compose/parallel.py", line 210, in producer
>   File "compose/project.py", line 556, in do
>   File "compose/service.py", line 563, in execute_convergence_plan
>   File "compose/service.py", line 490, in _execute_convergence_recreate
>   File "compose/parallel.py", line 112, in parallel_execute
>   File "compose/parallel.py", line 210, in producer
>   File "compose/service.py", line 483, in recreate
>   File "compose/service.py", line 602, in recreate_container
>   File "compose/service.py", line 627, in start_container
> TypeError: a bytes-like object is required, not 'str'
> [22390] Failed to execute script docker-compose
> make: *** [dev] Error 255
>
 ```


sry,cant make dev rule, and not familiar with docker-compose ....

**Comment by chrislusf** [comment]
Here are my exact steps to create the cluster for the step 1. Maybe you need to update docker. I am on 2.2.0.5.

```
docker$ pwd
/Users/chris/go/src/github.com/chrislusf/seaweedfs/docker
docker$ git diff Dockerfile.local
diff --git a/docker/Dockerfile.local b/docker/Dockerfile.local
index b4a7b650..ccf9c0e3 100644
--- a/docker/Dockerfile.local
+++ b/docker/Dockerfile.local
@@ -1,4 +1,4 @@
-FROM alpine AS final
+FROM centos:centos7.7.1908 AS final
 LABEL author="Chris Lu"
 COPY  ./weed /usr/bin/
 RUN mkdir -p /etc/seaweedfs
docker$ make dev
cd ../weed; GOOS=linux go build; mv weed ../docker/
docker build --no-cache -t chrislusf/seaweedfs:local -f Dockerfile.local .
Sending build context to Docker daemon  55.26MB
Step 1/17 : FROM centos:centos7.7.1908 AS final
 ---> 08d05d1d5859
Step 2/17 : LABEL author="Chris Lu"
 ---> Running in 8788c1e16906
Removing intermediate container 8788c1e16906
 ---> d72d4b0a6771
Step 3/17 : COPY  ./weed /usr/bin/
 ---> 47e2659cfe77
Step 4/17 : RUN mkdir -p /etc/seaweedfs
 ---> Running in 3a30b549711a
Removing intermediate container 3a30b549711a
 ---> 86638e54d95d
Step 5/17 : COPY ./filer.toml /etc/seaweedfs/filer.toml
 ---> 5a47c4626817
Step 6/17 : COPY ./entrypoint.sh /entrypoint.sh
 ---> 1d98a456a8e4
Step 7/17 : EXPOSE 18080
 ---> Running in 5afe855e4c32
Removing intermediate container 5afe855e4c32
 ---> 203f27baa6f6
Step 8/17 : EXPOSE 8080
 ---> Running in 318c91f7762b
Removing intermediate container 318c91f7762b
 ---> fb09cd94c273
Step 9/17 : EXPOSE 18888
 ---> Running in 4d9960bfacfd
Removing intermediate container 4d9960bfacfd
 ---> 50ebb2214b91
Step 10/17 : EXPOSE 8888
 ---> Running in 13bc9332c0bf
Removing intermediate container 13bc9332c0bf
 ---> fae8cadc7a87
Step 11/17 : EXPOSE 19333
 ---> Running in dfefbf059a9f
Removing intermediate container dfefbf059a9f
 ---> 542716c29791
Step 12/17 : EXPOSE 9333
 ---> Running in 0cfa4d9d41f2
Removing intermediate container 0cfa4d9d41f2
 ---> 6b9cb077fd94
Step 13/17 : EXPOSE 8333
 ---> Running in 3a20d12d321a
Removing intermediate container 3a20d12d321a
 ---> a333dc3f5060
Step 14/17 : RUN mkdir -p /data/filerldb2
 ---> Running in 6989ea395d0a
Removing intermediate container 6989ea395d0a
 ---> 5602054b747e
Step 15/17 : VOLUME /data
 ---> Running in 437322106dbe
Removing intermediate container 437322106dbe
 ---> 357c6750dddc
Step 16/17 : RUN chmod +x /entrypoint.sh
 ---> Running in 011d10701a54
Removing intermediate container 011d10701a54
 ---> 500db5b1bad0
Step 17/17 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Running in e359bfb70b2f
Removing intermediate container e359bfb70b2f
 ---> 60c66afe71a9
Successfully built 60c66afe71a9
Successfully tagged chrislusf/seaweedfs:local
rm ./weed
docker-compose -f local-dev-compose.yml -p seaweedfs up
WARNING: Found orphan containers (seaweedfs_cronjob_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Recreating seaweedfs_master_1 ... done
Recreating seaweedfs_volume_1 ... done
Recreating seaweedfs_filer_1  ... done
Recreating seaweedfs_s3_1     ... done
Attaching to seaweedfs_master_1, seaweedfs_volume_1, seaweedfs_filer_1, seaweedfs_s3_1
filer_1   | I0404 05:12:59     1 leveldb2_store.go:40] filer store leveldb2 dir: /data/filerldb2
master_1  | I0404 05:12:58     1 file_util.go:20] Folder /data Permission: -rwxr-xr-x
volume_1  | I0404 05:12:59     1 file_util.go:20] Folder /data Permission: -rwxr-xr-x
filer_1   | I0404 05:12:59     1 file_util.go:20] Folder /data/filerldb2 Permission: -rwxr-xr-x
master_1  | I0404 05:12:58     1 master_server.go:104] Volume Size Limit is 1024 MB
filer_1   | I0404 05:12:59     1 configuration.go:25] Configure filer for leveldb2
volume_1  | I0404 05:12:59     1 volume_loading.go:104] loading index /data/4.idx to memory
volume_1  | I0404 05:12:59     1 volume_loading.go:104] loading index /data/6.idx to memory
filer_1   | I0404 05:12:59     1 filer.go:133] Start Seaweed Filer 30GB 1.70 at :8888
master_1  | I0404 05:12:58     1 master_server.go:192] adminScripts:
master_1  | I0404 05:12:58     1 master.go:113] Start Seaweed Master 30GB 1.70 at 0.0.0.0:9333
master_1  | I0404 05:12:58     1 raft_server.go:47] Starting RaftServer with master:9333
volume_1  | I0404 05:12:59     1 disk_location.go:81] data file /data/6.idx, replicaPlacement=000 v=3 size=497936 ttl=
master_1  | I0404 05:12:58     1 raft_server.go:87] current cluster leader:
master_1  | I0404 05:12:58     1 master_server.go:147] [ master:9333 ] I am the leader!
volume_1  | I0404 05:12:59     1 disk_location.go:81] data file /data/4.idx, replicaPlacement=000 v=3 size=67352 ttl=
master_1  | I0404 05:12:58     1 master.go:137] Start Seaweed Master 30GB 1.70 grpc server at 0.0.0.0:19333
master_1  | I0404 05:12:58     1 master_grpc_server.go:252] + client master@172.18.0.2:33760
volume_1  | I0404 05:12:59     1 volume_loading.go:104] loading index /data/3.idx to memory
master_1  | I0404 05:12:59     1 node.go:278] topo adds child DefaultDataCenter
master_1  | I0404 05:12:59     1 node.go:278] topo:DefaultDataCenter adds child DefaultRack
master_1  | I0404 05:12:59     1 node.go:278] topo:DefaultDataCenter:DefaultRack adds child volume:8080
master_1  | I0404 05:12:59     1 master_grpc_server.go:72] added volume server volume:8080
volume_1  | I0404 05:12:59     1 volume_loading.go:104] loading index /data/1.idx to memory
master_1  | I0404 05:12:59     1 volume_layout.go:243] Volume 4 becomes writable
master_1  | I0404 05:12:59     1 volume_layout.go:243] Volume 1 becomes writable
master_1  | I0404 05:12:59     1 volume_layout.go:243] Volume 3 becomes writable
master_1  | I0404 05:12:59     1 volume_layout.go:243] Volume 5 becomes writable
master_1  | I0404 05:12:59     1 volume_layout.go:243] Volume 2 becomes writable
master_1  | I0404 05:12:59     1 volume_layout.go:243] Volume 7 becomes writable
master_1  | I0404 05:12:59     1 volume_layout.go:243] Volume 6 becomes writable
master_1  | I0404 05:12:59     1 master_grpc_server.go:111] master see new volume 4 from volume:8080
master_1  | I0404 05:12:59     1 master_grpc_server.go:111] master see new volume 1 from volume:8080
master_1  | I0404 05:12:59     1 master_grpc_server.go:111] master see new volume 3 from volume:8080
master_1  | I0404 05:12:59     1 master_grpc_server.go:111] master see new volume 5 from volume:8080
master_1  | I0404 05:12:59     1 master_grpc_server.go:111] master see new volume 2 from volume:8080
master_1  | I0404 05:12:59     1 master_grpc_server.go:111] master see new volume 7 from volume:8080
master_1  | I0404 05:12:59     1 master_grpc_server.go:111] master see new volume 6 from volume:8080
master_1  | I0404 05:12:59     1 master_grpc_server.go:157] master send to master@172.18.0.2:33760: url:"volume:8080" public_url:"volume:8080" new_vids:4 new_vids:1 new_vids:3 new_vids:5 new_vids:2 new_vids:7 new_vids:6
volume_1  | I0404 05:12:59     1 disk_location.go:81] data file /data/1.idx, replicaPlacement=000 v=3 size=219576 ttl=
volume_1  | I0404 05:12:59     1 volume_loading.go:104] loading index /data/2.idx to memory
master_1  | I0404 05:12:59     1 master_grpc_server.go:252] + client filer@172.18.0.4:18888
volume_1  | I0404 05:12:59     1 disk_location.go:81] data file /data/3.idx, replicaPlacement=000 v=3 size=21786056 ttl=
volume_1  | I0404 05:12:59     1 volume_loading.go:104] loading index /data/5.idx to memory
volume_1  | I0404 05:12:59     1 disk_location.go:81] data file /data/5.idx, replicaPlacement=000 v=3 size=4255064 ttl=
volume_1  | I0404 05:12:59     1 disk_location.go:81] data file /data/2.idx, replicaPlacement=000 v=3 size=4256152 ttl=
volume_1  | I0404 05:12:59     1 volume_loading.go:104] loading index /data/7.idx to memory
volume_1  | I0404 05:12:59     1 disk_location.go:81] data file /data/7.idx, replicaPlacement=000 v=3 size=17275976 ttl=
volume_1  | I0404 05:12:59     1 disk_location.go:117] Store started on dir: /data with 7 volumes max 0
volume_1  | I0404 05:12:59     1 disk_location.go:120] Store started on dir: /data with 0 ec shards
volume_1  | I0404 05:12:59     1 volume_grpc_client_to_master.go:27] Volume server start with seed master nodes: [master:9333]
volume_1  | I0404 05:12:59     1 volume.go:278] Start Seaweed volume server 30GB 1.70 at 0.0.0.0:8080
volume_1  | I0404 05:12:59     1 volume_grpc_client_to_master.go:71] Heartbeat to: master:9333
volume_1  | I0404 05:12:59     1 store.go:424] disk /data max 21 unclaimedSpace:15991MB, unused:7121MB volumeSizeLimit:1024/MB
s3_1      | I0404 05:13:00     1 s3.go:138] S3 read filer buckets dir: /buckets
s3_1      | I0404 05:13:00     1 s3.go:145] connected to filer filer:8888 grpc address filer:18888
s3_1      | I0404 05:13:00     1 s3.go:178] Start Seaweed S3 API Server 30GB 1.70 at http port 8333
master_1  | I0404 05:13:01     1 master_server.go:144] state change: &{typ:stateChange source:0xc0002d5320 value:candidate prevValue:follower}
master_1  | I0404 05:13:01     1 master_server.go:144] state change: &{typ:stateChange source:0xc0002d5320 value:leader prevValue:candidate}
master_1  | I0404 05:13:01     1 master_server.go:138] event: &{typ:leaderChange source:0xc0002d5320 value:master:9333 prevValue:}
master_1  | I0404 05:13:01     1 master_server.go:140] [ master:9333 ] master:9333 becomes leader.
```

**Comment by chrislusf** [comment]
Actually you do not need to follow my steps. I was just showing how to make it reproducible.

**Comment by Jevi06** [comment]
because docker container shares the same kernel of you host machine,you may have not reproduced the problem.
Here is what weed behaviour on my pc when do IO operation:
```python
[root@nobody]# cp images/fullViewPic.jpg tmp/base/buckets/
[root@nobody]# diff images/fullViewPic.jpg tmp/base/buckets/fullViewPic.jpg 
[root@nobody]# cmp images/fullViewPic.jpg tmp/base/buckets/fullViewPic.jpg 
[root@nobody]# md5sum images/fullViewPic.jpg tmp/base/buckets/fullViewPic.jpg 
           cff9e166a581e0a4091e057115f7bd40  images/fullViewPic.jpg
           f7aad3a31c30918ece437ed6470cf92d  tmp/base/buckets/fullViewPic.jpg
```
As you can see,the `diff` and `cap` show the two files are the same ,but `md5sum` not.

**Comment by chrislusf** [comment]
could you please share the `fullViewPic.jpg` file? just in case it is related to the file content.

**Comment by Jevi06** [comment]
> could you please share the `fullViewPic.jpg` file? just in case it is related to the file content.

It does exist some files keep the same after cp in/out ,but image and videos always corrupt in my test.
Here is the image,
![fullViewPic](https://user-images.githubusercontent.com/17949749/78635967-ebf28f80-78d9-11ea-8f3d-1c5eb62ddf40.jpg)

**Comment by chrislusf** [comment]
thanks. However , can not reproduce:

```
[root@aadd1ac3ea44 /]# md5sum t.jpg /mnt/seaweedfs/tt/t.jpg
cff9e166a581e0a4091e057115f7bd40  t.jpg
cff9e166a581e0a4091e057115f7bd40  /mnt/seaweedfs/tt/t.jpg
```

**Comment by Jevi06** [comment]
> thanks. However , can not reproduce:
> 
> ```
> [root@aadd1ac3ea44 /]# md5sum t.jpg /mnt/seaweedfs/tt/t.jpg
> cff9e166a581e0a4091e057115f7bd40  t.jpg
> cff9e166a581e0a4091e057115f7bd40  /mnt/seaweedfs/tt/t.jpg
> ```


I have reproduced it in  virtural box using  iso file below,

> 链接：https://pan.baidu.com/s/1z1VYcwA9DwrM01V1xpykEA 
> 提取码：qv5r

unzip that file and import from virtual box ....
Its a little tedious,,but I hope this bug colud be fix early rather then late
If BaiDuYun is not accessable for you,tell me your way for transfering file

**Comment by chrislusf** [comment]
Do you have other ways to download? BaiDuYun needs to install something to download, and need to install phone app to scan to login.

**Comment by Jevi06** [comment]
> Do you have other ways to download? BaiDuYun needs to install something to download, and need to install phone app to scan to login.

> 您有一份文件待查收！即刻点击链接获取文件：https://c-t.work/s/e1e732c1f8f14a 或进入 cowtransfer.com 获取，在首页输入取件码：pkg2kp（24小时内有效）
try this.

**Comment by Jevi06** [comment]
I have test using another iso in virtual box,and the result is expected.So  this bug may only occur in that version os.

**Comment by chrislusf** [comment]
which version is newer?

**Comment by Jevi06** [comment]
> still downloading. which os version is newer? or which fuse version is newer?

fuse are the same which download using yum from mirros.aliyun.com,the os version of  worked one is newer

**Comment by Jevi06** [comment]
And there are other two nodes which:
`centos version are the same`
`fuse are the same`
`kernel not the same`
the  kernel version of that worked one is `Linux 3.10.0-1062.el7.x86_64`
the other kernel version is: `Linux 3.10.0-957.el7.x86_64`

**Comment by Jevi06** [comment]
just acquire a skill that "yum update" could update os-version and kernel-version.
And after update os and kernerl from:

> CentOS Linux release 7.6.1810 (Core)
> Linux 3.10.0-957.el7.x86_64

To:

> CentOS Linux release 7.7.1908 (Core)
> Linux 3.10.0-1062.18.1.el7.x86_64

the problem disappear itself.

**Comment by chrislusf** [comment]
Seems we can close this now.

But This could be related a bug I just fixed.  Please try 1.72.

**Comment by Jevi06** [comment]
> Seems we can close this now.
> 
> But this could be related a bug I just fixed. Please try 1.72.

Thanks,YOU FIXED IT.(I use  version 1.73 )
