### ISSUE TITLE
multiple weed mount problem

### ISSUE THREAD

**Issue by michelelaporta** [chrislusf/seaweedfs#1350]
**Describe the bug**
Cannot add multiple weed mount

**System Setup**

```
Ubuntu 20.04
weed version version 8000GB 1.79 linux amd64
weed mount -filer=localhost:8888 -dir=/tmp/dataset -filer.path=/dataset &
weed mount -filer=localhost:8888 -dir=/tmp/output -filer.path=/output &
```

- if using filer, show the content of `filer.toml`
```
[leveldb2]
enabled = true
dir = "."
```
- the content of `fuse.conf`
```
# /etc/fuse.conf - Configuration file for Filesystem in Userspace (FUSE)
user_allow_other
```

**Expected behavior**
Have multiple weed mount working.Filer should also show the mount  if it's an empty directory.

**Problems **
 The filer ui doesn't show empty mount at all. It only shows when first file is copied.

The first mount works ok I can add from filer ui or copy to /tmp/dataset directly . 
The second directory is mounted:

```
I0605 11:57:25 67910 mount_std.go:187] mounted localhost:8888/output to /tmp/output
```
Adding a file from filer ui works ok.
```
/output
c4.png | image/png | 3.0 MB | 2020-06-05 12:12

```
but adding a file to the second directory directly produces zero size file:

```
/output
raspistill.sh 	  	0 B  	2020-06-05 11:58
rpi3-opencv4.txt 	0 B  	2020-06-05 11:57 
```

```
cp raspistill.sh /tmp/output/
2020-06-05 14:18:11.203408 I | fuse: panic in handler for Flush [ID=0x98 Node=0x5 Uid=1000 Gid=1000 Pid=170782] 0x1 fl=0x0 lk=0x54cec2e61969cf8c: runtime error: index out of range [0] with length 0
goroutine 155 [running]:
github.com/seaweedfs/fuse/fs.(*Server).serve.func2(0x205a600, 0xc00028cc30, 0xc000287eb0, 0xc000287e26)
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v0.0.0-20190510212405-310228904eff/fs/serve.go:861 +0x1a2
panic(0x1ad5ba0, 0xc00059e3a0)
	/home/travis/.gimme/versions/go1.14.3.linux.amd64/src/runtime/panic.go:969 +0x166
github.com/chrislusf/seaweedfs/weed/util/chunk_cache.(*OnDiskCacheLayer).setChunk(0xc000200860, 0x10, 0xc000049200, 0x1c, 0x600)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/util/chunk_cache/on_disk_cache_layer.go:45 +0x20a
github.com/chrislusf/seaweedfs/weed/util/chunk_cache.(*ChunkCache).doSetChunk(0xc0000b31c0, 0xc00028faf0, 0xc, 0xc000049200, 0x1c, 0x600)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/util/chunk_cache/chunk_cache.go:95 +0xb6
github.com/chrislusf/seaweedfs/weed/util/chunk_cache.(*ChunkCache).SetChunk(0xc0000b31c0, 0xc00028faf0, 0xc, 0xc000049200, 0x1c, 0x600)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/util/chunk_cache/chunk_cache.go:79 +0xaf
github.com/chrislusf/seaweedfs/weed/filesys.(*ContinuousDirtyPages).saveToStorage(0xc00019c2c0, 0x202e120, 0xc0001e2980, 0x0, 0x1c, 0xc000278808, 0x45123f, 0x10)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/dirty_page.go:188 +0x5d8
github.com/chrislusf/seaweedfs/weed/filesys.(*ContinuousDirtyPages).saveExistingLargestPageToStorage(0xc00019c2c0, 0x10, 0x10, 0x185a460, 0xc000278938)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/dirty_page.go:129 +0xb2
github.com/chrislusf/seaweedfs/weed/filesys.(*ContinuousDirtyPages).saveExistingPagesToStorage(0xc00019c2c0, 0x1, 0xc00020e1e4, 0x4, 0xc000278998, 0x40a26b)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/dirty_page.go:107 +0x4f
github.com/chrislusf/seaweedfs/weed/filesys.(*ContinuousDirtyPages).FlushToStorage(0xc00019c2c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/dirty_page.go:97 +0x82
github.com/chrislusf/seaweedfs/weed/filesys.(*FileHandle).Flush(0xc0000a0320, 0x2067200, 0xc00019c400, 0xc00028cc30, 0xc0000a0320, 0x1)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/filehandle.go:165 +0x127
github.com/seaweedfs/fuse/fs.(*Server).handleRequest(0xc0005d0180, 0x2067200, 0xc00019c400, 0x202b1c0, 0xc00064b560, 0xc000489c40, 0x205a600, 0xc00028cc30, 0xc000287eb0, 0x0, ...)
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v0.0.0-20190510212405-310228904eff/fs/serve.go:1288 +0x2f3a
github.com/seaweedfs/fuse/fs.(*Server).serve(0xc0005d0180, 0x205a600, 0xc00028cc30)
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v0.0.0-20190510212405-310228904eff/fs/serve.go:882 +0x2ba
github.com/seaweedfs/fuse/fs.(*Server).Serve.func1(0xc0005d0180, 0x205a600, 0xc00028cc30)
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v0.0.0-20190510212405-310228904eff/fs/serve.go:424 +0x6f
created by github.com/seaweedfs/fuse/fs.(*Server).Serve
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v0.0.0-20190510212405-310228904eff/fs/serve.go:422 +0x35a
cp: failed to close '/tmp/output/raspistill.sh': Errore di input/output
```

**Comment by chrislusf** [comment]
Can you try to set a different cache directory? `weed mount -cacheDir=xxx`

**Comment by michelelaporta** [comment]
Same story
```
mkdir master
mkdir data1
mkdir data2
mkdir mount1
mkdir mount2

weed scaffold -config=filer -output=.

weed master -mdir="./master" &
weed volume -dir="./data1" -max=10 -mserver=localhost:9333 -port=8480  &
weed volume -dir="./data2" -max=10 -mserver=localhost:9333 -port=8481  &
weed filer -port=8888 -master=localhost:9333 &
weed mount -filer=localhost:8888 -dir="./mount1" -filer.path=/dataset -cacheDir=/tmp/cache_1 &
weed mount -filer=localhost:8888 -dir="./mount2" -filer.path=/output -cacheDir=/tmp/cache_2 &
cp filer.toml ./mount1

```

mount is ok for both. Filer doesn't show empty mounted directories.  Try to copy a file into mounted file system directory:

```
2020-06-05 17:51:19.219481 I | fuse: panic in handler for Flush [ID=0x2a Node=0x2 Uid=1000 Gid=1000 Pid=17877] 0x1 fl=0x0 lk=0xb12c16280a875aae: runtime error: index out of range [0] with length 0
goroutine 105 [running]:
github.com/seaweedfs/fuse/fs.(*Server).serve.func2(0x205a600, 0xc0003d81e0, 0xc0003cdeb0, 0xc0003cde26)
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v0.0.0-20190510212405-310228904eff/fs/serve.go:861 +0x1a2
panic(0x1ad5ba0, 0xc0002b0420)
	/home/travis/.gimme/versions/go1.14.3.linux.amd64/src/runtime/panic.go:969 +0x166
github.com/chrislusf/seaweedfs/weed/util/chunk_cache.(*OnDiskCacheLayer).setChunk(0xc00000caa0, 0x1, 0xc000048c00, 0x21c, 0x600)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/util/chunk_cache/on_disk_cache_layer.go:45 +0x20a
github.com/chrislusf/seaweedfs/weed/util/chunk_cache.(*ChunkCache).doSetChunk(0xc0005a8ac0, 0xc00003f1b0, 0xc, 0xc000048c00, 0x21c, 0x600)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/util/chunk_cache/chunk_cache.go:95 +0xb6
github.com/chrislusf/seaweedfs/weed/util/chunk_cache.(*ChunkCache).SetChunk(0xc0005a8ac0, 0xc00003f1b0, 0xc, 0xc000048c00, 0x21c, 0x600)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/util/chunk_cache/chunk_cache.go:79 +0xaf
github.com/chrislusf/seaweedfs/weed/filesys.(*ContinuousDirtyPages).saveToStorage(0xc00035c100, 0x202e120, 0xc0001e25e0, 0x0, 0x21c, 0xc000433808, 0x45123f, 0x20)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/dirty_page.go:188 +0x5d8
github.com/chrislusf/seaweedfs/weed/filesys.(*ContinuousDirtyPages).saveExistingLargestPageToStorage(0xc00035c100, 0x10, 0x10, 0x185a460, 0xc000433938)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/dirty_page.go:129 +0xb2
github.com/chrislusf/seaweedfs/weed/filesys.(*ContinuousDirtyPages).saveExistingPagesToStorage(0xc00035c100, 0x1, 0xc00003f030, 0xd, 0xc000433998, 0x40a26b)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/dirty_page.go:107 +0x4f
github.com/chrislusf/seaweedfs/weed/filesys.(*ContinuousDirtyPages).FlushToStorage(0xc00035c100, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/dirty_page.go:97 +0x82
github.com/chrislusf/seaweedfs/weed/filesys.(*FileHandle).Flush(0xc000361d60, 0x2067200, 0xc000386b40, 0xc0003d81e0, 0xc000361d60, 0x1)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/filehandle.go:165 +0x127
github.com/seaweedfs/fuse/fs.(*Server).handleRequest(0xc00063a180, 0x2067200, 0xc000386b40, 0x202b1c0, 0xc0003ec3c0, 0xc00035c140, 0x205a600, 0xc0003d81e0, 0xc0003cdeb0, 0x2, ...)
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v0.0.0-20190510212405-310228904eff/fs/serve.go:1288 +0x2f3a
github.com/seaweedfs/fuse/fs.(*Server).serve(0xc00063a180, 0x205a600, 0xc0003d81e0)
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v0.0.0-20190510212405-310228904eff/fs/serve.go:882 +0x2ba
github.com/seaweedfs/fuse/fs.(*Server).Serve.func1(0xc00063a180, 0x205a600, 0xc0003d81e0)
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v0.0.0-20190510212405-310228904eff/fs/serve.go:424 +0x6f
created by github.com/seaweedfs/fuse/fs.(*Server).Serve
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v0.0.0-20190510212405-310228904eff/fs/serve.go:422 +0x35a

```

**Comment by chrislusf** [comment]
can you show the console output whens starting weed mount? 

do you see error like `failed to add cache`?

**Comment by michelelaporta** [comment]
The output of weed mount:

```
michele@mikdell:/tmp$ weed mount -filer=localhost:8888 -dir="./mount1" -filer.path=/dataset -cacheDir=/tmp/cache_1 &
[5] 7699
michele@mikdell:/tmp$ This is SeaweedFS version 8000GB 1.79 linux amd64
mount point owner uid=1000 gid=1000 mode=drwxrwxr-x
E0608 10:17:04  7699 on_disk_cache_layer.go:29] failed to add cache /tmp/cache_1/c0_1_0 : cannot create cache file /tmp/cache_1/c0_1_0.dat: open /tmp/cache_1/c0_1_0.dat: no such file or directory
E0608 10:17:04  7699 on_disk_cache_layer.go:29] failed to add cache /tmp/cache_1/c0_1_1 : cannot create cache file /tmp/cache_1/c0_1_1.dat: open /tmp/cache_1/c0_1_1.dat: no such file or directory
E0608 10:17:04  7699 on_disk_cache_layer.go:29] failed to add cache /tmp/cache_1/c0_1_2 : cannot create cache file /tmp/cache_1/c0_1_2.dat: open /tmp/cache_1/c0_1_2.dat: no such file or directory
E0608 10:17:04  7699 on_disk_cache_layer.go:29] failed to add cache /tmp/cache_1/c0_1_3 : cannot create cache file /tmp/cache_1/c0_1_3.dat: open /tmp/cache_1/c0_1_3.dat: no such file or directory
E0608 10:17:04  7699 on_disk_cache_layer.go:29] failed to add cache /tmp/cache_1/c1_4_0 : cannot create cache file /tmp/cache_1/c1_4_0.dat: open /tmp/cache_1/c1_4_0.dat: no such file or directory
E0608 10:17:04  7699 on_disk_cache_layer.go:29] failed to add cache /tmp/cache_1/c1_4_1 : cannot create cache file /tmp/cache_1/c1_4_1.dat: open /tmp/cache_1/c1_4_1.dat: no such file or directory
E0608 10:17:04  7699 on_disk_cache_layer.go:29] failed to add cache /tmp/cache_1/c1_4_2 : cannot create cache file /tmp/cache_1/c1_4_2.dat: open /tmp/cache_1/c1_4_2.dat: no such file or directory
E0608 10:17:04  7699 on_disk_cache_layer.go:29] failed to add cache /tmp/cache_1/c1_4_3 : cannot create cache file /tmp/cache_1/c1_4_3.dat: open /tmp/cache_1/c1_4_3.dat: no such file or directory
E0608 10:17:04  7699 on_disk_cache_layer.go:29] failed to add cache /tmp/cache_1/cache_0 : cannot create cache file /tmp/cache_1/cache_0.dat: open /tmp/cache_1/cache_0.dat: no such file or directory
E0608 10:17:04  7699 on_disk_cache_layer.go:29] failed to add cache /tmp/cache_1/cache_1 : cannot create cache file /tmp/cache_1/cache_1.dat: open /tmp/cache_1/cache_1.dat: no such file or directory
E0608 10:17:04  7699 on_disk_cache_layer.go:29] failed to add cache /tmp/cache_1/cache_2 : cannot create cache file /tmp/cache_1/cache_2.dat: open /tmp/cache_1/cache_2.dat: no such file or directory
E0608 10:17:04  7699 on_disk_cache_layer.go:29] failed to add cache /tmp/cache_1/cache_3 : cannot create cache file /tmp/cache_1/cache_3.dat: open /tmp/cache_1/cache_3.dat: no such file or directory
I0608 10:17:04  7699 leveldb_store.go:40] filer store dir: /tmp/cache_1/meta
I0608 10:17:04  7699 file_util.go:20] Folder /tmp/cache_1/meta Permission: -rwxr-xr-x
I0608 10:17:04  7699 meta_cache_init.go:13] synchronizing meta data ...
2020-06-08 10:17:04.912188 I | mount helper error: fusermount: unsafe option suid ignored
I0608 10:17:04  7620 filer_grpc_server_listen.go:98] + listener mount@127.0.0.1:59748
I0608 10:17:04  7620 filer_grpc_server_listen.go:25]  mount@127.0.0.1:59748 starts to subscribe /dataset from 2020-06-08 10:17:04.907836644 +0200 CEST
I0608 10:17:04  7699 mount_std.go:187] mounted localhost:8888/dataset to ./mount1

```

**Comment by chrislusf** [comment]
Need to set the cacheDir to an existing empty directory.

I will add code to create the directory if not exists already.

**Comment by michelelaporta** [comment]
Yes I see. I tested cache again with existing empty directory and it works correctly,but still the filer ui doesn't show the two mount points until some file is copy or uploded into.

**Comment by chrislusf** [comment]
you mean `/dataset` and `/output` from `-filer.path=` setting? this is expected. the path is created on first write.

**Comment by michelelaporta** [comment]
Yes I tested "the path is created on first write"  but I was expecting to mount  filer.path=/mount3 and filer ui shows http://localhost:8888/mount3 with the "empty" content of the mounted existing empty directory and not a HTTP 404.

**Comment by chrislusf** [comment]
Can not reproduce. I got 404 from `curl http://localhost:8888/non_existing_folder` if `weed mount -filer.path=/non_existing_folder`

**Comment by michelelaporta** [comment]
Yes I got 404 too . But I expected 200 OK with and empty directory and 404 Not Found.

**Comment by chrislusf** [comment]
you can try to create the directory first. For example, create a small file in the folder.
