### ISSUE TITLE
seaweedfs 1.82: weed volume fails with -dir volume,volume2,[...]

### ISSUE THREAD

**Issue by Radtoo** [chrislusf/seaweedfs#1366]
Seaweedfs version 8000GB 1.82 c48b407 linux amd64

Since around version 1.80 or 1,81, I had trouble starting volumes this way due to an index out of range error:
```
> weed volume -max=8,8,16,8,8,8 -rack=test -ip=192.168.1.3 -mserver=192.168.1.4:9333 -port=8995 -dir=/mnt/data01/SEAWEEDFS-DATA/,/mnt/data02/SEAWEEDFS-DATA/,/mnt/data03/SEAWEEDFS-DATA/,/mnt/data04/SEAWEEDFS-DATA/,/mnt/data05/SEAWEEDFS-DATA/,/mnt/data06/SEAWEEDFS-DATA/

I0621 04:56:05 11928 file_util.go:20] Folder /mnt/data01/SEAWEEDFS-DATA/ Permission: -rwxr-xr-x
I0621 04:56:05 11928 file_util.go:20] Folder /mnt/data02/SEAWEEDFS-DATA/ Permission: -rwxr-xr-x
I0621 04:56:05 11928 file_util.go:20] Folder /mnt/data03/SEAWEEDFS-DATA/ Permission: -rwxr-xr-x
I0621 04:56:05 11928 file_util.go:20] Folder /mnt/data04/SEAWEEDFS-DATA/ Permission: -rwxr-xr-x
I0621 04:56:05 11928 file_util.go:20] Folder /mnt/data05/SEAWEEDFS-DATA/ Permission: -rwxr-xr-x
I0621 04:56:05 11928 file_util.go:20] Folder /mnt/data06/SEAWEEDFS-DATA/ Permission: -rwxr-xr-x
I0621 04:56:05 11928 volume_loading.go:104] loading index /mnt/data01/SEAWEEDFS-DATA/15.idx to memory
I0621 04:56:05 11928 volume_loading.go:104] loading index /mnt/data01/SEAWEEDFS-DATA/16.idx to memory
I0621 04:56:05 11928 volume_loading.go:104] loading index /mnt/data01/SEAWEEDFS-DATA/2.idx to memory
I0621 04:56:05 11928 disk_location.go:86] data file /mnt/data01/SEAWEEDFS-DATA//15.idx, replicaPlacement=010 v=3 size=57926200 ttl=
I0621 04:56:05 11928 volume_loading.go:104] loading index /mnt/data01/SEAWEEDFS-DATA/3.idx to memory
I0621 04:56:05 11928 disk_location.go:86] data file /mnt/data01/SEAWEEDFS-DATA//16.idx, replicaPlacement=010 v=3 size=53525640 ttl=
I0621 04:56:05 11928 disk_location.go:86] data file /mnt/data01/SEAWEEDFS-DATA//2.idx, replicaPlacement=010 v=3 size=31458116640 ttl=
I0621 04:56:05 11928 disk_location.go:86] data file /mnt/data01/SEAWEEDFS-DATA//3.idx, replicaPlacement=010 v=3 size=31457995600 ttl=
I0621 04:56:05 11928 disk_location.go:122] Store started on dir: /mnt/data01/SEAWEEDFS-DATA/ with 4 volumes max 8
I0621 04:56:05 11928 disk_location.go:125] Store started on dir: /mnt/data01/SEAWEEDFS-DATA/ with 0 ec shards
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/storage.NewStore(0x20399c0, 0xc0001822f8, 0x2323, 0x7ffe864c85fc, 0xd, 0xc000575b80, 0x12, 0xc00028d5c0, 0x6, 0x6, ...)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/storage/store.go:55 +0x4a1
github.com/chrislusf/seaweedfs/weed/server.NewVolumeServer(0xc000468ac0, 0xc000468ac0, 0x7ffe864c85fc, 0xd, 0x2323, 0xc000575b80, 0x12, 0xc00028d5c0, 0x6, 0x6, ...)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/server/volume_server.go:71 +0x730
github.com/chrislusf/seaweedfs/weed/command.VolumeServerOptions.startVolumeServer(0xc0000ce968, 0xc0000ce978, 0xc00028d5c0, 0x6, 0x6, 0xc00020a280, 0x6, 0x8, 0xc00045ed10, 0xc00045ed20, ...)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/volume.go:189 +0x6df
github.com/chrislusf/seaweedfs/weed/command.runVolume(0x2ef84a0, 0xc00018c070, 0x0, 0x0, 0x0)``
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/volume.go:110 +0x117
main.main()
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/weed.go:66 +0x2f9

```

Individually starting the volumes on different ports seems to work fine. With the following I get no errors and all volumes show up in weed shell's "volume.list":
```
> weed volume -max=8 -rack=test -ip=192.168.1.3 -mserver=192.168.1.4:9333 -port=8995 -dir=/mnt/data01/SEAWEEDFS-DATA/ &
> weed volume -max=8 -rack=test -ip=192.168.1.3 -mserver=192.168.1.4:9333 -port=8996 -dir=/mnt/data02/SEAWEEDFS-DATA/ &
> weed volume -max=16 -rack=test -ip=192.168.1.3 -mserver=192.168.1.4:9333 -port=8997 -dir=/mnt/data03/SEAWEEDFS-DATA/ &
> weed volume -max=8 -rack=test -ip=192.168.1.3 -mserver=192.168.1.4:9333 -port=8998 -dir=/mnt/data04/SEAWEEDFS-DATA/ &
> weed volume -max=8 -rack=test -ip=192.168.1.3 -mserver=192.168.1.4:9333 -port=8999 -dir=/mnt/data05/SEAWEEDFS-DATA/ &
> weed volume -max=8 -rack=test -ip=192.168.1.3 -mserver=192.168.1.4:9333 -port=9900 -dir=/mnt/data06/SEAWEEDFS-DATA/ &
```
But that occupies more ports and of course doesn't allow balancing with volume.balance between racks anymore (modeled by only running one volume server each). Because instead of one volume server with 56 volumes max encompassing the whole rack, the max has 16 now.

**Comment by chrislusf** [comment]
Thanks for the helpful details! I added a fix.

To get around it for now, you can append `-minFreeSpacePercent=0,0,0,0,0,0` to your current `weed server` command.
