### ISSUE TITLE
Filer panic

### ISSUE THREAD

**Issue by yourchanges** [chrislusf/seaweedfs#1395]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs

Filer panic on our PROD env with seaweedfs v1.84

```
panic: runtime error: slice bounds out of range [:4194617] with capacity 4194304

goroutine 263 [running]:
github.com/chrislusf/seaweedfs/weed/util/log_buffer.(*LogBuffer).AddToBuffer(0xc00043e750, 0xc00a1a0810, 0x10, 0x10, 0xc006d7b040, 0x12d, 0x12d)
	/home/lee/workspace/seaweedfs3/weed/util/log_buffer/log_buffer.go:101 +0x716
github.com/chrislusf/seaweedfs/weed/filer2.(*MetaAggregator).subscribeToOneFiler.func1(0xc006ed30e0, 0xc006ed30e0, 0x0)
	/home/lee/workspace/seaweedfs3/weed/filer2/meta_aggregator.go:56 +0x1f4
github.com/chrislusf/seaweedfs/weed/filer2.(*MetaAggregator).subscribeToOneFiler.func2(0x21235a0, 0xc0003682b0, 0x4e73b1, 0x3018cb0)
	/home/lee/workspace/seaweedfs3/weed/filer2/meta_aggregator.go:80 +0x201
github.com/chrislusf/seaweedfs/weed/pb.WithGrpcFilerClient.func1(0xc000701180, 0x13, 0xc00098be80)
	/home/lee/workspace/seaweedfs3/weed/pb/grpc_client_server.go:178 +0x76
github.com/chrislusf/seaweedfs/weed/pb.WithCachedGrpcClient(0xc00098be70, 0xc000044940, 0x13, 0xc00098be80, 0x1, 0x1, 0xc000110000, 0x7f4d6a1e7108)
	/home/lee/workspace/seaweedfs3/weed/pb/grpc_client_server.go:105 +0x150
github.com/chrislusf/seaweedfs/weed/pb.WithGrpcFilerClient(0xc000044940, 0x13, 0x20c5ce0, 0xc00000f000, 0xc00098bf78, 0x0, 0x454b1a)
	/home/lee/workspace/seaweedfs3/weed/pb/grpc_client_server.go:176 +0x9f
github.com/chrislusf/seaweedfs/weed/pb.WithFilerClient(0xc0001491e0, 0x12, 0x20c5ce0, 0xc00000f000, 0xc00098bf78, 0x2, 0x2)
	/home/lee/workspace/seaweedfs3/weed/pb/grpc_client_server.go:170 +0x14c
github.com/chrislusf/seaweedfs/weed/filer2.(*MetaAggregator).subscribeToOneFiler(0xc000152080, 0xc0001491e0, 0x12, 0x16230594ad1a6f1b)
	/home/lee/workspace/seaweedfs3/weed/filer2/meta_aggregator.go:61 +0xc8
created by github.com/chrislusf/seaweedfs/weed/filer2.(*MetaAggregator).StartLoopSubscribe
	/home/lee/workspace/seaweedfs3/weed/filer2/meta_aggregator.go:42 +0x8e

```

**Comment by chrislusf** [comment]
This should have been fixed already in 1.85
