### ISSUE TITLE
fuse: panic in handler for Rename 

### ISSUE THREAD

**Issue by angad-k** [chrislusf/seaweedfs#1400]
**Describe the bug**
Trying to run a mongodb container mounted on directory which is mounted on SeaweedFS. The mount and the container give the following errors before the container terminates :
Container logs : 
<pre>
2020-07-24T15:19:09.341+0000 I CONTROL  [initandlisten] MongoDB starting : pid=10 port=27017 dbpath=/data/db 64-bit host=bba7d8cf1172
2020-07-24T15:19:09.341+0000 I CONTROL  [initandlisten] db version v3.4.4
2020-07-24T15:19:09.341+0000 I CONTROL  [initandlisten] git version: 888390515874a9debd1b6c5d36559ca86b44babd
2020-07-24T15:19:09.341+0000 I CONTROL  [initandlisten] OpenSSL version: LibreSSL 2.5.5
2020-07-24T15:19:09.341+0000 I CONTROL  [initandlisten] allocator: system
2020-07-24T15:19:09.341+0000 I CONTROL  [initandlisten] modules: none
2020-07-24T15:19:09.341+0000 I CONTROL  [initandlisten] build environment:
2020-07-24T15:19:09.341+0000 I CONTROL  [initandlisten]     distarch: x86_64
2020-07-24T15:19:09.341+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2020-07-24T15:19:09.341+0000 I CONTROL  [initandlisten] options: {}
2020-07-24T15:19:09.349+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3413M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2020-07-24T15:19:09.369+0000 E STORAGE  [initandlisten] WiredTiger error (5) [1595603949:369695][10:0x7f7e7348bdc0], connection: /data/db/WiredTiger.turtle.set to /data/db/WiredTiger.turtle: file-rename: rename: I/O error
2020-07-24T15:19:09.383+0000 I -        [initandlisten] Assertion: 28595:5: I/O error src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp 267
2020-07-24T15:19:09.411+0000 I STORAGE  [initandlisten] exception in initAndListen: 28595 5: I/O error, terminating
2020-07-24T15:19:09.411+0000 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
2020-07-24T15:19:09.411+0000 I NETWORK  [initandlisten] removing socket file: /tmp/mongodb-27017.sock
2020-07-24T15:19:09.411+0000 I NETWORK  [initandlisten] shutdown: going to flush diaglog...
2020-07-24T15:19:09.411+0000 I CONTROL  [initandlisten] now exiting
2020-07-24T15:19:09.411+0000 I CONTROL  [initandlisten] shutting down with code:100

</pre>

Mount error : 
<pre>
fuse: panic in handler for Rename [ID=0x170 Node=0x1 Uid=100 Gid=101 Pid=25386] from "WiredTiger.turtle.set" to dirnode 0x1 "WiredTiger.turtle": interface conversion: fs.Node is nil, not *filesys.Dir
goroutine 672 [running]:
github.com/seaweedfs/fuse/fs.(*Server).serve.func2(0x2815760, 0xc000556300, 0xc00aac1eb0, 0xc00aac1e26)
	/home/angad/gasper/vendor/github.com/seaweedfs/fuse/fs/serve.go:861 +0x1a2
panic(0x1f8a380, 0xc00c88c7b0)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/chrislusf/seaweedfs/weed/filesys.(*FsNode).connectToParent(0xc00bd0ddb0, 0xc00044e6e0)
	/home/angad/gasper/vendor/github.com/chrislusf/seaweedfs/weed/filesys/fscache.go:150 +0x1e5
github.com/chrislusf/seaweedfs/weed/filesys.(*FsCache).Move(0xc0004989e0, 0xc00c969140, 0x25, 0xc00c969110, 0x21, 0x0)
	/home/angad/gasper/vendor/github.com/chrislusf/seaweedfs/weed/filesys/fscache.go:135 +0x2a6
github.com/chrislusf/seaweedfs/weed/filesys.(*Dir).Rename(0xc00b7bc810, 0x2827a60, 0xc00c96d140, 0xc000556300, 0x27d72a0, 0xc00b7bc810, 0x0, 0x0)
	/home/angad/gasper/vendor/github.com/chrislusf/seaweedfs/weed/filesys/dir_rename.go:65 +0x85a
github.com/seaweedfs/fuse/fs.(*Server).handleRequest(0xc0005503c0, 0x2827a60, 0xc00c96d140, 0x27d72a0, 0xc00b7bc810, 0xc00049e6c0, 0x2815760, 0xc000556300, 0xc00aac1eb0, 0x0, ...)
	/home/angad/gasper/vendor/github.com/seaweedfs/fuse/fs/serve.go:1343 +0x22a4
github.com/seaweedfs/fuse/fs.(*Server).serve(0xc0005503c0, 0x2815760, 0xc000556300)
	/home/angad/gasper/vendor/github.com/seaweedfs/fuse/fs/serve.go:882 +0x2ba
github.com/seaweedfs/fuse/fs.(*Server).Serve.func1(0xc0005503c0, 0x2815760, 0xc000556300)
	/home/angad/gasper/vendor/github.com/seaweedfs/fuse/fs/serve.go:424 +0x6f
created by github.com/seaweedfs/fuse/fs.(*Server).Serve
	/home/angad/gasper/vendor/github.com/seaweedfs/fuse/fs/serve.go:422 +0x35a
</pre>

**System Setup**
- Started SeaweedFS server with `weed server -filer=true` and mounted the directory with `weed mount` command. 
- OS version
<pre>
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
</pre>
- Just the default filer.toml

**Expected behavior**
Container should run without any error.

**Comment by chrislusf** [comment]
added a fix to remove the unused code
