### ISSUE TITLE
elasticsearch start error AsyncLucenePersistedState#updateTask][T#1]], exiting  on a seaweedFS mounted volume

### ISSUE THREAD

**Issue by renweijun** [chrislusf/seaweedfs#1415]
**Describe the bug**
elasticsearch start error "nodes/0/_state/segments_4"  on a seaweedFS mounted volume

**System Setup**
-start master 3 
>"weed master -ip 10.0.9.1 -mdir /data/seaweedfs_master_data -peers 10.0.9.1:9333,10.0.9.2:9333,10.0.9.3:9333 -port 9333 -metrics.address pushgateway:9292  -defaultReplication 001 
weed master -ip 10.0.9.2 -mdir /data/seaweedfs_master_data -peers 10.0.9.1:9333,10.0.9.2:9333,10.0.9.3:9333 -port 9333 -metrics.address pushgateway:9292  -defaultReplication 001 
weed master -ip 10.0.9.3 -mdir /data/seaweedfs_master_data -peers 10.0.9.1:9333,10.0.9.2:9333,10.0.9.3:9333 -port 9333 -metrics.address pushgateway:9292  -defaultReplication 001 "
- start volume  30 
>"weed volume -max=100,100,100,100,100 -dir /data1/seaweedfs_data,/data2/seaweedfs_data,/data3/seaweedfs_data,/data4/seaweedfs_data,/data5/seaweedfs_data -mserver 10.0.9.1:9333,10.0.9.2:9333,10.0.93:9333  -port 9222 -port.public 9222 -dataCenter dc1 -rack rack1"
- start filer  3  
>"weed  filer -master 10.0.9.1:9333,10.0.9.2:9333,10.0.9.3:9333 -port 8888" 
- mount  
>"weed mount -filer 10.0.9.1:8888 -dir=/mnt -filer.path=/"

- OS version

> Ubuntu14.04.4 LTS 4.2.0-27-generic #32~14.04.1-Ubuntu

- `weed version
>` version 8000GB 1.87 a6b59d5 linux amd64
-  the content of `filer.toml`
>[cassandra]
enabled = true
keyspace="seaweedfs"
hosts=[
	"10.2.9.1:9042",
	"10.2.9.2:9042",
]

**Expected behavior**
elasticsearch start ok 

**Screenshots**
![image](https://user-images.githubusercontent.com/3645697/89708384-3c254f80-d9a9-11ea-8d1e-2f95b4bb9a3e.png)

**Additional context**
elasticsearch  start error log 
>`[2020-08-08T18:45:35,604][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [weed53-1] fatal error in thread [elasticsearch[weed53-1][AsyncLucenePersistedState#updateTask][T#1]], exiting
java.io.IOError: java.nio.file.NoSuchFileException: /mnt/weed53-1/nodes/0/_state/segments_ci
	at org.elasticsearch.gateway.PersistedClusterStateService$Writer.commit(PersistedClusterStateService.java:763) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.gateway.PersistedClusterStateService$Writer.writeIncrementalStateAndCommit(PersistedClusterStateService.java:616) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.gateway.GatewayMetaState$LucenePersistedState.setLastAcceptedState(GatewayMetaState.java:543) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.gateway.GatewayMetaState$AsyncLucenePersistedState$1.doRun(GatewayMetaState.java:428) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:695) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.8.0.jar:7.8.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.nio.file.NoSuchFileException: /mnt/weed53-1/nodes/0/_state/segments_ci
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:249) ~[?:?]
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105) ~[?:?]
	at java.nio.file.Files.delete(Files.java:1146) ~[?:?]
	at org.apache.lucene.store.FSDirectory.privateDeleteFile(FSDirectory.java:370) ~[lucene-core-8.5.1.jar:8.5.1 edb9fc409398f2c3446883f9f80595c884d245d0 - ivera - 2020-04-08 08:55:42]
	at org.apache.lucene.store.FSDirectory.deleteFile(FSDirectory.java:339) ~[lucene-core-8.5.1.jar:8.5.1 edb9fc409398f2c3446883f9f80595c884d245d0 - ivera - 2020-04-08 08:55:42]
	at org.apache.lucene.store.LockValidatingDirectoryWrapper.deleteFile(LockValidatingDirectoryWrapper.java:38) ~[lucene-core-8.5.1.jar:8.5.1 edb9fc409398f2c3446883f9f80595c884d245d0 - ivera - 2020-04-08 08:55:42]
	at org.apache.lucene.index.IndexFileDeleter.deleteFile(IndexFileDeleter.java:696) ~[lucene-core-8.5.1.jar:8.5.1 edb9fc409398f2c3446883f9f80595c884d245d0 - ivera - 2020-04-08 08:55:42]
	at org.apache.lucene.index.IndexFileDeleter.deleteFiles(IndexFileDeleter.java:683) ~[lucene-core-8.5.1.jar:8.5.1 edb9fc409398f2c3446883f9f80595c884d245d0 - ivera - 2020-04-08 08:55:42]
	at org.apache.lucene.index.IndexFileDeleter.decRef(IndexFileDeleter.java:589) ~[lucene-core-8.5.1.jar:8.5.1 edb9fc409398f2c3446883f9f80595c884d245d0 - ivera - 2020-04-08 08:55:42]
	at org.apache.lucene.index.IndexFileDeleter.deleteCommits(IndexFileDeleter.java:382) ~[lucene-core-8.5.1.jar:8.5.1 edb9fc409398f2c3446883f9f80595c884d245d0 - ivera - 2020-04-08 08:55:42]
	at org.apache.lucene.index.IndexFileDeleter.checkpoint(IndexFileDeleter.java:527) ~[lucene-core-8.5.1.jar:8.5.1 edb9fc409398f2c3446883f9f80595c884d245d0 - ivera - 2020-04-08 08:55:42]
	at org.apache.lucene.index.IndexWriter.finishCommit(IndexWriter.java:3497) ~[lucene-core-8.5.1.jar:8.5.1 edb9fc409398f2c3446883f9f80595c884d245d0 - ivera - 2020-04-08 08:55:42]
	at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:3453) ~[lucene-core-8.5.1.jar:8.5.1 edb9fc409398f2c3446883f9f80595c884d245d0 - ivera - 2020-04-08 08:55:42]
	at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:3410) ~[lucene-core-8.5.1.jar:8.5.1 edb9fc409398f2c3446883f9f80595c884d245d0 - ivera - 2020-04-08 08:55:42]
	at org.elasticsearch.gateway.PersistedClusterStateService$MetadataIndexWriter.commit(PersistedClusterStateService.java:530) ~[elasticsearch-7.8.0.jar:7.8.0]
	at org.elasticsearch.gateway.PersistedClusterStateService$Writer.commit(PersistedClusterStateService.java:752) ~[elasticsearch-7.8.0.jar:7.8.0]
	... 8 more
fatal error in thread [elasticsearch[weed53-1][AsyncLucenePersistedState#updateTask][T#1]], exiting
java.io.IOError: java.nio.file.NoSuchFileException: /mnt/weed53-1/nodes/0/_state/segments_ci
	at org.elasticsearch.gateway.PersistedClusterStateService$Writer.commit(PersistedClusterStateService.java:763)
	at org.elasticsearch.gateway.PersistedClusterStateService$Writer.writeIncrementalStateAndCommit(PersistedClusterStateService.java:616)
	at org.elasticsearch.gateway.GatewayMetaState$LucenePersistedState.setLastAcceptedState(GatewayMetaState.java:543)
	at org.elasticsearch.gateway.GatewayMetaState$AsyncLucenePersistedState$1.doRun(GatewayMetaState.java:428)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:695)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.nio.file.NoSuchFileException: /mnt/weed53-1/nodes/0/_state/segments_ci
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:249)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
	at java.base/java.nio.file.Files.delete(Files.java:1146)
	at org.apache.lucene.store.FSDirectory.privateDeleteFile(FSDirectory.java:370)
	at org.apache.lucene.store.FSDirectory.deleteFile(FSDirectory.java:339)
	at org.apache.lucene.store.LockValidatingDirectoryWrapper.deleteFile(LockValidatingDirectoryWrapper.java:38)
	at org.apache.lucene.index.IndexFileDeleter.deleteFile(IndexFileDeleter.java:696)
	at org.apache.lucene.index.IndexFileDeleter.deleteFiles(IndexFileDeleter.java:683)
	at org.apache.lucene.index.IndexFileDeleter.decRef(IndexFileDeleter.java:589)
	at org.apache.lucene.index.IndexFileDeleter.deleteCommits(IndexFileDeleter.java:382)
	at org.apache.lucene.index.IndexFileDeleter.checkpoint(IndexFileDeleter.java:527)
	at org.apache.lucene.index.IndexWriter.finishCommit(IndexWriter.java:3497)
	at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:3453)
	at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:3410)
	at org.elasticsearch.gateway.PersistedClusterStateService$MetadataIndexWriter.commit(PersistedClusterStateService.java:530)
	at org.elasticsearch.gateway.PersistedClusterStateService$Writer.commit(PersistedClusterStateService.java:752)
	... 8 more`

filer info 
>`filer_deletion.go:55] deleting fileIds len=5 error: delete fileId 1,0353a504c93d: already deleted
I0808 13:55:23 55963 filer_deletion.go:60] delete 5 fileIds actual 0
I0808 13:55:24 55963 filer_deletion.go:55] deleting fileIds len=7 error: delete fileId 1,035490c392be: already deleted
I0808 13:55:24 55963 filer_deletion.go:60] delete 7 fileIds actual 0
I0808 13:55:25 55963 filer_deletion.go:55] deleting fileIds len=2 error: delete fileId 1,032a7c68b178: already deleted
I0808 13:55:25 55963 filer_deletion.go:60] delete 2 fileIds actual 0
I0808 13:55:27 55963 filer_deletion.go:55] deleting fileIds len=9 error: delete fileId 1,0368d28f77cd: already deleted
I0808 13:55:27 55963 filer_deletion.go:60] delete 9 fileIds actual 0
I0808 13:55:28 55963 filer_deletion.go:55] deleting fileIds len=6 error: delete fileId 1,037cee697d5d: already deleted
I0808 13:55:28 55963 filer_deletion.go:60] delete 6 fileIds actual 0
I0808 13:55:29 55963 filer_deletion.go:55] deleting fileIds len=3 error: delete fileId 1,0389691c6e0c: already deleted`

 /tmp/weed.ERROR
>E0808 13:45:10 40635 on_disk_cache_layer.go:29] failed to add cache /tmp/bf98/c0_1_0 : loading leveldb /tmp/bf98/c0_1_0.ldb error: resource temporarily unavailable
E0808 13:45:10 40635 on_disk_cache_layer.go:29] failed to add cache /tmp/bf98/c0_1_1 : loading leveldb /tmp/bf98/c0_1_1.ldb error: resource temporarily unavailable
E0808 13:45:10 40635 on_disk_cache_layer.go:29] failed to add cache /tmp/bf98/c0_1_2 : loading leveldb /tmp/bf98/c0_1_2.ldb error: resource temporarily unavailable
E0808 13:45:10 40635 on_disk_cache_layer.go:29] failed to add cache /tmp/bf98/c0_1_3 : loading leveldb /tmp/bf98/c0_1_3.ldb error: resource temporarily unavailable
E0808 13:45:10 40635 on_disk_cache_layer.go:29] failed to add cache /tmp/bf98/c1_4_0 : loading leveldb /tmp/bf98/c1_4_0.ldb error: resource temporarily unavailable
E0808 13:45:10 40635 on_disk_cache_layer.go:29] failed to add cache /tmp/bf98/c1_4_1 : loading leveldb /tmp/bf98/c1_4_1.ldb error: resource temporarily unavailable
E0808 13:45:10 40635 on_disk_cache_layer.go:29] failed to add cache /tmp/bf98/c1_4_2 : loading leveldb /tmp/bf98/c1_4_2.ldb error: resource temporarily unavailable
E0808 13:45:10 40635 on_disk_cache_layer.go:29] failed to add cache /tmp/bf98/c1_4_3 : loading leveldb /tmp/bf98/c1_4_3.ldb error: resource temporarily unavailable
E0808 13:45:10 40635 on_disk_cache_layer.go:29] failed to add cache /tmp/bf98/cache_0 : loading leveldb /tmp/bf98/cache_0.ldb error: resource temporarily unavailable
E0808 13:45:10 40635 on_disk_cache_layer.go:29] failed to add cache /tmp/bf98/cache_1 : loading leveldb /tmp/bf98/cache_1.ldb error: resource temporarily unavailable
E0808 13:45:10 40635 on_disk_cache_layer.go:29] failed to add cache /tmp/bf98/cache_2 : loading leveldb /tmp/bf98/cache_2.ldb error: resource temporarily unavailable
E0808 13:45:10 40635 on_disk_cache_layer.go:29] failed to add cache /tmp/bf98/cache_3 : loading leveldb /tmp/bf98/cache_3.ldb error: resource temporarily unavailable

**Comment by chrislusf** [comment]
how to reproduce with elasticsearch?

**Comment by renweijun** [comment]
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.8.1-linux-x86_64.tar.gz

create  new file in config/elasticsearch.yml
> network.host: 0.0.0.0
http.port: 9203
transport.tcp.port: 9303
discovery.seed_hosts: ["10.2.1.17:9303"]
cluster.initial_master_nodes: ["10.2.1.17:9303"]
path.data: /mnt/seaweedfs/ops-es/${HOSTNAME}-3
path.logs: /data/logs/es7.8-2-logs

10.2.1.17  is localhost 
path.data is seaweedfs volume 
run  elasticsearch 
> nohup ./bin/elasticsearch &

thx @chrislusf

**Comment by chrislusf** [comment]
the 1.87 seems having some problem, but not exactly the same.

the latest version does not. 

You can build it from the source, or get it via `docker pull chrislusf/seaweedfs:dev` and copy out the `/usr/bin/weed` file.

**Comment by renweijun** [comment]
thx ，start es success ，build  from the source。
