### ISSUE TITLE
Raft leader election bug？

### ISSUE THREAD

**Issue by yanyiwu** [chrislusf/seaweedfs#144]
I have 3 master(m0,m1,m2) and 2 volume(v0,v1) in 2 machines(d0,d1).

+ d0: m0, m2, v0
+ d1: m1, v1

When I start m0 and m2 in d0,  if I start them both in one second(m0 first),  sometimes m2 would crash and log error as following:  

```
I0519 15:24:12 12345 master_server.go:93] [ ds0.xxbtest.com:9335 ] I am the leader!
panic: assertion failed: leader.elected.at.same.term.28


goroutine 15 [running]:
github.com/goraft/raft._assert(0xbec200, 0xca22f0, 0x1f, 0xc2081b1c98, 0x1, 0x1)
        /home/yanyiwu/golang/src/github.com/goraft/raft/util.go:60 +0xcf
github.com/goraft/raft.(*server).processAppendEntriesRequest(0xc208116b40, 0xc20813e050, 0xc20813e050, 0xc20813e050)
        /home/yanyiwu/golang/src/github.com/goraft/raft/server.go:948 +0x413
github.com/goraft/raft.(*server).leaderLoop(0xc208116b40)
        /home/yanyiwu/golang/src/github.com/goraft/raft/server.go:849 +0x769
github.com/goraft/raft.(*server).loop(0xc208116b40)
        /home/yanyiwu/golang/src/github.com/goraft/raft/server.go:609 +0x458
github.com/goraft/raft.func·007()
        /home/yanyiwu/golang/src/github.com/goraft/raft/server.go:470 +0x6a
created by github.com/goraft/raft.(*server).Start
        /home/yanyiwu/golang/src/github.com/goraft/raft/server.go:471 +0x4a8

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7fc39bdd8400, 0x72, 0x8)
        /home/yanyiwu/local/go/src/runtime/netpoll.go:149 +0x63
......
```

I use the weed which is built from commit 5c760523be1b48af4f831db8cfc969e937591a6a

**Comment by yanyiwu** [comment]
If I start m0 first, and sleep 2 seconds , and after that, start m2 ,  it always works fine.

**Comment by chrislusf** [comment]
Both m0 and m2 think they are leader themselves. We can fix this by putting a randomized wait before starting raft server.

**Comment by chrislusf** [comment]
I think it's better to leave it as is, and use your approach as a work around until we switch to latest raft branch.

**Comment by chrislusf** [comment]
upgraded to latest raft.
