### ISSUE TITLE
java Grpc 操作方法一直失败

### ISSUE THREAD

**Issue by wranglerlmx** [chrislusf/seaweedfs#1457]
## 网络上资料也很少，作者应该是个中国人吧？不知道怎么联系的到，有没有社区之类的。

- 这个对象存储分布式系统我很喜欢，可是 restful api 方式使用始终不安全，网络上也没有找到java 使用 Grpc 连接的方式。

- 一直找不到解决方案，希望作者能帮帮我，谢谢！

- 下面是我的代码，以及引用的包。
  ```
  <dependency>
    <groupId>com.github.chrislusf</groupId>
    <artifactId>seaweedfs-client</artifactId>
    <version>1.4.6</version>
  </dependency>

  try {
      String host = "XXXX";
      int port = 8888;
      int grpcPort = 10000 + port;

      final SslContext sslContext = FilerSslContext.buildSslContext("/Users/xxx/Downloads/keys/SeaweedFS_CA.crt",
              "/Users/xxx/Downloads/keys/client01.crt",
              "/Users/xxx/Downloads/keys/client01.pem");

      FilerGrpcClient filerGrpcClient = new FilerGrpcClient(host, grpcPort, sslContext);
      FilerClient filerClient = new FilerClient(filerGrpcClient);
      final List<FilerProto.Entry> entries = filerClient.listEntries("/");
      entries.forEach(k -> {
          System.out.println(k.getName());
      });
  } catch (Exception e) {
      e.printStackTrace();
  }
  ```
- 报错信息
  ```
  io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
  Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
    at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:235)
    at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:216)
    at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
    at seaweedfs.client.SeaweedFilerGrpc$SeaweedFilerBlockingStub.getFilerConfiguration(SeaweedFilerGrpc.java:1026)
    at seaweedfs.client.FilerGrpcClient.<init>(FilerGrpcClient.java:53)
    at seaweedfs.MainStart.main(MainStart.java:27)
  Caused by: io.grpc.netty.shaded.io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 000006040000000000000500004000
  ```

**Comment by chrislusf** [comment]
try to get non-ssl working first. you can follow https://github.com/chrislusf/seaweedfs/blob/master/other/java/hdfs2/src/main/java/seaweed/hdfs/SeaweedFileSystemStore.java#L33

you can join the slack channel listed in the README
