### ISSUE TITLE
weed export -dir='/srv/weed-volume' -o='/srv/backup/backup.tar' -collection='collection-name' -volumeId=123 throws "slice bounds out of range"

### ISSUE THREAD

**Issue by fedotxxl** [chrislusf/seaweedfs#146]
Weed version: `0.65`
We are trying to backup data by export command. Some volumes throw an exception:

```
panic: runtime error: slice bounds out of range

goroutine 16 [running]:
runtime.panic(0x9ca580, 0xd7d1af)
	/home/chris/apps/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/chrislusf/weed-fs/go/storage.(*Needle).readNeedleDataVersion2(0xc208044140, 0xc20842b800, 0x17de, 0x17e8)
	/home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/weed-fs/go/storage/needle_read_write.go:188 +0x44e
github.com/chrislusf/weed-fs/go/storage.(*Needle).ReadNeedleBody(0xc208044140, 0xc208038028, 0x1802, 0x1810, 0x17e8, 0x0, 0x0)
	/home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/weed-fs/go/storage/needle_read_write.go:250 +0x275
github.com/chrislusf/weed-fs/go/storage.ScanVolumeFile(0x7fffde364786, 0x10, 0x7fffde3647da, 0x12, 0xc20000003a, 0xc2080c5c98, 0x1, 0xc2080c5d20, 0x0, 0x0)
	/home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/weed-fs/go/storage/volume.go:302 +0x4a0
main.runExport(0xd7a920, 0xc2080040c0, 0x0, 0x0, 0x0)
	/home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/weed-fs/go/weed/export.go:119 +0x9a4
main.main()
	/home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/weed-fs/go/weed/weed.go:77 +0x612

goroutine 19 [finalizer wait]:
runtime.park(0x428bd0, 0xd81240, 0xd7f449)
	/home/chris/apps/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xd81240, 0xd7f449)
	/home/chris/apps/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/home/chris/apps/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/home/chris/apps/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
	/home/chris/apps/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/home/chris/apps/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 21 [chan receive]:
github.com/chrislusf/weed-fs/go/glog.(*loggingT).flushDaemon(0xd84140)
	/home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/weed-fs/go/glog/glog.go:833 +0x75
created by github.com/chrislusf/weed-fs/go/glog.init·1
	/home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/weed-fs/go/glog/glog.go:402 +0x2b2

goroutine 17 [syscall]:
runtime.goexit()
	/home/chris/apps/go/src/pkg/runtime/proc.c:1445

goroutine 23 [select]:
github.com/chrislusf/weed-fs/go/stats.(*ServerStats).Start(0xc208049140)
	/home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/weed-fs/go/stats/stats.go:92 +0x385
created by github.com/chrislusf/weed-fs/go/weed/weed_server.init·1
	/home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/weed-fs/go/weed/weed_server/common.go:24 +0x43

```

**Comment by fedotxxl** [comment]
tested with trunk version - everything is ok
