### ISSUE TITLE
Bug ETCD

### ISSUE THREAD

**Issue by fixNoobi** [chrislusf/seaweedfs#1463]
Hi, 

after update from 1.84, filer dosent startup

error

```
I0912 00:36:52  3116 etcd_store.go:48] filer store etcd: 10.113.128.53:2379,10.113.128.54:2379,10.113.128.55:2379
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11e7288]

goroutine 1 [running]:
go.etcd.io/etcd/clientv3.(*Op).applyOpts(0xc00015c000, 0xc000186b50, 0x1, 0x1)
	/home/travis/gopath/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20200425165423-262c93980547/clientv3/op.go:321 +0x38
go.etcd.io/etcd/clientv3.OpGet(0xc00037e300, 0xe, 0xc000186b50, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20200425165423-262c93980547/clientv3/op.go:226 +0x165
go.etcd.io/etcd/clientv3.(*kv).Get(0xc000371b60, 0x243f360, 0xc0000be010, 0xc00037e300, 0xe, 0xc000186b50, 0x1, 0x1, 0x11fe230, 0xc0001fd6d8, ...)
	/home/travis/gopath/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20200425165423-262c93980547/clientv3/kv.go:119 +0x77
github.com/chrislusf/seaweedfs/weed/filer/etcd.(*EtcdStore).KvGet(0xc000679070, 0x243f360, 0xc0000be010, 0xc00037e2f0, 0xe, 0xe, 0xc0005934e0, 0x0, 0x1ac7f60, 0xc000592d30, ...)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filer/etcd/etcd_store_kv.go:22 +0xf8
github.com/chrislusf/seaweedfs/weed/filer.(*Filer).setOrLoadFilerStoreSignature(0xc00001c500, 0x2464e00, 0xc000679070)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filer/filer.go:88 +0xbb
github.com/chrislusf/seaweedfs/weed/filer.(*Filer).SetStore(0xc00001c500, 0x2464e00, 0xc000679070)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filer/filer.go:83 +0x68
github.com/chrislusf/seaweedfs/weed/filer.(*Filer).LoadConfiguration(0xc00001c500, 0xc0004a6e00)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filer/configuration.go:24 +0x2f5
github.com/chrislusf/seaweedfs/weed/server.NewFilerServer(0xc000527440, 0xc000527440, 0xc000514e70, 0x1, 0x0, 0x2)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/server/filer_server.go:111 +0x792
github.com/chrislusf/seaweedfs/weed/command.(*FilerOptions).startFiler(0x34a3d80)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/filer.go:111 +0x2b3
github.com/chrislusf/seaweedfs/weed/command.runFiler(0x348c280, 0xc0000c8040, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/filer.go:87 +0x4b
main.main()
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/weed.go:66 +0x2f9
```

Config `/etc/seaweedfs/filer.toml`

```
[etcd]
enabled = true
servers = "10.113.128.53:2379,10.113.128.54:2379,10.113.128.55:2379"
timeout = "3s"
```

If downgrade, all goods

Thanx

**Comment by chrislusf** [comment]
Thanks for the detailed issue report!
