### ISSUE TITLE
use urbackup or borg  init error

### ISSUE THREAD

**Issue by caihexin** [chrislusf/seaweedfs#1474]
![图片](https://user-images.githubusercontent.com/13762872/93745118-93b00f80-fc25-11ea-9a16-b504230f8624.png)
use urbackup or borg  init   ,result  urbackup database  create  or borg config file error  ,

Is this operation not supported ？？？

**Comment by chrislusf** [comment]
<img width="549" alt="Screen Shot 2020-09-21 at 1 29 14 AM" src="https://user-images.githubusercontent.com/1543151/93746378-de8c4180-fba9-11ea-8776-94432e1f7ea1.png">

works for me

**Comment by caihexin** [comment]
![图片](https://user-images.githubusercontent.com/13762872/93747131-d58e8500-fc28-11ea-93da-f26cd62134c7.png)
i use filer.copy and curl upload file OK  ,  use mount  can cp 、mkdir 、 mv ... ，but  borg or urbackup error

**Comment by chrislusf** [comment]
use latest version

**Comment by caihexin** [comment]
thank, use latest version is ok

**Comment by caihexin** [comment]
weed v2  , use:  borg init -e repokey  .    ,is error
![图片](https://user-images.githubusercontent.com/13762872/93849914-a7b84780-fcdf-11ea-9b7b-088c27fc0b23.png)

borg init -e none .    ,is OK

**Comment by chrislusf** [comment]
```
Local Exception
Traceback (most recent call last):
  File "/usr/local/Cellar/borgbackup/1.1.13/libexec/lib/python3.8/site-packages/borg/archiver.py", line 4565, in main
    exit_code = archiver.run(args)
  File "/usr/local/Cellar/borgbackup/1.1.13/libexec/lib/python3.8/site-packages/borg/archiver.py", line 4497, in run
    return set_ec(func(args))
  File "/usr/local/Cellar/borgbackup/1.1.13/libexec/lib/python3.8/site-packages/borg/archiver.py", line 176, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/local/Cellar/borgbackup/1.1.13/libexec/lib/python3.8/site-packages/borg/archiver.py", line 290, in do_init
    key = key_creator(repository, args)
  File "/usr/local/Cellar/borgbackup/1.1.13/libexec/lib/python3.8/site-packages/borg/crypto/key.py", line 110, in key_creator
    return key.create(repository, args)
  File "/usr/local/Cellar/borgbackup/1.1.13/libexec/lib/python3.8/site-packages/borg/crypto/key.py", line 690, in create
    key.save(target, passphrase)
  File "/usr/local/Cellar/borgbackup/1.1.13/libexec/lib/python3.8/site-packages/borg/crypto/key.py", line 800, in save
    target.save_key(key_data)
  File "/usr/local/Cellar/borgbackup/1.1.13/libexec/lib/python3.8/site-packages/borg/repository.py", line 328, in save_key
    self.save_config(self.path, self.config)
  File "/usr/local/Cellar/borgbackup/1.1.13/libexec/lib/python3.8/site-packages/borg/repository.py", line 301, in save_config
    os.link(config_path, old_config_path)
OSError: [Errno 5] Input/output error: '/Users/chris/tmp/mm/borg/config' -> '/Users/chris/tmp/mm/borg/config.old'
```

The error is with `os.link()`, which uses hard links. Hard links are not supported yet.

```
os.link(src, dst, *, src_dir_fd=None, dst_dir_fd=None, follow_symlinks=True)
Create a hard link pointing to src named dst.
```

**Comment by caihexin** [comment]
very thank you !

**Comment by chrislusf** [comment]
FYI: now the hard link is supported in the latest git tip. This is working now.

**Comment by caihexin** [comment]
very thank you !  wait i have time test it
