### ISSUE TITLE
Multi-master documentation needs updating

### ISSUE THREAD

**Issue by netixx** [chrislusf/seaweedfs#1504]
**Describe the bug**
Documentation on multi-master server is outdated: https://github.com/chrislusf/seaweedfs/wiki/Failover-Master-Server

The parameter is now `-peers` and only allows an even number of master servers.
Does this mean that the current server shouldn't be listed in the peers anymore ?

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- OS version
- output of `weed version`
- if using filer, show the content of `filer.toml`

weed master, linux, version 30GB 2.01  linux amd64

**Expected behavior**
multi-master configuration should work as the wiki says.

**Comment by chrislusf** [comment]
Could you please show how you started weed master?

**Comment by netixx** [comment]
I did as suggested in the docs (adapting `-master.peers` to `-peers`) like so:

on host1 and host 2:
`weed master -peers="host1:9333,host2:9333" -port=9333`
I got a lot of connection errors with this setup.

I did some more testing, and from experienced I think that an odd number of masters are required, which is why I tried the following:

I added an additional master server.
```
# on host1
weed master -peers="host2:9333,host3:9333" -port=9333
# on host2
weed master -peers="host1:9333,host3:9333" -port=9333
# on host3
weed master -peers="host1:9333:host2:9333" -port=9333
```
which seems to work better.

**Comment by chrislusf** [comment]
does this work on host1? `curl http://host1:9333/dir/status`

**Comment by chrislusf** [comment]
you can also try:

`weed master -peers="host1:9333:host2:9333,host3:9333" -port=9333 -ip=host1`

**Comment by netixx** [comment]
The curl command works.

However if I use the command you provided, then I get an error:
```
F1003 13:32:40  1271 master.go:170] Only odd number of masters are supported!
goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0xc00031b500, 0xc000056210, 0x4e, 0xa3)
	/build/source/weed/glog/glog.go:767 +0xb9
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x31e6a20, 0xc000000003, 0xc00026c1c0, 0x30f2f87, 0x9, 0xaa, 0x0)
	/build/source/weed/glog/glog.go:718 +0x385
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x31e6a20, 0xc000000003, 0x20c04e5, 0x29, 0x0, 0x0, 0x0)
	/build/source/weed/glog/glog.go:656 +0x153
github.com/chrislusf/seaweedfs/weed/glog.Fatalf(...)
	/build/source/weed/glog/glog.go:1149
github.com/chrislusf/seaweedfs/weed/command.checkPeers(0x7ffdbe82aadd, 0xc, 0x2474, 0x7ffdbe82aa8e, 0x4a, 0x2, 0x0, 0x2, 0xc000317680, 0x0)
	/build/source/weed/command/master.go:170 +0x295
github.com/chrislusf/seaweedfs/weed/command.startMaster(0xc0002d2df8, 0xc000305c70, 0xc000305c80, 0xc000305c90, 0xc000305ca0, 0xc0002d2e68, 0xc0002d2e95, 0xc000305cb0, 0xc0002d2e98, 0xc000305cc0, ...)
	/build/source/weed/command/master.go:110 +0x22b
github.com/chrislusf/seaweedfs/weed/command.runMaster(0x3145f60, 0xc00003c0e0, 0x0, 0x0, 0x0)
	/build/source/weed/command/master.go:101 +0x167
main.main()
	/build/source/weed/weed.go:66 +0x30e
```

**Comment by chrislusf** [comment]
can you show the full log?

**Comment by chrislusf** [comment]
FYI: the host1 should be an IP address, or a hostname can can be resolved to an IP address.

**Comment by netixx** [comment]
Here is the log:
```
root@DiskStation:~# ~/weed master -peers="m02.storage.xinet.fr:9333,m02.storage.xinet.fr:9332,diskstation.storage.xinet.fr" -ip 10.0.113.201 -port 9333
I1005 18:26:32 22602 file_util.go:23] Folder /tmp Permission: -rwxrwxrwx
I1005 18:26:32 22602 master.go:152] current: 10.0.113.201:9333 peers:m02.storage.xinet.fr:9333,m02.storage.xinet.fr:9332,diskstation.storage.xinet.fr
F1005 18:26:32 22602 master.go:170] Only odd number of masters are supported!
goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0x2543000, 0x0, 0x4e, 0xa3)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0x94
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x252f748, 0x3, 0x4535ec0, 0x245989a, 0x9, 0xaa, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:718 +0x2b8
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x252f748, 0x3, 0x16ac09c, 0x29, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:656 +0x108
github.com/chrislusf/seaweedfs/weed/glog.Fatalf(...)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:1149
github.com/chrislusf/seaweedfs/weed/command.checkPeers(0xbeb1ee3c, 0xc, 0x2475, 0xbeb1ede7, 0x50, 0x2, 0x0, 0x2, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/master.go:170 +0x224
github.com/chrislusf/seaweedfs/weed/command.startMaster(0x440fff0, 0x439dd38, 0x439dd40, 0x439dd48, 0x439dd50, 0x403a0fc, 0x403a3d5, 0x439dd58, 0x403a3d8, 0x439dd60, ...)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/master.go:110 +0x198
github.com/chrislusf/seaweedfs/weed/command.runMaster(0x2523568, 0x4036178, 0x0, 0x1, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/master.go:101 +0x134
main.main()
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/weed.go:66 +0x330

```

As you can see, both hostname are resolvable:
```
root@DiskStation:~# nslookup diskstation.storage.xinet.fr
Server:	10.0.111.254
Address:	10.0.111.254#53

Name:	diskstation.storage.xinet.fr
Address: 10.0.113.201

root@DiskStation:~# nslookup m02.storage.xinet.fr
Server:	10.0.111.254
Address:	10.0.111.254#53

Name:	m02.storage.xinet.fr
Address: 10.0.113.202
```

**Comment by chrislusf** [comment]
How about this? Avoid mixing the domain name and IP.

```
~/weed master -peers="m02.storage.xinet.fr:9333,m02.storage.xinet.fr:9332,diskstation.storage.xinet.fr" -ip diskstation.storage.xinet.fr -port 9333
```

**Comment by netixx** [comment]
Yes, this works, I looked at the the `checkPeers` method and it seems that it adds the local peer in case it's not in the list of peers.
So in the end its the same thing.
