### ISSUE TITLE
Running Presto with SeaweedFS 

### ISSUE THREAD

**Issue by hilimd** [chrislusf/seaweedfs#1523]
**背景**

presto 0.242 版本对接hive，使用hive metastore及seaweedfs作为存储(seaweedfs-hadoop2-client-1.4.9.jar)

问题1：使用以下sql语句，多次插入数据概率性失败

```
presto> use test01;
USE
presto:test01> INSERT INTO limd01 VALUES ('zhangsan');
```

**正常情况presto日志：**
```
2020-10-11T08:35:16.687-0400	DEBUG	dispatcher-query-7	com.facebook.presto.execution.QueryStateMachine	Query 20201011_123516_00006_udsg7 is QUEUED
2020-10-11T08:35:16.688-0400	DEBUG	dispatcher-query-10	com.facebook.presto.execution.QueryStateMachine	Query 20201011_123516_00006_udsg7 is WAITING_FOR_RESOURCES
2020-10-11T08:35:16.747-0400	DEBUG	dispatcher-query-8	com.facebook.presto.execution.QueryStateMachine	Query 20201011_123516_00006_udsg7 is DISPATCHING
2020-10-11T08:35:16.748-0400	DEBUG	dispatcher-query-7	com.facebook.presto.execution.QueryStateMachine	Query 20201011_123516_00006_udsg7 is PLANNING
2020-10-11T08:35:16.826-0400	DEBUG	query-execution-4	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123516_00006_udsg7.0.0 is PLANNED
2020-10-11T08:35:16.827-0400	DEBUG	query-execution-5	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123516_00006_udsg7.1.0 is PLANNED
2020-10-11T08:35:16.828-0400	DEBUG	query-execution-5	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123516_00006_udsg7.2.0 is PLANNED
2020-10-11T08:35:16.829-0400	DEBUG	dispatcher-query-7	com.facebook.presto.execution.QueryStateMachine	Query 20201011_123516_00006_udsg7 is STARTING
2020-10-11T08:35:16.831-0400	DEBUG	query-execution-4	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123516_00006_udsg7.2.0 is SCHEDULING
2020-10-11T08:35:16.834-0400	DEBUG	query-execution-6	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123516_00006_udsg7.2.0 is SCHEDULED
2020-10-11T08:35:16.835-0400	DEBUG	dispatcher-query-8	com.facebook.presto.execution.QueryStateMachine	Query 20201011_123516_00006_udsg7 is RUNNING
2020-10-11T08:35:16.835-0400	DEBUG	query-execution-7	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123516_00006_udsg7.1.0 is SCHEDULING
2020-10-11T08:35:16.842-0400	DEBUG	query-execution-6	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123516_00006_udsg7.0.0 is SCHEDULING
2020-10-11T08:35:16.842-0400	DEBUG	query-execution-4	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123516_00006_udsg7.1.0 is SCHEDULED
2020-10-11T08:35:16.843-0400	DEBUG	task-notification-3	com.facebook.presto.execution.TaskStateMachine	Task 20201011_123516_00006_udsg7.2.0.0 is RUNNING
2020-10-11T08:35:16.853-0400	DEBUG	task-notification-1	com.facebook.presto.execution.TaskStateMachine	Task 20201011_123516_00006_udsg7.1.0.0 is RUNNING
2020-10-11T08:35:16.853-0400	DEBUG	query-execution-4	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123516_00006_udsg7.0.0 is SCHEDULED
2020-10-11T08:35:16.856-0400	DEBUG	task-notification-4	com.facebook.presto.execution.TaskStateMachine	Task 20201011_123516_00006_udsg7.0.0.0 is RUNNING
2020-10-11T08:35:16.887-0400	DEBUG	query-execution-5	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123516_00006_udsg7.2.0 is RUNNING
2020-10-11T08:35:16.887-0400	DEBUG	query-execution-4	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123516_00006_udsg7.1.0 is RUNNING
2020-10-11T08:35:16.888-0400	DEBUG	query-execution-4	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123516_00006_udsg7.0.0 is RUNNING
2020-10-11T08:35:16.904-0400	DEBUG	Task-20201011_123516_00006_udsg7.2.0.0-157	com.facebook.presto.execution.executor.TaskExecutor	Task scheduled 20201011_123516_00006_udsg7.2.0.0
2020-10-11T08:35:16.904-0400	DEBUG	Task-20201011_123516_00006_udsg7.0.0.0-165	com.facebook.presto.execution.executor.TaskExecutor	Task scheduled 20201011_123516_00006_udsg7.0.0.0
2020-10-11T08:35:16.906-0400	DEBUG	Task-20201011_123516_00006_udsg7.1.0.0-158	com.facebook.presto.execution.executor.TaskExecutor	Task scheduled 20201011_123516_00006_udsg7.1.0.0
2020-10-11T08:35:16.915-0400	DEBUG	20201011_123516_00006_udsg7.2.0.0-0-113	com.facebook.presto.execution.executor.TaskExecutor	Split 20201011_123516_00006_udsg7.2.0.0-0  (start = 1.211256506854493E9, wall = 9 ms, cpu = 1 ms, wait = 0 ms, calls = 1) is finished
2020-10-11T08:35:16.948-0400	DEBUG	http-worker-165	com.facebook.presto.execution.SqlTask	Aborting task 20201011_123516_00006_udsg7.2.0.0 output 0
2020-10-11T08:35:16.949-0400	DEBUG	task-notification-2	com.facebook.presto.execution.TaskStateMachine	Task 20201011_123516_00006_udsg7.2.0.0 is FINISHED
2020-10-11T08:35:16.949-0400	DEBUG	Task-20201011_123516_00006_udsg7.2.0.0-217	com.facebook.presto.execution.executor.TaskExecutor	Task finished or failed 20201011_123516_00006_udsg7.2.0.0
2020-10-11T08:35:16.958-0400	DEBUG	query-execution-4	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123516_00006_udsg7.2.0 is FINISHED
2020-10-11T08:35:16.959-0400	DEBUG	20201011_123516_00006_udsg7.1.0.0-3-126	com.facebook.presto.execution.executor.TaskExecutor	Split 20201011_123516_00006_udsg7.1.0.0-3  (start = 1.211256512788089E9, wall = 47 ms, cpu = 5 ms, wait = 5 ms, calls = 3) is finished
2020-10-11T08:35:16.959-0400	DEBUG	20201011_123516_00006_udsg7.1.0.0-0-111	com.facebook.presto.execution.executor.TaskExecutor	Split 20201011_123516_00006_udsg7.1.0.0-0  (start = 1.2112565095803E9, wall = 51 ms, cpu = 7 ms, wait = 1 ms, calls = 3) is finished
2020-10-11T08:35:16.959-0400	DEBUG	20201011_123516_00006_udsg7.1.0.0-2-117	com.facebook.presto.execution.executor.TaskExecutor	Split 20201011_123516_00006_udsg7.1.0.0-2  (start = 1.211256510473203E9, wall = 50 ms, cpu = 6 ms, wait = 0 ms, calls = 2) is finished
2020-10-11T08:35:16.976-0400	DEBUG	20201011_123516_00006_udsg7.1.0.0-1-118	com.facebook.presto.hive.HiveEventClient	File created: query: 20201011_123516_00006_udsg7, schema: test01, table: limd01, partition: 'null', format: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat, size: 9, path: seaweedfs://10.0.100.51:30888/tmp/presto-root/d3dd12c9-d52f-404f-aaa4-ba1a806304e1/20201011_123516_00006_udsg7_6312b54f-c4ce-4bfc-9597-ea1affee1585
2020-10-11T08:35:16.984-0400	DEBUG	20201011_123516_00006_udsg7.1.0.0-1-118	com.facebook.presto.execution.executor.TaskExecutor	Split 20201011_123516_00006_udsg7.1.0.0-1  (start = 1.211256510410175E9, wall = 75 ms, cpu = 14 ms, wait = 0 ms, calls = 2) is finished
2020-10-11T08:35:16.987-0400	DEBUG	20201011_123516_00006_udsg7.1.0.0-4-109	com.facebook.presto.execution.executor.TaskExecutor	Split 20201011_123516_00006_udsg7.1.0.0-4  (start = 1.211256512883964E9, wall = 75 ms, cpu = 3 ms, wait = 3 ms, calls = 3) is finished
2020-10-11T08:35:16.996-0400	DEBUG	http-worker-145	com.facebook.presto.execution.SqlTask	Aborting task 20201011_123516_00006_udsg7.1.0.0 output 0
2020-10-11T08:35:16.997-0400	DEBUG	task-notification-4	com.facebook.presto.execution.TaskStateMachine	Task 20201011_123516_00006_udsg7.1.0.0 is FINISHED
2020-10-11T08:35:16.998-0400	DEBUG	Task-20201011_123516_00006_udsg7.1.0.0-220	com.facebook.presto.execution.executor.TaskExecutor	Task finished or failed 20201011_123516_00006_udsg7.1.0.0
2020-10-11T08:35:17.000-0400	DEBUG	query-execution-5	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123516_00006_udsg7.1.0 is FINISHED
2020-10-11T08:35:17.034-0400	DEBUG	20201011_123516_00006_udsg7.0.0.0-0-112	com.facebook.presto.execution.executor.TaskExecutor	Split 20201011_123516_00006_udsg7.0.0.0-0  (start = 1.211256507635917E9, wall = 128 ms, cpu = 7 ms, wait = 1 ms, calls = 4) is finished
2020-10-11T08:35:17.042-0400	DEBUG	http-worker-154	com.facebook.presto.execution.SqlTask	Aborting task 20201011_123516_00006_udsg7.0.0.0 output 0
2020-10-11T08:35:17.044-0400	DEBUG	task-notification-1	com.facebook.presto.execution.TaskStateMachine	Task 20201011_123516_00006_udsg7.0.0.0 is FINISHED
2020-10-11T08:35:17.044-0400	DEBUG	Task-20201011_123516_00006_udsg7.0.0.0-216	com.facebook.presto.execution.executor.TaskExecutor	Task finished or failed 20201011_123516_00006_udsg7.0.0.0
2020-10-11T08:35:17.047-0400	DEBUG	query-execution-4	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123516_00006_udsg7.0.0 is FINISHED
2020-10-11T08:35:17.048-0400	DEBUG	dispatcher-query-8	com.facebook.presto.execution.QueryStateMachine	Query 20201011_123516_00006_udsg7 is FINISHING
2020-10-11T08:35:17.056-0400	INFO	hive-rename-hive-1	seaweed.hdfs.SeaweedFileSystemStore	rename source: seaweedfs://10.0.100.51:30888/tmp/presto-root/d3dd12c9-d52f-404f-aaa4-ba1a806304e1/20201011_123516_00006_udsg7_6312b54f-c4ce-4bfc-9597-ea1affee1585 destination:seaweedfs://10.0.100.51:30888/buckets/spark/apps/spark/warehouse/test01.db/limd01/20201011_123516_00006_udsg7_6312b54f-c4ce-4bfc-9597-ea1affee1585
2020-10-11T08:35:17.216-0400	DEBUG	dispatcher-query-8	com.facebook.presto.execution.QueryStateMachine	Query 20201011_123516_00006_udsg7 is FINISHED
2020-10-11T08:35:17.237-0400	INFO	dispatcher-query-10	com.facebook.presto.event.QueryMonitor	TIMELINE: Query 20201011_123516_00006_udsg7 :: Transaction:[923a400a-2baf-4560-9084-c02cba98937f] :: elapsed 528ms :: planning 82ms :: scheduling 138ms :: running 42ms :: finishing 266ms :: begin 2020-10-11T08:35:16.687-04:00 :: end 2020-10-11T08:35:17.215-04:00
```

**异常情况presto日志：**
```
2020-10-11T08:35:26.783-0400	DEBUG	dispatcher-query-8	com.facebook.presto.execution.QueryStateMachine	Query 20201011_123526_00007_udsg7 is QUEUED
2020-10-11T08:35:26.783-0400	DEBUG	dispatcher-query-6	com.facebook.presto.execution.QueryStateMachine	Query 20201011_123526_00007_udsg7 is WAITING_FOR_RESOURCES
2020-10-11T08:35:26.842-0400	DEBUG	dispatcher-query-7	com.facebook.presto.execution.QueryStateMachine	Query 20201011_123526_00007_udsg7 is DISPATCHING
2020-10-11T08:35:26.842-0400	DEBUG	dispatcher-query-8	com.facebook.presto.execution.QueryStateMachine	Query 20201011_123526_00007_udsg7 is PLANNING
2020-10-11T08:35:26.892-0400	WARN	Query-20201011_123526_00007_udsg7-301	seaweedfs.client.FilerClient	createEntry /tmp/presto-root/362fdda8-9a23-42cc-9e91-81d78a06c767: {}
io.grpc.StatusRuntimeException: UNKNOWN: not found /tmp/presto-root/362fdda8-9a23-42cc-9e91-81d78a06c767: filer: no entry is found in filer store
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:235)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:216)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
	at seaweedfs.client.SeaweedFilerGrpc$SeaweedFilerBlockingStub.updateEntry(SeaweedFilerGrpc.java:1079)
	at seaweedfs.client.FilerClient.updateEntry(FilerClient.java:288)
	at seaweed.hdfs.SeaweedFileSystemStore.setPermission(SeaweedFileSystemStore.java:272)
	at seaweed.hdfs.SeaweedFileSystem.setPermission(SeaweedFileSystem.java:293)
	at org.apache.hadoop.fs.HadoopExtendedFileSystem.setPermission(HadoopExtendedFileSystem.java:482)
	at com.facebook.presto.hive.metastore.MetastoreUtil.createDirectory(MetastoreUtil.java:639)
	at com.facebook.presto.hive.HiveWriteUtils.createTemporaryPath(HiveWriteUtils.java:438)
	at com.facebook.presto.hive.HiveLocationService.createLocationHandle(HiveLocationService.java:97)
	at com.facebook.presto.hive.HiveLocationService.forExistingTable(HiveLocationService.java:75)
	at com.facebook.presto.hive.HiveMetadata.beginInsert(HiveMetadata.java:1707)
	at com.facebook.presto.hive.HiveMetadata.beginInsert(HiveMetadata.java:317)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.beginInsert(ClassLoaderSafeConnectorMetadata.java:426)
	at com.facebook.presto.metadata.MetadataManager.beginInsert(MetadataManager.java:882)
	at com.facebook.presto.execution.scheduler.TableWriteInfo.createWriterTarget(TableWriteInfo.java:93)
	at com.facebook.presto.execution.scheduler.TableWriteInfo.createTableWriteInfo(TableWriteInfo.java:76)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createSectionExecutions(SectionExecutionFactory.java:166)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.createStageExecutions(LegacySqlQueryScheduler.java:343)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.<init>(LegacySqlQueryScheduler.java:233)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.createSqlQueryScheduler(LegacySqlQueryScheduler.java:164)
	at com.facebook.presto.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:474)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:347)
	at com.facebook.presto.$gen.Presto_0_242_bfc43c2____20201011_123259_1.run(Unknown Source)
	at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:254)
	at com.facebook.presto.dispatcher.LocalDispatchQuery.lambda$startExecution$5(LocalDispatchQuery.java:114)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


2020-10-11T08:35:26.902-0400	DEBUG	query-execution-5	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123526_00007_udsg7.0.0 is PLANNED
2020-10-11T08:35:26.902-0400	DEBUG	query-execution-5	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123526_00007_udsg7.1.0 is PLANNED
2020-10-11T08:35:26.902-0400	DEBUG	query-execution-5	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123526_00007_udsg7.2.0 is PLANNED
2020-10-11T08:35:26.905-0400	DEBUG	dispatcher-query-7	com.facebook.presto.execution.QueryStateMachine	Query 20201011_123526_00007_udsg7 is STARTING
2020-10-11T08:35:26.906-0400	DEBUG	query-execution-4	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123526_00007_udsg7.2.0 is SCHEDULING
2020-10-11T08:35:26.909-0400	DEBUG	query-execution-5	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123526_00007_udsg7.2.0 is SCHEDULED
2020-10-11T08:35:26.909-0400	DEBUG	dispatcher-query-8	com.facebook.presto.execution.QueryStateMachine	Query 20201011_123526_00007_udsg7 is RUNNING
2020-10-11T08:35:26.909-0400	DEBUG	query-execution-5	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123526_00007_udsg7.1.0 is SCHEDULING
2020-10-11T08:35:26.915-0400	DEBUG	query-execution-4	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123526_00007_udsg7.1.0 is SCHEDULED
2020-10-11T08:35:26.916-0400	DEBUG	task-notification-0	com.facebook.presto.execution.TaskStateMachine	Task 20201011_123526_00007_udsg7.2.0.0 is RUNNING
2020-10-11T08:35:26.917-0400	DEBUG	task-notification-3	com.facebook.presto.execution.TaskStateMachine	Task 20201011_123526_00007_udsg7.1.0.0 is RUNNING
2020-10-11T08:35:26.917-0400	DEBUG	query-execution-4	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123526_00007_udsg7.0.0 is SCHEDULING
2020-10-11T08:35:26.925-0400	DEBUG	query-execution-4	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123526_00007_udsg7.0.0 is SCHEDULED
2020-10-11T08:35:26.926-0400	DEBUG	task-notification-1	com.facebook.presto.execution.TaskStateMachine	Task 20201011_123526_00007_udsg7.0.0.0 is RUNNING
2020-10-11T08:35:26.934-0400	DEBUG	query-execution-4	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123526_00007_udsg7.2.0 is RUNNING
2020-10-11T08:35:26.934-0400	DEBUG	query-execution-6	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123526_00007_udsg7.1.0 is RUNNING
2020-10-11T08:35:26.934-0400	DEBUG	query-execution-6	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123526_00007_udsg7.0.0 is RUNNING
2020-10-11T08:35:26.936-0400	DEBUG	Task-20201011_123526_00007_udsg7.2.0.0-161	com.facebook.presto.execution.executor.TaskExecutor	Task scheduled 20201011_123526_00007_udsg7.2.0.0
2020-10-11T08:35:26.938-0400	DEBUG	Task-20201011_123526_00007_udsg7.1.0.0-167	com.facebook.presto.execution.executor.TaskExecutor	Task scheduled 20201011_123526_00007_udsg7.1.0.0
2020-10-11T08:35:26.938-0400	DEBUG	Task-20201011_123526_00007_udsg7.0.0.0-146	com.facebook.presto.execution.executor.TaskExecutor	Task scheduled 20201011_123526_00007_udsg7.0.0.0
2020-10-11T08:35:26.948-0400	DEBUG	20201011_123526_00007_udsg7.2.0.0-0-121	com.facebook.presto.execution.executor.TaskExecutor	Split 20201011_123526_00007_udsg7.2.0.0-0  (start = 1.211266539216854E9, wall = 10 ms, cpu = 0 ms, wait = 0 ms, calls = 1) is finished
2020-10-11T08:35:26.976-0400	DEBUG	http-worker-158	com.facebook.presto.execution.SqlTask	Aborting task 20201011_123526_00007_udsg7.2.0.0 output 0
2020-10-11T08:35:26.977-0400	DEBUG	task-notification-2	com.facebook.presto.execution.TaskStateMachine	Task 20201011_123526_00007_udsg7.2.0.0 is FINISHED
2020-10-11T08:35:26.978-0400	DEBUG	Task-20201011_123526_00007_udsg7.2.0.0-217	com.facebook.presto.execution.executor.TaskExecutor	Task finished or failed 20201011_123526_00007_udsg7.2.0.0
2020-10-11T08:35:26.988-0400	DEBUG	query-execution-6	com.facebook.presto.execution.StageExecutionStateMachine	Stage Execution 20201011_123526_00007_udsg7.2.0 is FINISHED
2020-10-11T08:35:26.988-0400	DEBUG	20201011_123526_00007_udsg7.1.0.0-1-116	com.facebook.presto.execution.executor.TaskExecutor	Split 20201011_123526_00007_udsg7.1.0.0-1  (start = 1.211266546791202E9, wall = 43 ms, cpu = 4 ms, wait = 3 ms, calls = 2) is finished
2020-10-11T08:35:26.988-0400	DEBUG	20201011_123526_00007_udsg7.1.0.0-0-115	com.facebook.presto.execution.executor.TaskExecutor	Split 20201011_123526_00007_udsg7.1.0.0-0  (start = 1.211266545475205E9, wall = 44 ms, cpu = 5 ms, wait = 2 ms, calls = 3) is finished
2020-10-11T08:35:26.989-0400	DEBUG	20201011_123526_00007_udsg7.1.0.0-2-107	com.facebook.presto.execution.executor.TaskExecutor	Split 20201011_123526_00007_udsg7.1.0.0-2  (start = 1.211266546839678E9, wall = 43 ms, cpu = 4 ms, wait = 0 ms, calls = 2) is finished
2020-10-11T08:35:27.005-0400	DEBUG	20201011_123526_00007_udsg7.1.0.0-3-124	com.facebook.presto.hive.HiveEventClient	File created: query: 20201011_123526_00007_udsg7, schema: test01, table: limd01, partition: 'null', format: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat, size: 9, path: seaweedfs://10.0.100.51:30888/tmp/presto-root/362fdda8-9a23-42cc-9e91-81d78a06c767/20201011_123526_00007_udsg7_4a73ebb1-aff2-436e-9502-9d3d0b360517
2020-10-11T08:35:27.012-0400	ERROR	SplitRunner-21-124	com.facebook.presto.execution.executor.TaskExecutor	Error processing Split 20201011_123526_00007_udsg7.1.0.0-3  (start = 1.21126654937531E9, wall = 63 ms, cpu = 2 ms, wait = 2 ms, calls = 2)
java.io.UncheckedIOException: java.io.FileNotFoundException: File does not exist: seaweedfs://10.0.100.51:30888/tmp/presto-root/362fdda8-9a23-42cc-9e91-81d78a06c767/20201011_123526_00007_udsg7_4a73ebb1-aff2-436e-9502-9d3d0b360517
	at com.facebook.presto.hive.RecordFileWriter.getWrittenBytes(RecordFileWriter.java:136)
	at com.facebook.presto.hive.HiveWriter.getWrittenBytes(HiveWriter.java:65)
	at java.util.stream.ReferencePipeline$5$1.accept(ReferencePipeline.java:227)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.LongPipeline.reduce(LongPipeline.java:461)
	at java.util.stream.LongPipeline.sum(LongPipeline.java:419)
	at com.facebook.presto.hive.HivePageSink.doFinish(HivePageSink.java:239)
	at com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
	at com.facebook.presto.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:81)
	at com.facebook.presto.hive.HivePageSink.finish(HivePageSink.java:219)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSink.finish(ClassLoaderSafeConnectorPageSink.java:74)
	at com.facebook.presto.operator.TableWriterOperator.finish(TableWriterOperator.java:252)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:440)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:300)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:721)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:293)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_0_242_bfc43c2____20201011_123259_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: File does not exist: seaweedfs://10.0.100.51:30888/tmp/presto-root/362fdda8-9a23-42cc-9e91-81d78a06c767/20201011_123526_00007_udsg7_4a73ebb1-aff2-436e-9502-9d3d0b360517
	at seaweed.hdfs.SeaweedFileSystemStore.getFileStatus(SeaweedFileSystemStore.java:93)
	at seaweed.hdfs.SeaweedFileSystem.getFileStatus(SeaweedFileSystem.java:256)
	at org.apache.hadoop.fs.HadoopExtendedFileSystem.getFileStatus(HadoopExtendedFileSystem.java:384)
	at com.facebook.presto.hive.RecordFileWriter.getWrittenBytes(RecordFileWriter.java:133)
	... 26 more
```

问题2：
无法进行create table操作，抛异常为
```
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:235)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:216)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
	at seaweedfs.client.SeaweedFilerGrpc$SeaweedFilerBlockingStub.getFilerConfiguration(SeaweedFilerGrpc.java:1135)
	at seaweedfs.client.FilerGrpcClient.<init>(FilerGrpcClient.java:53)
	at seaweedfs.client.FilerGrpcClient.<init>(FilerGrpcClient.java:39)
	at seaweed.hdfs.SeaweedFileSystemStore.<init>(SeaweedFileSystemStore.java:29)
	at seaweed.hdfs.SeaweedFileSystem.initialize(SeaweedFileSystem.java:64)
	at org.apache.hadoop.fs.PrestoFileSystemCache.createFileSystem(PrestoFileSystemCache.java:133)
	at org.apache.hadoop.fs.PrestoFileSystemCache.getInternal(PrestoFileSystemCache.java:87)
	at org.apache.hadoop.fs.PrestoFileSystemCache.get(PrestoFileSystemCache.java:60)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at com.facebook.presto.hive.cache.HiveCachingHdfsConfiguration.lambda$getConfiguration$0(HiveCachingHdfsConfiguration.java:68)
	at com.facebook.presto.hive.cache.HiveCachingHdfsConfiguration$CachingJobConf.createFileSystem(HiveCachingHdfsConfiguration.java:104)
	at org.apache.hadoop.fs.PrestoFileSystemCache.get(PrestoFileSystemCache.java:57)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at com.facebook.presto.hive.HdfsEnvironment.lambda$getFileSystem$0(HdfsEnvironment.java:71)
	at com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
	at com.facebook.presto.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:70)
	at com.facebook.presto.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:64)
	at com.facebook.presto.hive.HiveWriteUtils.isS3FileSystem(HiveWriteUtils.java:379)
	at com.facebook.presto.hive.HiveWriteUtils.getTableDefaultLocation(HiveWriteUtils.java:359)
	at com.facebook.presto.hive.HiveLocationService.forNewTable(HiveLocationService.java:61)
	at com.facebook.presto.hive.HiveMetadata.createTable(HiveMetadata.java:895)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.createTable(ClassLoaderSafeConnectorMetadata.java:346)
	at com.facebook.presto.metadata.MetadataManager.createTable(MetadataManager.java:659)
	at com.facebook.presto.execution.CreateTableTask.internalExecute(CreateTableTask.java:195)
	at com.facebook.presto.execution.CreateTableTask.execute(CreateTableTask.java:82)
	at com.facebook.presto.execution.CreateTableTask.execute(CreateTableTask.java:64)
	at com.facebook.presto.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:187)
	at com.facebook.presto.$gen.Presto_0_242_bfc43c2____20201011_114900_1.run(Unknown Source)
	at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:254)
	at com.facebook.presto.dispatcher.LocalDispatchQuery.lambda$startExecution$5(LocalDispatchQuery.java:114)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by chrislusf** [comment]
In https://github.com/prestodb/presto/blob/472538a02722c5409649533f9a602b5b76d9dd2d/presto-hive-metastore/src/main/java/com/facebook/presto/hive/metastore/MetastoreUtil.java#L626

the function would `mkdirs()` and then `setPermission()`. And seems mkdir was successful, but not found the dir when changing permission. Maybe show some verbose logs on the filer at that point of time.

**Comment by chrislusf** [comment]
`create table` error seems related to grpc version mismatch.

**Comment by chrislusf** [comment]
> 2020-10-11T08:35:26.892-0400	WARN	Query-20201011_123526_00007_udsg7-301	seaweedfs.client.FilerClient	createEntry /tmp/presto-root/362fdda8-9a23-42cc-9e91-81d78a06c767: {}

there is a warning but not printed out the content.

**Comment by hilimd** [comment]
多谢，我持续跟踪测试下
