### ISSUE TITLE
FUSE Mount: SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by Suika** [chrislusf/seaweedfs#1597]
```
This is SeaweedFS version 8000GB 2.07 4492122 linux amd64
mount point owner uid=0 gid=0 mode=drwxr-xr-x
current uid=0 gid=0
I1103 11:52:23 10402 leveldb_store.go:40] filer store dir: /snapraid/storage_c2/test/seaweed-cache/e1b2/meta
I1103 11:52:23 10402 file_util.go:23] Folder /snapraid/storage_c2/test/seaweed-cache/e1b2/meta Permission: -rwxr-xr-x
I1103 11:52:27 10402 mount_std.go:206] mounted localhost:8888/ to /mnt/weed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xeac8b5]

goroutine 1215531 [running]:
github.com/chrislusf/seaweedfs/weed/filer.MergeIntoVisibles(0x0, 0x1, 0x1, 0xc0093a6aa0, 0x1, 0x17fb4ca6da998, 0x7fb4a3539880)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filer/filechunks.go:182 +0x175
github.com/chrislusf/seaweedfs/weed/filesys.(*File).addChunks(0xc00a72fda0, 0xc01275c048, 0x1, 0x1)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/file.go:280 +0x126
github.com/chrislusf/seaweedfs/weed/filesys.(*ContinuousDirtyPages).saveToStorage.func1(0xc009d6ecb0, 0xc0027838b0, 0x172b6c, 0x200000, 0x16440d01cdd8d4bd)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/dirty_page.go:122 +0x268
created by github.com/chrislusf/seaweedfs/weed/filesys.(*ContinuousDirtyPages).saveToStorage
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/dirty_page.go:110 +0x12d


```

**Describe the bug**
 ¯\_(ツ)_/¯
Was loading data into seaweed via the FUSE mount and then this happens.

**System Setup**
- see #1594 

**Expected behavior**
No SIGSEGV

**Additional context**
No other loogs indicate anything. dmesg also does not show anything.

**Comment by chrislusf** [comment]
Added a couple of fixes. 0ae4d7bfdfb1318c71d64ba395c27882f9b3fd6a

But seems no good way to reproduce it and confirm the fix. Closing this for now.
