### ISSUE TITLE
master got a panic

### ISSUE THREAD

**Issue by kmlebedev** [chrislusf/seaweedfs#1676]
**Describe the bug**
panic

**System Setup**
`version=2.13`

**Additional context**
```
panic: interface conversion: topology.Node is nil, not *topology.NodeImpl

goroutine 279 [running]:
github.com/chrislusf/seaweedfs/weed/topology.(*DataNode).GetDataCenter(...)
	/go/src/github.com/chrislusf/seaweedfs/weed/topology/data_node.go:154
github.com/chrislusf/seaweedfs/weed/server.(*MasterServer).SendHeartbeat(0xc0002bfc80, 0x26b6360, 0xc000700010, 0x0, 0x0)
	/go/src/github.com/chrislusf/seaweedfs/weed/server/master_grpc_server.go:91 +0x20d0
github.com/chrislusf/seaweedfs/weed/pb/master_pb._Seaweed_SendHeartbeat_Handler(0x20dcca0, 0xc0002bfc80, 0x26ac760, 0xc000ac4000, 0x37e3c70, 0xc00018cf00)
	/go/src/github.com/chrislusf/seaweedfs/weed/pb/master_pb/master.pb.go:4329 +0xad
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000735040, 0x26b96c0, 0xc000adbe00, 0xc00018cf00, 0xc000786990, 0x3719fa0, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1329 +0xb2e
google.golang.org/grpc.(*Server).handleStream(0xc000735040, 0x26b96c0, 0xc000adbe00, 0xc00018cf00, 0x0)
	/root/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1409 +0xcc0
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0006d19d0, 0xc000735040, 0x26b96c0, 0xc000adbe00, 0xc00018cf00)
	/root/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/root/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa1
```

**Comment by chrislusf** [comment]
reproducible?

**Comment by chrislusf** [comment]
Not able to reproduce.

**Comment by norteee** [comment]
i got the same problem...

**Comment by chrislusf** [comment]
How to reproduce it?
