### ISSUE TITLE
When updating from 2.15 to 2.16 got panic on filler

### ISSUE THREAD

**Issue by kmlebedev** [chrislusf/seaweedfs#1691]
**Describe the bug**
When updating from 2.15 to 2.16 got panic on filler

**System Setup**
```2.16```

**Additional context**
```
I1221 07:45:42     1 filer.go:101] existing filer.store.id = -395420478
I1221 07:45:42     1 configuration.go:28] configured filer for mysql
panic: reflect: call of reflect.Value.Elem on zero Value

goroutine 1 [running]:
reflect.Value.Elem(0x0, 0x0, 0x0, 0x5, 0x37f5fc0, 0x1)
	/usr/lib/go/src/reflect/value.go:837 +0x1c3
github.com/chrislusf/seaweedfs/weed/filer.(*Filer).LoadConfiguration(0xc000469340, 0xc00023e900)
	/go/src/github.com/chrislusf/seaweedfs/weed/filer/configuration.go:63 +0x474
github.com/chrislusf/seaweedfs/weed/server.NewFilerServer(0xc000410880, 0xc000410880, 0xc000270000, 0x1, 0x0, 0x0)
	/go/src/github.com/chrislusf/seaweedfs/weed/server/filer_server.go:121 +0x83b
github.com/chrislusf/seaweedfs/weed/command.(*FilerOptions).startFiler(0x37d4b00)
	/go/src/github.com/chrislusf/seaweedfs/weed/command/filer.go:140 +0x2ed
github.com/chrislusf/seaweedfs/weed/command.runFiler(0x372ef00, 0xc00003c1d0, 0x0, 0x0, 0x0)
	/go/src/github.com/chrislusf/seaweedfs/weed/command/filer.go:116 +0x82
main.main()
	/go/src/github.com/chrislusf/seaweedfs/weed/weed.go:66 +0x2f9
```

**Comment by chrislusf** [comment]
are you using the path-specific filer store? What is your `filer.toml` content?

**Comment by kmlebedev** [comment]
> are you using the path-specific filer store? What is your `filer.toml` content?

```
/ # cat /etc/seaweedfs/filer.toml

[filer.options]
recursive_delete = false
# directories under this folder will be automatically creating a separate bucket
buckets_folder = "/buckets"
buckets_fsync = [          # a list of buckets with all write requests fsync=true
  "important_bucket",
  "should_always_fsync",
]
[leveldb2]
enabled = false

[mysql]  # or tidb
# CREATE TABLE IF NOT EXISTS filemeta (
#   dirhash     BIGINT         COMMENT 'first 64 bits of MD5 hash value of directory field',
#   name        VARCHAR(1000)  COMMENT 'directory or file name',
#   directory   TEXT           COMMENT 'full path to parent directory',
#   meta        LONGBLOB,
#   PRIMARY KEY (dirhash, name)
# ) DEFAULT CHARSET=utf8;

enabled = true
hostname = "s3-pxc.query.consul"
port = 3306
database = "seaweedfs_fast"     # create or use an existing database
connection_max_idle = 2
connection_max_open = 40
interpolateParams = false
```

**Comment by kmlebedev** [comment]
Locally not reproducible

**Comment by chrislusf** [comment]
The mysql instance in the #1693 first run will take a fairly long time to initialize. When filer tried to connect to it before it is ready, the filer store will show the error. 

Seems the docker compose file needs to wait until the mysql instance is ready first before starting filer.

```
Creating seaweedfs_ingress_1 ... done
Creating seaweedfs_master_1  ... done
Creating seaweedfs_mysql_1   ... done
Creating seaweedfs_volume_1  ... done
Creating seaweedfs_filer_1   ... done
Creating seaweedfs_s3_1      ... done
Attaching to seaweedfs_mysql_1, seaweedfs_master_1, seaweedfs_ingress_1, seaweedfs_volume_1, seaweedfs_filer_1, seaweedfs_s3_1
ingress_1  | WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A pre-generated dhparam.pem will be used for now while a new one
ingress_1  | is being generated in the background.  Once the new dhparam.pem is in place, nginx will be reloaded.
filer_1    | F1221 20:38:17     1 configuration.go:25] failed to initialize store for mysql: connect to seaweedfs:secret@tcp(mysql:3306)/seaweedfs?charset=utf8 error:dial tcp 172.20.0.2:3306: connect: connection refused
master_1   | I1221 20:38:15     1 file_util.go:23] Folder /data Permission: -rwxr-xr-x
ingress_1  | forego     | starting dockergen.1 on port 5000
filer_1    | goroutine 1 [running]:
filer_1    | github.com/chrislusf/seaweedfs/weed/glog.stacks(0xc000254700, 0xc000184640, 0xcf, 0x124)
filer_1    | 	/Users/chris/go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0xb9
filer_1    | github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x3263400, 0xc000000003, 0xc00017c3f0, 0x3190f49, 0x10, 0x19, 0x0)
filer_1    | 	/Users/chris/go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:718 +0x385
filer_1    | github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x3263400, 0x3, 0x20dd4a0, 0x26, 0xc0004f5730, 0x2, 0x2)
filer_1    | 	/Users/chris/go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:656 +0x153
filer_1    | github.com/chrislusf/seaweedfs/weed/glog.Fatalf(...)
filer_1    | 	/Users/chris/go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:1149
filer_1    | github.com/chrislusf/seaweedfs/weed/filer.(*Filer).LoadConfiguration(0xc00013c2c0, 0xc0000ae100)
filer_1    | 	/Users/chris/go/src/github.com/chrislusf/seaweedfs/weed/filer/configuration.go:25 +0x1051
filer_1    | github.com/chrislusf/seaweedfs/weed/server.NewFilerServer(0xc0007e3440, 0xc0007e3440, 0xc0007f8000, 0x1, 0x0, 0x0)
filer_1    | 	/Users/chris/go/src/github.com/chrislusf/seaweedfs/weed/server/filer_server.go:121 +0x82d
filer_1    | github.com/chrislusf/seaweedfs/weed/command.(*FilerOptions).startFiler(0x3263220)
filer_1    | 	/Users/chris/go/src/github.com/chrislusf/seaweedfs/weed/command/filer.go:140 +0x2f8
filer_1    | github.com/chrislusf/seaweedfs/weed/command.runFiler(0x3247c80, 0xc00003a1d0, 0x0, 0x0, 0x0)
filer_1    | 	/Users/chris/go/src/github.com/chrislusf/seaweedfs/weed/command/filer.go:116 +0x85
filer_1    | main.main()
filer_1    | 	/Users/chris/go/src/github.com/chrislusf/seaweedfs/weed/weed.go:66 +0x30e
master_1   | I1221 20:38:15     1 master.go:168] current: master:9333 peers:
ingress_1  | forego     | starting nginx.1 on port 5100
master_1   | I1221 20:38:15     1 master_server.go:107] Volume Size Limit is 1024 MB
mysql_1    | Initializing database
volume_1   | I1221 20:38:16     1 file_util.go:23] Folder /data Permission: -rwxr-xr-x
ingress_1  | dockergen.1 | 2020/12/21 20:38:15 Generated '/etc/nginx/conf.d/default.conf' from 3 containers
ingress_1  | dockergen.1 | 2020/12/21 20:38:15 Running 'nginx -s reload'
mysql_1    | 2020-12-21T20:38:15.615404Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_1    | 2020-12-21T20:38:16.315621Z 0 [Warning] InnoDB: New log files created, LSN=45790
ingress_1  | dockergen.1 | 2020/12/21 20:38:15 Watching docker events
master_1   | I1221 20:38:15     1 master_server.go:192] adminScripts:
master_1   | I1221 20:38:15     1 master.go:122] Start Seaweed Master 30GB 2.16  at 0.0.0.0:9333
master_1   | I1221 20:38:15     1 raft_server.go:70] Starting RaftServer with master:9333
ingress_1  | dockergen.1 | 2020/12/21 20:38:15 Error inspecting container: 3e0069cf593edfd296914893db042781a578e56fb323fa66b9db2b97113afff5: No such container: 3e0069cf593edfd296914893db042781a578e56fb323fa66b9db2b97113afff5
mysql_1    | 2020-12-21T20:38:16.398290Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
master_1   | I1221 20:38:15     1 raft_server.go:129] current cluster leader:
master_1   | I1221 20:38:15     1 master.go:146] Start Seaweed Master 30GB 2.16  grpc server at 0.0.0.0:19333
mysql_1    | 2020-12-21T20:38:16.408895Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: 7409501a-43cc-11eb-a822-0242ac140002.
master_1   | I1221 20:38:17     1 masterclient.go:78] No existing leader found!
master_1   | I1221 20:38:17     1 raft_server.go:154] Initializing new cluster
master_1   | I1221 20:38:17     1 master_server.go:141] leader change event:  => master:9333
master_1   | I1221 20:38:17     1 master_server.go:143] [ master:9333 ] master:9333 becomes leader.
ingress_1  | dockergen.1 | 2020/12/21 20:38:15 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
seaweedfs_filer_1 exited with code 255
master_1   | I1221 20:38:17     1 master_grpc_server.go:250] + client filer@172.20.0.6:8888
mysql_1    | 2020-12-21T20:38:16.410612Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
ingress_1  | dockergen.1 | 2020/12/21 20:38:16 Received event start for container 3e0069cf593e
ingress_1  | dockergen.1 | 2020/12/21 20:38:16 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
mysql_1    | 2020-12-21T20:38:16.597588Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
ingress_1  | dockergen.1 | 2020/12/21 20:38:17 Received event start for container 5d4e51d1a8ca
ingress_1  | dockergen.1 | 2020/12/21 20:38:17 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
master_1   | I1221 20:38:17     1 master_grpc_server.go:266] - client filer@172.20.0.6:8888
ingress_1  | dockergen.1 | 2020/12/21 20:38:17 Received event die for container 5d4e51d1a8ca
ingress_1  | dockergen.1 | 2020/12/21 20:38:17 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
ingress_1  | dockergen.1 | 2020/12/21 20:38:17 Received event start for container 15cdfc7ee414
ingress_1  | dockergen.1 | 2020/12/21 20:38:17 Generated '/etc/nginx/conf.d/default.conf' from 5 containers
mysql_1    | Database initialized
mysql_1    | Initializing certificates
mysql_1    | Ignoring -days; not generating a certificate
mysql_1    | Generating a RSA private key
mysql_1    | .........................................................................+++++
mysql_1    | .+++++
mysql_1    | writing new private key to 'ca-key.pem'
mysql_1    | -----
mysql_1    | Ignoring -days; not generating a certificate
mysql_1    | Generating a RSA private key
mysql_1    | .......................................................................+++++
mysql_1    | .........................................+++++
mysql_1    | writing new private key to 'server-key.pem'
mysql_1    | -----
mysql_1    | Ignoring -days; not generating a certificate
mysql_1    | Generating a RSA private key
mysql_1    | ....+++++
mysql_1    | .............................+++++
mysql_1    | writing new private key to 'client-key.pem'
mysql_1    | -----
mysql_1    | Certificates initialized
mysql_1    | MySQL init process in progress...
mysql_1    | 2020-12-21T20:38:19.995978Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_1    | 2020-12-21T20:38:19.996926Z 0 [Note] mysqld (mysqld 5.7.32-35) starting as process 72 ...
mysql_1    | 2020-12-21T20:38:19.999473Z 0 [Note] InnoDB: PUNCH HOLE support available
mysql_1    | 2020-12-21T20:38:19.999509Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql_1    | 2020-12-21T20:38:19.999513Z 0 [Note] InnoDB: Uses event mutexes
mysql_1    | 2020-12-21T20:38:19.999515Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mysql_1    | 2020-12-21T20:38:19.999517Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql_1    | 2020-12-21T20:38:19.999519Z 0 [Note] InnoDB: Using Linux native AIO
mysql_1    | 2020-12-21T20:38:19.999758Z 0 [Note] InnoDB: Number of pools: 1
mysql_1    | 2020-12-21T20:38:19.999916Z 0 [Note] InnoDB: Using CPU crc32 instructions
mysql_1    | 2020-12-21T20:38:20.001243Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
mysql_1    | 2020-12-21T20:38:20.004712Z 0 [Note] InnoDB: Completed initialization of buffer pool
mysql_1    | 2020-12-21T20:38:20.006752Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql_1    | 2020-12-21T20:38:20.017819Z 0 [Note] InnoDB: Crash recovery did not find the parallel doublewrite buffer at /var/lib/mysql/xb_doublewrite
mysql_1    | 2020-12-21T20:38:20.018512Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
mysql_1    | 2020-12-21T20:38:20.037347Z 0 [Note] InnoDB: Created parallel doublewrite buffer at /var/lib/mysql/xb_doublewrite, size 3932160 bytes
mysql_1    | 2020-12-21T20:38:20.040977Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql_1    | 2020-12-21T20:38:20.041145Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql_1    | 2020-12-21T20:38:20.111440Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql_1    | 2020-12-21T20:38:20.112071Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
mysql_1    | 2020-12-21T20:38:20.112162Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
mysql_1    | 2020-12-21T20:38:20.112589Z 0 [Note] InnoDB: Waiting for purge to start
mysql_1    | 2020-12-21T20:38:20.162934Z 0 [Note] InnoDB: Percona XtraDB (http://www.percona.com) 5.7.32-35 started; log sequence number 2751968
mysql_1    | 2020-12-21T20:38:20.163324Z 0 [Note] Plugin 'FEDERATED' is disabled.
mysql_1    | 2020-12-21T20:38:20.167884Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
mysql_1    | 2020-12-21T20:38:20.167922Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
mysql_1    | 2020-12-21T20:38:20.168823Z 0 [Warning] CA certificate ca.pem is self signed.
mysql_1    | 2020-12-21T20:38:20.168887Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
mysql_1    | 2020-12-21T20:38:20.169192Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql_1    | 2020-12-21T20:38:20.170741Z 0 [Note] InnoDB: Buffer pool(s) load completed at 201221 20:38:20
mysql_1    | 2020-12-21T20:38:20.178265Z 0 [Note] Event Scheduler: Loaded 0 events
mysql_1    | 2020-12-21T20:38:20.178598Z 0 [Note] mysqld: ready for connections.
mysql_1    | Version: '5.7.32-35'  socket: '/var/lib/mysql/mysql.sock'  port: 0  Percona Server (GPL), Release 35, Revision 5688520
ingress_1  | 2020/12/21 20:38:20 [notice] 67#67: signal process started
ingress_1  | Generating DSA parameters, 4096 bit long prime
ingress_1  | dhparam generation complete, reloading nginx
master_1   | I1221 20:38:20     1 masterclient.go:126] redirected to leader master:9333
master_1   | I1221 20:38:20     1 master_grpc_server.go:250] + client master@172.20.0.3:33524
mysql_1    | mysql: [Warning] Using a password on the command line interface can be insecure.
mysql_1    | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
mysql_1    | Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
volume_1   | I1221 20:38:21     1 disk_location.go:173] Store started on dir: /data with 0 volumes max 0
volume_1   | I1221 20:38:21     1 disk_location.go:176] Store started on dir: /data with 0 ec shards
volume_1   | I1221 20:38:21     1 volume_grpc_client_to_master.go:52] Volume server start with seed master nodes: [master:9333]
volume_1   | I1221 20:38:21     1 volume.go:334] Start Seaweed volume server 30GB 2.16  at 0.0.0.0:8080
volume_1   | I1221 20:38:21     1 volume_grpc_client_to_master.go:114] Heartbeat to: master:9333
master_1   | I1221 20:38:21     1 node.go:278] topo adds child DefaultDataCenter
master_1   | I1221 20:38:21     1 node.go:278] topo:DefaultDataCenter adds child DefaultRack
master_1   | I1221 20:38:21     1 node.go:278] topo:DefaultDataCenter:DefaultRack adds child volume:8080
master_1   | I1221 20:38:21     1 master_grpc_server.go:73] added volume server volume:8080
mysql_1    | Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
mysql_1    | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
mysql_1    | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
mysql_1    | mysql: [Warning] Using a password on the command line interface can be insecure.
mysql_1    | mysql: [Warning] Using a password on the command line interface can be insecure.
mysql_1    | mysql: [Warning] Using a password on the command line interface can be insecure.
mysql_1    | mysql: [Warning] Using a password on the command line interface can be insecure.
mysql_1    | mysql: [Warning] Using a password on the command line interface can be insecure.
mysql_1    |
mysql_1    | /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/seaweedfs.sql
mysql_1    | mysql: [Warning] Using a password on the command line interface can be insecure.
mysql_1    | 2020-12-21T20:38:27.858279Z 9 [Warning] Following users were specified in CREATE USER IF NOT EXISTS but they already exist. Corresponding entry in binary log used default authentication plugin 'mysql_native_password' to rewrite authentication information(if any) for them: 'seaweedfs'@'%'
mysql_1    |
mysql_1    |
mysql_1    |
mysql_1    | 2020-12-21T20:38:27.895814Z 0 [Note] Giving 0 client threads a chance to die gracefully
mysql_1    | 2020-12-21T20:38:27.895911Z 0 [Note] Shutting down slave threads
mysql_1    | 2020-12-21T20:38:27.895918Z 0 [Note] Forcefully disconnecting 0 remaining clients
mysql_1    | 2020-12-21T20:38:27.895924Z 0 [Note] Event Scheduler: Purging the queue. 0 events
mysql_1    | 2020-12-21T20:38:27.896000Z 0 [Note] Binlog end
mysql_1    | 2020-12-21T20:38:27.896526Z 0 [Note] Shutting down plugin 'ngram'
mysql_1    | 2020-12-21T20:38:27.896562Z 0 [Note] Shutting down plugin 'partition'
mysql_1    | 2020-12-21T20:38:27.896567Z 0 [Note] Shutting down plugin 'BLACKHOLE'
mysql_1    | 2020-12-21T20:38:27.896570Z 0 [Note] Shutting down plugin 'ARCHIVE'
mysql_1    | 2020-12-21T20:38:27.896571Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
mysql_1    | 2020-12-21T20:38:27.896574Z 0 [Note] Shutting down plugin 'MyISAM'
mysql_1    | 2020-12-21T20:38:27.896579Z 0 [Note] Shutting down plugin 'INNODB_TABLESPACES_SCRUBBING'
mysql_1    | 2020-12-21T20:38:27.896582Z 0 [Note] Shutting down plugin 'INNODB_TABLESPACES_ENCRYPTION'
mysql_1    | 2020-12-21T20:38:27.896584Z 0 [Note] Shutting down plugin 'INNODB_SYS_VIRTUAL'
mysql_1    | 2020-12-21T20:38:27.896585Z 0 [Note] Shutting down plugin 'INNODB_CHANGED_PAGES'
mysql_1    | 2020-12-21T20:38:27.896587Z 0 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
mysql_1    | 2020-12-21T20:38:27.896588Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
mysql_1    | 2020-12-21T20:38:27.896590Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
mysql_1    | 2020-12-21T20:38:27.896592Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
mysql_1    | 2020-12-21T20:38:27.896593Z 0 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
mysql_1    | 2020-12-21T20:38:27.896595Z 0 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
mysql_1    | 2020-12-21T20:38:27.896596Z 0 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
mysql_1    | 2020-12-21T20:38:27.896598Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
mysql_1    | 2020-12-21T20:38:27.896599Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
mysql_1    | 2020-12-21T20:38:27.896601Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
mysql_1    | 2020-12-21T20:38:27.896603Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
mysql_1    | 2020-12-21T20:38:27.896604Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
mysql_1    | 2020-12-21T20:38:27.896606Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
mysql_1    | 2020-12-21T20:38:27.896607Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
mysql_1    | 2020-12-21T20:38:27.896609Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
mysql_1    | 2020-12-21T20:38:27.896610Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
mysql_1    | 2020-12-21T20:38:27.896612Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
mysql_1    | 2020-12-21T20:38:27.896614Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
mysql_1    | 2020-12-21T20:38:27.896616Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
mysql_1    | 2020-12-21T20:38:27.896617Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
mysql_1    | 2020-12-21T20:38:27.896619Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
mysql_1    | 2020-12-21T20:38:27.896620Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
mysql_1    | 2020-12-21T20:38:27.896623Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
mysql_1    | 2020-12-21T20:38:27.896625Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
mysql_1    | 2020-12-21T20:38:27.896626Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
mysql_1    | 2020-12-21T20:38:27.896628Z 0 [Note] Shutting down plugin 'INNODB_CMP'
mysql_1    | 2020-12-21T20:38:27.896630Z 0 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
mysql_1    | 2020-12-21T20:38:27.896631Z 0 [Note] Shutting down plugin 'INNODB_LOCKS'
mysql_1    | 2020-12-21T20:38:27.896633Z 0 [Note] Shutting down plugin 'INNODB_TRX'
mysql_1    | 2020-12-21T20:38:27.896635Z 0 [Note] Shutting down plugin 'XTRADB_ZIP_DICT_COLS'
mysql_1    | 2020-12-21T20:38:27.896636Z 0 [Note] Shutting down plugin 'XTRADB_ZIP_DICT'
mysql_1    | 2020-12-21T20:38:27.896638Z 0 [Note] Shutting down plugin 'XTRADB_RSEG'
mysql_1    | 2020-12-21T20:38:27.896640Z 0 [Note] Shutting down plugin 'XTRADB_INTERNAL_HASH_TABLES'
mysql_1    | 2020-12-21T20:38:27.896641Z 0 [Note] Shutting down plugin 'XTRADB_READ_VIEW'
mysql_1    | 2020-12-21T20:38:27.896643Z 0 [Note] Shutting down plugin 'InnoDB'
mysql_1    | 2020-12-21T20:38:27.896949Z 0 [Note] InnoDB: FTS optimize thread exiting.
mysql_1    | 2020-12-21T20:38:27.897213Z 0 [Note] InnoDB: Starting shutdown...
mysql_1    | 2020-12-21T20:38:27.998426Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
mysql_1    | 2020-12-21T20:38:27.999098Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 201221 20:38:27
mysql_1    | 2020-12-21T20:38:28.304023Z 0 [Note] InnoDB: Waiting for page_cleaner to finish flushing of buffer pool
mysql_1    | 2020-12-21T20:38:29.948509Z 0 [Note] InnoDB: Shutdown completed; log sequence number 12323093
mysql_1    | 2020-12-21T20:38:29.953314Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
mysql_1    | 2020-12-21T20:38:29.953435Z 0 [Note] Shutting down plugin 'MEMORY'
mysql_1    | 2020-12-21T20:38:29.953444Z 0 [Note] Shutting down plugin 'CSV'
mysql_1    | 2020-12-21T20:38:29.953447Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
mysql_1    | 2020-12-21T20:38:29.953512Z 0 [Note] Shutting down plugin 'sha256_password'
mysql_1    | 2020-12-21T20:38:29.953521Z 0 [Note] Shutting down plugin 'mysql_native_password'
mysql_1    | 2020-12-21T20:38:29.953794Z 0 [Note] Shutting down plugin 'binlog'
mysql_1    | 2020-12-21T20:38:29.957175Z 0 [Note] mysqld: Shutdown complete
mysql_1    |
mysql_1    |
mysql_1    | MySQL init process done. Ready for start up.
mysql_1    |
mysql_1    | 2020-12-21T20:38:30.173676Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_1    | 2020-12-21T20:38:30.174818Z 0 [Note] mysqld (mysqld 5.7.32-35) starting as process 1 ...
mysql_1    | 2020-12-21T20:38:30.177707Z 0 [Note] InnoDB: PUNCH HOLE support available
mysql_1    | 2020-12-21T20:38:30.177757Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql_1    | 2020-12-21T20:38:30.177762Z 0 [Note] InnoDB: Uses event mutexes
mysql_1    | 2020-12-21T20:38:30.177764Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mysql_1    | 2020-12-21T20:38:30.177766Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql_1    | 2020-12-21T20:38:30.177769Z 0 [Note] InnoDB: Using Linux native AIO
mysql_1    | 2020-12-21T20:38:30.177990Z 0 [Note] InnoDB: Number of pools: 1
mysql_1    | 2020-12-21T20:38:30.178104Z 0 [Note] InnoDB: Using CPU crc32 instructions
mysql_1    | 2020-12-21T20:38:30.179385Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
mysql_1    | 2020-12-21T20:38:30.183197Z 0 [Note] InnoDB: Completed initialization of buffer pool
mysql_1    | 2020-12-21T20:38:30.185365Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql_1    | 2020-12-21T20:38:30.196631Z 0 [Note] InnoDB: Crash recovery did not find the parallel doublewrite buffer at /var/lib/mysql/xb_doublewrite
mysql_1    | 2020-12-21T20:38:30.197238Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
mysql_1    | 2020-12-21T20:38:30.371752Z 0 [Note] InnoDB: Created parallel doublewrite buffer at /var/lib/mysql/xb_doublewrite, size 3932160 bytes
mysql_1    | 2020-12-21T20:38:30.376083Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql_1    | 2020-12-21T20:38:30.376173Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql_1    | 2020-12-21T20:38:30.953669Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql_1    | 2020-12-21T20:38:30.954344Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
mysql_1    | 2020-12-21T20:38:30.954388Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
mysql_1    | 2020-12-21T20:38:30.954787Z 0 [Note] InnoDB: Waiting for purge to start
mysql_1    | 2020-12-21T20:38:31.007316Z 0 [Note] InnoDB: Percona XtraDB (http://www.percona.com) 5.7.32-35 started; log sequence number 12323093
mysql_1    | 2020-12-21T20:38:31.008069Z 0 [Note] Plugin 'FEDERATED' is disabled.
mysql_1    | 2020-12-21T20:38:31.008094Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql_1    | 2020-12-21T20:38:31.011281Z 0 [Note] InnoDB: Buffer pool(s) load completed at 201221 20:38:31
mysql_1    | 2020-12-21T20:38:31.013512Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
mysql_1    | 2020-12-21T20:38:31.013558Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
mysql_1    | 2020-12-21T20:38:31.014316Z 0 [Warning] CA certificate ca.pem is self signed.
mysql_1    | 2020-12-21T20:38:31.014378Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
mysql_1    | 2020-12-21T20:38:31.014741Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
mysql_1    | 2020-12-21T20:38:31.014828Z 0 [Note] IPv6 is available.
mysql_1    | 2020-12-21T20:38:31.014835Z 0 [Note]   - '::' resolves to '::';
mysql_1    | 2020-12-21T20:38:31.014890Z 0 [Note] Server socket created on IP: '::'.
mysql_1    | 2020-12-21T20:38:31.024660Z 0 [Note] Event Scheduler: Loaded 0 events
mysql_1    | 2020-12-21T20:38:31.025088Z 0 [Note] mysqld: ready for connections.
mysql_1    | Version: '5.7.32-35'  socket: '/var/lib/mysql/mysql.sock'  port: 3306  Percona Server (GPL), Release 35, Revision 5688520
```

**Comment by chrislusf** [comment]
I added one more fix for the original error stack in the issue.

**Comment by kmlebedev** [comment]
@chrislusf 
I rebuild image from master and got 
```
I1222 10:23:15     1 filer.go:101] existing filer.store.id = -395420478
I1222 10:23:15     1 configuration.go:28] configured filer for mysql
E1222 10:23:15     1 configuration.go:64] path-specific filer store https.client is not found
```

**Comment by chrislusf** [comment]
some `.toml` file has `https.client.enabled`?

**Comment by kmlebedev** [comment]
> some `.toml` file has `https.client.enabled` defined?

Yes.

security.toml:
```
    [https.client]
    enabled = false
```

**Comment by chrislusf** [comment]
I see. Added a fix.
