### ISSUE TITLE
Data loss after vacuuming

### ISSUE THREAD

**Issue by kmlebedev** [chrislusf/seaweedfs#1709]
**Describe the bug**
Data loss after vacuuming 

**System Setup**
```2.13```

**Expected behavior**

**Additional context**
```

Dec 24, 2020 @ 03:03:00.429 | I1223 22:03:00     1 topology_vacuum.go:70] 1 Start vacuuming 362 on fast-volume-1.dc1:8080

  | Dec 24, 2020 @ 03:03:00.429 | I1223 22:03:00     1 topology_vacuum.go:70] 0 Start vacuuming 362 on fast-volume-6.dc2:8080

  | Dec 24, 2020 @ 03:03:03.089 | I1223 22:03:02     1 topology_vacuum.go:70] 0 Start vacuuming 362 on fast-volume-6.s3-fast-volume.service.dcix.consul:8080

  | Dec 24, 2020 @ 03:03:03.089 | I1223 22:03:02     1 topology_vacuum.go:70] 1 Start vacuuming 362 on fast-volume-1.s3-fast-volume.service.dcdp.consul:8080

  | Dec 24, 2020 @ 03:03:03.089 | I1223 22:03:02     1 topology_vacuum.go:106] Start Committing vacuum 264 on fast-volume-0.s3-fast-volume.service.dcdp.consul:8080

  | Dec 24, 2020 @ 03:03:03.089 | I1223 22:03:02     1 volume_layout.go:352] Volume 264 becomes writable

  | Dec 24, 2020 @ 03:03:12.089 | I1223 22:03:11     1 topology_vacuum.go:82] Complete vacuuming 362 on fast-volume-6.dc2:8080

  | Dec 24, 2020 @ 03:03:12.420 | I1223 22:03:11     1 topology_vacuum.go:82] Complete vacuuming 362 on fast-volume-6.dc2:8080

  | Dec 24, 2020 @ 03:03:15.382 | I1223 22:03:15     1 volume_loading.go:109] loading index /data/registry_362.idx to memory

  | Dec 24, 2020 @ 03:03:15.382 | I1223 22:03:15     1 volume_vacuum.go:93] Committing volume 362 vacuuming...

  | Dec 24, 2020 @ 03:03:15.382 | I1223 22:03:15     1 volume_vacuum.go:93] Committing volume 362 vacuuming...

  | Dec 24, 2020 @ 03:03:15.382 | E1223 22:03:15     1 volume_grpc_vacuum.go:50] commit volume 362: rename /data/registry_362.cpd: rename /data/registry_362.cpd /data/registry_362.dat: no such file or directory

  | Dec 24, 2020 @ 03:03:15.432 | I1223 22:03:15     1 topology_vacuum.go:106] Start Committing vacuum 362 on fast-volume-6.dc2:8080

  | Dec 24, 2020 @ 03:03:15.432 | I1223 22:03:15     1 topology_vacuum.go:82] Complete vacuuming 362 on fast-volume-1.dc1:8080

  | Dec 24, 2020 @ 03:03:15.432 | I1223 22:03:15     1 topology_vacuum.go:120] Complete Committing vacuum 362 on fast-volume-6.dc2:8080

  | Dec 24, 2020 @ 03:03:15.432 | I1223 22:03:15     1 topology_vacuum.go:106] Start Committing vacuum 362 on fast-volume-1.dc1:8080

  | Dec 24, 2020 @ 03:03:15.432 | I1223 22:03:15     1 master_grpc_server.go:266] - client master@10.1.1.9:58850

  | Dec 24, 2020 @ 03:03:15.432 | I1223 22:03:15     1 topology_vacuum.go:120] Complete Committing vacuum 362 on fast-volume-1.dc1:8080

  | Dec 24, 2020 @ 03:03:15.432 | I1223 22:03:15     1 volume_layout.go:352] Volume 362 becomes writable

  | Dec 24, 2020 @ 03:03:15.741 | I1223 22:03:15     1 volume_loading.go:109] loading index /data/registry_362.idx to memory

  | Dec 24, 2020 @ 03:03:15.741 | I1223 22:03:15     1 volume_vacuum.go:93] Committing volume 362 vacuuming...

 | Dec 24, 2020 @ 03:03:16.087 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x179d1ab]

  | Dec 24, 2020 @ 03:03:16.087 | github.com/chrislusf/seaweedfs/weed/operation.WithVolumeServerClient.func1(0xc000a04380, 0x36, 0xc000ddbb18)

  | Dec 24, 2020 @ 03:03:16.087 | /go/src/github.com/chrislusf/seaweedfs/weed/operation/grpc_client.go:24 +0x1ae

  | Dec 24, 2020 @ 03:03:16.087 | /go/src/github.com/chrislusf/seaweedfs/weed/topology/topology_vacuum.go:107 +0x314

  | Dec 24, 2020 @ 03:03:16.087 | github.com/chrislusf/seaweedfs/weed/topology.vacuumOneVolumeLayout(0x2658be0, 0xc00017a0f0, 0xc000276a80, 0xc0007f28a0, 0x3fd3333333333333, 0x0)

  | Dec 24, 2020 @ 03:03:16.087 | created by github.com/chrislusf/seaweedfs/weed/topology.(*Topology).StartRefreshWritableVolumes

  | Dec 24, 2020 @ 03:03:16.087 | /go/src/github.com/chrislusf/seaweedfs/weed/pb/grpc_client_server.go:106 +0x150

  | Dec 24, 2020 @ 03:03:16.087 | github.com/chrislusf/seaweedfs/weed/topology.batchVacuumVolumeCommit(0x2658be0, 0xc00017a0f0, 0xc000276a80, 0xc00000016a, 0xc00075d9e0, 0x0)

  | Dec 24, 2020 @ 03:03:16.087 | panic: runtime error: invalid memory address or nil pointer dereference

Dec 24, 2020 @ 03:03:16.087 | github.com/chrislusf/seaweedfs/weed/operation.WithVolumeServerClient(0xc0008d2880, 0x35, 0x2658be0, 0xc00017a0f0, 0xc000ddbc18, 0xc000f9b6bc, 0x4)
-- | --

  | Dec 24, 2020 @ 03:03:16.087 | /go/src/github.com/chrislusf/seaweedfs/weed/topology/topology_event_handling.go:22 +0x8f

  | Dec 24, 2020 @ 03:03:16.087 | I1223 22:03:15     1 topology_vacuum.go:82] Complete vacuuming 362 on fast-volume-1.dc1:8080

  | Dec 24, 2020 @ 03:03:16.087 | github.com/chrislusf/seaweedfs/weed/pb.WithCachedGrpcClient(0xc000ddbb08, 0xc0008d28c0, 0x36, 0xc000ddbb18, 0x1, 0x1, 0xc0008d28b1, 0xc000ddbb80)

  | Dec 24, 2020 @ 03:03:16.087 | /go/src/github.com/chrislusf/seaweedfs/weed/topology/topology_vacuum.go:193 +0x4d8

  | Dec 24, 2020 @ 03:03:16.087 | /go/src/github.com/chrislusf/seaweedfs/weed/topology/topology_vacuum.go:164 +0x236

  | Dec 24, 2020 @ 03:03:16.087 | github.com/chrislusf/seaweedfs/weed/topology.(*Topology).StartRefreshWritableVolumes.func2(0xc00013e000, 0x2658be0, 0xc00017a0f0, 0x0, 0x3fd3333333333333)


topology_vacuum.go:106] Start Committing vacuum 362 on fast-volume-6.dc2:8080
--

  | Dec 24, 2020 @ 03:03:16.087 | goroutine 130 [running]:

  | Dec 24, 2020 @ 03:03:16.087 | github.com/chrislusf/seaweedfs/weed/topology.batchVacuumVolumeCommit.func1(0x26d8160, 0xc000f26c20, 0xdbfd99, 0x21258e6)

  | Dec 24, 2020 @ 03:03:16.087 | /go/src/github.com/chrislusf/seaweedfs/weed/topology/topology_vacuum.go:111 +0xab

  | Dec 24, 2020 @ 03:03:16.087 | /go/src/github.com/chrislusf/seaweedfs/weed/operation/grpc_client.go:26 +0x76

  | Dec 24, 2020 @ 03:03:16.087 | /go/src/github.com/chrislusf/seaweedfs/weed/topology/topology_event_handling.go:26 +0xd9

  | Dec 24, 2020 @ 03:03:16.087 | github.com/chrislusf/seaweedfs/weed/topology.(*Topology).Vacuum(0xc00013e000, 0x2658be0, 0xc00017a0f0, 0x3fd3333333333333, 0x0)

  | Dec 24, 2020 @ 03:03:17.383 |  

  | Dec 24, 2020 @ 03:03:17.383 | panic: runtime error: invalid memory address or nil pointer dereference

  | Dec 24, 2020 @ 03:03:17.383 | github.com/chrislusf/seaweedfs/weed/storage.(*Volume).ToVolumeInformationMessage(0xc00003d0e0, 0xc00c451200, 0xc00064e646)

  | Dec 24, 2020 @ 03:03:17.383 | github.com/chrislusf/seaweedfs/weed/storage.(*Store).CollectHeartbeat(0xc00067e000, 0xc000304400)

  | Dec 24, 2020 @ 03:03:17.383 | github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).doHeartbeat(0xc0002ae240, 0xc000854140, 0x3c, 0xc008408040, 0x3d, 0x2658be0, 0xc00022c1a0, 0x12a05f200, 0xc000854140, 0x3c, ...)

  | Dec 24, 2020 @ 03:03:17.383 | goroutine 275 [running]:

  | Dec 24, 2020 @ 03:03:17.383 | /go/src/github.com/chrislusf/seaweedfs/weed/storage/volume.go:250 +0x40

  | Dec 24, 2020 @ 03:03:17.383 | /go/src/github.com/chrislusf/seaweedfs/weed/server/volume_grpc_client_to_master.go:207 +0x135c

  | Dec 24, 2020 @ 03:03:17.383 | /go/src/github.com/chrislusf/seaweedfs/weed/server/volume_grpc_client_to_master.go:74 +0x411

  | Dec 24, 2020 @ 03:03:17.383 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xe592e6]

  | Dec 24, 2020 @ 03:03:17.383 | created by github.com/chrislusf/seaweedfs/weed/server.NewVolumeServer

  | Dec 24, 2020 @ 03:03:17.383 | /go/src/github.com/chrislusf/seaweedfs/weed/storage/store.go:214 +0x1b2

  | Dec 24, 2020 @ 03:03:17.383 | github.com/chrislusf/seaweedfs/weed/storage.(*Volume).CollectStatus(0xc00003d0e0, 0x439089, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)

  | Dec 24, 2020 @ 03:03:17.383 | /go/src/github.com/chrislusf/seaweedfs/weed/storage/volume.go:239 +0x166

  | Dec 24, 2020 @ 03:03:17.383 | github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).heartbeat(0xc0002ae240)

  | Dec 24, 2020 @ 03:03:17.384 | /go/src/github.com/chrislusf/seaweedfs/weed/server/volume_server.go:100 +0xb1a

  | Dec 24, 2020 @ 03:03:17.744 | E1223 22:03:17     1 needle_read_write.go:175] entry not found1: offset 1331826792 found id 64366537633466366437386134306462 size -1494050589, expected size 2064


```

```

Dec 24, 2020 @ 03:04:13.913 | I1223 22:04:13     1 filer_deletion.go:89] deleting fileIds len=1 error: delete fileId 362,438af500aeced9: EOF

  | Dec 24, 2020 @ 03:04:14.382 | E1223 22:04:13     1 needle_read_write.go:175] entry not found1: offset 3879494448 found id 64333062346632393833626339333130 size -1533095409, expected size 1208687

  | Dec 24, 2020 @ 03:04:26.915 | I1223 22:04:26     1 filer_deletion.go:89] deleting fileIds len=1 error: delete fileId 362,43510ae85c9b95: EOF

  | Dec 24, 2020 @ 03:04:27.385 | E1223 22:04:26     1 needle_read_write.go:175] entry not found1: offset 1896690904 found id 38386532373438653538626432336239 size -1685361565, expected size 286

  | Dec 24, 2020 @ 03:04:27.741 | E1223 22:04:26     1 needle_read_write.go:175] entry not found1: offset 1896690904 found id 39633936613362613462613530613836 size -689843619, expected size 286


```

after
```

Dec 24, 2020 @ 03:17:26.739 | E1223 22:17:26     1 stream.go:39] read chunk: http://fast-volume-6.dc2:8080/362,43260ceeceaaec?readDeleted=true: 404 Not Found

  | Dec 24, 2020 @ 03:17:26.739 | E1223 22:17:26     1 stream.go:39] read chunk: http://fast-volume-6.dc2:8080/362,43260ceeceaaec?readDeleted=true: 404 Not Found

  | Dec 24, 2020 @ 03:17:26.739 | E1223 22:17:26     1 stream.go:39] read chunk: http://fast-volume-6.dc2:8080/362,43260ceeceaaec?readDeleted=true: 404 Not Found

```

**Comment by chrislusf** [comment]
Sorry this happened. There were 2 vacuuming going on at the same time.

This is related to a problem where the volume is loaded twice. It has been fixed by https://github.com/chrislusf/seaweedfs/commit/e2076201d79e84df0407a9e1e535bf966452bba0

**Comment by kmlebedev** [comment]
Thank you, not critical as this is a registry
