### ISSUE TITLE
2.17 s3 "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by antitbone** [chrislusf/seaweedfs#1712]
Hello

I have a crash with seaweedfs s3  2.17

**Describe the bug**
s3 server crash on upload file

**System Setup**
seaweedfs 2.17
mc client RELEASE.2019-10-02T19-41-02Z (OLD)

**s3_config.json**
```
/etc/seaweedfs/s3_config.json:
{
  "identities": [
  {...},
    {
      "name": "ibp-minio",
      "credentials": [
        {
          "accessKey": "xxx",
          "secretKey": "xxx"
        }
      ],
      "actions": [
        "Read",
        "Write",
	"List",
        "Tagging"
      ]
    }
  ]
}
```

**seaweedfs 2.16**
```
mc: <DEBUG> PUT /ldi-prod/5a7c1b238fe56f40ea0c3732/84/30d/linux_amd64.tar.gz HTTP/1.1
Host: seaweedfs-vip-http.exemple.com:8333
User-Agent: MinIO (linux; amd64) minio-go/v6.0.38 mc/2019-10-02T19:41:02Z
Content-Length: 24219087
Authorization: AWS4-HMAC-SHA256 Credential=9Otnaidyon/20201228/us-east-1/s3/aws4_request,SignedHeaders=hos
t;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length,Signature=**REDACTED**
Content-Type: application/gzip
X-Amz-Content-Sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
X-Amz-Date: 20201228T160555Z
X-Amz-Decoded-Content-Length: 24185703
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 0
Accept-Ranges: bytes
Date: Mon, 28 Dec 2020 16:05:56 GMT
Etag: "e2372b8feb5f09266df436f3de5c1166"
Server: SeaweedFS S3 30GB 2.16
X-Amz-Request-Id: 1609171556776577066

mc: <DEBUG> Response Time:  1.777194714s
```

```
déc. 28 17:05:55 test-seaweedfs1.exemple.com weed-s3[25542]: I1228 17:05:55 25542 auth_credentials.go:172] v4 auth type
déc. 28 17:05:55 test-seaweedfs1.exemple.com weed-s3[25542]: I1228 17:05:55 25542 auth_credentials.go:189] auth error: 0
déc. 28 17:05:55 test-seaweedfs1.exemple.com weed-s3[25542]: I1228 17:05:55 25542 auth_credentials.go:194] user name: ibp-minio actions: [Read Write List Tagging]
déc. 28 17:05:55 test-seaweedfs1.exemple.com weed-s3[25542]: I1228 17:05:55 25542 s3api_object_handlers.go:229] s3 proxying HEAD to http://test-seaweedfs1-s:8888/buckets/ldi-prod/5a7c1b238fe56f40ea0c3732/84/30d/linux_amd64.tar.gz
```

**seaweedfs 2.17**
```
mc: <DEBUG> GET /ldi-prod/?location= HTTP/1.1
Host: seaweedfs-vip-http.exemple.com:8333
User-Agent: MinIO (linux; amd64) minio-go/v6.0.38 mc/2019-10-02T19:41:02Z
Authorization: AWS4-HMAC-SHA256 Credential=9Otnaidyon/20201228/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20201228T162835Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 20606
Accept-Ranges: bytes
Content-Type: application/xml
Date: Mon, 28 Dec 2020 16:28:38 GMT
Server: SeaweedFS S3 30GB 2.17
X-Amz-Request-Id: 1609172918527143831

mc: <DEBUG> Response Time:  3.233419178s

mc: <DEBUG> GET /ldi-prod/?delimiter=%2F&encoding-type=url&max-keys=1000&prefix=5a7c1b238fe56f40ea0c3732%2F84%2F30d%2Flinux_amd64.tar.gz HTTP/1.1
Host: seaweedfs-vip-http.exemple.com:8333
User-Agent: MinIO (linux; amd64) minio-go/v6.0.38 mc/2019-10-02T19:41:02Z
Authorization: AWS4-HMAC-SHA256 Credential=9Otnaidyon/20201228/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20201228T162838Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 579
Accept-Ranges: bytes
Content-Type: application/xml
Date: Mon, 28 Dec 2020 16:28:38 GMT
Server: SeaweedFS S3 30GB 2.17
X-Amz-Request-Id: 1609172918574041365

mc: <DEBUG> Response Time:  43.738142ms
...
```

```
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: I1228 17:26:37 27169 auth_credentials.go:190] v4 auth type
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: I1228 17:26:37 27169 auth_credentials.go:207] auth error: 0
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: I1228 17:26:37 27169 auth_credentials.go:164] user name: ibp-minio actions: [Read Write List Tagging]
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: 2020/12/28 17:26:37 http: panic serving 212.95.66.74:42548: runtime error: invalid memory address or nil pointer dereference
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: goroutine 167 [running]:
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: net/http.(*conn).serve.func1(0xc0001ea820)
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: /home/travis/.gimme/versions/go1.15.6.linux.amd64/src/net/http/server.go:1801 +0x147
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: panic(0x1e0a780, 0x33c3f20)
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: /home/travis/.gimme/versions/go1.15.6.linux.amd64/src/runtime/panic.go:975 +0x47a
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: github.com/chrislusf/seaweedfs/weed/s3api.(*IdentityAccessManagement).authRequest(0xc0005fef00, 0xc00017c600, 0x216f0df, 0x5, 0xc000b15990, 0x46d69b)
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/s3api/auth_credentials.go:164 +0x6a
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: github.com/chrislusf/seaweedfs/weed/s3api.(*IdentityAccessManagement).Auth.func1(0x2552520, 0xc0001e2160, 0xc00017c600)
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/s3api/auth_credentials.go:142 +0x56
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: github.com/chrislusf/seaweedfs/weed/s3api.track.func1(0x2559da0, 0xc0009ca000, 0xc00017c600)
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/s3api/stats.go:34 +0x23c
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: net/http.HandlerFunc.ServeHTTP(0xc000956a00, 0x2559da0, 0xc0009ca000, 0xc00017c600)
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: /home/travis/.gimme/versions/go1.15.6.linux.amd64/src/net/http/server.go:2042 +0x44
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000cd5c0, 0x2559da0, 0xc0009ca000, 0xc0004d5200)
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: /home/travis/gopath/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xd3
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: net/http.serverHandler.ServeHTTP(0xc00017f180, 0x2559da0, 0xc0009ca000, 0xc0004d5200)
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: /home/travis/.gimme/versions/go1.15.6.linux.amd64/src/net/http/server.go:2843 +0xa3
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: net/http.(*conn).serve(0xc0001ea820, 0x2564520, 0xc0001d8700)
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: /home/travis/.gimme/versions/go1.15.6.linux.amd64/src/net/http/server.go:1925 +0x8ad
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: created by net/http.(*Server).Serve
déc. 28 17:26:37 test-sdv-seaweedfs1.sdv.fr weed-s3[27169]: /home/travis/.gimme/versions/go1.15.6.linux.amd64/src/net/http/server.go:2969 +0x36c
```

Do you need more information?

Antoine

**Comment by chrislusf** [comment]
Thanks for the detailed report!

This duplicates with https://github.com/chrislusf/seaweedfs/issues/1707

I will try to create a new release to avoid this common issue.
