### ISSUE TITLE
Uploading file with Alpakka AWS S3 connector

### ISSUE THREAD

**Issue by Joseph-Hui** [chrislusf/seaweedfs#1716]
I am adding an upload function to my Play Framework app. 

```
def saveS3FileService(filename: String, tempFile: java.nio.file.Path): Future[MultipartUploadResult] = {
    val s3Sink: Sink[ByteString, Future[MultipartUploadResult]] = S3.multipartUpload(s3fsBucket, filename)
    FileIO.fromPath(tempFile).runWith(s3Sink)
}
```
And I got the following exception reported:

`play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[S3Exception: {"error":"volume id some-file.bmp not found: Unknown volume id some-file.bmp"}]]
`

It seems I can only use a File ID rather than a file name here. Besides, when I try to list the content in the bucket with the following code.

```
def listS3Files(): Future[Seq[String]] = {
    S3.listBucket(s3fsBucket, None)
        .map(c => c.toString)
        .runWith(Sink.seq[String])
  }
```

The following exception is encounter. I think Alpakka was expecting some XML response from S3, rather than HTML. 

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[UnsupportedContentTypeException: Unsupported Content-Type [Some(text/html; charset=UTF-8)], supported: application/xml; charset=UTF-8]]

I have no experience with AWS S3 and I have not test my code on real S3 and therefore, I cannot comment whether it is Alpakka or Seaweed problem.

**Comment by chrislusf** [comment]
Need to have a way to reproduce it.

I have no experience with Alpakka.

**Comment by chrislusf** [comment]
Seems you configured s3 endpoint wrong. It should not point to the master. It should point to s3 gateway.

Usually the S3 end point is `http://localhost:8333`

**Comment by Joseph-Hui** [comment]
You are right. I pointed to localhost:9333. However, I encountered another exception after setting the end point to localhost:8333.

```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[S3Exception: ]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:359)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:261)
	at play.filters.cors.AbstractCORSPolicy$$anonfun$1.applyOrElse(AbstractCORSPolicy.scala:128)
	at play.filters.cors.AbstractCORSPolicy$$anonfun$1.applyOrElse(AbstractCORSPolicy.scala:126)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
Caused by: akka.stream.alpakka.s3.S3Exception:
	at akka.stream.alpakka.s3.S3Exception$.apply(S3Exception.scala:73)
	at akka.stream.alpakka.s3.impl.S3Stream$.$anonfun$unmarshalError$1(S3Stream.scala:246)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transform(FastFuture.scala:84)
	at scala.concurrent.Future.map(Future.scala:292)
	at scala.concurrent.Future.map$(Future.scala:292)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.map(FastFuture.scala:77)
```

In additions, I have added a file with AWS CLI and Alpakka listBucket returned nothing. I wonder this could be some other configuration problems. Do you have any idea? The following is the configuration I am using. Thanks!

```
alpakka.s3 {
  # whether the buffer request chunks (up to 5MB each) to "memory" or "disk"
  buffer = "memory"

  # location for temporary files, if buffer is set to "disk". If empty, uses the standard java temp path.
  disk-buffer-path = ""

  # DEPRECATED since Alpakka 1.0.1
  # Please use alpakka.s3.endpoint-url for setting custom scheme, host and port.
  proxy {
    # hostname of the proxy. If undefined ("") proxy is not enabled.
    host = ""
    # port = 8000

    # if "secure" is set to "true" then HTTPS will be used for all requests to S3, otherwise HTTP will be used
    secure = false
  }

  # An address of a proxy that will be used for all connections using HTTP CONNECT tunnel.
  # forward-proxy {
  #   scheme = "https"
  #   host = "proxy"
  #   port = 8080
  #   credentials {
  #     username = "username"
  #     password = "password"
  #   }
  # }

  # default values for AWS configuration
  aws {
    # If this section is absent, the fallback behavior is
    # to use the same configuration as if credentials.provider = default
    credentials {
      # anonymous requests (no auth)
      #
      # provider = anon

      # static credentials
      #
      # provider = static
      # access-key-id = ""
      # secret-access-key = ""
      # token = "" # optional

      # default: as described in software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider docs,
      # attempts to get the credentials from either:
      #   - environment variables
      #   - system properties
      #   - credentials file
      #   - EC2 credentials service
      #   - IAM / metadata
      provider = static
      access-key-id = "any"
      secret-access-key = "any"

    }

    # If this section is absent, the fallback behavior is
    # to use the same configuration as if region.provider = default
    region {
      # static credentials
      #
      # provider = static
      #
      # This can be set to the `id` value of any of the regions defined in
      # software.amazon.awssdk.regions.Region
      # default-region = ""

      # default: as described in software.amazon.awssdk.regions.providers.DefaultAwsRegionProviderChain docs,
      # attempts to get the region from either:
      #   - environment variables
      #   - system properties
      #   - progile file
      #   - EC2 metadata
      provider = static
      default-region = "us-east-1"
    }
  }

  # DEPRECATED (since Alpakka 2.0.0)
  # AWS S3 is going to retire path-style access, thus prefer the virtual-host-style access
  # https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/
  #
  # Also, prefer to use the newer access-style property.
  #
  # Possible values:
  #  - false: use virtual-host style access
  #  - true: use legacy path-style access, warnings will be logged
  #  - force: use legacy path-style access, disable warnings
  #  - empty, null or absent (default): use `access-style`, which in turn defaults to virtual-host style access
  # path-style-access = false

  # Which access style to use. Prefer to use this setting over path-style-access.
  # Path-style access has been deprecated by Amazon and will not work on buckets created after September 30, 2020.
  # For alternative S3 implementations (MinIO, Rados Gateway, etc.), path-style access may continue to be required.
  # Possible values:
  #  - virtual: virtual host-style access, i.e. https://<bucket name>.s3.amazonaws.com/file/inside/bucket
  #  - path: path-style access, i.e. https://<region>.amazonaws.com/<bucket>/file/inside/bucket
  access-style = virtual

  # Custom endpoint url, used for alternate s3 implementations
  # To enable virtual-host-style access with Alpakka S3 use the placeholder `{bucket}` in the URL
  # eg. endpoint-url = "http://{bucket}.s3minio.alpakka:9000"
  #
  endpoint-url = "http://192.168.1.91:8333"

  # Which version of the list bucket api to use. Set to 1 to use the old style version 1 API.
  # By default the newer version 2 api is used.
  list-bucket-api-version = 2

  # Object keys are validated to NOT use sub-directory selection with `..` to improve security.
  # This flag may disable the validation.
  # See https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html
  validate-object-key = true

  # Default settings corresponding to automatic retry of requests in an S3 stream.
  retry-settings {
    # The maximum number of additional attempts (following transient errors) that will be made to process a given
    # request before giving up.
    max-retries = 3

    # The minimum delay between request retries.
    min-backoff = 200ms

    # The maximum delay between request retries.
    max-backoff = 10s

    # Random jitter factor applied to retry delay calculation.
    random-factor = 0.0
  }

  # Settings specific to S3 multipart uploads.
  multipart-upload {
    retry-settings = ${alpakka.s3.retry-settings}
  }
}
```

**Comment by Joseph-Hui** [comment]
For record, the following are the log of AWS CLI ls and Alpakka S3 connector listBucket respectively. 

```
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>scolionet-archive</Name><Prefix></Prefix><MaxKeys>10000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><KeyCount>0</KeyCount></ListBucketResult>

I1230 12:21:27  6549 filer_client.go:113] read directory: directory:"/buckets" limit:2147483647
I1230 12:21:27  6549 s3api_handlers.go:89] status 200 application/xml: <?xml version="1.0" encoding="UTF-8"?>
<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Owner><DisplayName></DisplayName><ID></ID></Owner><Buckets></Buckets></ListAllMyBucketsResult>
```

**Comment by Joseph-Hui** [comment]
Found the problem. Need to set path-style access, rather than virtual host-style access in configuration.

**Comment by chrislusf** [comment]
Thanks for the update!
