### ISSUE TITLE
v2.16 panic during raft.newSnapshotRequest(...) in raft/snapshot.go:219

### ISSUE THREAD

**Issue by dch** [chrislusf/seaweedfs#1718]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs

**Describe the bug**

seaweedfs v2.16 panic during `raft.newSnapshotRequest(...)` in `raft/snapshot.go:219`.
This also occurred at approx the same time on 2 masters, 1 x86_64, the other aarch64.

**System Setup**

###  volservers x86_64

- `FreeBSD 13.0-CURRENT amd64` 
- `version 30GB 2.16  freebsd amd64`
- `go version go1.15.6 freebsd/amd64`
- each volserver is also a raft participant (master)
- ip, rack obviously vary

```
weed -logtostderr -v=2 server \
        -master.peers=172.16.1.5:9333,172.16.1.4:9333,172.16.1.8:9333 \
        -master.port=9333 \
        -master.defaultReplication=010 \
        -master.dir=/var/db/seaweedfs/metadata \
        -filer=true \
        -filer.port=8888 \
        -dir=/var/db/seaweedfs/data \
        -volume.port=9334 \
        -volume.index=leveldb \
        -volume.max=0 \
        -volume.preStopSeconds=3 \
        -dataCenter lobau -rack continuity \
        -ip=172.16.1.8
```

### master armv8 / aarch64

- `FreeBSD 13.0-CURRENT aarch64` 
- `version 30GB 2.16  freebsd arm64`
- `go version go1.15.6 freebsd/armd64`

```
weed -logtostderr -v=2 master \
    -peers=172.16.1.5:9333,172.16.1.4:9333,172.16.1.8:9333 -port=9333 \
    -defaultReplication=010 \
    -mdir=/var/db/seaweedfs/metadata \
    -ip=172.16.1.5
```

**Expected behavior**

no panics!

**Additional context**

```
2020-12-30T15:29:09.490925+00:00 straylight seaweedfs[53] I1230 15:29:09  3126 masterclient.go:138] adminShell: 172.16.1.4:9334 masterClient adds volume 368
2020-12-30T15:29:10.419641+00:00 straylight seaweedfs[53] panic: runtime error: invalid memory address or nil pointer dereference
2020-12-30T15:29:10.419658+00:00 straylight seaweedfs[53] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1414594]
2020-12-30T15:29:10.419665+00:00 straylight seaweedfs[53] 
2020-12-30T15:29:10.419695+00:00 straylight seaweedfs[53] goroutine 1619 [running]:
2020-12-30T15:29:10.419703+00:00 straylight seaweedfs[53] github.com/chrislusf/raft.newSnapshotRequest(...)
2020-12-30T15:29:10.419768+00:00 straylight seaweedfs[53] #011/tmp/usr/ports/net/seaweedfs/work/seaweedfs-2.16/vendor/github.com/chrislusf/raft/snapshot.go:219
2020-12-30T15:29:10.419796+00:00 straylight seaweedfs[53] github.com/chrislusf/raft.(*Peer).flush(0x40007a3900)
2020-12-30T15:29:10.419810+00:00 straylight seaweedfs[53] #011/tmp/usr/ports/net/seaweedfs/work/seaweedfs-2.16/vendor/github.com/chrislusf/raft/peer.go:184 +0x1a4
2020-12-30T15:29:10.419820+00:00 straylight seaweedfs[53] github.com/chrislusf/raft.(*Peer).heartbeat(0x40007a3900, 0x4000962d80)
2020-12-30T15:29:10.419831+00:00 straylight seaweedfs[53] #011/tmp/usr/ports/net/seaweedfs/work/seaweedfs-2.16/vendor/github.com/chrislusf/raft/peer.go:167 +0x180
2020-12-30T15:29:10.419841+00:00 straylight seaweedfs[53] github.com/chrislusf/raft.(*Peer).startHeartbeat.func1(0x40007a3900, 0x4000962d80)
2020-12-30T15:29:10.419863+00:00 straylight seaweedfs[53] #011/tmp/usr/ports/net/seaweedfs/work/seaweedfs-2.16/vendor/github.com/chrislusf/raft/peer.go:100 +0x58
2020-12-30T15:29:10.419874+00:00 straylight seaweedfs[53] created by github.com/chrislusf/raft.(*Peer).startHeartbeat
2020-12-30T15:29:10.419887+00:00 straylight seaweedfs[53] #011/tmp/usr/ports/net/seaweedfs/work/seaweedfs-2.16/vendor/github.com/chrislusf/raft/peer.go:98 +0x108
```
```

**Comment by chrislusf** [comment]
When the panic happened, how long the cluster has been running?

**Comment by dch** [comment]
probably under an hour, I guess? lots of testing still

**Comment by chrislusf** [comment]
Thanks! Upgraded the dependency.
