### ISSUE TITLE
weed mount panic err: "fuse: panic in handler for Read"

### ISSUE THREAD

**Issue by earthdiaosi** [chrislusf/seaweedfs#1750]
**Describe the bug**
Mount seaweedfs to two directories on the same host. When reading files from the second directory, the second `weed mount` panic
```
$ weed server -filer=true
$ weed mount -filer=localhost:8888 -dir=./t1 -filer.path=/
$ weed mount -filer=localhost:8888 -dir=./t2 -filer.path=/

$ echo "1" > ./t1/1.txt
$ cat ./t1/1.txt
1

$ cat ./t2/1.txt
cat: ./t2/1.txt: Input/output error
```

after `cat ./t2/1.txt`, the process of `weed mount -filer=localhost:8888 -dir=./t2 -filer.path=/` panic, and error log is: 
```
2021/01/22 12:02:11 fuse: panic in handler for Read [ID=0x4 Node=0x2 Uid=501 Gid=20 Pid=38596] 0x2 2 @0x0 dir=false fl=0 lock=0 ffl=OpenReadOnly: runtime error: index out of range [0] with length 0
goroutine 141 [running]:
github.com/seaweedfs/fuse/fs.(*Server).serve.func2(0x32411a0, 0xc0002f0480, 0xc0006c7e78, 0xc0006c7dee)
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v1.0.8/fs/serve.go:881 +0x1af
panic(0x2cd4660, 0xc0001269e0)
	/home/travis/.gimme/versions/go1.15.6.linux.amd64/src/runtime/panic.go:969 +0x1b9
github.com/chrislusf/seaweedfs/weed/util/chunk_cache.(*OnDiskCacheLayer).setChunk(0xc0006167a0, 0x1, 0xc000488a80, 0x2, 0x40)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/util/chunk_cache/on_disk_cache_layer.go:45 +0x38c
github.com/chrislusf/seaweedfs/weed/util/chunk_cache.(*TieredChunkCache).doSetChunk(0xc00070e5a0, 0xc0002a5c10, 0xc, 0xc000488a80, 0x2, 0x40)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/util/chunk_cache/chunk_cache.go:115 +0xbe
github.com/chrislusf/seaweedfs/weed/util/chunk_cache.(*TieredChunkCache).SetChunk(0xc00070e5a0, 0xc0002a5c10, 0xc, 0xc000488a80, 0x2, 0x40)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/util/chunk_cache/chunk_cache.go:99 +0x15c
github.com/chrislusf/seaweedfs/weed/filer.(*ChunkReadAt).readOneWholeChunk.func1(0x2ab1ea0, 0xc0007060c0, 0xc0002a5c10, 0xc)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filer/reader_at.go:213 +0x45d
github.com/golang/groupcache/singleflight.(*Group).Do(0xc000129e38, 0xc0002a5c10, 0xc, 0xc000845400, 0x10, 0x10, 0x29ceac0, 0x72656e6e692e662c)
	/home/travis/gopath/pkg/mod/github.com/golang/groupcache@v0.0.0-20190702054246-869f871628b6/singleflight/singleflight.go:56 +0x196
github.com/chrislusf/seaweedfs/weed/filer.(*ChunkReadAt).readOneWholeChunk(0xc000129e00, 0xc000111720, 0x28656772656d2e6e, 0x6c6968632e662c6c, 0x2c297365646f4e64, 0x737269662e6b3d66)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filer/reader_at.go:200 +0x85
github.com/chrislusf/seaweedfs/weed/filer.(*ChunkReadAt).readFromWholeChunkData(0xc000129e00, 0xc000111720, 0xc0006c75a0, 0x1, 0x1, 0x72416e692e6e3d3d, 0x29642c6528796172, 0x2e6e3d6928262629, 0x736e6961746e6f63, 0x72656e776f2e6528)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filer/reader_at.go:176 +0x58
github.com/chrislusf/seaweedfs/weed/filer.(*ChunkReadAt).doReadAt(0xc000129e00, 0xc0002a5c78, 0x2, 0x2, 0x0, 0xc0002a5c10, 0x4f806f0, 0x70)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filer/reader_at.go:142 +0x3ae
github.com/chrislusf/seaweedfs/weed/filer.(*ChunkReadAt).ReadAt(0xc000129e00, 0xc0002a5c78, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filer/reader_at.go:110 +0x1fc
github.com/chrislusf/seaweedfs/weed/filesys.(*FileHandle).readFromChunks(0xc000760600, 0xc0002a5c78, 0x2, 0x2, 0x0, 0x2ab1000, 0x0, 0x246520)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/filehandle.go:133 +0x330
github.com/chrislusf/seaweedfs/weed/filesys.(*FileHandle).Read(0xc000760600, 0x3251120, 0xc00015f540, 0xc0002f0480, 0xc00010fce0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/filehandle.go:74 +0x2da
github.com/seaweedfs/fuse/fs.(*Server).handleRequest(0xc0001c8d80, 0x3251120, 0xc00015f540, 0x32104a0, 0xc00085d5c0, 0xc00015f3c0, 0x32411a0, 0xc0002f0480, 0xc0006c7e78, 0x0, ...)
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v1.0.8/fs/serve.go:1275 +0xa75
github.com/seaweedfs/fuse/fs.(*Server).serve(0xc0001c8d80, 0x32411a0, 0xc0002f0480)
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v1.0.8/fs/serve.go:902 +0x2c7
github.com/seaweedfs/fuse/fs.(*Server).Serve.func1(0x31)
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v1.0.8/fs/serve.go:416 +0x79
github.com/seaweedfs/fuse/fs.(*Server).Serve.func2(0xc0001c8d80, 0xc000456270, 0x31)
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v1.0.8/fs/serve.go:423 +0x64
created by github.com/seaweedfs/fuse/fs.(*Server).Serve
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v1.0.8/fs/serve.go:421 +0x3b0
```

**System Setup**
- `weed server -filer=true`
- `weed mount -filer=localhost:8888 -dir=./t1 -filer.path=/`
- `weed mount -filer=localhost:8888 -dir=./t2 -filer.path=/`
- darwin amd64
- version 30GB `2.21` e439b65 darwin amd64
- version 30GB `2.11` 98827d6 darwin amd64

**Expected behavior**
```
$ cat ./t2/1.txt
1
```

**Screenshots**

**Additional context**

**Comment by chrislusf** [comment]
see https://github.com/chrislusf/seaweedfs/wiki/FUSE-Mount#multiple-mount-on-one-machine
