### ISSUE TITLE
[filer] Panic on startup with https.client.enabled

### ISSUE THREAD

**Issue by ustuzhanin** [chrislusf/seaweedfs#1757]
**Describe the bug**
```
I0123 11:27:53    51 config.go:28] Reading security.toml from
I0123 11:27:53    51 config.go:28] Reading filer.toml from
I0123 11:27:53    51 masterclient.go:49] filer masterClient bootstraps with masters [kube-throne-seaweed-fuse-master-direct.query.consul:9333]
I0123 11:27:53    51 masterclient.go:97] filer masterClient Connecting to master kube-throne-seaweed-fuse-master-direct.query.consul:9333
I0123 11:27:53    51 config.go:28] Reading notification.toml from
I0123 11:27:53    51 masterclient.go:114] filer masterClient Connected to kube-throne-seaweed-fuse-master-direct.query.consul:9333
I0123 11:27:53    51 config.go:35] Reading : Config File "notification" Not Found in "[/ /root/.seaweedfs /usr/local/etc/seaweedfs /etc/seaweedfs]"
I0123 11:27:53    51 filer.go:98] create filer.store.id to 158283383
I0123 11:27:53    51 configuration.go:28] configured filer for mysql
panic: reflect: call of reflect.Value.Elem on zero Value

goroutine 1 [running]:
reflect.Value.Elem(0x0, 0x0, 0x0, 0x5, 0x37f5fc0, 0x1)
        /usr/lib/go/src/reflect/value.go:837 +0x1c3
github.com/chrislusf/seaweedfs/weed/filer.(*Filer).LoadConfiguration(0xc000589ad0, 0xc00024a300)
        /go/src/github.com/chrislusf/seaweedfs/weed/filer/configuration.go:63 +0x474
github.com/chrislusf/seaweedfs/weed/server.NewFilerServer(0xc0003ed4c0, 0xc0003ed4c0, 0xc000164180, 0x1, 0x0, 0x0)
        /go/src/github.com/chrislusf/seaweedfs/weed/server/filer_server.go:121 +0x83b
github.com/chrislusf/seaweedfs/weed/command.(*FilerOptions).startFiler(0x37d4b00)
        /go/src/github.com/chrislusf/seaweedfs/weed/command/filer.go:140 +0x2ed
github.com/chrislusf/seaweedfs/weed/command.runFiler(0x372ef00, 0xc00003c1d0, 0x0, 0x0, 0x0)
        /go/src/github.com/chrislusf/seaweedfs/weed/command/filer.go:116 +0x82
main.main()
        /go/src/github.com/chrislusf/seaweedfs/weed/weed.go:66 +0x2f9
```

filler.toml:
```
[filer.options]
recursive_delete = false
# directories under this folder will be automatically creating a separate bucket
buckets_folder = "/buckets"
buckets_fsync = [          # a list of buckets with all write requests fsync=true
  "important_bucket",
  "should_always_fsync",
]
[leveldb2]
enabled = false

[mysql]  # or tidb
# CREATE TABLE IF NOT EXISTS filemeta (
#   dirhash     BIGINT         COMMENT 'first 64 bits of MD5 hash value of directory field',
#   name        VARCHAR(1000)  COMMENT 'directory or file name',
#   directory   TEXT           COMMENT 'full path to parent directory',
#   meta        LONGBLOB,
#   PRIMARY KEY (dirhash, name)
# ) DEFAULT CHARSET=utf8;

enabled = true
hostname = "mysql"
username = "seaweedfs"
password = "password"
port = 3306
database = "seaweedfs"     # create or use an existing database
connection_max_idle = 2
connection_max_open = 40
connection_max_lifetime_seconds = 600
interpolateParams = true
```

security.toml:
```
# this file is read by master, volume server, and filer

# the jwt signing key is read by master and volume server
# a jwt expires in 10 seconds
[jwt.signing]
# key = "aaaaasdasd"
expires_after_seconds = 10           # seconds

[jwt.signing.read]
key = ""
expires_after_seconds = 10           # seconds
# all grpc tls authentications are mutual
# the values for the following ca, cert, and key are paths to the PERM files.
[grpc]
ca = "/usr/local/share/ca-certificates/ca.crt"

[grpc.volume]
cert = "/usr/local/share/ca-certificates/tls.crt"
key  = "/usr/local/share/ca-certificates/tls.key"
ca = "/usr/local/share/ca-certificates/ca.crt"

[grpc.master]
cert = "/usr/local/share/ca-certificates/tls.crt"
key  = "/usr/local/share/ca-certificates/tls.key"
ca = "/usr/local/share/ca-certificates/ca.crt"

[grpc.filer]
cert = "/usr/local/share/ca-certificates/tls.crt"
key  = "/usr/local/share/ca-certificates/tls.key"
ca = "/usr/local/share/ca-certificates/ca.crt"

[grpc.msg_broker]
cert = "/usr/local/share/ca-certificates/tls.crt"
key  = "/usr/local/share/ca-certificates/tls.key"
ca = "/usr/local/share/ca-certificates/ca.crt"

# use this for any place needs a grpc client
# i.e., "weed backup|benchmark|filer.copy|filer.replicate|mount|s3|upload"
[grpc.client]
cert = "/usr/local/share/ca-certificates/tls.crt"
key  = "/usr/local/share/ca-certificates/tls.key"
ca = "/usr/local/share/ca-certificates/ca.crt"

# volume server https options
# Note: work in progress!
#     this does not work with other clients, e.g., "weed filer|mount" etc, yet.
[https.client]
enabled = false
[https.volume]
cert = ""
key  = ""
```

```
/ # weed version
version 30GB 2.16 6912bf94 linux amd64
```

after comment 
```
[https.client]
enabled = false
```
load config and start normal
not locally reproduce

I think the problem is in https://github.com/chrislusf/seaweedfs/blob/master/weed/filer/configuration.go#L50
if this cycle get first https.client.enabled - there will be panic

**Comment by chrislusf** [comment]
This should have been fixed already. Could you please try the latest
version?

**Comment by ustuzhanin** [comment]
thanks, in 2.21 do not reproduce
