### ISSUE TITLE
2.24 fuse panic when mounting

### ISSUE THREAD

**Issue by SvenDowideit** [chrislusf/seaweedfs#1799]
```
I0211 02:22:57     1 mount_std.go:210] mounted filer:8888/mnt/docker-volumes/new to /mnt/docker-volumes/new/_data
2021/02/11 02:22:57 fuse: panic in handler for Getxattr [ID=0x2 Node=0x1 Uid=0 Gid=0 Pid=0] "security.capability" 24 @0: runtime error: slice bounds out of range [23:19]
goroutine 28 [running]:
github.com/seaweedfs/fuse/fs.(*Server).serve.func2(0x266ca60, 0xc0001260f0, 0xc0005a7e78, 0xc0005a7dee)
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v1.1.1/fs/serve.go:937 +0x1af
panic(0x20fcb20, 0xc00012e620)
	/home/travis/.gimme/versions/go1.15.8.linux.amd64/src/runtime/panic.go:969 +0x1b9
github.com/chrislusf/seaweedfs/weed/util/bounded_tree.(*BoundedTree).EnsureVisited(0xc0004bf4a0, 0xc00012e560, 0x13, 0xc0005a79c0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/util/bounded_tree/bounded_tree.go:45 +0x230
github.com/chrislusf/seaweedfs/weed/filesys/meta_cache.EnsureVisited(0xc0007f3b40, 0x265b760, 0xc000149000, 0xc00012e560, 0x13, 0xc00012e574, 0x3)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/meta_cache/meta_cache_init.go:15 +0x9b
github.com/chrislusf/seaweedfs/weed/filesys.(*WFS).maybeLoadEntry(0xc000149000, 0xc00012e560, 0x13, 0xc00012e574, 0x3, 0x3, 0x1, 0xc000878570)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/xattr.go:117 +0x106
github.com/chrislusf/seaweedfs/weed/filesys.(*Dir).maybeLoadEntry(0xc00054a720, 0x17, 0xc000878570)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/dir.go:515 +0x9f
github.com/chrislusf/seaweedfs/weed/filesys.(*Dir).Getxattr(0xc00054a720, 0x267cda0, 0xc00081e040, 0xc0001260f0, 0xc0001162a0, 0x1, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/dir.go:77 +0x96
github.com/seaweedfs/fuse/fs.(*Server).handleRequest(0xc000328b40, 0x267cda0, 0xc00081e040, 0x263c120, 0xc00054a720, 0xc0002d01c0, 0x266ca60, 0xc0001260f0, 0xc0005a7e78, 0xc000560600, ...)
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v1.1.1/fs/serve.go:1207 +0x235b
github.com/seaweedfs/fuse/fs.(*Server).serve(0xc000328b40, 0x266ca60, 0xc0001260f0)
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v1.1.1/fs/serve.go:958 +0x2c7
github.com/seaweedfs/fuse/fs.(*Server).Serve.func1(0x0)
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v1.1.1/fs/serve.go:472 +0x79
github.com/seaweedfs/fuse/fs.(*Server).Serve.func2(0xc000328b40, 0xc0002919b0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v1.1.1/fs/serve.go:479 +0x64
created by github.com/seaweedfs/fuse/fs.(*Server).Serve
	/home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v1.1.1/fs/serve.go:477 +0x3b0

```

**System Setup**

https://github.com/onaci/docker-plugin-seaweedfs/blob/seaweedfs-2.24/seaweedfs.yml

(I'm working to remove the use of etcd, and instead want to have replicating filers on each node)

**Expected behavior**

no crash :) maybe an error, or maybe success

## extra context

the full log before the panic from the volume mount container looks like:

```
root@onaci-002:/var/lib/docker/plugins/seaweedfs/rootfs/mnt/docker-volumes/new# docker logs -f seaweed-volume-plugin-new
I0211 02:22:57     1 config.go:29] Reading security.toml from 
I0211 02:22:57     1 config.go:33] Reading : Config File "security" Not Found in "[/ /root/.seaweedfs /usr/local/etc/seaweedfs /etc/seaweedfs]"
This is SeaweedFS version 30GB 2.24 a833021 linux amd64
mount point owner uid=0 gid=0 mode=drwxr-xr-x
current uid=0 gid=0
I0211 02:22:57     1 volume_create_linux.go:19] Preallocated 65536000 bytes disk space for /tmp/afeef8bc/c0_2_0.dat
I0211 02:22:57     1 chunk_cache_on_disk.go:66] loading leveldb /tmp/afeef8bc/c0_2_0.ldb
I0211 02:22:57     1 needle_map_leveldb.go:30] Start to Generate /tmp/afeef8bc/c0_2_0.ldb from /tmp/afeef8bc/c0_2_0.idx
I0211 02:22:57     1 needle_map_leveldb.go:32] Finished Generating /tmp/afeef8bc/c0_2_0.ldb from /tmp/afeef8bc/c0_2_0.idx
I0211 02:22:57     1 needle_map_leveldb.go:34] Opening /tmp/afeef8bc/c0_2_0.ldb...
I0211 02:22:57     1 needle_map_leveldb.go:44] Loading /tmp/afeef8bc/c0_2_0.idx...
I0211 02:22:57     1 volume_create_linux.go:19] Preallocated 65536000 bytes disk space for /tmp/afeef8bc/c0_2_1.dat
I0211 02:22:57     1 chunk_cache_on_disk.go:66] loading leveldb /tmp/afeef8bc/c0_2_1.ldb
I0211 02:22:57     1 needle_map_leveldb.go:30] Start to Generate /tmp/afeef8bc/c0_2_1.ldb from /tmp/afeef8bc/c0_2_1.idx
I0211 02:22:57     1 needle_map_leveldb.go:32] Finished Generating /tmp/afeef8bc/c0_2_1.ldb from /tmp/afeef8bc/c0_2_1.idx
I0211 02:22:57     1 needle_map_leveldb.go:34] Opening /tmp/afeef8bc/c0_2_1.ldb...
I0211 02:22:57     1 needle_map_leveldb.go:44] Loading /tmp/afeef8bc/c0_2_1.idx...
I0211 02:22:57     1 volume_create_linux.go:19] Preallocated 131072000 bytes disk space for /tmp/afeef8bc/c1_3_0.dat
I0211 02:22:57     1 chunk_cache_on_disk.go:66] loading leveldb /tmp/afeef8bc/c1_3_0.ldb
I0211 02:22:57     1 needle_map_leveldb.go:30] Start to Generate /tmp/afeef8bc/c1_3_0.ldb from /tmp/afeef8bc/c1_3_0.idx
I0211 02:22:57     1 needle_map_leveldb.go:32] Finished Generating /tmp/afeef8bc/c1_3_0.ldb from /tmp/afeef8bc/c1_3_0.idx
I0211 02:22:57     1 needle_map_leveldb.go:34] Opening /tmp/afeef8bc/c1_3_0.ldb...
I0211 02:22:57     1 needle_map_leveldb.go:44] Loading /tmp/afeef8bc/c1_3_0.idx...
I0211 02:22:57     1 volume_create_linux.go:19] Preallocated 131072000 bytes disk space for /tmp/afeef8bc/c1_3_1.dat
I0211 02:22:57     1 chunk_cache_on_disk.go:66] loading leveldb /tmp/afeef8bc/c1_3_1.ldb
I0211 02:22:57     1 needle_map_leveldb.go:30] Start to Generate /tmp/afeef8bc/c1_3_1.ldb from /tmp/afeef8bc/c1_3_1.idx
I0211 02:22:57     1 needle_map_leveldb.go:32] Finished Generating /tmp/afeef8bc/c1_3_1.ldb from /tmp/afeef8bc/c1_3_1.idx
I0211 02:22:57     1 needle_map_leveldb.go:34] Opening /tmp/afeef8bc/c1_3_1.ldb...
I0211 02:22:57     1 needle_map_leveldb.go:44] Loading /tmp/afeef8bc/c1_3_1.idx...
I0211 02:22:57     1 volume_create_linux.go:19] Preallocated 131072000 bytes disk space for /tmp/afeef8bc/c1_3_2.dat
I0211 02:22:57     1 chunk_cache_on_disk.go:66] loading leveldb /tmp/afeef8bc/c1_3_2.ldb
I0211 02:22:57     1 needle_map_leveldb.go:30] Start to Generate /tmp/afeef8bc/c1_3_2.ldb from /tmp/afeef8bc/c1_3_2.idx
I0211 02:22:57     1 needle_map_leveldb.go:32] Finished Generating /tmp/afeef8bc/c1_3_2.ldb from /tmp/afeef8bc/c1_3_2.idx
I0211 02:22:57     1 needle_map_leveldb.go:34] Opening /tmp/afeef8bc/c1_3_2.ldb...
I0211 02:22:57     1 needle_map_leveldb.go:44] Loading /tmp/afeef8bc/c1_3_2.idx...
I0211 02:22:57     1 volume_create_linux.go:19] Preallocated 262144000 bytes disk space for /tmp/afeef8bc/c2_2_0.dat
I0211 02:22:57     1 chunk_cache_on_disk.go:66] loading leveldb /tmp/afeef8bc/c2_2_0.ldb
I0211 02:22:57     1 needle_map_leveldb.go:30] Start to Generate /tmp/afeef8bc/c2_2_0.ldb from /tmp/afeef8bc/c2_2_0.idx
I0211 02:22:57     1 needle_map_leveldb.go:32] Finished Generating /tmp/afeef8bc/c2_2_0.ldb from /tmp/afeef8bc/c2_2_0.idx
I0211 02:22:57     1 needle_map_leveldb.go:34] Opening /tmp/afeef8bc/c2_2_0.ldb...
I0211 02:22:57     1 needle_map_leveldb.go:44] Loading /tmp/afeef8bc/c2_2_0.idx...
I0211 02:22:57     1 volume_create_linux.go:19] Preallocated 262144000 bytes disk space for /tmp/afeef8bc/c2_2_1.dat
I0211 02:22:57     1 chunk_cache_on_disk.go:66] loading leveldb /tmp/afeef8bc/c2_2_1.ldb
I0211 02:22:57     1 needle_map_leveldb.go:30] Start to Generate /tmp/afeef8bc/c2_2_1.ldb from /tmp/afeef8bc/c2_2_1.idx
I0211 02:22:57     1 needle_map_leveldb.go:32] Finished Generating /tmp/afeef8bc/c2_2_1.ldb from /tmp/afeef8bc/c2_2_1.idx
I0211 02:22:57     1 needle_map_leveldb.go:34] Opening /tmp/afeef8bc/c2_2_1.ldb...
I0211 02:22:57     1 needle_map_leveldb.go:44] Loading /tmp/afeef8bc/c2_2_1.idx...
I0211 02:22:57     1 leveldb_store.go:40] filer store dir: /tmp/afeef8bc/meta
I0211 02:22:57     1 file_util.go:23] Folder /tmp/afeef8bc/meta Permission: -rwxr-xr-x
I0211 02:22:57     1 mount_std.go:210] mounted filer:8888/mnt/docker-volumes/new to /mnt/docker-volumes/new/_data
2021/02/11 02:22:57 fuse: panic in handler for Getxattr [ID=0x2 Node=0x1 Uid=0 Gid=0 Pid=0] "security.capability" 24 @0: runtime error: slice bounds out of range [23:19]
goroutine 28 [running]:
```

**Comment by SvenDowideit** [comment]
Note that this is very plausibly due to my not getting config right - I'm seeing some weird "its there, no, its not" things - I thought I'd raise the issues just in case its obvious to someone, and they can help me quickly

(is there a way to add filer peers after a filer has started?)

**Comment by chrislusf** [comment]
It seems when you mount, the `-filer.path` is configured. Added a fix to ensure the filer.path value is used correctly.

**Comment by SvenDowideit** [comment]
nice!, thanks :) hopefully will test later, though its just as possible that I'll fail to ever see this panic again
