### ISSUE TITLE
io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service filer_pb.SeaweedFiler

### ISSUE THREAD

**Issue by valsun2016** [chrislusf/seaweedfs#1800]
first，i do so 。。。

sudo ./weed master -mdir=/tmp/data -port=9333 -defaultReplication=001  &> /tmp/logs/master.log
sudo ./weed volume -dir=/tmp/data1 -max=3  -mserver="192.168.0.7:9333" -port=8888 &> /tmp/logs/vol1.log

it is ok，

then  ，i download the seaweedfs-hadoop3-client-1.6.1.jar ， i do so 。。。 

 > hdfs dfs -Dfs.defaultFS=seaweedfs://192.168.0.7:8888 -Dfs.seaweedfs.impl=seaweed.hdfs.SeaweedFileSystem -libjars ./seaweedfs-hadoop3-client-1.6.1.jar -ls
2021-02-11 11:48:57,359 WARN fs.FileSystem: Failed to initialize fileystem seaweedfs://192.168.0.7:8888: **io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service filer_pb.SeaweedFiler**
-ls: Fatal internal error
io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service filer_pb.SeaweedFiler
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:235)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:216)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        ...

why? help me，thank you

**Comment by chrislusf** [comment]
you need to start filer, which usually runs on port 8888.

you started a volume server at port 8888.
