### ISSUE TITLE
[master] panic: assertion failed: leader.elected.at.same.term.289

### ISSUE THREAD

**Issue by kmlebedev** [chrislusf/seaweedfs#1839]
**System Setup**
2.21(dc1), when updating to 2.26(dc2)

**Describe the bug**
```
I0225 09:57:42     1 masterclient.go:120] master masterClient failed to receive from fast-master-0.dc1: EOF
I0225 09:57:42     1 masterclient.go:126] redirected to leader fast-master-0.dc2:9333
I0225 09:57:46     1 master_server.go:141] leader change event: fast-master-0.dc2:9333 =>
I0225 09:57:46     1 master_server.go:141] leader change event:  => fast-master-0.dc1.9333
I0225 09:57:46     1 master_server.go:143] [ fast-master-0.dc1:9333 ] fast-master-0.dc1:9333 becomes leader.
panic: assertion failed: leader.elected.at.same.term.289


goroutine 151 [running]:
github.com/chrislusf/raft._assert(...)
	/root/go/pkg/mod/github.com/chrislusf/raft@v1.0.4/util.go:60
github.com/chrislusf/raft.(*server).processAppendEntriesRequest(0xc00079ac60, 0xc000aa5040, 0xc000aa5040, 0x0)
	/root/go/pkg/mod/github.com/chrislusf/raft@v1.0.4/server.go:983 +0xb37
github.com/chrislusf/raft.(*server).leaderLoop(0xc00079ac60)
	/root/go/pkg/mod/github.com/chrislusf/raft@v1.0.4/server.go:884 +0x441
github.com/chrislusf/raft.(*server).loop(0xc00079ac60)
	/root/go/pkg/mod/github.com/chrislusf/raft@v1.0.4/server.go:609 +0x1fd
github.com/chrislusf/raft.(*server).Start.func1(0xc00079ac60)
	/root/go/pkg/mod/github.com/chrislusf/raft@v1.0.4/server.go:470 +0x64
created by github.com/chrislusf/raft.(*server).Start
	/root/go/pkg/mod/github.com/chrislusf/raft@v1.0.4/server.go:468 +0x1a8
```

**Comment by lrvl** [comment]
Had this until adding localhost to the master peer list. For the minimum of 3 (odd) or 5(odd) reachable masters raft election:

`weed server -dir=/a/srv1 -ip master1 -master.peers=localhost:9333,master1:9333,master2:9333 -s3`

**Comment by kmlebedev** [comment]
This issue has not been reproduced again.
