### ISSUE TITLE
Bug - Weed Master node can't start when all master nodes are written: Only odd number of masters are supported!

### ISSUE THREAD

**Issue by kaaaq** [chrislusf/seaweedfs#1868]
Hi,
I run weed yesterday with new version binary file and I got error about running so I try to troubleshoot it and I found that when I enter all servers in front of "-peers" it will show error but when I remove the local server from the list and let other server exist it will work correctly, In previous version (I don't remember the exact version number) I hadn't problem.

./weed version
version 8000GB 2.29 f29ae0d linux amd64

./weed --help
  -peers string
    	all master nodes in comma separated ip:port list, example: 127.0.0.1:9093,127.0.0.1:9094,127.0.0.1:9095

The Error:

./weed master --peers 172.30.103.249:8080
I0306 18:25:04 22378 file_util.go:23] Folder /tmp Permission: -rwxrwxrwx
I0306 18:25:04 22378 master.go:168] current: 172.30.103.249:9333 peers:172.30.103.249:8080
F0306 18:25:04 22378 master.go:186] Only odd number of masters are supported!
goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0xc0007c2300, 0xc0007c8000, 0x4e, 0xa3)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0xb9
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x3652060, 0xc000000003, 0xc000195ab0, 0x2b7a41a, 0x9, 0xba, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:718 +0x37a
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x3652060, 0xc000000003, 0x22fbd27, 0x29, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:656 +0x153
github.com/chrislusf/seaweedfs/weed/glog.Fatalf(...)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:1149
github.com/chrislusf/seaweedfs/weed/command.checkPeers(0xc000183280, 0xe, 0x2475, 0x7ffc53225719, 0x13, 0x3651980, 0xc0007bfcd8, 0x76344a, 0x3652060, 0xc000195ab0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/master.go:186 +0x295
github.com/chrislusf/seaweedfs/weed/command.startMaster(0xc0001831e8, 0xc0005cd7c0, 0xc0005cd7e0, 0xc0005cd800, 0xc0005cd820, 0xc0001832a0, 0xc0001832b5, 0xc0005cd830, 0xc0001832c0, 0xc0005cd850, ...)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/master.go:117 +0x85
github.com/chrislusf/seaweedfs/weed/command.runMaster(0x36323a0, 0xc00004c0b0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/master.go:108 +0x1aa
main.main()
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/weed.go:66 +0x315

**Comment by chrislusf** [comment]
> ./weed master --peers 172.30.103.249:8080
> I0306 18:25:04 22378 file_util.go:23] Folder /tmp Permission: -rwxrwxrwx
> I0306 18:25:04 22378 master.go:168] current: 172.30.103.249:9333 peers:172.30.103.249:8080

This seems correct behavior since there are 2 masters `172.30.103.249:9333` and `172.30.103.249:8080`.

**Comment by kaaaq** [comment]
I found the problem:
In my configuration I didn't adjust "-ip " flag and just define "--peers" and by default weed will bind on ip so when it see its ip and name show error "Only odd number of masters are supported!" 
I add "-ip " and adjust the name of my node not ip, so now it is working correctly.

**Comment by kaaaq** [comment]
I'm binding weed on specific name that DNS refers it to ipv4 "ip=weed-master-002.example.local" but when I'm checking listen ip via "netstat -ntlp" and "ss -ntlp" it shows that binds on ipv6! : 
`
sudo ss -ntlp:
LISTEN      0      128                                                                      :::19333                                                                                :::*                   users:(("weed",pid=15431,fd=11))
LISTEN      0      128                                                                      :::9333                                                                                 :::*                   users:(("weed",pid=15431,fd=9))
`
`
sudo netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1235/sshd       
tcp6       0      0 :::19333                :::*                    LISTEN      15431/weed      
tcp6       0      0 :::9333                 :::*                    LISTEN      15431/weed      
`
Why weed is binding on ipv6 ?

**Comment by chrislusf** [comment]
there are no code to bind to ipv4 or ipv6. Maybe "weed-master-002.example.local" is ipv6.

**Comment by kaaaq** [comment]
But my Dns server returns the ipv4:
`
sudo nslookup weed-master-002.example.local 192.168.200.225
Server:		192.168.200.225
Address:	192.168.200.225#53

Name:	weed-master-002.example.local
Address: 192.168.200.44
`

**Comment by chrislusf** [comment]
ok. but no idea here.
