### ISSUE TITLE
Fuse mount panic runtime error

### ISSUE THREAD

**Issue by johncadengo** [chrislusf/seaweedfs#1882]
Ran the following command:

```
$ sudo ./weed mount -filer=localhost:8888 -dir=/seaweedfs -volumeServerAccess=filerProxy -filer.path=/
This is SeaweedFS version 30GB 2.31 f5b5e4d linux amd64
mount point owner uid=1000 gid=1000 mode=drwxr-xr-x
I0309 20:22:05 26954 leveldb_store.go:40] filer store dir: /tmp/47a8c899/meta
I0309 20:22:05 26954 file_util.go:23] Folder /tmp/47a8c899/meta Permission: -rwxr-xr-x
I0309 20:22:05 26954 mount_std.go:214] mounted localhost:8888/ to /seaweedfs
```

Got this error after removing a file:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1c25f2c]

goroutine 58038 [running]:
github.com/chrislusf/seaweedfs/weed/filesys.(*File).addChunks(0xc000cb5f80, 0xc00000e0e8, 0x1, 0x1)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/file.go:303 +0xac
github.com/chrislusf/seaweedfs/weed/filesys.(*ContinuousDirtyPages).saveToStorage.func1()
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/dirty_page.go:102 +0x2bd
github.com/chrislusf/seaweedfs/weed/util.(*LimitedConcurrentExecutor).Execute.func1(0xc0006ece50, 0x5c, 0xc00e5847e0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/util/limiter.go:38 +0x5d
created by github.com/chrislusf/seaweedfs/weed/util.(*LimitedConcurrentExecutor).Execute
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/util/limiter.go:33 +0x7b
```

**Comment by chrislusf** [comment]
Is it always reproducible?

**Comment by johncadengo** [comment]
@chrislusf thanks for fixing.

Here is how I was reproducing it. Have a terminal window open and run this, while in the mounted directory,

```
$ watch -n 1 ls -a .
```

And in another window erase a file,

```
$ rm filename
```

**Comment by chrislusf** [comment]
thanks! seems working fine with the latest code.
