### ISSUE TITLE
[mount][regression] FUSE mount panics with `filer.path` set to non-root in 2.33

### ISSUE THREAD

**Issue by PeterCxy** [chrislusf/seaweedfs#1911]
**Describe the bug**

After the resolution of #1906, `weed mount` starts fine with `filer.path`, but it results in a panic as soon as any I/O is attempted in the mounted directory (or probably in a subdirectory of the mounted directory)

```
Mar 16 08:45:59 storage weed[197]: 2021/03/16 08:45:59 fuse: panic in handler for Lookup [ID=0x3a Node=0x1 Uid=0 Gid=0 Pid=198] "<redacted_directory_name>": runtime error: slice bounds out of range [17:8]
Mar 16 08:45:59 storage weed[197]: goroutine 209 [running]:
Mar 16 08:45:59 storage weed[197]: github.com/seaweedfs/fuse/fs.(*Server).serve.func2(0x260cf80, 0xc000798460, 0xc000ea3e78, 0xc000ea3dde)
Mar 16 08:45:59 storage weed[197]:         /home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v1.1.3/fs/serve.go:940 +0x19e
Mar 16 08:45:59 storage weed[197]: panic(0x2084fc0, 0xc000314318)
Mar 16 08:45:59 storage weed[197]:         /home/travis/.gimme/versions/go1.16.2.linux.amd64/src/runtime/panic.go:965 +0x1b9
Mar 16 08:45:59 storage weed[197]: github.com/chrislusf/seaweedfs/weed/util/bounded_tree.(*BoundedTree).EnsureVisited(0xc0002efc80, 0xc0000f7511, 0x8, 0xc000ea3968, 0x0, 0x0)
Mar 16 08:45:59 storage weed[197]:         /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/util/bounded_tree/bounded_tree.go:45 +0x237
Mar 16 08:45:59 storage weed[197]: github.com/chrislusf/seaweedfs/weed/filesys/meta_cache.EnsureVisited(0xc0002feb80, 0x25ff010, 0xc00030aa90, 0xc0000f7511, 0x8, 0xc000318c57, 0x5)
Mar 16 08:45:59 storage weed[197]:         /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/meta_cache/meta_cache_init.go:15 +0x9b
Mar 16 08:45:59 storage weed[197]: github.com/chrislusf/seaweedfs/weed/filesys.(*Dir).Lookup(0xc0008da270, 0x261b058, 0xc000546740, 0xc000798460, 0xc00067a840, 0x1, 0x0, 0x0, 0x0)
Mar 16 08:45:59 storage weed[197]:         /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/dir.go:258 +0x3a6
Mar 16 08:45:59 storage weed[197]: github.com/seaweedfs/fuse/fs.(*Server).handleRequest(0xc0001d2c00, 0x261b058, 0xc000546740, 0x25dfee0, 0xc0008da270, 0xc000313bc0, 0x260cf80, 0xc000798460, 0xc000ea3e78, 0x0, ...)
Mar 16 08:45:59 storage weed[197]:         /home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v1.1.3/fs/serve.go:1135 +0x3a8e
Mar 16 08:45:59 storage weed[197]: github.com/seaweedfs/fuse/fs.(*Server).serve(0xc0001d2c00, 0x260cf80, 0xc000798460)
Mar 16 08:45:59 storage weed[197]:         /home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v1.1.3/fs/serve.go:961 +0x2d6
Mar 16 08:45:59 storage weed[197]: github.com/seaweedfs/fuse/fs.(*Server).Serve.func1(0x38)
Mar 16 08:45:59 storage weed[197]:         /home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v1.1.3/fs/serve.go:472 +0x79
Mar 16 08:45:59 storage weed[197]: github.com/seaweedfs/fuse/fs.(*Server).Serve.func2(0xc0001d2c00, 0xc0008da480, 0x38)
Mar 16 08:45:59 storage weed[197]:         /home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v1.1.3/fs/serve.go:479 +0x64
Mar 16 08:45:59 storage weed[197]: created by github.com/seaweedfs/fuse/fs.(*Server).Serve
Mar 16 08:45:59 storage weed[197]:         /home/travis/gopath/pkg/mod/github.com/seaweedfs/fuse@v1.1.3/fs/serve.go:477 +0x3bf
```

**System Setup**

My `weed mount` command looks something like the following

```
weed mount -filer=<filer_address> -chunkSizeLimitMB=24 -concurrentWriters=8 -filer.path=/some/path -collection=some-collection -dir=/mnt/mountpoint -allowOthers=true -cacheCapacityMB=100
```

**Expected behavior**

It should not crash

**Additional context**

This seems to be more complex than the original issue. I am using a bind mount over the FUSE mount for now as a workaround. I guess this `filer.path` logic probably needs some unit tests (?).

**Comment by chrislusf** [comment]
can not reproduce

**Comment by PeterCxy** [comment]
@chrislusf: here are the verbose logs

```
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 volume_create_linux.go:19] Preallocated 6553600 bytes disk space for /tmp/1d406728/c0_2_0.dat
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 chunk_cache_on_disk.go:66] loading leveldb /tmp/1d406728/c0_2_0.ldb
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 needle_map_leveldb.go:30] Start to Generate /tmp/1d406728/c0_2_0.ldb from /tmp/1d406728/c0_2_0.idx
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 needle_map_leveldb.go:32] Finished Generating /tmp/1d406728/c0_2_0.ldb from /tmp/1d406728/c0_2_0.idx
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 needle_map_leveldb.go:39] Opening /tmp/1d406728/c0_2_0.ldb...
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 needle_map_leveldb.go:49] Loading /tmp/1d406728/c0_2_0.idx...
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 volume_create_linux.go:19] Preallocated 6553600 bytes disk space for /tmp/1d406728/c0_2_1.dat
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 chunk_cache_on_disk.go:66] loading leveldb /tmp/1d406728/c0_2_1.ldb
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 needle_map_leveldb.go:30] Start to Generate /tmp/1d406728/c0_2_1.ldb from /tmp/1d406728/c0_2_1.idx
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 needle_map_leveldb.go:32] Finished Generating /tmp/1d406728/c0_2_1.ldb from /tmp/1d406728/c0_2_1.idx
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 needle_map_leveldb.go:39] Opening /tmp/1d406728/c0_2_1.ldb...
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 needle_map_leveldb.go:49] Loading /tmp/1d406728/c0_2_1.idx...
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 volume_create_linux.go:19] Preallocated 13107200 bytes disk space for /tmp/1d406728/c1_3_0.dat
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 chunk_cache_on_disk.go:66] loading leveldb /tmp/1d406728/c1_3_0.ldb
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 needle_map_leveldb.go:30] Start to Generate /tmp/1d406728/c1_3_0.ldb from /tmp/1d406728/c1_3_0.idx
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 needle_map_leveldb.go:32] Finished Generating /tmp/1d406728/c1_3_0.ldb from /tmp/1d406728/c1_3_0.idx
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 needle_map_leveldb.go:39] Opening /tmp/1d406728/c1_3_0.ldb...
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 needle_map_leveldb.go:49] Loading /tmp/1d406728/c1_3_0.idx...
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 volume_create_linux.go:19] Preallocated 13107200 bytes disk space for /tmp/1d406728/c1_3_1.dat
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 chunk_cache_on_disk.go:66] loading leveldb /tmp/1d406728/c1_3_1.ldb
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 needle_map_leveldb.go:30] Start to Generate /tmp/1d406728/c1_3_1.ldb from /tmp/1d406728/c1_3_1.idx
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 needle_map_leveldb.go:32] Finished Generating /tmp/1d406728/c1_3_1.ldb from /tmp/1d406728/c1_3_1.idx
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 needle_map_leveldb.go:39] Opening /tmp/1d406728/c1_3_1.ldb...
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 needle_map_leveldb.go:49] Loading /tmp/1d406728/c1_3_1.idx...
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 volume_create_linux.go:19] Preallocated 13107200 bytes disk space for /tmp/1d406728/c1_3_2.dat
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 chunk_cache_on_disk.go:66] loading leveldb /tmp/1d406728/c1_3_2.ldb
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 needle_map_leveldb.go:30] Start to Generate /tmp/1d406728/c1_3_2.ldb from /tmp/1d406728/c1_3_2.idx
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 needle_map_leveldb.go:32] Finished Generating /tmp/1d406728/c1_3_2.ldb from /tmp/1d406728/c1_3_2.idx
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 needle_map_leveldb.go:39] Opening /tmp/1d406728/c1_3_2.ldb...
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 needle_map_leveldb.go:49] Loading /tmp/1d406728/c1_3_2.idx...
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 volume_create_linux.go:19] Preallocated 26214400 bytes disk space for /tmp/1d406728/c2_2_0.dat
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 chunk_cache_on_disk.go:66] loading leveldb /tmp/1d406728/c2_2_0.ldb
Mar 16 09:17:03 storage weed[8755]: I0316 09:17:03  8755 needle_map_leveldb.go:30] Start to Generate /tmp/1d406728/c2_2_0.ldb from /tmp/1d406728/c2_2_0.idx
Mar 16 09:17:04 storage weed[8755]: I0316 09:17:04  8755 needle_map_leveldb.go:32] Finished Generating /tmp/1d406728/c2_2_0.ldb from /tmp/1d406728/c2_2_0.idx
Mar 16 09:17:04 storage weed[8755]: I0316 09:17:04  8755 needle_map_leveldb.go:39] Opening /tmp/1d406728/c2_2_0.ldb...
Mar 16 09:17:04 storage weed[8755]: I0316 09:17:04  8755 needle_map_leveldb.go:49] Loading /tmp/1d406728/c2_2_0.idx...
Mar 16 09:17:04 storage weed[8755]: I0316 09:17:04  8755 volume_create_linux.go:19] Preallocated 26214400 bytes disk space for /tmp/1d406728/c2_2_1.dat
Mar 16 09:17:04 storage weed[8755]: I0316 09:17:04  8755 chunk_cache_on_disk.go:66] loading leveldb /tmp/1d406728/c2_2_1.ldb
Mar 16 09:17:04 storage weed[8755]: I0316 09:17:04  8755 needle_map_leveldb.go:30] Start to Generate /tmp/1d406728/c2_2_1.ldb from /tmp/1d406728/c2_2_1.idx
Mar 16 09:17:04 storage weed[8755]: I0316 09:17:04  8755 needle_map_leveldb.go:32] Finished Generating /tmp/1d406728/c2_2_1.ldb from /tmp/1d406728/c2_2_1.idx
Mar 16 09:17:04 storage weed[8755]: I0316 09:17:04  8755 needle_map_leveldb.go:39] Opening /tmp/1d406728/c2_2_1.ldb...
Mar 16 09:17:04 storage weed[8755]: I0316 09:17:04  8755 needle_map_leveldb.go:49] Loading /tmp/1d406728/c2_2_1.idx...
Mar 16 09:17:04 storage weed[8755]: I0316 09:17:04  8755 leveldb_store.go:41] filer store dir: /tmp/1d406728/meta
Mar 16 09:17:04 storage weed[8755]: I0316 09:17:04  8755 file_util.go:23] Folder /tmp/1d406728/meta Permission: -rwxr-xr-x
Mar 16 09:17:04 storage weed[8755]: I0316 09:17:04  8755 mount_std.go:221] mounted <filer_address_redacted>/<path_redacted> to /mnt/<redacted>
Mar 16 09:17:13 storage weed[8755]: 2021/03/16 09:17:13 fuse: panic in handler for Read [ID=0x4 Node=0x1 Uid=1000 Gid=1000 Pid=8774] 0x1 4096 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock: runtime error: slice bounds out of range [17:8]
```

Following this is the same error stack trace posted in the original issue.

**Comment by PeterCxy** [comment]
https://github.com/chrislusf/seaweedfs/blob/master/weed/util/bounded_tree/bounded_tree.go#L45

Apparently `len(baseDir)` here exceeded the length of `p`, which is supposed to be the full path

**Comment by PeterCxy** [comment]
> slice bounds out of range [17:8]

For context, 17 is the length of my path prefix in `filer.path`, let's say `/some/path`, and `8` is the length of the `/path` part.

**Comment by PeterCxy** [comment]
Interestingly, when I set a higher verbose level, there's log like this

> dir Attr /path, attr: valid=1s ino=0 size=0 mode=drwxr-xr-x

Note that the `/some` part in my `/some/path` prefix seems to have been lost.

**Comment by PeterCxy** [comment]
Update: If I mount `/some` to `/mnt`, then try to `ls /some/path`, `weed` will fail with the same error as posted above. Seems like it has issues with second-level subdirectories when prefix is used.

**Comment by PeterCxy** [comment]
Switching back to 2.31 confirms that the correct behavior (log output) should be something like

> dir Attr /some/path, attr: valid=1s ino=0 size=0 ....

For some reason the first part of the path (`/some`) gets lost in the latest version. I think it is related to 7d57664.

**Comment by PeterCxy** [comment]
`dir.entry.FullPath` turned out to be `/some/path/path` instead of `/some/path/` when executing `ls /some/path/`. This seems like the cause of the issue.

**Comment by chrislusf** [comment]
reverted 7d57664

**Comment by PeterCxy** [comment]
Just reverting the `FullPath()` function seems to be enough. Currently testing if anything else breaks.

**Comment by PeterCxy** [comment]
@chrislusf I have found the problem: https://github.com/chrislusf/seaweedfs/blob/7d57664c2d80f2b7d3eb4cecc57a3275bafee44d/weed/filesys/wfs.go#L134

`filer.FromPbEntry` merges the `FilerMountRootPath` and `entry.Name`, which results in the extra `/path` at the end of the entry.

No need to revert the full commit.

**Comment by chrislusf** [comment]
ok. building 2.34 release. Will revisit this later.

**Comment by PeterCxy** [comment]
So basically:

1. The fix 22a07a is incorrect and not needed
2. In `wfs.go`, just strip `entry.Name` from the end of `FilerMountRootPath`

I tested locally without reverting the full commit 7d57664 and things seem to be working fine. Of course, my test case is very limited and I cannot say for sure there are no other broken cases.

**Comment by PeterCxy** [comment]
I know I've been raising quite some issues today. Sorry for all the noise, and thanks a lot for your quick response and your dedication to the project.
