### ISSUE TITLE
Master server crashed

### ISSUE THREAD

**Issue by thaines** [chrislusf/seaweedfs#1928]
As the title suggested one of the master servers crashed; have three and fall over happened as expected, which is good:-)

Here is the log of the crash:
```
Mar 21 21:49:49 jeannie weed[998710]: I0321 21:49:49 98710 topology_event_handling.go:65] Removing Volume 33 from the dead volume server 192.168.1.125:9380
Mar 21 21:49:49 jeannie weed[998710]: I0321 21:49:49 98710 topology_event_handling.go:65] Removing Volume 16 from the dead volume server 192.168.1.125:9380
Mar 21 21:49:49 jeannie weed[998710]: I0321 21:49:49 98710 topology_event_handling.go:65] Removing Volume 139 from the dead volume server 192.168.1.125:9380
Mar 21 21:49:49 jeannie weed[998710]: I0321 21:49:49 98710 master_grpc_server.go:29] unregister disconnected volume server 192.168.1.125:9380
Mar 21 21:49:49 jeannie weed[998710]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 21 21:49:49 jeannie weed[998710]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x18d67a6]
Mar 21 21:49:49 jeannie weed[998710]: goroutine 499953 [running]:
Mar 21 21:49:49 jeannie weed[998710]: github.com/chrislusf/seaweedfs/weed/topology.(*DataNode).GetDataCenter(0xc0016a6640, 0xc0016d2df0)
Mar 21 21:49:49 jeannie weed[998710]:         /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/topology/data_node.go:180 +0x26
Mar 21 21:49:49 jeannie weed[998710]: github.com/chrislusf/seaweedfs/weed/server.(*MasterServer).SendHeartbeat(0xc00051f200, 0x2629cd8, 0xc0010400e0, 0x0, 0x0)
Mar 21 21:49:49 jeannie weed[998710]:         /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/server/master_grpc_server.go:86 +0x12a5
Mar 21 21:49:49 jeannie weed[998710]: github.com/chrislusf/seaweedfs/weed/pb/master_pb._Seaweed_SendHeartbeat_Handler(0x21aa420, 0xc00051f200, 0x2622868, 0xc00013e300, 0x35168e0, 0xc0011fa000)
Mar 21 21:49:49 jeannie weed[998710]:         /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/pb/master_pb/master.pb.go:4341 +0xad
Mar 21 21:49:49 jeannie weed[998710]: google.golang.org/grpc.(*Server).processStreamingRPC(0xc000496000, 0x262c7b8, 0xc000b3c180, 0xc0011fa000, 0xc00034da10, 0x34c1980, 0x0, 0x0, 0x0)
Mar 21 21:49:49 jeannie weed[998710]:         /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1329 +0xcd8
Mar 21 21:49:49 jeannie weed[998710]: google.golang.org/grpc.(*Server).handleStream(0xc000496000, 0x262c7b8, 0xc000b3c180, 0xc0011fa000, 0x0)
Mar 21 21:49:49 jeannie weed[998710]:         /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1409 +0xc68
Mar 21 21:49:49 jeannie weed[998710]: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00070c1e0, 0xc000496000, 0x262c7b8, 0xc000b3c180, 0xc0011fa000)
Mar 21 21:49:49 jeannie weed[998710]:         /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xab
Mar 21 21:49:49 jeannie weed[998710]: created by google.golang.org/grpc.(*Server).serveStreams.func1
Mar 21 21:49:49 jeannie weed[998710]:         /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa5
Mar 21 21:49:49 jeannie systemd[1]: seaweed-master.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 21 21:49:49 jeannie systemd[1]: seaweed-master.service: Failed with result 'exit-code'.
```
there are many more of the removing volume events, i.e. all of the volumes on that server.

Setup is 6 nodes, with security fully setup, version 2.34

Three masters, started with:
```
weed -logdir=/var/log/seaweed/master master -mdir=/var/lib/seaweedfs -ip=192.168.1.119 -defaultReplication=001 -peers=192.168.1.119:9333,192.168.1.125:9333,192.168.1.117:9333
```
Six volume servers started with
```
weed -logdir=/var/log/seaweed/volume volume -port=9380 -dir=/mnt/seaweed001/data,/mnt/seaweed002/data,/mnt/seaweed003/data,/mnt/seaweed004/data -max=0,0,0,0 -ip=192.168.1.125 -mserver=192.168.1.119:9333,192.168.1.125:9333,192.168.1.117:9333 -dataCenter=1W251 -rack=Rack1
```
Then each node also has a filer and mount on it as well
```
weed -logdir=/var/log/seaweed/filer filer -ip=192.168.1.119 -port=8888 -master=192.168.1.119:9333,192.168.1.125:9333,192.168.1.117:9333 -disableHttp -peers=192.168.1.115:8888,192.168.1.117:8888,192.168.1.118:8888,192.168.1.119:8888,192.168.1.121:8888,192.168.1.123:8888,192.168.1.125:8888

weed -logdir=/var/log/seaweed/mount mount -memprofile=/var/log/seaweed/mount/memprofile -filer=192.168.1.119:8888 -dir=/mnt/seaweed
```

No other errors at the time of the crash, except the volumes all jumped to the replacement master. I am seeing a lot of java Web Token errors on the servers (well, maybe one per hour), but not at the same time so probably unrelated (if worrying, but currently backing up another server to this system and get the impression this might be "timeouts" caused by load), e.g. on a mount this looks like
```
Mar 21 22:33:11 bigchin weed[1475578]: W0321 22:33:11 75578 upload_content.go:103] uploading to http://192.168.1.119:9380/79,01c0514f2ebc5ec1: unmarshalled error http://192.168.1.119:9380/79,01c0514f2ebc5ec1: wrong jwt
Mar 21 22:33:11 bigchin weed[1475578]: W0321 22:33:11 75578 upload_content.go:103] uploading to http://192.168.1.119:9380/79,01c0514f2ebc5ec1: unmarshalled error http://192.168.1.119:9380/79,01c0514f2ebc5ec1: wrong jwt
Mar 21 22:33:12 bigchin weed[1475578]: W0321 22:33:12 75578 upload_content.go:103] uploading to http://192.168.1.119:9380/79,01c0514f2ebc5ec1: unmarshalled error http://192.168.1.119:9380/79,01c0514f2ebc5ec1: wrong jwt
Mar 21 22:33:12 bigchin weed[1475578]: I0321 22:33:12 75578 wfs_write.go:62] upload data .immutable_collections.cpython-38.pyc.CCv6vA to http://192.168.1.119:9380/79,01c0514f2ebc5ec1: unmarshalled error http://192.168.1.119:9380/79,01c0514f2ebc5ec1: wrong jwt
Mar 21 22:33:12 bigchin weed[1475578]: I0321 22:33:12 75578 dirty_page.go:99] /backup_garlick_home_2021-3/<username>/anaconda3/envs/monodepth/lib/python3.8/site-packages/torch/fx/__pycache__/.immutable_collections.cpython-38.pyc.CCv6vA saveToStorage [0,1372): upload data: unmarshalled error http://192.168.1.119:9380/79,01c0514f2ebc5ec1: wrong jwt
Mar 21 22:33:12 bigchin weed[1475578]: E0321 22:33:12 75578 filehandle.go:247] /backup_garlick_home_2021-3/<username>/anaconda3/envs/monodepth/lib/python3.8/site-packages/torch/fx/__pycache__/.immutable_collections.cpython-38.pyc.CCv6vA doFlush last err: upload data: unmarshalled error http://192.168.1.119:9380/79,01c0514f2ebc5ec1: wrong jwt
Mar 21 22:33:12 bigchin weed[1475578]: E0321 22:33:12 75578 filehandle.go:229] Flush doFlush .immutable_collections.cpython-38.pyc.CCv6vA: input/output error
```

Happy to grab more information, but I'm assuming you're probably not going to wade through the logs of 21 processes!

**Comment by chrislusf** [comment]
Thanks for all the details! This has been reported before but lacked enough details.
