### ISSUE TITLE
Periodic panic of weed master during raft.saveSnapshot(...) in raft/server.go:1299

### ISSUE THREAD

**Issue by Flowm** [chrislusf/seaweedfs#1974]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
After starting to use seaweedfs with its planned workload (~100 GET/PUT req/s on small files) we started observing periodic restarts of the single master instance. This happens approximately every 1-2 days on two independent, identical deployments (staging and prod). 

The logs reveal a SIGSEGV in `raft.saveSnapshot(...) in raft/server.go:1299`:
```
I0407 18:45:31     1 volume_layout.go:355] Volume 10850 becomes writable
I0407 18:45:31     1 volume_growth.go:229] Created Volume 10850 on topo:DefaultDataCenter:DefaultRack:172.22.0.6:8083
I0407 18:45:31     1 master_grpc_server.go:154] master send to filer@172.22.0.8:8888: url:"172.22.0.6:8083"  public_url:"172.22.0.6:8083"  new_vids:10850  data_center:"DefaultDataCenter"
I0407 18:45:31     1 master_grpc_server.go:154] master send to master@172.22.0.2:35384: url:"172.22.0.6:8083"  public_url:"172.22.0.6:8083"  new_vids:10850  data_center:"DefaultDataCenter"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x194791a]

goroutine 11680105 [running]:
github.com/chrislusf/raft.(*server).saveSnapshot(0xc000818a20, 0xc000c18280, 0xc0004f8f00)
        /root/go/pkg/mod/github.com/chrislusf/raft@v1.0.4/server.go:1299 +0x7a
github.com/chrislusf/raft.(*server).TakeSnapshot(0xc000818a20, 0xc00102ca80, 0xc000b5e200)
        /root/go/pkg/mod/github.com/chrislusf/raft@v1.0.4/server.go:1270 +0x4a5
github.com/chrislusf/raft.(*server).maybeTakeSnapshot.func1(0xc000818a20)
        /root/go/pkg/mod/github.com/chrislusf/raft@v1.0.4/server.go:1221 +0x5b
created by github.com/chrislusf/raft.(*server).maybeTakeSnapshot
        /root/go/pkg/mod/github.com/chrislusf/raft@v1.0.4/server.go:1219 +0x98
I0407 18:45:40     1 file_util.go:23] Folder /data Permission: -rwxr-xr-x
I0407 18:45:40     1 master.go:165] current: master:9333 peers:
I0407 18:45:40     1 master_server.go:107] Volume Size Limit is 1024 MB
I0407 18:45:40     1 master_server.go:192] adminScripts:
I0407 18:45:40     1 master.go:120] Start Seaweed Master 30GB 2.36 6b7aa963 at :9333
```

**System Setup**
- OS version (Host running docker)
```
Linux hydra-tiles-staging 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
```
- Running with the following `docker-compose.yml` config:
```
version: '3.5'

services:
  master:
    image: chrislusf/seaweedfs:${SEAWEEDFS_VERSION:-2.36}
    restart: unless-stopped
    networks:
      - intern
    volumes:
      - sw_master:/data
    command: "master -ip=master"

  volume1:
    image: chrislusf/seaweedfs:${SEAWEEDFS_VERSION:-2.36}
    restart: unless-stopped
    networks:
      - intern
    volumes:
      - sw_vol1:/data
    command: 'volume -mserver="master:9333" -port=8081 -metricsPort=9325 --disk hdd'
    depends_on:
      - master

  volume2:
    image: chrislusf/seaweedfs:${SEAWEEDFS_VERSION:-2.36}
    restart: unless-stopped
    networks:
      - intern
    volumes:
      - sw_vol2:/data
    command: 'volume -mserver="master:9333" -port=8082 -metricsPort=9325 --disk hdd'
    depends_on:
      - master

  volume3:
    image: chrislusf/seaweedfs:${SEAWEEDFS_VERSION:-2.36}
    restart: unless-stopped
    networks:
      - intern
    volumes:
      - sw_vol3:/data
    command: 'volume -mserver="master:9333" -port=8083 -metricsPort=9325 --disk hdd'
    depends_on:
      - master

  filer:
    image: chrislusf/seaweedfs:${SEAWEEDFS_VERSION:-2.36}
    restart: unless-stopped
    networks:
      - intern
    ports:
      - 127.0.0.1:8333:8333
    volumes:
      - sw_filer:/data
      - ./config/seaweedfs/filer.toml:/etc/seaweedfs/filer.toml
      - ./config/seaweedfs/s3.json:/etc/seaweedfs/s3.json
    command: 'filer -master="master:9333" -metricsPort=9326 -s3 -s3.config=/etc/seaweedfs/s3.json'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume1
      - volume2
      - volume3

volumes:
  sw_master:
  sw_filer:
  sw_vol1:
  sw_vol2:
  sw_vol3:

networks:
  public:
  intern:
```
- output of `weed version`
Originally observed on `2.32`, but still occurs in `2.36`:
```
version 30GB 2.36 6b7aa963 linux amd64
```
- if using filer, show the content of `filer.toml`
```
[leveldb3]
enabled = true
dir = "/data/filerldb3"
```

**Expected behavior**
`weed master` running stable without SIGSEGV.

**Additional context**
Sorry for not providing a more concise setup/ reproduction, but the infrequent nature makes it hard to simplify.

Only slightly related issue I could find (which seems to be solved some month ago): https://github.com/chrislusf/seaweedfs/issues/1718

Thanks for this amazing project, happy to try out things and test with changes to the config or code if it helps.

**Comment by chrislusf** [comment]
Added fix to avoid this particular nil case. You may need to wait for the next release this week.

**Comment by Flowm** [comment]
Thanks for the incredibly fast response! Looking forward to upgrade to the next release once it comes out.
