### ISSUE TITLE
Weird behavior working with large files

### ISSUE THREAD

**Issue by Lupus** [chrislusf/seaweedfs#205]
We've tried it today and got some weird errors. Here's what we tried:

```
$ weed master -mdir .
I1008 21:32:24 17635 file_util.go:20] Folder . Permission: -rwxr-xr-x
I1008 21:32:24 17635 topology.go:86] Using default configurations.
I1008 21:32:24 17635 master_server.go:59] Volume Size Limit is 30000 MB
I1008 21:32:24 17635 master.go:69] Start Seaweed Master 0.70 beta at 0.0.0.0:9333
I1008 21:32:24 17635 raft_server.go:90] Initializing new cluster
I1008 21:32:24 17635 master_server.go:93] [ localhost:9333 ] I am the leader!
```

```
$ weed volume -dir="./data1" -max=5  -mserver="localhost:9333" -port=8080
I1008 21:33:04 17866 file_util.go:20] Folder ./data1 Permission: -rwxr-xr-x
I1008 21:33:04 17866 store.go:227] Store started on dir: ./data1 with 0 volumes max 5
I1008 21:33:04 17866 volume.go:138] Start Seaweed volume server 0.70 beta at 0.0.0.0:8080
I1008 21:33:04 17866 volume_server.go:73] Volume server bootstraps with master localhost:9333
```

```
$ weed volume -dir="./data2" -max=5  -mserver="localhost:9333" -port=8081
I1008 21:33:19 17951 file_util.go:20] Folder ./data2 Permission: -rwxr-xr-x
I1008 21:33:19 17951 store.go:227] Store started on dir: ./data2 with 0 volumes max 5
I1008 21:33:19 17951 volume.go:138] Start Seaweed volume server 0.70 beta at 0.0.0.0:8081
I1008 21:33:19 17951 volume_server.go:73] Volume server bootstraps with master localhost:9333
```

Master acknowledged new nodes:

```
I1008 21:33:04 17635 node.go:208] topo adds child DefaultDataCenter
I1008 21:33:04 17635 node.go:208] topo:DefaultDataCenter adds child DefaultRack
I1008 21:33:04 17635 node.go:208] topo:DefaultDataCenter:DefaultRack adds child 127.0.0.1:8080
I1008 21:33:19 17635 node.go:208] topo:DefaultDataCenter:DefaultRack adds child 127.0.0.1:8081
```

We've created a new file:

```
$ curl -X POST http://localhost:9333/dir/assign
{"fid":"4,0195e44e0e","url":"127.0.0.1:8081","publicUrl":"127.0.0.1:8081","count":1}
```

Logs for master and volume nodes correspondingly:

```
I1008 21:34:52 17635 volume_growth.go:204] Created Volume 1 on topo:DefaultDataCenter:DefaultRack:127.0.0.1:8080
I1008 21:34:52 17635 volume_growth.go:204] Created Volume 2 on topo:DefaultDataCenter:DefaultRack:127.0.0.1:8080
I1008 21:34:52 17635 volume_growth.go:204] Created Volume 3 on topo:DefaultDataCenter:DefaultRack:127.0.0.1:8081
I1008 21:34:52 17635 volume_growth.go:204] Created Volume 4 on topo:DefaultDataCenter:DefaultRack:127.0.0.1:8081
I1008 21:34:52 17635 volume_growth.go:204] Created Volume 5 on topo:DefaultDataCenter:DefaultRack:127.0.0.1:8080
I1008 21:34:52 17635 volume_growth.go:204] Created Volume 6 on topo:DefaultDataCenter:DefaultRack:127.0.0.1:8080
I1008 21:34:52 17635 volume_growth.go:204] Created Volume 7 on topo:DefaultDataCenter:DefaultRack:127.0.0.1:8081
```

```
I1008 21:34:52 17866 volume.go:110] loading index file data1/1.idx readonly false
I1008 21:34:52 17866 store.go:192] In dir ./data1 adds volume:2 collection: replicaPlacement:000 ttl:
I1008 21:34:52 17866 volume.go:110] loading index file data1/2.idx readonly false
I1008 21:34:52 17866 store.go:192] In dir ./data1 adds volume:5 collection: replicaPlacement:000 ttl:
I1008 21:34:52 17866 volume.go:110] loading index file data1/5.idx readonly false
I1008 21:34:52 17866 store.go:192] In dir ./data1 adds volume:6 collection: replicaPlacement:000 ttl:
I1008 21:34:52 17866 volume.go:110] loading index file data1/6.idx readonly false
```

```
I1008 21:34:52 17951 store.go:192] In dir ./data2 adds volume:3 collection: replicaPlacement:000 ttl:
I1008 21:34:52 17951 volume.go:110] loading index file data2/3.idx readonly false
I1008 21:34:52 17951 store.go:192] In dir ./data2 adds volume:4 collection: replicaPlacement:000 ttl:
I1008 21:34:52 17951 volume.go:110] loading index file data2/4.idx readonly false
I1008 21:34:52 17951 store.go:192] In dir ./data2 adds volume:7 collection: replicaPlacement:000 ttl:
I1008 21:34:52 17951 volume.go:110] loading index file data2/7.idx readonly false
```

Here's our file:

```
$ du -hs big_test_file.bin
4.6G    big_test_file.bin
```

So we've uploaded it:

 ```
$ curl -X PUT -F file=@big_test_file.bin http://127.0.0.1:8081/4,0195e44e0e
{"name":"big_test_file.bin","size":574619648}
```

And tried to download it:

```
$ curl http://localhost:9333/dir/lookup?volumeId=4
{"volumeId":"4","locations":[{"url":"127.0.0.1:8081","publicUrl":"127.0.0.1:8081"}]}

$ curl -v http://localhost:8081/4,0195e44e0e -o /dev/null
* About to connect() to localhost port 8081 (#0)
*   Trying 127.0.0.1... connected
* Connected to localhost (127.0.0.1) port 8081 (#0)
> GET /4,0195e44e0e HTTP/1.1
> User-Agent: curl/7.21.0 (x86_64-pc-linux-gnu) libcurl/7.21.0 OpenSSL/0.9.8o zlib/1.2.3.4 libidn/1.15 libssh2/1.2.6
> Host: localhost:8081
> Accept: */*
>
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
* Closing connection #0
```

And the following appeared in the logs of volume node 2:

```
2015/10/08 21:40:49 http: panic serving 127.0.0.1:38753: runtime error: slice bounds out of range
goroutine 82 [running]:
net/http.(*conn).serve.func1(0xc82013a000, 0x7fabbf5bf3d8, 0xc82054eaa0)
        /usr/lib/go/src/net/http/server.go:1287 +0xb5
github.com/chrislusf/seaweedfs/go/storage.(*Needle).readNeedleDataVersion2(0xc8201880a0, 0xc8282ea010, 0x2240001d, 0x22400028)
        /home/kolkhovskiy/gocode/src/github.com/chrislusf/seaweedfs/go/storage/needle_read_write.go:197 +0x49d
github.com/chrislusf/seaweedfs/go/storage.(*Needle).ReadData(0xc8201880a0, 0xc8200bc0e8, 0x8, 0x22240001d, 0x0, 0x0)
        /home/kolkhovskiy/gocode/src/github.com/chrislusf/seaweedfs/go/storage/needle_read_write.go:158 +0x576
github.com/chrislusf/seaweedfs/go/storage.(*Volume).readNeedle(0xc820178880, 0xc8201880a0, 0xc820178880, 0x0, 0x0)
        /home/kolkhovskiy/gocode/src/github.com/chrislusf/seaweedfs/go/storage/volume.go:289 +0xeb
github.com/chrislusf/seaweedfs/go/storage.(*Store).ReadVolumeNeedle(0xc8200c8780, 0xc800000004, 0xc8201880a0, 0x4, 0x0, 0x0)
        /home/kolkhovskiy/gocode/src/github.com/chrislusf/seaweedfs/go/storage/store.go:378 +0x67
github.com/chrislusf/seaweedfs/go/weed/weed_server.(*VolumeServer).GetOrHeadHandler(0xc82001c310, 0x7fabc2bf40d8, 0xc820c88000, 0xc820c76460)
        /home/kolkhovskiy/gocode/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/volume_server_handlers_read.go:55 +0x150f
github.com/chrislusf/seaweedfs/go/weed/weed_server.(*VolumeServer).privateStoreHandler(0xc82001c310, 0x7fabc2bf40d8, 0xc820c88000, 0xc820c76460)
        /home/kolkhovskiy/gocode/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/volume_server_handlers.go:28 +0xf6
github.com/chrislusf/seaweedfs/go/weed/weed_server.(*VolumeServer).(github.com/chrislusf/seaweedfs/go/weed/weed_server.privateStoreHandler)-fm(0x7fabc2bf40d8, 0xc820c88000, 0xc820c76460)
        /home/kolkhovskiy/gocode/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/volume_server.go:64 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc820191560, 0x7fabc2bf40d8, 0xc820c88000, 0xc820c76460)
        /usr/lib/go/src/net/http/server.go:1422 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820192270, 0x7fabc2bf40d8, 0xc820c88000, 0xc820c76460)
        /usr/lib/go/src/net/http/server.go:1699 +0x17d
net/http.serverHandler.ServeHTTP(0xc82000a900, 0x7fabc2bf40d8, 0xc820c88000, 0xc820c76460)
        /usr/lib/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc82013a000)
        /usr/lib/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:1910 +0x3f6
```

It did not die completely, but it did not work. We tried with weed upload:

```
$ weed upload big_test_file.bin
[{"fileName":"big_test_file.bin","fileUrl":"127.0.0.1:8081/7,0217f4976d","fid":"7,0217f4976d","size":574619648}]
```

And download attempt:

```
$ weed download 7,0217f4976d
Fetch Error: Get http://127.0.0.1:8081/7,0217f4976d: EOF
```

Same "slice bounds out of range" error in the logs.

During another set of tests with the same big file we got the following error when uploading with weed upload and downloading with weed download:

```
I1008 19:29:10 30263 volume_server_handlers_read.go:58] read error: CRC error! Data On Disk Corrupted /3,01f6a70061
```

When we tried chunked upload/download with weed command line, it worked fine.

Is that the expected behavior? Are we hitting some size limits?

Our repository is at 2dcdd121ec3586937d42ae1ecb910d6a57972909. No configuration changes were made, just default build and run.

**Comment by chrislusf** [comment]
Thanks for the detailed information.

I think you are hitting weird behavior when memory usage is high. To upload a file, the volume server will read everything in memory, and then saved to disk. It must be failing for 4.6GB. I can not tell where it is failing though. It could be golang itself, os file buffer, etc.

The only way is to use the chunked uploading. Just don't fight with the memory.

**Comment by chrislusf** [comment]
Is your OS 32bit or 64bit?

**Comment by Lupus** [comment]
Some of the environment information:

```
$ uname -a
Linux 3.2.0-0.bpo.4-amd64 #1 SMP Debian 3.2.68-1+deb7u1~bpo60+1 x86_64 GNU/Linux
```

```
$ dpkg -l | grep golang
ii  golang                                      2:1.5.1-1~exp1                               Go programming language compiler - metapackage
```

```
$ free -g
             total       used       free     shared    buffers     cached
Mem:            63         32         30          0          0         21
-/+ buffers/cache:         11         51
Swap:            1          0          1
```

So neither server, nor OS should have any problems with this.

I've tried to run the following go code:

```
$ cat alloc.go
package main

import (
        "bufio"
        "fmt"
        "os"
)

func main() {
        var s []byte
        s = make([]byte, 10000000000, 10000000000)
        for i := 0; i < len(s); i++ {
                s[i] = 'A'
        }
        fmt.Printf("slice len: %d", len(s))
        bio := bufio.NewReader(os.Stdin)
        _, _, _ = bio.ReadLine()
}
```

Here's top output:

```
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
21343 kolkhovs  20   0 9849m 9.6g  688 S    0 15.3   0:09.55 alloc
```

So it occupied 10 GB of memory without any issues.

You say that it was not capable of uploading large file, but if we read my report once again, we would see that it fails during the download of successfully uploaded large file. It's a data loss case actually: uploading was acknowledged to the client, but client was never able to get the data back.

**Comment by chrislusf** [comment]
Now I think maybe there are some variables used is 32bit int instead of 64bit int during uploading.

**Comment by chrislusf** [comment]
The large file, 4.6GB, is not supported. If needed, please use the "weed upload" command that can support chunking.

I think the 4GB or 2GB(maybe some int32 is used somewhere) should be the max limit for direct file uploading to volume server.
