### ISSUE TITLE
Segfaul on master after triggering volume.fix.replication.

### ISSUE THREAD

**Issue by AlexMikhalev** [chrislusf/seaweedfs#2059]
My master keeps crashing with 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x166a084]

goroutine 87 [running]:
github.com/chrislusf/seaweedfs/weed/topology.(*Topology).SetVolumeCapacityFull(0x40003700f0, 0x4021a24750, 0x0)
	/home/alex/go/src/github.com/chrislusf/seaweedfs/weed/topology/topology_event_handling.go:52 +0x124
github.com/chrislusf/seaweedfs/weed/topology.(*Topology).StartRefreshWritableVolumes.func3(0x40003700f0)
	/home/alex/go/src/github.com/chrislusf/seaweedfs/weed/topology/topology_event_handling.go:35 +0xc8
created by github.com/chrislusf/seaweedfs/weed/topology.(*Topology).StartRefreshWritableVolumes
	/home/alex/go/src/github.com/chrislusf/seaweedfs/weed/topology/topology_event_handling.go:31 +0xa4

```
Started after I run code from [wiki](https://github.com/chrislusf/seaweedfs/wiki/Volume-Management) to manage volumes

the master node starts with 
```
~/go/bin/weed server -filer -s3 -ip=rpi4node3 -volume.max=0,0 -master.volumeSizeLimitMB=1024 -volume.port=8088 -dir=/mnt/usbslow/weed,/mnt/usbfast/weed/ -master.dir=/mnt/usbfast/weed/master
```

Volume nodes start with 
```
~/go/bin/weed volume -mserver="rpi4node3:9333" -max=0,0  -port=8088 -disk=hdd,ssd -dir=/mnt/usbslow/weed,/mnt/usbfast/weed/
```
Filer.toml
```
filer.toml
[leveldb3]
# similar to leveldb2.
# each bucket has its own meta store.
enabled = true
dir = "/mnt/usbfast/weed/master/filerldb3"					# directory to store level db files
```
Master.toml

```
cat master.toml

# Put this file to one of the location, with descending priority
#    ./master.toml
#    $HOME/.seaweedfs/master.toml
#    /etc/seaweedfs/master.toml
# this file is read by master

[master.maintenance]
# periodically run these scripts are the same as running them from 'weed shell'
scripts = """
  lock
  ec.encode -fullPercent=95 -quietFor=1h
  ec.rebuild -force
  ec.balance -force
  volume.balance -force
  volume.fix.replication
  unlock
"""
sleep_minutes = 360          # sleep minutes between each script execution

[master.filer]
default = "localhost:8888"    # used by maintenance scripts if the scripts needs to use fs related commands


[master.sequencer]
type = "raft"     # Choose [raft|etcd] type for storing the file id sequence
# when sequencer.type = etcd, set listen client urls of etcd cluster that store file id sequence
# example : http://127.0.0.1:2379,http://127.0.0.1:2389
sequencer_etcd_urls = "http://127.0.0.1:2379"


# configurations for tiered cloud storage
# old volumes are transparently moved to cloud for cost efficiency
#[storage.backend]
#	[storage.backend.s3.default]
#	enabled = false
#	aws_access_key_id     = ""     # if empty, loads from the shared credentials file (~/.aws/credentials).
#	aws_secret_access_key = ""     # if empty, loads from the shared credentials file (~/.aws/credentials).
#	region = "us-east-2"
#	bucket = "your_bucket_name"    # an existing bucket
#	endpoint = ""

# create this number of logical volumes if no more writable volumes
# count_x means how many copies of data.
# e.g.:
#   000 has only one copy, copy_1
#   010 and 001 has two copies, copy_2
#   011 has only 3 copies, copy_3
[master.volume_growth]
copy_1 = 7                # create 1 x 7 = 7 actual volumes
copy_2 = 6                # create 2 x 6 = 12 actual volumes
copy_3 = 3                # create 3 x 3 = 9 actual volumes
copy_other = 1            # create n x 1 = n actual volumes

# configuration flags for replication
[master.replication]
# any replication counts should be considered minimums. If you specify 010 and
# have 3 different racks, that's still considered writable. Writes will still
# try to replicate to all available volumes. You should only use this option
# if you are doing your own replication or periodic sync of volumes.
treat_replication_as_minimums = false

```

**System Setup**
Gentoo: uname -a
Linux rpi4node3 5.4.45-v8-3b41649ff96d-p4-bis+ #2 SMP PREEMPT Tue Jun 16 14:11:43 GMT 2020 aarch64 GNU/Linux

~/go/bin/weed version
version 30GB 2.43 8f873886 linux arm64

**Expected behavior**
Don't crash

```
weed shell -master="rpi4node3:9333" -filer="rpi4node3:8888"
master: rpi4node3:9333 filer: rpi4node3:8888
> fs.configure
{
  "locations": [
    {
      "locationPrefix": "/buckets/",
      "volumeGrowthCount": 1
    },
    {
      "locationPrefix": "/buckets/slowvolume",
      "volumeGrowthCount": 1
    }
  ]
}
```

**Comment by chrislusf** [comment]
could not tell what's wrong. can you try to remove the trailing "/" first? 
```
change from
-dir=/mnt/usbslow/weed,/mnt/usbfast/weed/

to
-dir=/mnt/usbslow/weed,/mnt/usbfast/weed

```

**Comment by chrislusf** [comment]
Added a possible fix. Let me know if it works or not.
