### ISSUE TITLE
Running `npm install` in a nodejs project may result in lost data or "Unknown system error -116"

### ISSUE THREAD

**Issue by treo** [chrislusf/seaweedfs#2169]
### Describe the bug
When running `npm install` in a NodeJS project that is on a SeaweedFS Fuse mount, unexpected behavior happens.

Either it fails with something like the following. One thing to note is that it fails on a different modules.
```
npm ERR! code Unknown system error -116
npm ERR! syscall rename
npm ERR! path /mnt/seaweedfs/tmp/my-app/node_modules/@types/.uglify-js.DELETE/node_modules/source-map
npm ERR! dest /mnt/seaweedfs/tmp/my-app/node_modules/@types/uglify-js/node_modules/source-map
npm ERR! errno -116
npm ERR! Unknown system error -116: Unknown system error -116, rename '/mnt/seaweedfs/tmp/my-app/node_modules/@types/.uglify-js.DELETE/node_modules/source-map' -> '/mnt/seaweedfs/tmp/my-app/node_modules/@types/uglify-js/node_modules/source-map'
```

Or it results in **the entire contents of the folder that it was working in being deleted.  In one case, it even lost the entire parent folder.**

### Reproduction Instructions
The following will download NodeJS, and try to create a react application, during that process it runs `npm install`
```
cd /mnt/seaweedfs
mkdir tmp
cd tmp
wget  https://nodejs.org/dist/v14.17.1/node-v14.17.1-linux-x64.tar.xz
tar xf  node-v14.17.1-linux-x64.tar.xz
export PATH=$PATH:`pwd`/node-v14.17.1-linux-x64/bin
npx create-react-app my-app
```

Alternative reproduction (with nodejs still being on the PATH):
```
cd /tmp
npx create-react-app my-app2
rm -rf my-app/node_modules
mv my-app2 /mnt/seaweedfs/tmp/
cd /mnt/seaweedfs/tmp/my-app2
npm install
```

### System Setup
3 machines with single master and 3 volume servers. 

`version 30GB 2.56 a2979aa linux amd64`

Master:
- `/srv/seaweedfs/weed master -mdir="/srv/seaweedfs/metadata"`
- `/srv/seaweedfs/weed volume -max=30 -mserver=localhost:9333 -dir=/srv/seaweedfs/volumes`
- `/srv/seaweedfs/weed filer -s3 -s3.config=/srv/seaweedfs/s3.config.json -master=localhost:9333`
- `/srv/seaweedfs/weed mount -umask=000 -dir=/mnt/seaweedfs -collection=storage -filer=localhost:8888`
- filer.toml: 
```
[leveldb2]
enabled = true
dir = "/srv/seaweedfs/filer"
```

Volume Servers:
- `/srv/seaweedfs/weed volume -max=30 -mserver=10.10.10.22:9333 -dir=/srv/seaweedfs/volumes`
- `/srv/seaweedfs/weed mount -umask=000 -dir=/mnt/seaweedfs -collection=storage -filer=10.10.10.22:8888`

### Expected behavior
`npm install` should finish without any errors and the folder contents should stay where they are in any case.

### Additional Context
The following lines appear in the error log on the master. This was collected during the reproduction run when the entire /mnt/seaweedfs/tmp folder was lost.
```
E0630 11:59:59 48653 dir.go:583] UpdateEntry dir /tmp/my-app2/node_modules/.staging/acorn-globals-146eb470: rpc error: code = Unknown desc = not found /tmp/my-app2/node_modules/.staging/acorn-globals-146eb470: filer: no entry is found in filer store
E0630 12:00:05 48653 dir.go:583] UpdateEntry dir /tmp/my-app2/node_modules/.staging/@types/webpack-sources-6888de33/lib: rpc error: code = Unknown desc = not found /tmp/my-app2/node_modules/.staging/@types/webpack-sources-6888de33/lib: filer: no entry is found in filer store
E0630 12:00:05 48653 meta_cache_subscribe.go:95] subscribing filer meta change: rpc error: code = Canceled desc = grpc: the client connection is closing
E0630 12:00:32 48653 dir.go:583] UpdateEntry dir /tmp/my-app2/node_modules/.staging/@types/babel__traverse-25d577b5/ts4.1: rpc error: code = Unknown desc = not found /tmp/my-app2/node_modules/.staging/@types/babel__traverse-25d577b5/ts4.1: filer: no entry is found in filer store
```

**Comment by chrislusf** [comment]
Seems working for me now after fixes:

```
nodejs$ npm i create-react-app
...
added 67 packages in 12s

4 packages are looking for funding
  run `npm fund` for details
npm notice
npm notice New minor version of npm available! 7.18.1 -> 7.19.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.19.1
npm notice Run npm install -g npm@7.19.1 to update!
npm notice
nodejs$ ls
node_modules		package-lock.json	package.json
nodejs$ ls -al
total 85
drwxr-xr-x  1 chris  staff      0 Jul  1 01:29 .
drwxr-xr-x  1 chris  staff      0 Jul  2 23:52 ..
drwxr-xr-x  1 chris  staff      0 Jul  2 23:54 node_modules
-rw-r--r--  1 chris  staff  42651 Jul  2 23:54 package-lock.json
-rw-r--r--  1 chris  staff     61 Jul  2 23:54 package.json
nodejs$ pwd
/Users/chris/tmp/mm/nodejs
nodejs$ npx create-react-app my-app2

Creating a new React app in /Users/chris/tmp/mm/nodejs/my-app2.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...


added 1923 packages in 4m

145 packages are looking for funding
  run `npm fund` for details

Initialized a git repository.

Installing template dependencies using npm...
npm http fetch GET 200
....................

added 43 packages in 10s

146 packages are looking for funding
  run `npm fund` for details
Removing template package using npm...

...

removed 1 package in 3s

146 packages are looking for funding
  run `npm fund` for details

Created git commit.

Success! Created my-app2 at /Users/chris/tmp/mm/nodejs/my-app2
Inside that directory, you can run several commands:

  npm start
    Starts the development server.

  npm run build
    Bundles the app into static files for production.

  npm test
    Starts the test runner.

  npm run eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd my-app2
  npm start

Happy hacking!
```

**Comment by treo** [comment]
During the finalization stage of it it still sometimes loses the entire directory here, but it isn't as consistent as it was before the fix.

**Comment by chrislusf** [comment]
Added one more fix related to this.

**Comment by treo** [comment]
Unfortunately I still run into the same issue.

```
# /srv/seaweedfs/weed version
version 30GB 2.56 fa0dab60299e73acfb8bca72b50184722db8e3ab linux amd64
```

It hangs here:
```
/mnt/seaweedfs/tmp$ npx create-react-app my-app --template typescript
npx: installed 67 in 17.749s

Creating a new React app in /mnt/seaweedfs/tmp/my-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template-typescript...


> core-js@2.6.12 postinstall /mnt/seaweedfs/tmp/my-app/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.15.2 postinstall /mnt/seaweedfs/tmp/my-app/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js-pure@3.15.2 postinstall /mnt/seaweedfs/tmp/my-app/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"


> ejs@2.7.4 postinstall /mnt/seaweedfs/tmp/my-app/node_modules/ejs
> node ./postinstall.js

+ react-scripts@4.0.3
+ cra-template-typescript@1.1.2
+ react@17.0.2
+ react-dom@17.0.2
added 1899 packages from 704 contributors and audited 1902 packages in 215.03s

145 packages are looking for funding
  run `npm fund` for details

found 5 vulnerabilities (3 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

Initialized a git repository.

Installing template dependencies using npm...
[            ......] \ finalize:web-vitals: sill doSerial finalize 314
```

And at the same time:
```
/mnt/seaweedfs/tmp$ ls -lahs /mnt/seaweedfs/tmp/
total 0
```

**Comment by chrislusf** [comment]
was the `weed` binary updated on all servers and the mount?

seems the npx commands are stateful themselves. Is there any way to always execute the same steps?

It was fine on my local.
```
nodejs$ npx create-react-app my-app --template typescript

......

added 48 packages, and changed 1 package in 10s

146 packages are looking for funding
  run `npm fund` for details

We detected TypeScript in your project (src/App.test.tsx) and created a tsconfig.json file for you.

Your tsconfig.json has been populated with default values.

Removing template package using npm...

...

removed 1 package in 2s

146 packages are looking for funding
  run `npm fund` for details

Created git commit.

Success! Created my-app at /Users/chris/tmp/mm/nodejs/my-app
Inside that directory, you can run several commands:

  npm start
    Starts the development server.

  npm run build
    Bundles the app into static files for production.

  npm test
    Starts the test runner.

  npm run eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd my-app
  npm start

Happy hacking!
```

**Comment by treo** [comment]
> was the `weed` binary updated on all servers and the mount?

Yes. I've stopped all services on all servers, updated it, started the master first and then on the other machines before mounting again.

> seems the npx commands are stateful themselves. Is there any way to always execute the same steps?

You can also delete ~/.npm, but I didn't clean it up before reproducing.

One difference that I can see, is that I'm using a Linux client:
```
$ uname -a
Linux skymind-001 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/issue
Ubuntu 20.04.2 LTS \n \l
```

And you seem to be on macos, so the underlying FUSE system is probably different.

**Comment by chrislusf** [comment]
Tried these with a docker linux instance:
```
cd docker/
make run_image
apk add tmux
tmux
```
Start Seaweed in one window
```
weed mount -dir=/mnt/seaweedfs -filer=192.168.2.5:8888
```

Start npm installation in another window
```
f4320db60165:~# cd /mnt/seaweedfs/
f4320db60165:/mnt/seaweedfs# ls
f4320db60165:/mnt/seaweedfs# mkdir nodejs
f4320db60165:/mnt/seaweedfs# cd nodejs/
f4320db60165:/mnt/seaweedfs/nodejs# apk add --update npm
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
(1/8) Installing ca-certificates (20191127-r5)
(2/8) Installing nghttp2-libs (1.43.0-r0)
(3/8) Installing brotli-libs (1.0.9-r5)
(4/8) Installing c-ares (1.17.1-r1)
(5/8) Installing libgcc (10.3.1_git20210424-r2)
(6/8) Installing libstdc++ (10.3.1_git20210424-r2)
(7/8) Installing nodejs (14.17.1-r0)
(8/8) Installing npm (7.17.0-r0)
Executing busybox-1.33.1-r2.trigger
Executing ca-certificates-20191127-r5.trigger
OK: 60 MiB in 28 packages
f4320db60165:/mnt/seaweedfs/nodejs# apk add git
(1/4) Installing libcurl (7.77.0-r1)
(2/4) Installing expat (2.4.1-r0)
(3/4) Installing pcre2 (10.36-r0)
(4/4) Installing git (2.32.0-r0)
Executing busybox-1.33.1-r2.trigger
OK: 72 MiB in 32 packages
f4320db60165:/mnt/seaweedfs/nodejs# npx create-react-app my-app

Creating a new React app in /mnt/seaweedfs/nodejs/my-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...


added 1920 packages, and audited 1921 packages in 3m

145 packages are looking for funding
  run `npm fund` for details

19 vulnerabilities (9 moderate, 10 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

Initialized a git repository.

Installing template dependencies using npm...

added 43 packages, and audited 1964 packages in 11s

146 packages are looking for funding
  run `npm fund` for details

19 vulnerabilities (9 moderate, 10 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
Removing template package using npm...


removed 1 package, and audited 1963 packages in 5s

146 packages are looking for funding
  run `npm fund` for details

19 vulnerabilities (9 moderate, 10 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force
Run `npm audit` for details.
Git commit not created Error: Command failed: git commit -m "Initialize project using Create React App"
    at checkExecSyncError (child_process.js:643:11)
    at execSync (child_process.js:679:15)
    at tryGitCommit (/mnt/seaweedfs/nodejs/my-app/node_modules/react-scripts/scripts/init.js:62:5)
    at module.exports (/mnt/seaweedfs/nodejs/my-app/node_modules/react-scripts/scripts/init.js:352:25)
    at [eval]:3:14
    at Script.runInThisContext (vm.js:134:12)
    at Object.runInThisContext (vm.js:311:38)
    at internal/process/execution.js:77:19
    at [eval]-wrapper:6:22
    at evalScript (internal/process/execution.js:76:60) {
  status: 128,
  signal: null,
  output: [ null, null, null ],
  pid: 326,
  stdout: null,
  stderr: null
}
Removing .git directory...

Success! Created my-app at /mnt/seaweedfs/nodejs/my-app
Inside that directory, you can run several commands:

  npm start
    Starts the development server.

  npm run build
    Bundles the app into static files for production.

  npm test
    Starts the test runner.

  npm run eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can_t go back!

We suggest that you begin by typing:

  cd my-app
  npm start

Happy hacking!
f4320db60165:/mnt/seaweedfs/nodejs# npm install

up to date, audited 5 packages in 1s

found 0 vulnerabilities
f4320db60165:/mnt/seaweedfs/nodejs# npm audit
found 0 vulnerabilities
```

**Comment by treo** [comment]
As I said, unfortunately it isn't exactly deterministic anymore after the last fixes you pushed, but it does still happen regularly here.

As I was testing some more, I noticed a new thing: I've been using that tmp folder over and over again during my testing, and now I can't even create a new file in it anymore:

```
/mnt/seaweedfs/tmp$ touch foo
touch: cannot touch 'foo': No such file or directory
```

And that continues to happen even after I've removed and recreated it - so that prefix seems to be effectively unusable now.

So I created a new folder and tried it again.

It again failed in a similar fashion as to the previous run:

```
npx create-react-app my-app2
npx: installed 67 in 6.261s

Creating a new React app in /mnt/seaweedfs/tmp2/my-app2.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...


> core-js@2.6.12 postinstall /mnt/seaweedfs/tmp2/my-app2/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.15.2 postinstall /mnt/seaweedfs/tmp2/my-app2/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js-pure@3.15.2 postinstall /mnt/seaweedfs/tmp2/my-app2/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"


> ejs@2.7.4 postinstall /mnt/seaweedfs/tmp2/my-app2/node_modules/ejs
> node ./postinstall.js

+ react-scripts@4.0.3
+ react@17.0.2
+ cra-template@1.1.2
+ react-dom@17.0.2
added 1899 packages from 704 contributors and audited 1902 packages in 151.512s

145 packages are looking for funding
  run `npm fund` for details

found 5 vulnerabilities (3 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

Initialized a git repository.

Installing template dependencies using npm...
npm WARN @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.14.5 requires a peer of @babel/core@^7.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ web-vitals@1.1.2
+ @testing-library/user-event@12.8.3
+ @testing-library/react@11.2.7
+ @testing-library/jest-dom@5.14.1
added 29 packages from 78 contributors and audited 1931 packages in 12.822s

145 packages are looking for funding
  run `npm fund` for details

found 5 vulnerabilities (3 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Removing template package using npm...

[            ......] - finalize:fsevents: sill doSerial finalize 26
```

This time around I've got the following in the seaweedfs.logs in /tmp:
*INFO:*
```
I0704 08:34:36 56187 filer_grpc_server_sub_meta.go:204] => client filer:10.10.10.22:8888@10.10.10.22:47554: rpc error: code = Unavailable desc = transport is closing
E0704 08:34:36 56187 filer_grpc_server_sub_meta.go:127] processed to 2021-07-04 08:34:36.310570039 +0000 UTC: rpc error: code = Unavailable desc = transport is closing
I0704 08:34:36 56187 filer_grpc_server_sub_meta.go:204] => client filer:10.10.10.22:8888@10.10.10.22:47286: rpc error: code = Unavailable desc = transport is closing
E0704 08:34:36 56187 filer_grpc_server_sub_meta.go:127] processed to 2021-07-04 08:34:36.310570039 +0000 UTC: rpc error: code = Unavailable desc = transport is closing
I0704 08:34:36 56187 filer_grpc_server_sub_meta.go:204] => client mount@10.10.18.21:40204: rpc error: code = Unavailable desc = transport is closing
E0704 08:34:36 56187 filer_grpc_server_sub_meta.go:66] processed to 2021-07-04 08:34:36.310887609 +0000 UTC: rpc error: code = Unavailable desc = transport is closing
I0704 08:34:36 56187 filer_grpc_server_sub_meta.go:218] - listener mount@10.10.18.21:40204
I0704 08:34:37 56187 filer_grpc_server_sub_meta.go:218] - listener filer:10.10.10.22:8888@10.10.10.22:47286
I0704 08:34:37 56187 filer_grpc_server_sub_meta.go:218] - listener filer:10.10.10.22:8888@10.10.10.22:47554
I0704 08:34:47 56187 filer_grpc_server_sub_meta.go:204] => client mount@10.10.10.25:50078: rpc error: code = Unavailable desc = transport is closing
I0704 08:34:47 56187 filer_grpc_server_sub_meta.go:218] - listener mount@10.10.10.25:50078
I0704 08:34:48 56187 filer_grpc_server_sub_meta.go:204] => client mount@10.10.18.21:55706: rpc error: code = Unavailable desc = transport is closing
I0704 08:34:48 56187 filer_grpc_server_sub_meta.go:218] - listener mount@10.10.18.21:55706
I0704 08:34:48 56187 filer_grpc_server_sub_meta.go:204] => client mount@10.10.18.21:48828: rpc error: code = Unavailable desc = transport is closing
I0704 08:34:48 56187 filer_grpc_server_sub_meta.go:218] - listener mount@10.10.18.21:48828
I0704 08:34:48 56187 filer_grpc_server_sub_meta.go:204] => client mount@10.10.10.25:35448: rpc error: code = Unavailable desc = transport is closing
I0704 08:34:48 56187 filer_grpc_server_sub_meta.go:218] - listener mount@10.10.10.25:35448
I0704 08:39:56 56187 filer_grpc_server_sub_meta.go:204] => client mount@127.0.0.1:48918: rpc error: code = Unavailable desc = transport is closing
E0704 08:39:56 56187 filer_grpc_server_sub_meta.go:66] processed to 2021-07-04 08:39:56.535364 +0000 UTC: rpc error: code = Unavailable desc = transport is closing
I0704 08:39:56 56187 filer_grpc_server_sub_meta.go:218] - listener mount@127.0.0.1:48918
I0704 08:39:56 56187 filer_grpc_server_sub_meta.go:204] => client mount@127.0.0.1:43546: rpc error: code = Unavailable desc = transport is closing
E0704 08:39:56 56187 filer_grpc_server_sub_meta.go:66] processed to 2021-07-04 08:39:56.535364 +0000 UTC: rpc error: code = Unavailable desc = transport is closing
I0704 08:39:56 56187 filer_grpc_server_sub_meta.go:218] - listener mount@127.0.0.1:43546
I0704 08:40:47 56187 filer_grpc_server_sub_meta.go:100] read on disk filer:10.10.10.22:8888@10.10.10.22:51000 local subscribe / from 2021-07-04 08:40:46.712717104 +0000 UTC
I0704 08:40:49 56187 filer_grpc_server_sub_meta.go:115] read in memory filer:10.10.10.22:8888@10.10.10.22:51000 local subscribe / from 2021-07-04 08:40:47.308811913 +0000 UTC
```
*ERROR:*
```
E0704 08:34:36 56187 filer_grpc_server_sub_meta.go:127] processed to 2021-07-04 08:34:36.310570039 +0000 UTC: rpc error: code = Unavailable desc = transport is closing
E0704 08:34:36 56187 filer_grpc_server_sub_meta.go:127] processed to 2021-07-04 08:34:36.310570039 +0000 UTC: rpc error: code = Unavailable desc = transport is closing
E0704 08:34:36 56187 filer_grpc_server_sub_meta.go:66] processed to 2021-07-04 08:34:36.310887609 +0000 UTC: rpc error: code = Unavailable desc = transport is closing
E0704 08:39:56 56187 filer_grpc_server_sub_meta.go:66] processed to 2021-07-04 08:39:56.535364 +0000 UTC: rpc error: code = Unavailable desc = transport is closing
E0704 08:39:56 56187 filer_grpc_server_sub_meta.go:66] processed to 2021-07-04 08:39:56.535364 +0000 UTC: rpc error: code = Unavailable desc = transport is closing
```

*WARNING:* doesn't have anything related to that time frame. 

So maybe it is something that only happens when multiple servers are involved? The connection between the servers is a rather simple though, they are all on the same network, and connected to the same network switch.

**Comment by chrislusf** [comment]
I tried again after https://github.com/chrislusf/seaweedfs/issues/2248

Everything seems running fine now.

Please help to verify if possible.

**Comment by chrislusf** [comment]
Closing for now.
