### ISSUE TITLE
panic: assertion failed: leader.elected.at.same.term

### ISSUE THREAD

**Issue by lygfanye** [chrislusf/seaweedfs#218]
I run :

```
weed master  -defaultReplication=001 -mdir='/data/storage'  

weed volume -max=100 -mserver=0.0.0.0:9333 -dir=/data/storage/v1 -port=9083 -ip=0.0.0.0 -dataCenter=dc1 -rack=rack1

weed volume -max=100 -mserver=0.0.0.0:9333 -dir=/data/storage/v3 -port=9085 -ip=0.0.0.0 -dataCenter=dc1 -rack=rack1

 weed volume -max=100 -mserver=0.0.0.0:9333 -dir=/data/storage/v2 -port=9084 -ip=0.0.0.0 -dataCenter=dc1 -rack=rack1
```

it says 

```
panic: assertion failed: leader.elected.at.same.term
```

===========================================
```
goroutine 33 [running]:
github.com/chrislusf/raft._assert(0xccba00, 0xd76540, 0x1f, 0xc820201c20, 0x1, 0x1)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/raft/util.go:60 +0xee
github.com/chrislusf/raft.(*server).processAppendEntriesRequest(0xc8201fa000, 0xc82013c9b0, 0xc82013c9b0, 0xc820201d18)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/raft/server.go:948 +0x68b
github.com/chrislusf/raft.(*server).leaderLoop(0xc8201fa000)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/raft/server.go:849 +0x6e0
github.com/chrislusf/raft.(*server).loop(0xc8201fa000)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/raft/server.go:609 +0x38a
github.com/chrislusf/raft.(*server).Start.func1(0xc8201fa000)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/raft/server.go:470 +0x59
created by github.com/chrislusf/raft.(*server).Start
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/raft/server.go:471 +0x467

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7fdc7ee82f18, 0x72, 0xc8200101d0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201e0060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201e0060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8201e0000, 0x0, 0x7fdc7ee83038, 0xc82027ab60)
	/usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc82002c178, 0xc820208d40, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc82002c178, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
github.com/chrislusf/seaweedfs/go/util.(*Listener).Accept(0xc8201ca460, 0x0, 0x0, 0x0, 0x0)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/seaweedfs/go/util/net_timeout.go:19 +0x5f
net/http.(*Server).Serve(0xc8200174a0, 0x7fdc7ee82fd8, 0xc8201ca460, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1887 +0xb3
net/http.Serve(0x7fdc7ee82fd8, 0xc8201ca460, 0x7fdc7ee83010, 0xc820078960, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1765 +0x85
main.runMaster(0x10c3580, 0xc82000a170, 0x0, 0x0, 0x0)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/seaweedfs/go/weed/master.go:87 +0x91c
main.main()
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/seaweedfs/go/weed/weed.go:78 +0x68d

goroutine 5 [chan receive]:
github.com/chrislusf/seaweedfs/go/glog.(*loggingT).flushDaemon(0x10cc2a0)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/seaweedfs/go/glog/glog.go:883 +0x67
created by github.com/chrislusf/seaweedfs/go/glog.init.1
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/seaweedfs/go/glog/glog.go:410 +0x297

goroutine 7 [select]:
github.com/chrislusf/seaweedfs/go/stats.(*ServerStats).Start(0xc82016e4c0)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/seaweedfs/go/stats/stats.go:92 +0x45f
created by github.com/chrislusf/seaweedfs/go/weed/weed_server.init.1
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/common.go:27 +0x50

goroutine 8 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 9 [sleep]:
time.Sleep(0x132b9ba80)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/chrislusf/seaweedfs/go/topology.(*Topology).StartRefreshWritableVolumes.func1(0xc8200bcd80)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/seaweedfs/go/topology/topology_event_handling.go:18 +0xdc
created by github.com/chrislusf/seaweedfs/go/topology.(*Topology).StartRefreshWritableVolumes
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/seaweedfs/go/topology/topology_event_handling.go:20 +0x39

goroutine 20 [select]:
github.com/chrislusf/raft.(*server).send(0xc8201fa000, 0xc18ce0, 0x10f43c0, 0x0, 0x0, 0x0, 0x0)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/raft/server.go:630 +0x300
github.com/chrislusf/raft.(*server).Do(0xc8201fa000, 0x7fdc7edfd1a0, 0x10f43c0, 0x0, 0x0, 0x0, 0x0)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/raft/server.go:897 +0x6d
github.com/chrislusf/raft.(*server).leaderLoop.func1(0xc8201fa000)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/raft/server.go:828 +0xb6
created by github.com/chrislusf/raft.(*server).leaderLoop
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/raft/server.go:829 +0x2b6

goroutine 11 [select]:
github.com/chrislusf/seaweedfs/go/topology.(*Topology).StartRefreshWritableVolumes.func3(0xc8200bcd80)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/seaweedfs/go/topology/topology_event_handling.go:31 +0x681
created by github.com/chrislusf/seaweedfs/go/topology.(*Topology).StartRefreshWritableVolumes
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/seaweedfs/go/topology/topology_event_handling.go:42 +0x91

goroutine 34 [select]:
github.com/chrislusf/raft.(*server).send(0xc8201fa000, 0xbc8180, 0xc82013c9b0, 0x0, 0x0, 0x0, 0x0)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/raft/server.go:630 +0x300
github.com/chrislusf/raft.(*server).AppendEntries(0xc8201fa000, 0xc82013c9b0, 0xc82013b180)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/raft/server.go:933 +0x41
github.com/chrislusf/raft.(*HTTPTransporter).appendEntriesHandler.func1(0x7fdc7ee3d228, 0xc82027da20, 0xc82027f5e0)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/raft/http_transporter.go:246 +0x2a9
net/http.HandlerFunc.ServeHTTP(0xc8201f0280, 0x7fdc7ee3d228, 0xc82027da20, 0xc82027f5e0)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820078960, 0x7fdc7ee3d228, 0xc82027da20, 0xc82027f5e0)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/gorilla/mux/mux.go:100 +0x29e
net/http.serverHandler.ServeHTTP(0xc8200174a0, 0x7fdc7ee3d228, 0xc82027da20, 0xc82027f5e0)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc82022bad0)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6

goroutine 49 [IO wait]:
net.runtime_pollWait(0x7fdc7ee82e58, 0x72, 0xc8200101d0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820236060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820236060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820236000, 0xc82023e000, 0x1000, 0x1000, 0x0, 0x7fdc7ee7d050, 0xc8200101d0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820132010, 0xc82023e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
github.com/chrislusf/seaweedfs/go/util.(*Conn).Read(0xc820136040, 0xc82023e000, 0x1000, 0x1000, 0xc820016480, 0x0, 0x0)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/seaweedfs/go/util/net_timeout.go:45 +0x1b2
net/http.(*liveSwitchReader).Read(0xc820238048, 0xc82023e000, 0x1000, 0x1000, 0xc82023f000, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc820136060, 0xc82023e000, 0x1000, 0x1000, 0xecdca939a, 0x0, 0x0)
	/usr/local/go/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc82023c000)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82023c000, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*conn).readRequest(0xc820238000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:629 +0x2bb
net/http.(*conn).serve(0xc820238000)
	/usr/local/go/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6

goroutine 13 [IO wait]:
net.runtime_pollWait(0x7fdc7ee82d98, 0x72, 0xc8200101d0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201e00d0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201e00d0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201e0070, 0xc8200cb000, 0x1000, 0x1000, 0x0, 0x7fdc7ee7d050, 0xc8200101d0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82002c180, 0xc8200cb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
github.com/chrislusf/seaweedfs/go/util.(*Conn).Read(0xc8201ca4c0, 0xc8200cb000, 0x1000, 0x1000, 0xc820016480, 0x0, 0x0)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/seaweedfs/go/util/net_timeout.go:45 +0x1b2
net/http.(*liveSwitchReader).Read(0xc82010f858, 0xc8200cb000, 0x1000, 0x1000, 0xc820258000, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc8201ca4e0, 0xc8200cb000, 0x1000, 0x1000, 0xecdca939a, 0x0, 0x0)
	/usr/local/go/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc820017500)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820017500, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*conn).readRequest(0xc82010f810, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:629 +0x2bb
net/http.(*conn).serve(0xc82010f810)
	/usr/local/go/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6

goroutine 50 [IO wait]:
net.runtime_pollWait(0x7fdc7ee82cd8, 0x72, 0xc8200101d0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820236290, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820236290, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820236230, 0xc82025a000, 0x1000, 0x1000, 0x0, 0x7fdc7ee7d050, 0xc8200101d0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820132100, 0xc82025a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
github.com/chrislusf/seaweedfs/go/util.(*Conn).Read(0xc820136520, 0xc82025a000, 0x1000, 0x1000, 0xc820016480, 0x0, 0x0)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/seaweedfs/go/util/net_timeout.go:45 +0x1b2
net/http.(*liveSwitchReader).Read(0xc820238678, 0xc82025a000, 0x1000, 0x1000, 0xc82025b000, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc820136540, 0xc82025a000, 0x1000, 0x1000, 0xecdca939a, 0x0, 0x0)
	/usr/local/go/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc82023c1e0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82023c1e0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*conn).readRequest(0xc820238630, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:629 +0x2bb
net/http.(*conn).serve(0xc820238630)
	/usr/local/go/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6

goroutine 19 [select]:
net/http.(*persistConn).roundTrip(0xc82027d3f0, 0xc820150f20, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1164 +0xb0d
net/http.(*Transport).RoundTrip(0xc8201f4090, 0xc8201622a0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:235 +0x530
net/http.send(0xc8201622a0, 0x7fdc7ee816e8, 0xc8201f4090, 0xc820168f30, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:220 +0x52c
net/http.(*Client).send(0xc8201f4058, 0xc8201622a0, 0x29, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:143 +0x15a
net/http.(*Client).doFollowingRedirects(0xc8201f4058, 0xc8201622a0, 0xe311c8, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:380 +0xbc0
net/http.(*Client).Post(0xc8201f4058, 0xc820168ed0, 0x29, 0xd4b8d0, 0x14, 0x7fdc7ee3d488, 0xc8202b8150, 0xc820150c40, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:471 +0x107
github.com/chrislusf/raft.(*HTTPTransporter).SendAppendEntriesRequest(0xc8201f4000, 0x7fdc7edbd068, 0xc8201fa000, 0xc8201f36c0, 0xc82014cc80, 0x0)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/raft/http_transporter.go:125 +0x566
github.com/chrislusf/raft.(*Peer).sendAppendEntriesRequest(0xc8201f36c0, 0xc82014cc80)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/raft/peer.go:193 +0x375
github.com/chrislusf/raft.(*Peer).flush(0xc8201f36c0)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/raft/peer.go:178 +0x2c4
github.com/chrislusf/raft.(*Peer).heartbeat(0xc8201f36c0, 0xc82008e1e0)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/raft/peer.go:163 +0x6af
github.com/chrislusf/raft.(*Peer).startHeartbeat.func1(0xc8201f36c0, 0xc82008e1e0)
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/raft/peer.go:97 +0x66
created by github.com/chrislusf/raft.(*Peer).startHeartbeat
	/Users/fanye/GoProjects/seaweedfs/src/github.com/chrislusf/raft/peer.go:98 +0x109

goroutine 53 [IO wait]:
net.runtime_pollWait(0x7fdc7ee82c18, 0x72, 0xc8200101d0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8202371e0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202371e0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820237180, 0xc8202a6000, 0x1000, 0x1000, 0x0, 0x7fdc7ee7d050, 0xc8200101d0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8201321f8, 0xc8202a6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7fdc7ee3d508, 0xc8201321f8, 0xc82027d448, 0xc8202a6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8202982a0, 0xc8202a6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc82023c5a0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82023c5a0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82027d3f0)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 54 [select]:
net/http.(*persistConn).writeLoop(0xc82027d3f0)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d
 ```

**Comment by chrislusf** [comment]
Cleanup mdir and restart.

**Comment by lygfanye** [comment]
yeah , it works, ^_^
