### ISSUE TITLE
"weed server" peer check thinks it's a master when master has been disabled.

### ISSUE THREAD

**Issue by Robinysh** [chrislusf/seaweedfs#2352]
**Describe the bug**
I'm getting `Only odd number of masters are supported: [node1:9333 node3:9333 node4:9333 node2:9333]` on `weed server -options=/etc/xdg/seaweedfs/server.conf -ip=node2` when there is a master=false flag in the config file. Node2 shouldn't be counted as a master.
I suspect it's the `if *isStartingMasterServer {` here removed that's causing the bug https://github.com/chrislusf/seaweedfs/commit/e5fc35ed0c970fea060a5b3b7a3f5efb5af425d6#diff-25bae991aa8050efe57406452575e53bb89eb91244dcfa772587872b05f862aeL170

**Relevant logs**
`weed server -options=/etc/xdg/seaweedfs/server.conf -ip=node2` log
```
Oct 03 20:17:22 node2 systemd[1]: Started Seaweed Master.
Oct 03 20:17:22 node2 weed[1015247]: I1003 20:17:22 15247 master.go:170] current: node2:9333 peers:node1:9333,node3:9333,node4:9333
Oct 03 20:17:22 node2 weed[1015247]: F1003 20:17:22 15247 master.go:186] Only odd number of masters are supported: [node1:9333 node3:9333 node4:9333 node2:9333]
Oct 03 20:17:22 node2 weed[1015247]: goroutine 1 [running]:
Oct 03 20:17:22 node2 weed[1015247]: github.com/chrislusf/seaweedfs/weed/glog.stacks(0x0)
Oct 03 20:17:22 node2 weed[1015247]:         github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0xc5
Oct 03 20:17:22 node2 weed[1015247]: github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x5581706f8620, 0x3, 0xc000262310, {0x55816f9531f3, 0x9}, 0xba, 0x0)
Oct 03 20:17:22 node2 weed[1015247]:         github.com/chrislusf/seaweedfs/weed/glog/glog.go:718 +0x465
Oct 03 20:17:22 node2 weed[1015247]: github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x5581706f8620, 0x3, {0x55816eaf1622, 0x2d}, {0xc000be38a8, 0x1, 0x1})
Oct 03 20:17:22 node2 weed[1015247]:         github.com/chrislusf/seaweedfs/weed/glog/glog.go:656 +0x1bb
Oct 03 20:17:22 node2 weed[1015247]: github.com/chrislusf/seaweedfs/weed/glog.Fatalf({0x55816eaf1622, 0x2d}, {0xc000be38a8, 0x1, 0x1})
Oct 03 20:17:22 node2 weed[1015247]:         github.com/chrislusf/seaweedfs/weed/glog/glog.go:1149 +0x57
Oct 03 20:17:22 node2 weed[1015247]: github.com/chrislusf/seaweedfs/weed/command.checkPeers({0x7ffd910c4f15, 0x5}, 0x2475, 0x0, {0xc00013436d, 0x20})
Oct 03 20:17:22 node2 weed[1015247]:         github.com/chrislusf/seaweedfs/weed/command/master.go:186 +0x42c
Oct 03 20:17:22 node2 weed[1015247]: github.com/chrislusf/seaweedfs/weed/command.runServer(0x5581706165a0, {0xc00004e0b0, 0x0, 0x0})
Oct 03 20:17:22 node2 weed[1015247]:         github.com/chrislusf/seaweedfs/weed/command/server.go:174 +0x388
Oct 03 20:17:22 node2 weed[1015247]: main.main()
Oct 03 20:17:22 node2 weed[1015247]:         github.com/chrislusf/seaweedfs/weed/weed.go:78 +0x5b3
Oct 03 20:17:22 node2 systemd[1]: seaweedfs.service: Main process exited, code=exited, status=255/EXCEPTION
Oct 03 20:17:22 node2 systemd[1]: seaweedfs.service: Failed with result 'exit-code'.
Oct 03 20:17:22 node2 systemd[1]: seaweedfs.service: Scheduled restart job, restart counter is at 5.
Oct 03 20:17:22 node2 systemd[1]: Stopped Seaweed Master.
```

**System Setup**
- Arch linux
- version 30GB 2.70  linux amd64
- server.conf:
```
master=false
master.defaultReplication=001
volume.dir.idx=index
dir=/brick/0
filer=true
filer.peers=node1:8888,node2:8888,node3:8888,node4:8888
master.volumePreallocate=true
master.peers=node1:9333,node3:9333,node4:9333
rack=rack1
dataCenter=dc1
volume.max=100
volume.concurrentUploadLimitMB=999999
filer.concurrentUploadLimitMB=999999
metrics.address=node3:9091
```

**Expected behavior**
The server should not be counted as a master on `master=false` during peer checking.

**Comment by chrislusf** [comment]
Thanks a lot for the bug report and debugging!

**Comment by Robinysh** [comment]
@chrislusf Thanks for the fix, however I might be unclear on what I meant, the bug comes from the checkPeers() call right after your fix https://github.com/chrislusf/seaweedfs/commit/e5fc35ed0c970fea060a5b3b7a3f5efb5af425d6#diff-25bae991aa8050efe57406452575e53bb89eb91244dcfa772587872b05f862aeR174 
so the bug is actually still here.

**Comment by chrislusf** [comment]
ok. Added some more fix.

**Comment by Robinysh** [comment]
Great, it's working on my end, thanks a lot.
