### ISSUE TITLE
Server panic: invalid memory address

### ISSUE THREAD

**Issue by Robinysh** [chrislusf/seaweedfs#2357]
**Describe the bug**
I got a random `panic: runtime error: invalid memory address or nil pointer dereference` after a 10-hour uptime and it crashed the server. I was running `weed filter.copy` on node1 and node3 at that time since the server was up. I'm honestly not sure if this is reproducible so feel free to close this if you have no idea about this.

Not sure if they're related, but 1 out of 4 servers is running a different commit, as stated down below in the system setup section.

As a side note, what's up with the `deleting fileIds len=9 error: delete fileId 55,90fa22e53c0185: volume 55 not found on node4:8080` I'm seeing too? Not that they're blocking issues just curious.
 
**Relevant logs**
`weed server -options=/etc/xdg/seaweedfs/server.conf -ip=node1` log
```
Oct 05 03:58:07 node1 weed[3229970]: I1005 03:58:07 29970 filer_grpc_server_sub_meta.go:101] read on disk filer:node2:8888@192.168.50.202:48712 local subscribe / from 2021-10-04 07:59:43.536408833 +0800 HKT
Oct 05 03:58:07 node1 weed[3229970]: I1005 03:58:07 29970 filer_grpc_server_sub_meta.go:246] - listener filer:node2:8888@192.168.50.202:48712
Oct 05 03:58:07 node1 weed[3229970]: I1005 03:58:07 29970 filer_deletion.go:57] deleting fileIds len=3 error: delete fileId 55,90fa0935601152: volume 55 not found on node2:8080
Oct 05 03:58:08 node1 weed[3229970]: I1005 03:58:08 29970 filer_grpc_server_sub_meta.go:241] + listener filer:node2:8888@192.168.50.202:48712
Oct 05 03:58:08 node1 weed[3229970]: I1005 03:58:08 29970 filer_grpc_server_sub_meta.go:89]  filer:node2:8888@192.168.50.202:48712 local subscribe / from 2021-10-04 07:59:43.536408833 +0800 HKT
Oct 05 03:58:08 node1 weed[3229970]: I1005 03:58:08 29970 filer_grpc_server_sub_meta.go:101] read on disk filer:node2:8888@192.168.50.202:48712 local subscribe / from 2021-10-04 07:59:43.536408833 +0800 HKT
Oct 05 03:58:08 node1 weed[3229970]: I1005 03:58:08 29970 filer_grpc_server_sub_meta.go:246] - listener filer:node2:8888@192.168.50.202:48712
Oct 05 03:58:08 node1 weed[3229970]: I1005 03:58:08 29970 filer_deletion.go:57] deleting fileIds len=3 error: delete fileId 55,90fa0b5f04cb61: volume 55 not found on node4:8080
Oct 05 03:58:09 node1 weed[3229970]: I1005 03:58:09 29970 filer_deletion.go:57] deleting fileIds len=3 error: delete fileId 55,90fa167197206a: volume 55 not found on node2:8080
Oct 05 03:58:10 node1 weed[3229970]: I1005 03:58:10 29970 filer_grpc_server_sub_meta.go:241] + listener filer:node2:8888@192.168.50.202:48712
Oct 05 03:58:10 node1 weed[3229970]: I1005 03:58:10 29970 filer_grpc_server_sub_meta.go:89]  filer:node2:8888@192.168.50.202:48712 local subscribe / from 2021-10-04 07:59:43.536408833 +0800 HKT
Oct 05 03:58:10 node1 weed[3229970]: I1005 03:58:10 29970 filer_grpc_server_sub_meta.go:101] read on disk filer:node2:8888@192.168.50.202:48712 local subscribe / from 2021-10-04 07:59:43.536408833 +0800 HKT
Oct 05 03:58:10 node1 weed[3229970]: I1005 03:58:10 29970 filer_grpc_server_sub_meta.go:246] - listener filer:node2:8888@192.168.50.202:48712
Oct 05 03:58:11 node1 weed[3229970]: I1005 03:58:11 29970 filer_deletion.go:57] deleting fileIds len=4 error: delete fileId 55,90fa263b252be4: volume 55 not found on node2:8080
Oct 05 03:58:11 node1 weed[3229970]: I1005 03:58:11 29970 topology_vacuum.go:83] Complete vacuuming 30 on node1:8080
Oct 05 03:58:11 node1 weed[3229970]: I1005 03:58:11 29970 topology_vacuum.go:107] Start Committing vacuum 30 on node1:8080
Oct 05 03:58:11 node1 weed[3229970]: I1005 03:58:11 29970 volume_vacuum.go:93] Committing volume 30 vacuuming...
Oct 05 03:58:12 node1 weed[3229970]: I1005 03:58:12 29970 volume_loading.go:86] readSuperBlock volume 30 version 3
Oct 05 03:58:12 node1 weed[3229970]: I1005 03:58:12 29970 volume_loading.go:133] loading index /index/30.idx to memory
Oct 05 03:58:12 node1 weed[3229970]: I1005 03:58:12 29970 filer_deletion.go:57] deleting fileIds len=9 error: delete fileId 55,90fa22e53c0185: volume 55 not found on node4:8080
Oct 05 03:58:12 node1 weed[3229970]: I1005 03:58:12 29970 topology_vacuum.go:121] Complete Committing vacuum 30 on node1:8080
Oct 05 03:58:12 node1 weed[3229970]: I1005 03:58:12 29970 topology_vacuum.go:107] Start Committing vacuum 30 on node2:8080
Oct 05 03:58:12 node1 weed[3229970]: I1005 03:58:12 29970 filer_grpc_server_sub_meta.go:241] + listener filer:node2:8888@192.168.50.202:48712
Oct 05 03:58:12 node1 weed[3229970]: I1005 03:58:12 29970 filer_grpc_server_sub_meta.go:89]  filer:node2:8888@192.168.50.202:48712 local subscribe / from 2021-10-04 07:59:43.536408833 +0800 HKT
Oct 05 03:58:12 node1 weed[3229970]: I1005 03:58:12 29970 filer_grpc_server_sub_meta.go:101] read on disk filer:node2:8888@192.168.50.202:48712 local subscribe / from 2021-10-04 07:59:43.536408833 +0800 HKT
Oct 05 03:58:12 node1 weed[3229970]: I1005 03:58:12 29970 filer_grpc_server_sub_meta.go:246] - listener filer:node2:8888@192.168.50.202:48712
Oct 05 03:58:12 node1 weed[3229970]: I1005 03:58:12 29970 topology_vacuum.go:121] Complete Committing vacuum 30 on node2:8080
Oct 05 03:58:12 node1 weed[3229970]: I1005 03:58:12 29970 volume_layout.go:362] Volume 30 becomes writable
Oct 05 03:58:12 node1 weed[3229970]: I1005 03:58:12 29970 topology_vacuum.go:71] 1 Start vacuuming 76 on node3:8080
Oct 05 03:58:12 node1 weed[3229970]: I1005 03:58:12 29970 topology_vacuum.go:71] 0 Start vacuuming 76 on node1:8080
Oct 05 03:58:12 node1 weed[3229970]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 05 03:58:12 node1 weed[3229970]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x557cb3888bfb]
Oct 05 03:58:12 node1 weed[3229970]: goroutine 36721451 [running]:
Oct 05 03:58:12 node1 weed[3229970]: github.com/chrislusf/seaweedfs/weed/topology.(*VolumeLayout).GetActiveVolumeCount(0xc00d042400, 0xc046482930)
Oct 05 03:58:12 node1 weed[3229970]:         github.com/chrislusf/seaweedfs/weed/topology/volume_layout.go:322 +0x31b
Oct 05 03:58:12 node1 weed[3229970]: github.com/chrislusf/seaweedfs/weed/server.(*MasterServer).shouldVolumeGrow(0xc000306c00, 0xc046482930)
Oct 05 03:58:12 node1 weed[3229970]:         github.com/chrislusf/seaweedfs/weed/server/master_server_handlers_admin.go:137 +0xed
Oct 05 03:58:12 node1 weed[3229970]: github.com/chrislusf/seaweedfs/weed/server.(*MasterServer).Assign(0xc000306c00, {0x557cb486edb8, 0xc041698480}, 0xc00672e790)
Oct 05 03:58:12 node1 weed[3229970]:         github.com/chrislusf/seaweedfs/weed/server/master_grpc_server_volume.go:133 +0x4e5
Oct 05 03:58:12 node1 weed[3229970]: github.com/chrislusf/seaweedfs/weed/pb/master_pb._Seaweed_Assign_Handler({0x557cb47a1880, 0xc000306c00}, {0x557cb486edb8, 0xc041698480}, 0xc02952d080, 0x0)
Oct 05 03:58:12 node1 weed[3229970]:         github.com/chrislusf/seaweedfs/weed/pb/master_pb/master.pb.go:4505 +0x385
Oct 05 03:58:12 node1 weed[3229970]: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00044d6c0, {0x557cb48997e8, 0xc00001d080}, 0xc015e8d680, 0xc00986be90, 0x557cb5a987b8, 0x0)
Oct 05 03:58:12 node1 weed[3229970]:         google.golang.org/grpc@v1.40.0/server.go:1297 +0x14c9
Oct 05 03:58:12 node1 weed[3229970]: google.golang.org/grpc.(*Server).handleStream(0xc00044d6c0, {0x557cb48997e8, 0xc00001d080}, 0xc015e8d680, 0x0)
Oct 05 03:58:12 node1 weed[3229970]:         google.golang.org/grpc@v1.40.0/server.go:1626 +0x85e
Oct 05 03:58:12 node1 weed[3229970]: google.golang.org/grpc.(*Server).serveStreams.func1.2()
Oct 05 03:58:12 node1 weed[3229970]:         google.golang.org/grpc@v1.40.0/server.go:941 +0x11d
Oct 05 03:58:12 node1 weed[3229970]: created by google.golang.org/grpc.(*Server).serveStreams.func1
Oct 05 03:58:12 node1 weed[3229970]:         google.golang.org/grpc@v1.40.0/server.go:939 +0x345
Oct 05 04:03:06 node1 systemd[1]: seaweedfs.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 05 04:03:06 node1 systemd[1]: seaweedfs.service: Failed with result 'exit-code'.

```

**System Setup**
- Arch linux
- node1, node3, node4 version: b297849147a570af9a5413bd668e786a5897de34
- node2 version: 6a030547a2efa3efe38491aa8fc06f3b7d3acc75
- server.conf:
```
master.defaultReplication=001
volume.dir.idx=/index
dir=/brick/05
filer=true
filer.peers=node1:8888,node2:8888,node3:8888,node4:8888
master.volumePreallocate=true
master.peers=node1:9333,node3:9333,node4:9333
rack=rack1
dataCenter=dc1
volume.max=10000
volume.concurrentUploadLimitMB=999999
filer.concurrentUploadLimitMB=999999
metrics.address=node3:9091
```

**Comment by Robinysh** [comment]
P.S. I'm also noticing I have a node with negative amount of volumes, not sure if they're related.
Part of `volume.list` in `weed shell`
```
      DataNode node4:8080 hdd(volume:-1/10000 active:-1 free:10001 remote:0)
        Disk hdd(volume:-1/10000 active:-1 free:10001 remote:0)
          ec volume id:5 collection: shards:[3]
          ec volume id:22 collection: shards:[0 1]
          ec volume id:46 collection: shards:[0 2 3 4]
          ec volume id:81 collection: shards:[0 4 8 12]
          ec volume id:45 collection: shards:[0 2 3 4]
          ec volume id:16 collection: shards:[2]
          ec volume id:28 collection: shards:[0 1 2 3]
          ec volume id:75 collection: shards:[0 4 8 12]
          ec volume id:86 collection: shards:[0 4 8 12]
          ec volume id:49 collection: shards:[0 1 2 4]
          ec volume id:58 collection: shards:[0 4 8 12]
          ec volume id:62 collection: shards:[0 4 8 12]
          ec volume id:74 collection: shards:[0 4 8 12]
          ec volume id:14 collection: shards:[2]
          ec volume id:4 collection: shards:[1]
          ec volume id:79 collection: shards:[0 4 8 12]
          ec volume id:78 collection: shards:[0 4 8 12]
          ec volume id:82 collection: shards:[0 4 8 12]
          ec volume id:35 collection: shards:[0 4 8 12]
          ec volume id:30 collection: shards:[0 1 2 3]
          ec volume id:52 collection: shards:[0 4 8 12]
          ec volume id:55 collection: shards:[0 3 4 6]
          ec volume id:48 collection: shards:[0 1 2 4]
          ec volume id:2 collection: shards:[1]
          ec volume id:27 collection: shards:[0 4 8 12]
          ec volume id:21 collection: shards:[0 1]
          ec volume id:24 collection: shards:[0 1]
          ec volume id:6 collection: shards:[2]
          ec volume id:29 collection: shards:[0 4 8 12]
          ec volume id:61 collection: shards:[0 4 8 12]
          ec volume id:23 collection: shards:[0 1]
          ec volume id:20 collection: shards:[0 1]
          ec volume id:73 collection: shards:[0 4 8 12]
          ec volume id:40 collection: shards:[0 4 8 12]
          ec volume id:26 collection: shards:[0 1 3 4]
          ec volume id:33 collection: shards:[0 4 8 12]
        Disk hdd total size:0 file_count:0 
      DataNode node4:8080 total size:0 file_count:0 
```

**Comment by chrislusf** [comment]
closing since no more updates
