### ISSUE TITLE
Failed to write to local disk: volume size limit exceeded

### ISSUE THREAD

**Issue by Robinysh** [chrislusf/seaweedfs#2359]
**Describe the bug**
I'm getting some `Failed to write to local disk: volume size limit exceeded` after a few hours of data transfer with `weed filer.copy`. Deleting the broken volume should work for now but the same error comes around every few hours.
 
**Relevant logs**
`weed server -options=/etc/xdg/seaweedfs/server.conf -ip=node1` log:
```
Oct 06 11:33:09 node1 weed[2538376]: I1006 11:33:09 38376 store_replicate.go:48] failed to write to local disk: volume size limit 34359738368 exceeded! current size is 34359738285
Oct 06 11:33:09 node1 weed[2538376]: I1006 11:33:09 38376 common.go:67] response method:POST URL:/92,f1a83423c5dffd with httpStatus:500 and JSON:{"name":"1329.obj-1","size":4194304,"error":"failed to write to local disk: volume size limit 34359738368 exceeded! current size is 34359738285","eTag":"12e79c95","mime":"text/plain; charset=utf-8"}
Oct 06 11:33:09 node1 weed[2538376]: I1006 11:33:09 38376 store_replicate.go:48] failed to write to local disk: volume size limit 34359738368 exceeded! current size is 34359738285
Oct 06 11:33:09 node1 weed[2538376]: I1006 11:33:09 38376 common.go:67] response method:POST URL:/92,f1a85d77684546 with httpStatus:500 and JSON:{"name":"1345.mtl","size":8773,"error":"failed to write to local disk: volume size limit 34359738368 exceeded! current size is 34359738285","eTag":"95772b04","mime":"text/plain; charset=utf-8"}
Oct 06 11:33:09 node1 weed[2538376]: I1006 11:33:09 38376 filer_deletion.go:57] deleting fileIds len=68 error: delete fileId 76,edca7ad421b2af: volume 76 not found on node1:8080
Oct 06 11:33:09 node1 weed[2538376]: I1006 11:33:09 38376 store_replicate.go:48] failed to write to local disk: volume size limit 34359738368 exceeded! current size is 34359738285
Oct 06 11:33:09 node1 weed[2538376]: I1006 11:33:09 38376 common.go:67] response method:POST URL:/92,f1a85d77684546 with httpStatus:500 and JSON:{"name":"1345.mtl","size":8773,"error":"failed to write to local disk: volume size limit 34359738368 exceeded! current size is 34359738285","eTag":"95772b04","mime":"text/plain; charset=utf-8"}
Oct 06 11:33:09 node1 weed[2538376]: I1006 11:33:09 38376 store_replicate.go:48] failed to write to local disk: volume size limit 34359738368 exceeded! current size is 34359738285
Oct 06 11:33:09 node1 weed[2538376]: I1006 11:33:09 38376 common.go:67] response method:POST URL:/92,f1a821b9fa8a43 with httpStatus:500 and JSON:{"name":"1321.obj-1","size":4194304,"error":"failed to write to local disk: volume size limit 34359738368 exceeded! current size is 34359738285","eTag":"82024fb7","mime":"text/plain; charset=utf-8"}
Oct 06 11:33:09 node1 weed[2538376]: I1006 11:33:09 38376 store_replicate.go:48] failed to write to local disk: volume size limit 34359738368 exceeded! current size is 34359738285
Oct 06 11:33:09 node1 weed[2538376]: I1006 11:33:09 38376 common.go:67] response method:POST URL:/92,f1a83423c5dffd with httpStatus:500 and JSON:{"name":"1329.obj-1","size":4194304,"error":"failed to write to local disk: volume size limit 34359738368 exceeded! current size is 34359738285","eTag":"12e79c95","mime":"text/plain; charset=utf-8"}
```
`sudo  weed filer.copy -c 48 -concurrentChunks 24 /my_dir  http://localhost:8888/` log:
```
W1006 11:33:09 93678 upload_content.go:111] uploading to http://node1:8080/92,f1a83423c5dffd: unmarshalled error http://node1:8080/92,f1a83423c5dffd: failed to write to local disk: volume size limit 34359738368 exceeded! current size is 34359738285
copy file error: upload 1325.mtl: upload data 1325.mtl to http://node1:8080/92,f1a82b2945c4ae: unmarshalled error http://node1:8080/92,f1a82b2945c4ae: failed to write to local disk: volume size limit 34359738368 exceeded! current size is 34359738285
```

Last few lines of ` go run ./see_idx/see_idx.go -dir /index -volumeId 92`:
```
key:f1a0fc offset:303290304 size:1544993(1.47 MiB)
key:f1a116 offset:303483432 size:983841(960.78 KiB)
key:f1a11c offset:303606416 size:318345(310.88 KiB)
key:f1a12a offset:303646213 size:299809(292.78 KiB)
key:f1a130 offset:303683693 size:103201(100.78 KiB)
key:f1a133 offset:303696597 size:586529(572.78 KiB)
key:f1a138 offset:303769917 size:119585(116.78 KiB)
key:f1a14c offset:303784869 size:82721(80.78 KiB)
key:f1a167 offset:303795213 size:1475361(1.41 MiB)
key:f1a194 offset:303979637 size:1076(1.05 KiB)
key:f1a19a offset:303979776 size:54335(53.06 KiB)
key:f1a1a1 offset:303986572 size:989(989 B)
key:f1a1b3 offset:303986700 size:363(363 B)
key:f1a1be offset:303986749 size:1091(1.07 KiB)
key:f1a1c9 offset:303986889 size:616(616 B)
key:f1a1f5 offset:303986970 size:299809(292.78 KiB)
key:f1a260 offset:304024450 size:10002(9.77 KiB)
key:f1a276 offset:304025704 size:1560(1.52 KiB)
key:f1a27f offset:304025903 size:410(410 B)
key:f1a280 offset:304025958 size:1073(1.05 KiB)
key:f1a2f7 offset:304026096 size:508(508 B)
key:f1a304 offset:304026164 size:1466(1.43 KiB)
key:f1a317 offset:304026351 size:1472(1.44 KiB)
key:f1a315 offset:304026539 size:1884(1.84 KiB)
key:f1a323 offset:304026779 size:2208(2.16 KiB)
key:f1a324 offset:304027059 size:846(846 B)
key:f1a32b offset:304027169 size:5392(5.27 KiB)
key:f1a338 offset:304027847 size:279(279 B)
key:f1a339 offset:304027886 size:1232(1.20 KiB)
key:f1a355 offset:304028044 size:1902(1.86 KiB)
key:f1a35e offset:304028286 size:2263(2.21 KiB)
key:f1a36e offset:304028573 size:1353(1.32 KiB)
key:f1a3a4 offset:304028746 size:747(747 B)
key:f1a455 offset:304028843 size:375(375 B)
key:f1908b offset:304028894 size:-1(16.00 EiB)
key:f19cb2 offset:304028898 size:-1(16.00 EiB)
key:f16c8c offset:304028902 size:-1(16.00 EiB)
key:f195b8 offset:304028906 size:-1(16.00 EiB)
key:f1a11c offset:304028910 size:-1(16.00 EiB)
```

`go run ./see_dat/see_dat.go -dir /brick/05 -volumeId 92`:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8b6b3b]

goroutine 1 [running]:
os.(*File).Name(...)
        /usr/lib/go/src/os/file.go:57
github.com/chrislusf/seaweedfs/weed/storage/backend.NewDiskFile(0x0)
        /home/robin/seaweedfs-git/src/seaweedfs-git/weed/storage/backend/disk_file.go:24 +0x5b
github.com/chrislusf/seaweedfs/weed/storage.(*Volume).load(0xc000450120, 0x0, 0x0, 0x0, 0xffffffffffffffff)
        /home/robin/seaweedfs-git/src/seaweedfs-git/weed/storage/volume_loading.go:67 +0x35a
github.com/chrislusf/seaweedfs/weed/storage.loadVolumeWithoutIndex({0x7fff8ca574f9, 0x9}, {0x0, 0x0}, 0x5c, 0x0)
        /home/robin/seaweedfs-git/src/seaweedfs-git/weed/storage/volume_loading.go:21 +0xf7
github.com/chrislusf/seaweedfs/weed/storage.ScanVolumeFile({0x7fff8ca574f9, 0xc000132010}, {0x0, 0xc00039ff70}, 0x407a19, 0x405031, {0xfbad88, 0xc00003d192})
        /home/robin/seaweedfs-git/src/seaweedfs-git/weed/storage/volume_read.go:82 +0x73
main.main()
        /home/robin/seaweedfs-git/src/seaweedfs-git/unmaintained/see_dat/see_dat.go:46 +0xb0
exit status 2
```

**System Setup**
- Arch linux
- SeaweedFS version: f0d1e7bd05e962e1f432cb1699229de8d194714a
- server.conf:
```
master.defaultReplication=001
volume.dir.idx=/index
dir=/brick/05
filer=true
filer.peers=node1:8888,node2:8888,node3:8888,node4:8888
master.volumePreallocate=true
master.peers=node1:9333,node3:9333,node4:9333
rack=rack1
dataCenter=dc1
volume.max=10000
volume.concurrentUploadLimitMB=999999
filer.concurrentUploadLimitMB=999999
metrics.address=node3:9091
```

**Comment by chrislusf** [comment]
This should be fine. There are already re-tries.

**Comment by Robinysh** [comment]
The `weed filer.copy` stops after a few hundred lines of warnings and errors, and I don't see the failed files succeded with a line of `copied my_file => http://localhost:8888/my_file` afterwards, so I'm not sure if the retries are kicking in.

**Comment by Robinysh** [comment]
You mean for `weed server`? It has already been set with `weed server -options=/etc/xdg/seaweedfs/server.conf -ip=node1`

**Comment by Robinysh** [comment]
I agree, but Im not sure if it’s a configuration error since it has been running successfully for a few hours.

**Comment by chrislusf** [comment]
Very likely there were no recent volume status reported to the master.

**Comment by chrislusf** [comment]
closing since no more updates
