### ISSUE TITLE
seaweedfs-volume: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by LuckyFrost** [chrislusf/seaweedfs#2452]
**Describe the bug**
Volume server died

**System Setup**
- List the command line to start "weed volume"
`/opt/weed -logdir=/var/log/weed volume -ip=ip_addr1 -mserver=ip_addr1:9333,ip_addr2:9333,ip_addr3:9333 -dir=/backup/vweed -dir.idx=/srv/vweed/ -disk=hdd -compactionMBps=40 -dataCenter=DC1 -rack=R1 -max=0`

- OS version
Centos 7
- output of `weed version`
`version 8000GB 2.76 fc9e246592351085b31ce9ad0d6a4790fa54b4f1 linux amd64`

**Additional context**
```
Nov 14 18:03:08 seaweedfs-volume: panic: runtime error: invalid memory address or nil pointer dereference
Nov 14 18:03:08 seaweedfs-volume: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1a08317]
Nov 14 18:03:08 seaweedfs-volume: goroutine 690884 [running]:
Nov 14 18:03:08 seaweedfs-volume: github.com/chrislusf/seaweedfs/weed/server.writeToFile({0x284a5e0, 0xc0006f6cc0}, {0xc000636090, 0x21}, 0x0, 0x0, 0xc0006b1900
)
Nov 14 18:03:08 seaweedfs-volume: /github/workspace/weed/server/volume_grpc_copy.go:229 +0x217
Nov 14 18:03:08 seaweedfs-volume: github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).doCopyFile(0xc000787c00, {0x2887e98, 0xc0005ce4a0}, 0x0, {0x0, 0x0}
, 0x13, 0x0, 0x4b05160e50, {0xc000e840a0, ...}, ...)
Nov 14 18:03:08 seaweedfs-volume: /github/workspace/weed/server/volume_grpc_copy.go:177 +0x305
Nov 14 18:03:08 seaweedfs-volume: github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).VolumeCopy.func1({0x2887e98, 0xc0005ce4a0})
Nov 14 18:03:08 seaweedfs-volume: /github/workspace/weed/server/volume_grpc_copy.go:87 +0x555
Nov 14 18:03:08 seaweedfs-volume: github.com/chrislusf/seaweedfs/weed/operation.WithVolumeServerClient.func1(0xc0004b0e00)
Nov 14 18:03:08 seaweedfs-volume: /github/workspace/weed/operation/grpc_client.go:15 +0x6f
Nov 14 18:03:08 seaweedfs-volume: github.com/chrislusf/seaweedfs/weed/pb.WithCachedGrpcClient(0xc0005c5a38, {0xc003f260d8, 0x13}, {0xc0005c5a28, 0x16, 0x16})
Nov 14 18:03:08 seaweedfs-volume: /github/workspace/weed/pb/grpc_client_server.go:121 +0xfd
Nov 14 18:03:08 seaweedfs-volume: github.com/chrislusf/seaweedfs/weed/operation.WithVolumeServerClient({0xc003f260c0, 0x0}, {0x27e0d20, 0xc0007160d8}, 0xc0005c5
b98)
Nov 14 18:03:08 seaweedfs-volume: /github/workspace/weed/operation/grpc_client.go:13 +0x8a
Nov 14 18:03:08 seaweedfs-volume: github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).VolumeCopy(0xc000787c00, 0xc000315800, {0x284a8b0, 0xc0005ce460})
Nov 14 18:03:08 seaweedfs-volume: /github/workspace/weed/server/volume_grpc_copy.go:48 +0x332
Nov 14 18:03:08 seaweedfs-volume: github.com/chrislusf/seaweedfs/weed/pb/volume_server_pb._VolumeServer_VolumeCopy_Handler({0x231b680, 0xc000787c00}, {0x2838098
, 0xc00004d8c0})
Nov 14 18:03:08 seaweedfs-volume: /github/workspace/weed/pb/volume_server_pb/volume_server.pb.go:8882 +0xd3
Nov 14 18:03:08 seaweedfs-volume: google.golang.org/grpc.(*Server).processStreamingRPC(0xc0008ac8c0, {0x2855f28, 0xc0005b9680}, 0xc000522d80, 0xc000b23050, 0x3b
cec00, 0x0)
Nov 14 18:03:08 seaweedfs-volume: /go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1550 +0xeba
Nov 14 18:03:08 seaweedfs-volume: google.golang.org/grpc.(*Server).handleStream(0xc0008ac8c0, {0x2855f28, 0xc0005b9680}, 0xc000522d80, 0x0)
Nov 14 18:03:08 seaweedfs-volume: /go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1630 +0x9e5
Nov 14 18:03:08 seaweedfs-volume: google.golang.org/grpc.(*Server).serveStreams.func1.2()
Nov 14 18:03:08 seaweedfs-volume: /go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:941 +0x98
Nov 14 18:03:08 seaweedfs-volume: created by google.golang.org/grpc.(*Server).serveStreams.func1
Nov 14 18:03:08 seaweedfs-volume: /go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:939 +0x294
Nov 14 18:03:08 systemd: weed-volume.service: main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by chrislusf** [comment]
thanks for reporting! added a nil check.
