### ISSUE TITLE
add s3 config.json to seaweedfs-compose.yml, but start failed

### ISSUE THREAD

**Issue by stardustman** [chrislusf/seaweedfs#2484]
**Describe the bug**
I add s3 config.json to [seaweedfs-compose.yml](https://github.com/chrislusf/seaweedfs/blob/master/docker/seaweedfs-compose.yml)
```yaml
  s3:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8333:8333
      - 9327:9327
    command: 's3 -filer="filer:8888" -metricsPort=9327 -config="/etc/weed/config.json"'
    depends_on:
      - master
      - volume
      - filer
```
but when use docker-compose to start, the `seaweedfs-s3-1` service start failed. logs are 
```bash
$ docker logs -f --tail 400 seaweedfs-s3-1  
I1201 05:29:17     1 s3.go:158] S3 read filer buckets dir: /buckets
I1201 05:29:17     1 s3.go:165] connected to filer filer:8888 grpc address filer:18888
W1201 05:29:17     1 auth_credentials.go:100] fail to read /etc/weed/config.json : open /etc/weed/config.json: no such file or directory
F1201 05:29:17     1 auth_credentials.go:75] fail to load config file /etc/weed/config.json: fail to read /etc/weed/config.json : open /etc/weed/config.json: no such file or directory
goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0x0)
        /go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0x8a
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x3c00b40, 0x3, 0xc0001e82a0, {0x2dfbb47, 0xc00098fbf8}, 0x2, 0x0)
        /go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:718 +0x3ab
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x7ffd039d4f5f, 0x15, {0x2390584, 0x1f}, {0xc00098fbf8, 0x2, 0x2})
        /go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:656 +0x110
github.com/chrislusf/seaweedfs/weed/glog.Fatalf(...)
        /go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:1149
github.com/chrislusf/seaweedfs/weed/s3api.NewIdentityAccessManagement(0xc0005251a0)
        /go/src/github.com/chrislusf/seaweedfs/weed/s3api/auth_credentials.go:75 +0x118
github.com/chrislusf/seaweedfs/weed/s3api.NewS3ApiServer(0xc00000208d, 0xc0005251a0)
        /go/src/github.com/chrislusf/seaweedfs/weed/s3api/s3api_server.go:35 +0x2a
github.com/chrislusf/seaweedfs/weed/command.(*S3Options).startS3Server(0x3bffc00)
        /go/src/github.com/chrislusf/seaweedfs/weed/command/s3.go:174 +0x550
github.com/chrislusf/seaweedfs/weed/command.runS3(0x3be45d8, {0xc00013a020, 0x6, 0x6})
        /go/src/github.com/chrislusf/seaweedfs/weed/command/s3.go:134 +0x71
main.main()
        /go/src/github.com/chrislusf/seaweedfs/weed/weed.go:78 +0x3a3
I1201 05:30:13     1 s3.go:158] S3 read filer buckets dir: /buckets
I1201 05:30:13     1 s3.go:165] connected to filer filer:8888 grpc address filer:18888
W1201 05:30:13     1 auth_credentials.go:100] fail to read /etc/weed/config.json : open /etc/weed/config.json: no such file or directory
F1201 05:30:13     1 auth_credentials.go:75] fail to load config file /etc/weed/config.json: fail to read /etc/weed/config.json : open /etc/weed/config.json: no such file or directory
goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0x0)
        /go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0x8a
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x3c00b40, 0x3, 0xc0005942a0, {0x2dfbb47, 0xc000a9fbf8}, 0x2, 0x0)
        /go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:718 +0x3ab
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x7ffc0614bf5f, 0x15, {0x2390584, 0x1f}, {0xc000a9fbf8, 0x2, 0x2})
        /go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:656 +0x110
github.com/chrislusf/seaweedfs/weed/glog.Fatalf(...)
        /go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:1149
github.com/chrislusf/seaweedfs/weed/s3api.NewIdentityAccessManagement(0xc000a0b0e0)
        /go/src/github.com/chrislusf/seaweedfs/weed/s3api/auth_credentials.go:75 +0x118
github.com/chrislusf/seaweedfs/weed/s3api.NewS3ApiServer(0xc00000208d, 0xc000a0b0e0)
        /go/src/github.com/chrislusf/seaweedfs/weed/s3api/s3api_server.go:35 +0x2a
github.com/chrislusf/seaweedfs/weed/command.(*S3Options).startS3Server(0x3bffc00)
        /go/src/github.com/chrislusf/seaweedfs/weed/command/s3.go:174 +0x550
github.com/chrislusf/seaweedfs/weed/command.runS3(0x3be45d8, {0xc00013a020, 0x6, 0x6})
        /go/src/github.com/chrislusf/seaweedfs/weed/command/s3.go:134 +0x71
main.main()
        /go/src/github.com/chrislusf/seaweedfs/weed/weed.go:78 +0x3a3

```
`W1201 05:29:17     1 auth_credentials.go:100] fail to read /etc/weed/config.json : open /etc/weed/config.json: no such file or directory`.
I put the config.json in /etc/weed/ 
```bash
stardust@mbp /etc/weed
$ ls
config.json
```
why report this error?

**Expected behavior**
add s3 config.json, then s3 start successfully.

**Comment by kmlebedev** [comment]
You need to mount the config volume in the same way
https://github.com/chrislusf/seaweedfs/blob/3cf84b5fae0634a018f00dec5e4b04a839fe4b0c/docker/compose/local-registry-compose.yml#L26

**Comment by stardustman** [comment]
Thanks a lot.
