### ISSUE TITLE
Weed volume starts failed

### ISSUE THREAD

**Issue by guol-fnst** [chrislusf/seaweedfs#2540]
version:2.77
arch:x86

There are 3 nodes which weed are running on.  But I found on node-2, weed volume couldn't be started. The command is as follows:
`" weed -v=4 volume -dir=/mnt/pool/object_object/data_1/ -port=27002 -ip=20.20.21.11 -max 4294967295 -mserver=20.20.21.11:26000,20.20.21.12:26000,20.20.21.13:26000"`

So I checked the log.Normally  I think when "/mnt/pool/object_object/data_1/test4124_2718.dat" is being vacuumed, the same dat file shouldn't be created.

A possible reason, maybe because  node-2 was shut down when weed on node-2 is vacuuming volume , then I started weed volume with the same commands on node-1. And at the same time I was writing data to weed volume. Which lead to creating another "/mnt/pool/object_object/data_1/test4124_2718.dat" file.

```
I1224 10:08:12  8015 disk_location.go:138] data file /mnt/pool/object_object/data_1/test594_3422.dat, replication=000 v=3 size=46244328 ttl=
I1224 10:08:12  8015 disk_location.go:138] data file /mnt/pool/object_object/data_1/test596_3440.dat, replication=000 v=3 size=45867896 ttl=
I1224 10:08:12  8015 disk_location.go:138] data file /mnt/pool/object_object/data_1/test597_3447.dat, replication=000 v=3 size=45985744 ttl=
I1224 10:08:12  8015 disk_location.go:180] Store started on dir: /mnt/pool/object_object/data_1 with 224 volumes max 4294967295
I1224 10:08:12  8015 disk_location.go:183] Store started on dir: /mnt/pool/object_object/data_1 with 0 ec shards
I1224 10:08:12  8015 volume_grpc_client_to_master.go:50] Volume server start with seed master nodes: [192.168.215.11:26000 192.168.215.12:26000 192.168.215.13:26000]
I1224 10:08:12  8015 volume.go:360] Start Seaweed volume server 30GB 2.75  at :27000
I1224 10:08:12  8015 volume_grpc_client_to_master.go:107] Heartbeat to: 192.168.215.11:26000
I1224 10:22:36  8015 volume_vacuum.go:95] Committing volume 2718 vacuuming...
E1224 10:22:36  8015 volume_grpc_vacuum.go:66] commit volume 2718: rename /mnt/pool/object_object/data_1/test4124_2718.cpd: rename /mnt/pool/object_object/data_1/test4124_2718.cpd /mnt/pool/object_object/data_1/test4124_2718.dat: file exists
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x130b50e]

goroutine 521 [running]:
github.com/chrislusf/seaweedfs/weed/storage.(*Volume).collectStatus(0xc000160fc0)
        /root/seaweedfs_master/weed/storage/volume.go:255 +0x22e
github.com/chrislusf/seaweedfs/weed/storage.(*Volume).ToVolumeInformationMessage(0xc000160fc0)
        /root/seaweedfs_master/weed/storage/volume.go:266 +0x65
github.com/chrislusf/seaweedfs/weed/storage.(*Store).CollectHeartbeat(0xc000194750)
        /root/seaweedfs_master/weed/storage/store.go:227 +0x9d2
github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).doHeartbeat(0xc0001b2e00, {0x7ffdfa784e56, 0x14}, {0x33fbd40, 0xc000cb2158}, 0x12a05f200)
        /root/seaweedfs_master/weed/server/volume_grpc_client_to_master.go:201 +0x1c65
github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).heartbeat(0xc0001b2e00)
        /root/seaweedfs_master/weed/server/volume_grpc_client_to_master.go:67 +0x365
created by github.com/chrislusf/seaweedfs/weed/server.NewVolumeServer
        /root/seaweedfs_master/weed/server/volume_server.go:115 +0xa59
```

**Comment by chrislusf** [comment]
Just stop everything on node-2 and then start the volume server.
