### ISSUE TITLE
[bug:shell] volume.balance -force failed and data seemed lost

### ISSUE THREAD

**Issue by rykinia** [chrislusf/seaweedfs#2816]
I'm using systemd to run volume services.

After executed ` volume.balance -force `, I found that some volumes services is down.

part of `journalctl -xe` logs: 
```
Mar 26 04:29:33 ts97 weed[2055]: I0326 04:29:33  2055 file_util.go:23] Folder /mnt/oss-d10/v10 Permission: -rwxr-xr-x
Mar 26 04:29:33 ts97 weed[2055]: I0326 04:29:33  2055 volume_loading.go:89] readSuperBlock volume 135 version 3
Mar 26 04:29:33 ts97 weed[2055]: I0326 04:29:33  2055 volume_loading.go:126] volumeDataIntegrityChecking failed verifyIndexFileIntegrity /mn
Mar 26 04:29:33 ts97 weed[2055]: I0326 04:29:33  2055 volume_loading.go:131] loading sorted db /mnt/oss-d10/v10/135.sdx error: unexpected fi
Mar 26 04:29:33 ts97 weed[2055]: I0326 04:29:33  2055 volume_loading.go:89] readSuperBlock volume 143 version 3
Mar 26 04:29:33 ts97 weed[2055]: I0326 04:29:33  2055 volume_loading.go:89] readSuperBlock volume 190 version 3
Mar 26 04:29:33 ts97 weed[2055]: I0326 04:29:33  2055 volume_loading.go:141] loading leveldb /mnt/oss-d10/v10/143.ldb
Mar 26 04:29:33 ts97 weed[2055]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 26 04:29:33 ts97 weed[2055]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xe0db94]
Mar 26 04:29:33 ts97 weed[2055]: goroutine 108 [running]:
Mar 26 04:29:33 ts97 weed[2055]: github.com/chrislusf/seaweedfs/weed/storage.(*SortedFileNeedleMap).Close(0xc000edf440)
Mar 26 04:29:33 ts97 weed[2055]: /github/workspace/weed/storage/needle_map_sorted_file.go:97 +0x14
Mar 26 04:29:33 ts97 weed[2055]: github.com/chrislusf/seaweedfs/weed/storage.(*Volume).load.func1()
Mar 26 04:29:33 ts97 weed[2055]: /github/workspace/weed/storage/volume_loading.go:32 +0x42
Mar 26 04:29:33 ts97 weed[2055]: github.com/chrislusf/seaweedfs/weed/storage.(*Volume).load(0xc0000e5b00, 0x1, 0x1, 0x1, 0xa0501d)
Mar 26 04:29:33 ts97 weed[2055]: /github/workspace/weed/storage/volume_loading.go:185 +0x1699
Mar 26 04:29:33 ts97 weed[2055]: github.com/chrislusf/seaweedfs/weed/storage.NewVolume({0x7ffc904e0f6b, 0x10}, {0x7ffc904e0f6b, 0x10}, {0x0,
Mar 26 04:29:33 ts97 weed[2055]: /github/workspace/weed/storage/volume.go:59 +0x1d8
Mar 26 04:29:33 ts97 weed[2055]: github.com/chrislusf/seaweedfs/weed/storage.(*DiskLocation).loadExistingVolume(0xc000d1f760, {0x28e83f0, 0x
Mar 26 04:29:33 ts97 weed[2055]: /github/workspace/weed/storage/disk_location.go:131 +0x369
Mar 26 04:29:33 ts97 weed[2055]: github.com/chrislusf/seaweedfs/weed/storage.(*DiskLocation).concurrentLoadingVolumes.func2()
Mar 26 04:29:33 ts97 weed[2055]: /github/workspace/weed/storage/disk_location.go:171 +0x9a
Mar 26 04:29:33 ts97 weed[2055]: created by github.com/chrislusf/seaweedfs/weed/storage.(*DiskLocation).concurrentLoadingVolumes
Mar 26 04:29:33 ts97 weed[2055]: /github/workspace/weed/storage/disk_location.go:168 +0xc5
```

Now only 2 of 13 volume services are able to start up, is there any way to fix this, or recover the data?

**Comment by kmlebedev** [comment]
@rykinia  version ?

**Comment by kmlebedev** [comment]
@rykinia rykinia

> Now only 2 of 13 volume services are able to start up, is there any way to fix this, or recover the data?

It seems that you can delete or better rename the *.sdx files to another extension

**Comment by rykinia** [comment]
> @rykinia rykinia
> 
> > Now only 2 of 13 volume services are able to start up, is there any way to fix this, or recover the data?
> 
> It seems that you can delete or better rename the *.sdx files to another extension

The version is 2.9.0

I delete the .sdx files and the volume servers can be started, thanks a lot @kmlebedev 

I'm using `volume.move` this time, and this command works fine.

**Comment by rykinia** [comment]
Before I executing `volume.balance --force`, the disks of volume services 1~8 was full, and I saw there was a grpc exception at the end of the command progress. Maybe the issue is related to that.

**Comment by chrislusf** [comment]
not clear what to do for this particular issue. Closing for now.
