### ISSUE TITLE
[Question] Can not deploy seaweedfs via helm chart

### ISSUE THREAD

**Issue by joy717** [chrislusf/seaweedfs#2877]
**Describe the bug**
I've cloned the `main` branch, and deploy seaweedfs with `helm chart`.
But with the default configurations, the filer pod panicked.

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- OS version
- output of `weed version`
- if using filer, show the content of `filer.toml`

**Expected behavior**
Can deploy seaweedfs succeed via helm chart with default configuration.

**Screenshots**

**Additional context**
The filer pods panicked log:
```
failed to initialize store for mysql: connect to YourSWUser:HardCodedPassword@tcp(mysql-db-host:3306)/sw_database?charset=utf8&interpolateParams=true error:dial tcp: lookup mysql-db-host on 10.233.0.3:53: no such host
goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0x0)
        /go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0x8a
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x401af60, 0x3, 0xc00029bdc0, {0x312b477, 0xc0003518e8}, 0x2, 0x0)
        /go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:718 +0x3ab
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x24f0c12, 0x5, {0x254eddb, 0x26}, {0xc0003518e8, 0x2, 0x2})
        /go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:656 +0x110
github.com/chrislusf/seaweedfs/weed/glog.Fatalf(...)
        /go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:1149
github.com/chrislusf/seaweedfs/weed/filer.(*Filer).LoadConfiguration(0xc000125740, 0x4011a60)
        /go/src/github.com/chrislusf/seaweedfs/weed/filer/configuration.go:25 +0xab4
github.com/chrislusf/seaweedfs/weed/server.NewFilerServer(0xc00039e380, 0xc00039e380, 0xc0007fab00)
        /go/src/github.com/chrislusf/seaweedfs/weed/server/filer_server.go:151 +0x985
github.com/chrislusf/seaweedfs/weed/command.(*FilerOptions).startFiler(0x401b0e0)
        /go/src/github.com/chrislusf/seaweedfs/weed/command/filer.go:200 +0x2f6
github.com/chrislusf/seaweedfs/weed/command.runFiler(0x3ffc7b8, {0xc0000ccad0, 0x9, 0x9})
        /go/src/github.com/chrislusf/seaweedfs/weed/command/filer.go:176 +0x3da
main.main()
        /go/src/github.com/chrislusf/seaweedfs/weed/weed.go:81 +0x3a3
```

**Comment by chrislusf** [comment]
lookup mysql-db-host on 10.233.0.3:53: no such host

**Comment by joy717** [comment]
> lookup mysql-db-host on 10.233.0.3:53: no such host

yes, I know there is no mysql on this host.
should I set up a mysql by myself?

With default configuration, but missing a mysql, 
Is this wired?

**Comment by chrislusf** [comment]
the helm chart you are using is expecting a mysql.

**Comment by joy717** [comment]
Hi, chrislusf

I installed a mysql. 
But filer still not work, here is the log:
```
F0407 07:14:29     1 filer.go:126] read filer.store.id= : kv get: Error 1146: Table 'sw_database.filemeta' doesn't exist
goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0x0)
        /go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0x8a
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x401af60, 0x3, 0xc0001524d0, {0x312b603, 0xc0007af668}, 0x3, 0x0)
        /go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:718 +0x3ab
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x0, 0x2abc2f0, {0x2504742, 0xf}, {0xc0007af668, 0x3, 0x3})
        /go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:656 +0x110
github.com/chrislusf/seaweedfs/weed/glog.Fatalf(...)
        /go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:1149
github.com/chrislusf/seaweedfs/weed/filer.(*Filer).setOrLoadFilerStoreSignature(0xc0006d8000, {0x2b0bf40, 0xc0005f9020})
        /go/src/github.com/chrislusf/seaweedfs/weed/filer/filer.go:126 +0x1e5
github.com/chrislusf/seaweedfs/weed/filer.(*Filer).SetStore(0xc0006d8000, {0x2b0bf40, 0xc0005f9020})
        /go/src/github.com/chrislusf/seaweedfs/weed/filer/filer.go:108 +0x21e
github.com/chrislusf/seaweedfs/weed/filer.(*Filer).LoadConfiguration(0xc0006d8000, 0x4011a60)
        /go/src/github.com/chrislusf/seaweedfs/weed/filer/configuration.go:27 +0xad1
github.com/chrislusf/seaweedfs/weed/server.NewFilerServer(0xc00065e380, 0xc00065e380, 0xc00043c370)
        /go/src/github.com/chrislusf/seaweedfs/weed/server/filer_server.go:151 +0x985
github.com/chrislusf/seaweedfs/weed/command.(*FilerOptions).startFiler(0x401b0e0)
        /go/src/github.com/chrislusf/seaweedfs/weed/command/filer.go:200 +0x2f6
github.com/chrislusf/seaweedfs/weed/command.runFiler(0x3ffc7b8, {0xc00004c860, 0x9, 0x9})
        /go/src/github.com/chrislusf/seaweedfs/weed/command/filer.go:176 +0x3da
main.main()
        /go/src/github.com/chrislusf/seaweedfs/weed/weed.go:81 +0x3a3
```

Should create db structure by myself?
Where can I find it?

**Comment by chrislusf** [comment]
check the `weed scaffold -config=filer` output, the table DDL is inside.

**Comment by chrislusf** [comment]
please List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".

**Comment by joy717** [comment]
> please List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".

I deployed seaweedfs using helm chart.

chart url:

https://github.com/chrislusf/seaweedfs/tree/master/k8s/helm_charts2

**Comment by joy717** [comment]
Here are processes related with seaweedfs. (which started via docker container)

```
[root@k8s-1 kubernetes]# ps aux | grep seaweedfs
root      1201  0.1  0.4 769152 77484 ?        Ssl  08:06   0:14 /usr/bin/weed -logdir=/logs -v=4 filer -port=8888 -metricsPort 9327 -dirListLimit=100000 -defaultReplicaPlacement=000 -ip=10.233.95.212 -s3 -s3.port=8333 -master=seaweedfs-master-0.seaweedfs-master:9333
root      3024  0.0  0.1 717116 16984 ?        Ssl  10:49   0:00 /csi-node-driver-registrar --v=5 --csi-address=/csi/csi.sock --kubelet-registration-path=/var/lib/kubelet/plugins/seaweedfs-csi-driver/csi.sock
root      3061  0.0  0.1 723652 23732 ?        Ssl  10:49   0:00 /seaweedfs-csi-driver --endpoint=unix:///csi/csi.sock --filer=10.233.95.212:8888 --nodeid=k8s-1
```

```
[root@k8s-2 images]# ps aux | grep seaweedfs
root      1221  0.0  0.3 769152 62384 ?        Ssl  08:06   0:09 /usr/bin/weed -logdir=/logs -v=4 master -port=9333 -mdir=/data -ip.bind=0.0.0.0 -defaultReplication=000 -volumeSizeLimitMB=30000 -metrics.intervalSeconds=15 -ip=seaweedfs-master-0.seaweedfs-master -peers=seaweedfs-master-0.seaweedfs-master:9333
root      1941  0.0  0.3 769152 61652 ?        Ssl  08:06   0:05 /usr/bin/weed -logdir=/logs -v=4 volume -port=8080 -metricsPort 9327 -dir=/data -max=0 -ip.bind=0.0.0.0 -readMode=proxy -minFreeSpacePercent=7 -ip=seaweedfs-volume-0.seaweedfs-volume -compactionMBps=50 -mserver=seaweedfs-master-0.seaweedfs-master:9333
root     13134  0.0  0.1 723792 23404 ?        Ssl  10:49   0:00 /seaweedfs-csi-driver --endpoint=unix:///var/lib/csi/sockets/pluginproxy/csi.sock --filer=10.233.95.212:8888 --nodeid=k8s-2
root     13234  0.0  0.1 717308 17684 ?        Ssl  10:49   0:00 /csi-node-driver-registrar --v=5 --csi-address=/csi/csi.sock --kubelet-registration-path=/var/lib/kubelet/plugins/seaweedfs-csi-driver/csi.sock
root     13271  0.0  0.1 723344 21292 ?        Ssl  10:49   0:00 /seaweedfs-csi-driver --endpoint=unix:///csi/csi.sock --filer=10.233.95.212:8888 --nodeid=k8s-2
```

```
[root@k8s-3 images]# ps aux | grep seaweedfs
root      3374  0.0  0.0 717052 16360 ?        Ssl  10:49   0:00 /csi-node-driver-registrar --v=5 --csi-address=/csi/csi.sock --kubelet-registration-path=/var/lib/kubelet/plugins/seaweedfs-csi-driver/csi.sock
root      3424  0.0  0.1 723792 21016 ?        Ssl  10:49   0:00 /seaweedfs-csi-driver --endpoint=unix:///csi/csi.sock --filer=10.233.95.212:8888 --nodeid=k8s-3
```

**Comment by chrislusf** [comment]
Very likely you need to reduce the volume size `-volumeSizeLimitMB=30000` in order to have more volumes.

**Comment by joy717** [comment]
> Very likely you need to reduce the volume size `-volumeSizeLimitMB=30000` in order to have more volumes.

Thx chrislusf,
That's it!!  It works now.

So If the `volumeSizeLimitMB=30000`, I should allocate 8 times of this size?  like 240000Mi?

Where can I reduce `8`? Any docs?
Thank you in advance.
