### ISSUE TITLE
[BUG] - weed volume won't bring up and stick in a crash loop 

### ISSUE THREAD

**Issue by kaaaq** [chrislusf/seaweedfs#2922]
Hi @chrislusf ,
I've upgraded my cluster from 1.93 to 1.98 but in some volume servers(not all of them) that disks are approximately full, weed volume uses 100% CPU and is stuck in a crash loop and exits many times and tries to bring up again (I don't know what's the exact reason but some volumes that have data works well), When I downgrade broken volume servers to 1.93 they worked correctly,
Server log:

```

Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]: I0416 14:59:48  4821 disk_location.go:140] data file /srv/node/sdf/InfoFile_32.dat, replication=010 v=3 size=35594588008 ttl=
Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]: I0416 14:59:48  4821 disk_location.go:182] Store started on dir: /srv/node/sdf with 63 volumes max 0
Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]: I0416 14:59:48  4821 disk_location.go:185] Store started on dir: /srv/node/sdf with 0 ec shards
Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]: I0416 14:59:48  4821 metrics.go:193] volumeServer server sends metrics to weed-monitoring:9091 every 15 seconds
Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]: I0416 14:59:48  4821 volume_grpc_client_to_master.go:50] Volume server start with seed master nodes: [weed-master-1:9333 weed-master-2:9333 weed-master-3:9333]
Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]: F0416 14:59:48  4821 volume.go:322] failed to listen on grpc port 18084: listen tcp 172.30.102.104:18084: bind: cannot assign requested address
Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]: goroutine 1 [running]:
Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]: github.com/chrislusf/seaweedfs/weed/glog.stacks(0x0)
Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]:         /github/workspace/weed/glog/glog.go:767 +0x8a
Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]: github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x42b50c0, 0x3, 0xc0008d43f0, {0x34ba92e?, 0xc0008ed688?}, 0x2?, 0x0)
Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]:         /github/workspace/weed/glog/glog.go:718 +0x3ab
Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]: github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x46a4?, 0x1f?, {0x283877f, 0x24}, {0xc0008ed688, 0x2, 0x2})
Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]:         /github/workspace/weed/glog/glog.go:656 +0x110
Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]: github.com/chrislusf/seaweedfs/weed/glog.Fatalf(...)
Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]:         /github/workspace/weed/glog/glog.go:1149
Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]: github.com/chrislusf/seaweedfs/weed/command.VolumeServerOptions.startGrpcService({0xc00013e480, 0xc00013e498, 0xc00013e4a0, {0xc000784780, 0x1, 0x1}, {0xc00078a9a0, 0x1, 0x1}, 0xc0003a6df0, ...}, ...)
Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]:         /github/workspace/weed/command/volume.go:322 +0x109
Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]: github.com/chrislusf/seaweedfs/weed/command.VolumeServerOptions.startVolumeServer({0xc00013e480, 0xc00013e498, 0xc00013e4a0, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0xc0003a6df0, ...}, ...)
Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]:         /github/workspace/weed/command/volume.go:249 +0xee5
Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]: github.com/chrislusf/seaweedfs/weed/command.runVolume(0x4295678?, {0xc00013a020?, 0x9?, 0x9?})
Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]:         /github/workspace/weed/command/volume.go:131 +0x19f
Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]: main.main()
Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]:         /github/workspace/weed/weed.go:81 +0x383
Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]: I0416 14:59:48  4821 volume_grpc_client_to_master.go:107] Heartbeat to: weed-master-1:9333
Apr 16 14:59:48 weed-volume-003 systemd[1]: weedfs_volume_sdf.service: Main process exited, code=exited, status=255/n/a
Apr 16 14:59:48 weed-volume-003 systemd[1]: weedfs_volume_sdf.service: Unit entered failed state.
Apr 16 14:59:48 weed-volume-003 systemd[1]: weedfs_volume_sdf.service: Failed with result 'exit-code'.

```

This picture shows the server CPU status is 100% () when I upgrade to the weed version 1.98 and the server is starting:
The yellow color defines user(weed) CPU usage:

![image](https://user-images.githubusercontent.com/43205944/163672211-fd6e3ca6-fbd7-4fd6-91fe-d16faccb15eb.png)

![image](https://user-images.githubusercontent.com/43205944/163672192-993b86b3-f6ea-4778-be4d-9f1f4bdb7565.png)

**Comment by chrislusf** [comment]
the error is "Apr 16 14:59:48 weed-volume-003 seaweedfs-sdf-volume[4821]: F0416 14:59:48  4821 volume.go:322] failed to listen on grpc port 18084: listen tcp 172.30.102.104:18084: bind: cannot assign requested address"

Need to kill the process running on port 18084

**Comment by kaaaq** [comment]
@chrislusf 

> Need to kill the process running on port 18084

I restart the server but weed couldn't listen on the port
When I check the result of the command "ss -ntlp" it shows there is no process listen on 18084 
Why couldn't Weed bind to this port?

**Comment by chrislusf** [comment]
Maybe try to use a different port

**Comment by kaaaq** [comment]
> Maybe try to use a different port

I change it but the same problem, the problem is not port 
I'm using each disk as a service and they try to bind on different ports

**Comment by chrislusf** [comment]
Sorry, "cannot assign requested address" seems the ip address problem, not a port problem.

Google showed many results for this. But I do not know the correct answer.

**Comment by kaaaq** [comment]
> Google showed many results for this. But I do not know the correct answer.

There is a problem with version 1.98 cause when I downgrade weed to 2.93 it worked correctly

**Comment by kaaaq** [comment]
[solved](https://github.com/chrislusf/seaweedfs/issues/3076)
