### ISSUE TITLE
master option `-port.grpc` is not picked up by HashiCorp raft

### ISSUE THREAD

**Issue by nahsi** [chrislusf/seaweedfs#2958]
I'm trying to run seaweedfs version 2.99 in Nomad and with HashiCorp raft enabled.

When grpc port is different from default (specified with the option `-port.grpc`) master a not able to start.
I suspect that this option somehow is not picked up when using HashiCorp raft.

Snippet from Nomad job:
```hcl
    network {
      port "http" {
        to     = 9333
        static = 9333
      }
      port "grpc" {
        to     = 9334
        static = 9334
      }
      port "metrics" {}
```
```hcl
      ports = [
          "http",
          "grpc",
          "metrics",
        ]

      args = [
          "-v=${var.log_level}",
          "master",
          "-mdir=/data",
          "-peers=10.1.10.10:9333,10.1.10.20:9333,10.1.10.1:9333",

          "-ip=${NOMAD_IP_http}",
          "-ip.bind=0.0.0.0",
          "-port=${NOMAD_PORT_http}",
          "-port.grpc=${NOMAD_PORT_grpc}",
          "-metricsPort=${NOMAD_PORT_metrics}",

          "-raftHashicorp",
          "-resumeState",
        ]
      }

```

Log:
```
I0423 13:46:34     1 config.go:46] Reading : Config File "security" Not Found in "[/data /.seaweedfs /usr/local/etc/seaweedfs /etc/seaweedfs]"
I0423 13:46:34     1 config.go:46] Reading : Config File "master" Not Found in "[/data /.seaweedfs /usr/local/etc/seaweedfs /etc/seaweedfs]"
I0423 13:46:34     1 file_util.go:23] Folder /data Permission: -rwx------
I0423 13:46:34     1 master.go:255] current: 10.1.10.20:9333 peers:10.1.10.10:9333,10.1.10.20:9333,10.1.10.1:9333
I0423 13:46:34     1 master_server.go:327] [master.sequencer.type] : []
I0423 13:46:34     1 master_server.go:131] Volume Size Limit is 30000 MB
I0423 13:46:34     1 master.go:147] Start Seaweed Master 30GB 2.99 8e98d732 at 0.0.0.0:9333
2022-04-23T13:46:34.123Z [INFO]  raft: initial configuration: index=0 servers=[]
I0423 13:46:34     1 raft_hashicorp.go:155] Bootstrapping idx: -1 sleep: -354.387457ms new cluster: {Servers:[{Suffrage:Voter ID:10.1.10.10:9333 Address:10.1.10.10:19333} {Suffrage:Voter ID:10.1.10.20:9333 Address:10.1.10.20:19333} {Suffrage:Voter ID:10.1.10.1:9333 Address:10.1.10.1:19333}]}
2022-04-23T13:46:34.127Z [INFO]  raft: entering follower state: follower="Node at 10.1.10.20:9333.9334 [Follower]" leader-address= leader-id=
F0423 13:46:34     1 master.go:169] NewHashicorpRaftServer: raft.Raft.BootstrapCluster: node is not a voter
goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0x0)
	/go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0x8a
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x456d620, 0x3, 0xc0004afc70, {0x36e9645?, 0xc0007bfc58?}, 0x1?, 0x0)
	/go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:718 +0x3ab
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0xc0007bfd40?, 0x5?, {0x29da4b9, 0x1a}, {0xc0007bfc58, 0x1, 0x1})
	/go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:656 +0x110
github.com/chrislusf/seaweedfs/weed/glog.Fatalf(...)
	/go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:1149
github.com/chrislusf/seaweedfs/weed/command.startMaster({0xc0003a53a8, 0xc0003a53c0, 0xc0005733e0, 0xc000573400, 0xc000573410, 0xc000573430, 0xc0003a5420, 0xc0003a5435, 0xc000573440, 0xc0003a5440, ...}, ...)
	/go/src/github.com/chrislusf/seaweedfs/weed/command/master.go:169 +0x545
github.com/chrislusf/seaweedfs/weed/command.runMaster(0x454cb98?, {0xc00004c0f0?, 0x9?, 0x9?})
	/go/src/github.com/chrislusf/seaweedfs/weed/command/master.go:121 +0x290
main.main()
	/go/src/github.com/chrislusf/seaweedfs/weed/weed.go:81 +0x383
```

Full nomad job:
```hcl
variables {
  log_level = "4" # log level [0|1|2|3|4]
  versions = {
    seaweedfs = "2.99"
  }
}

job "seaweedfs" {
  datacenters = [
    "syria",
  ]
  namespace = "infra"

  group "seaweedfs-master" {
    count = 3

    update {
      max_parallel = 1
      stagger      = "2m"
    }

    migrate {
      min_healthy_time = "2m"
    }

    network {
      port "http" {
        to     = 9333
        static = 9333
      }
      port "grpc" {
        to     = 9334
        static = 9334
      }
      port "metrics" {}
    }

    volume "master" {
      type   = "host"
      source = "seaweedfs-master"
    }

    task "seaweedfs-master" {
      driver = "docker"
      user   = "nobody"

      kill_signal  = "SIGINT"
      kill_timeout = "90s"

      volume_mount {
        volume      = "master"
        destination = "/data"
      }

      config {
        image = "chrislusf/seaweedfs:${var.versions.seaweedfs}"

        ports = [
          "http",
          "grpc",
          "metrics",
        ]

        args = [
          "-v=${var.log_level}",
          "master",
          "-mdir=/data",
          "-peers=10.1.10.10:9333,10.1.10.20:9333,10.1.10.1:9333",

          "-ip=${NOMAD_IP_http}",
          "-ip.bind=0.0.0.0",
          "-port=${NOMAD_PORT_http}",
          "-port.grpc=${NOMAD_PORT_grpc}",
          "-metricsPort=${NOMAD_PORT_metrics}",

          "-raftHashicorp",
          "-resumeState",
        ]
      }

      resources {
        cpu    = 100
        memory = 128
      }

      service {
        name = "seaweedfs"
        port = "metrics"

        tags = [
          "master",
          "master-${meta.seaweedfs_index}",
        ]

        meta {
          alloc_id  = NOMAD_ALLOC_ID
          component = "master"
        }

        check {
          name     = "SeaweedFS master"
          type     = "http"
          protocol = "http"
          port     = "http"
          path     = "/stats/heath"
          interval = "20s"
          timeout  = "1s"

          initial_status = "passing"
        }
      }
    }
  }

  group "seaweedfs-volume" {
    count = 2

    update {
      max_parallel = 1
      stagger      = "2m"
    }

    migrate {
      min_healthy_time = "2m"
    }

    network {
      port "http" {
        to     = 9433
        static = 9433
      }
      port "grpc" {
        to     = 9434
        static = 9434
      }
      port "metrics" {}
    }

    volume "ssd" {
      type   = "host"
      source = "seaweedfs-ssd"
    }

    task "seaweedfs-volume" {
      driver = "docker"
      user   = "nobody"

      kill_signal  = "SIGINT"
      kill_timeout = "90s"

      volume_mount {
        volume      = "ssd"
        destination = "/data/ssd"
      }

      config {
        image = "chrislusf/seaweedfs:${var.versions.seaweedfs}"

        ports = [
          "http",
          "grpc",
          "metrics",
        ]

        args = [
          "-v=${var.log_level}",
          "volume",
          "-dir=/data/ssd",
          "-volume.disk=ssd",

          "-dataCenter=${node.datacenter}",
          "-rack=${node.unique.name}",
          "-publicUrl=${NOMAD_ADDR_http}",

          "-mserver=master.seaweedfs.service.consul:9333",

          "-ip=${NOMAD_IP_http}",
          "-ip.bind=0.0.0.0",
          "-volume.port=${NOMAD_PORT_http}",
          "-volume.port.grpc=${NOMAD_PORT_grpc}",
          "-metricsPort=${NOMAD_PORT_metrics}",
        ]
      }

      resources {
        cpu        = 512
        memory     = 2048
        memory_max = 4096
      }

      service {
        name = "seaweedfs"
        port = "metrics"

        tags = [
          "volume",
        ]

        meta {
          alloc_id  = NOMAD_ALLOC_ID
          component = "volume"
        }

        check {
          name     = "SeaweedFS volume"
          type     = "http"
          protocol = "http"
          port     = "http"
          path     = "/stats/heath"
          interval = "20s"
          timeout  = "1s"
        }
      }
    }
  }
}
```

**Comment by chrislusf** [comment]
use `-peers=10.1.10.10:9333.9334,10.1.10.20:9333.9334,10.1.10.1:9333.9334`

**Comment by kmlebedev** [comment]
> use `-peers=10.1.10.10:9333.9334,10.1.10.20:9333.9334,10.1.10.1:9333.9334` because you configured grpc port to 9334

It seems that this can be written in a help
