### ISSUE TITLE
cluster.raft.ps in weed shell results in SIGSEGV in master process

### ISSUE THREAD

**Issue by dailypixel** [chrislusf/seaweedfs#2987]
If you use weed shell and execute cluster.raft.ps the leader master fails with SIGSEGV:
~~~
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x184c72c]

goroutine 119 [running]:
github.com/hashicorp/raft.(*Raft).getLatestConfiguration(...)
	/go/pkg/mod/github.com/hashicorp/raft@v1.3.7/raft.go:1937
github.com/hashicorp/raft.(*Raft).GetConfiguration(0x0)
	/go/pkg/mod/github.com/hashicorp/raft@v1.3.7/api.go:864 +0x6c
github.com/chrislusf/seaweedfs/weed/server.(*MasterServer).RaftListClusterServers(0xc0004bfdd0, {0xc0007f1140?, 0x52f986?}, 0x0?)
	/github/workspace/weed/server/master_grpc_server_raft.go:14 +0x5a
github.com/chrislusf/seaweedfs/weed/pb/master_pb._Seaweed_RaftListClusterServers_Handler({0x21d5100?, 0xc0004bfdd0}, {0x27d22e8, 0xc0007f1110}, 0xc0005ec240, 0x0)
	/github/workspace/weed/pb/master_pb/master_grpc.pb.go:642 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00053bdc0, {0x27dd298, 0xc0006024e0}, 0xc000404d80, 0xc000945bf0, 0x3880478, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc00053bdc0, {0x27dd298, 0xc0006024e0}, 0xc000404d80, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:920 +0x28a
~~~

To reproduce:
~~~
$ weed master
$ weed shell
> cluster.raft.ps
~~~

Same happens if real cluster is active (3 masters started).

System Setup
~~~
$ ./weed version
version 30GB 3.00 b1dac20c704cf5322c6c516e5f064eb00701aec9 linux amd64
$ uname -a
Linux phoebe 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
~~~

Full output from weed master:
~~~
I0429 16:12:52  9683 file_util.go:23] Folder /tmp Permission: -rwxrwxrwx
I0429 16:12:52  9683 master.go:255] current: 192.168.1.14:9333 peers:
I0429 16:12:52  9683 master_server.go:131] Volume Size Limit is 30000 MB
I0429 16:12:52  9683 master.go:147] Start Seaweed Master 30GB 3.00 b1dac20c704cf5322c6c516e5f064eb00701aec9 at 192.168.1.14:9333
I0429 16:12:52  9683 raft_server.go:119] Starting RaftServer with 192.168.1.14:9333
I0429 16:12:52  9683 raft_server.go:168] current cluster leader: 
I0429 16:13:10  9683 master.go:196] Start Seaweed Master 30GB 3.00 b1dac20c704cf5322c6c516e5f064eb00701aec9 grpc server at 192.168.1.14:19333
I0429 16:13:11  9683 masterclient.go:85] No existing leader found!
I0429 16:13:11  9683 raft_server.go:190] Initializing new cluster
I0429 16:13:11  9683 master_server.go:176] leader change event:  => 192.168.1.14:9333
I0429 16:13:11  9683 master_server.go:179] [ 192.168.1.14:9333 ] 192.168.1.14:9333 becomes leader.
I0429 16:13:15  9683 master_grpc_server.go:281] + client master@192.168.1.14:9333
I0429 16:13:15  9683 masterclient.go:176] + master 192.168.1.14:9333 leader:false
I0429 16:13:17  9683 master_grpc_server.go:281] + client adminShell@
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x184c72c]

goroutine 61 [running]:
github.com/hashicorp/raft.(*Raft).getLatestConfiguration(...)
	/go/pkg/mod/github.com/hashicorp/raft@v1.3.7/raft.go:1937
github.com/hashicorp/raft.(*Raft).GetConfiguration(0x0)
	/go/pkg/mod/github.com/hashicorp/raft@v1.3.7/api.go:864 +0x6c
github.com/chrislusf/seaweedfs/weed/server.(*MasterServer).RaftListClusterServers(0xc0004c4360, {0xc00088dbf0?, 0x52f986?}, 0x0?)
	/github/workspace/weed/server/master_grpc_server_raft.go:14 +0x5a
github.com/chrislusf/seaweedfs/weed/pb/master_pb._Seaweed_RaftListClusterServers_Handler({0x21d5100?, 0xc0004c4360}, {0x27d22e8, 0xc00088dbc0}, 0xc0008b6540, 0x0)
	/github/workspace/weed/pb/master_pb/master_grpc.pb.go:642 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000870fc0, {0x27dd298, 0xc0007024e0}, 0xc0008ae240, 0xc00088c900, 0x3880478, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc000870fc0, {0x27dd298, 0xc0007024e0}, 0xc0008ae240, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:920 +0x28a
~~~

weed shell:
~~~
$ ./weed shell 
master: localhost:9333 
> cluster.raft.ps
error: raft list cluster: rpc error: code = Unavailable desc = error reading from server: EOF
> I0429 16:13:26  9727 masterclient.go:133] adminShell masterClient failed to receive from localhost:9333: rpc error: code = Unavailable desc = error reading from server: EOF
~~~

**Comment by dailypixel** [comment]
same with master tree
~~~
$ ./weed master
I0429 16:53:07 21837 file_util.go:23] Folder /tmp Permission: -rwxrwxrwx
I0429 16:53:07 21837 master.go:255] current: 192.168.1.14:9333 peers:
I0429 16:53:07 21837 master_server.go:131] Volume Size Limit is 30000 MB
I0429 16:53:07 21837 master.go:147] Start Seaweed Master 30GB 3.00  at 192.168.1.14:9333
I0429 16:53:07 21837 raft_server.go:119] Starting RaftServer with 192.168.1.14:9333
I0429 16:53:07 21837 raft_server.go:168] current cluster leader: 
I0429 16:53:25 21837 master.go:196] Start Seaweed Master 30GB 3.00  grpc server at 192.168.1.14:19333
I0429 16:53:26 21837 masterclient.go:85] No existing leader found!
I0429 16:53:26 21837 raft_server.go:190] Initializing new cluster
I0429 16:53:26 21837 master_server.go:176] leader change event:  => 192.168.1.14:9333
I0429 16:53:26 21837 master_server.go:179] [ 192.168.1.14:9333 ] 192.168.1.14:9333 becomes leader.
I0429 16:53:29 21837 master_grpc_server.go:281] + client adminShell@
I0429 16:53:30 21837 master_grpc_server.go:281] + client master@192.168.1.14:9333
I0429 16:53:30 21837 masterclient.go:176] + master 192.168.1.14:9333 leader:false
I0429 16:53:30 21837 master_grpc_server.go:281] + client adminShell@
I0429 16:53:30 21837 master_grpc_server.go:281] + client adminShell@
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1851cec]

goroutine 151 [running]:
github.com/hashicorp/raft.(*Raft).getLatestConfiguration(...)
	/home/mike/go/pkg/mod/github.com/hashicorp/raft@v1.3.8/raft.go:1937
github.com/hashicorp/raft.(*Raft).GetConfiguration(0x0)
	/home/mike/go/pkg/mod/github.com/hashicorp/raft@v1.3.8/api.go:864 +0x6c
github.com/chrislusf/seaweedfs/weed/server.(*MasterServer).RaftListClusterServers(0xc000a42510, {0xc000a53e60?, 0x5317a6?}, 0x0?)
	/home/mike/Onebox/Projects/weed/seaweedfs-master/weed/server/master_grpc_server_raft.go:14 +0x5a
github.com/chrislusf/seaweedfs/weed/pb/master_pb._Seaweed_RaftListClusterServers_Handler({0x21dca80?, 0xc000a42510}, {0x27da488, 0xc000a53e30}, 0xc000b32000, 0x0)
	/home/mike/Onebox/Projects/weed/seaweedfs-master/weed/pb/master_pb/master_grpc.pb.go:642 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000a64000, {0x27e5438, 0xc000602ea0}, 0xc000a7c240, 0xc000a528d0, 0x38966d8, 0x0)
	/home/mike/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc000a64000, {0x27e5438, 0xc000602ea0}, 0xc000a7c240, 0x0)
	/home/mike/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/home/mike/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/mike/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:920 +0x28a

$ ./weed version
version 30GB 3.00  linux amd64
~~~

**Comment by kmlebedev** [comment]
@dailypixel  raft commands only work with the `-raftHashicorp` option
