### ISSUE TITLE
Segmentation fault running master 3.01 with default config

### ISSUE THREAD

**Issue by remram44** [chrislusf/seaweedfs#3000]
**Describe the bug**
Running `weed master` with the configuration from `weed scaffold` causes a segmentation fault.

Running `weed master` without a configuration file still works.

```
/tmp$ mkdir defaultmaster
/tmp$ cd defaultmaster
/tmp/defaultmaster$ weed scaffold -config=master -output=.
/tmp/defaultmaster$ weed master
I0502 11:06:24 00127 file_util.go:23] Folder /tmp Permission: -rwxrwxrwx
I0502 11:06:24 00127 master.go:255] current: 192.168.1.210:9333 peers:
I0502 11:06:24 00127 master_server.go:131] Volume Size Limit is 30000 MB
I0502 11:06:24 00127 master_server.go:257] adminScripts:   lock
  ec.encode -fullPercent=95 -quietFor=1h
  ec.rebuild -force
  ec.balance -force
  volume.deleteEmpty -quietFor=24h -force
  volume.balance -force
  volume.fix.replication
  s3.clean.uploads -timeAgo=24h
  unlock
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18ea923]

goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/shell.NewCommandEnv(0xc000668600)
        /github/workspace/weed/shell/commands.go:50 +0xa3
github.com/chrislusf/seaweedfs/weed/server.(*MasterServer).startAdminScripts(0xc000632360)
        /github/workspace/weed/server/master_server.go:276 +0x3f1
github.com/chrislusf/seaweedfs/weed/server.NewMasterServer(0xc00093fdb0?, 0xc00081c100, 0xc000799cb0)
        /github/workspace/weed/server/master_server.go:165 +0xfa5
github.com/chrislusf/seaweedfs/weed/command.startMaster({0xc00030e058, 0xc00030e070, 0xc00009d230, 0xc00009d250, 0xc00009d260, 0xc00009d280, 0xc00030e158, 0xc00030e16d, 0xc00009d290, 0xc00030e178, ...}, ...)
        /github/workspace/weed/command/master.go:145 +0x237
github.com/chrislusf/seaweedfs/weed/command.runMaster(0x387ed38?, {0xc00013a010?, 0x0?, 0x0?})
        /github/workspace/weed/command/master.go:121 +0x290
main.main()
        /github/workspace/weed/weed.go:81 +0x383
```

**System Setup**
- Ubuntu 20.04 amd64, where seaweedfs 3.00 worked fine
- `version 30GB 3.01 73961e24d8b311b938dfb692f93e172866813487 linux amd64`

**Expected behavior**
Default configuration should work (and invalid config probably shouldn't segfault.

**Additional context**
<details><summary>The config file, `master.toml`</summary>

```
# Put this file to one of the location, with descending priority
#    ./master.toml
#    $HOME/.seaweedfs/master.toml
#    /etc/seaweedfs/master.toml
# this file is read by master

[master.maintenance]
# periodically run these scripts are the same as running them from 'weed shell'
scripts = """
  lock
  ec.encode -fullPercent=95 -quietFor=1h
  ec.rebuild -force
  ec.balance -force
  volume.deleteEmpty -quietFor=24h -force
  volume.balance -force
  volume.fix.replication
  s3.clean.uploads -timeAgo=24h
  unlock
"""
sleep_minutes = 17          # sleep minutes between each script execution


[master.sequencer]
type = "raft"     # Choose [raft|snowflake] type for storing the file id sequence
# when sequencer.type = snowflake, the snowflake id must be different from other masters
sequencer_snowflake_id = 0     # any number between 1~1023


# configurations for tiered cloud storage
# old volumes are transparently moved to cloud for cost efficiency
[storage.backend]
[storage.backend.s3.default]
enabled = false
aws_access_key_id = ""         # if empty, loads from the shared credentials file (~/.aws/credentials).
aws_secret_access_key = ""     # if empty, loads from the shared credentials file (~/.aws/credentials).
region = "us-east-2"
bucket = "your_bucket_name"    # an existing bucket
endpoint = ""
storage_class = "STANDARD_IA"

# create this number of logical volumes if no more writable volumes
# count_x means how many copies of data.
# e.g.:
#   000 has only one copy, copy_1
#   010 and 001 has two copies, copy_2
#   011 has only 3 copies, copy_3
[master.volume_growth]
copy_1 = 7                # create 1 x 7 = 7 actual volumes
copy_2 = 6                # create 2 x 6 = 12 actual volumes
copy_3 = 3                # create 3 x 3 = 9 actual volumes
copy_other = 1            # create n x 1 = n actual volumes

# configuration flags for replication
[master.replication]
# any replication counts should be considered minimums. If you specify 010 and
# have 3 different racks, that's still considered writable. Writes will still
# try to replicate to all available volumes. You should only use this option
# if you are doing your own replication or periodic sync of volumes.
treat_replication_as_minimums = false
```

</details>

**Comment by remram44** [comment]
Removing the `[master.maintenance] scripts=` section allows the master to start.

**Comment by grepler** [comment]
Confirmed, I see this same behaviour and removing `[master.maintenance] scripts=` allows it to start.
