### ISSUE TITLE
weed mount - volume.fix.replication - mount point down

### ISSUE THREAD

**Issue by shapememory** [chrislusf/seaweedfs#3039]
Everytihng works find master, filer and volume. 

After the execution of volume.fix.replication the mount is down.

weed version 3.02 / go version go1.18.1 linux/amd64
ubuntu: 18.04 lts 

mount command: sudo -u vmail /usr/local/bin/weed mount -nonempty -filer=10.1.0.3:8888 -dir=/var/vmail -filer.path=/home/seaweed/filer -cacheDir=/var/vmailcache -cacheCapacityMB 4096 -allowOthers &> /var/log/seaweedmount.log

vmail is the owner of /home/seaweed 
and of the storage mountpoint /storageboxes/001box 

It's a cluster of 3 machine. 

seaweedmount.log 

This is SeaweedFS version 8000GB 3.02 a4ca3ed1f0c2bcde1d36bb48f81dedc3e1924679 linux amd64
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1bfd93d]

goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/mount.(*InodeToPath).MovePath(0xc0005e83c0, {0xc000365700, 0x38}, {0xc000365740, 0x33})
        /github/workspace/weed/mount/inode_to_path.go:168 +0x15d
github.com/chrislusf/seaweedfs/weed/mount.(*WFS).handleRenameResponse(0xc000522900, {0x27d6440, 0xc000106e80}, 0xc00031d220)
        /github/workspace/weed/mount/weedfs_rename.go:236 +0x4ba
github.com/chrislusf/seaweedfs/weed/mount.(*WFS).Rename.func1({0x27e8818, 0xc00035f580})
        /github/workspace/weed/mount/weedfs_rename.go:199 +0x3fc
github.com/chrislusf/seaweedfs/weed/mount.(*WFS).WithFilerClient.func1.1(0xc000727180)
        /github/workspace/weed/mount/wfs_filer_client.go:25 +0x6f
github.com/chrislusf/seaweedfs/weed/pb.WithGrpcClient(0xc5?, 0xc0006935a0, {0xc00027aa90, 0xe}, {0xc000693590?, 0xc000693568?, 0x8?})
        /github/workspace/weed/pb/grpc_client_server.go:145 +0x17f
github.com/chrislusf/seaweedfs/weed/mount.(*WFS).WithFilerClient.func1()
        /github/workspace/weed/mount/wfs_filer_client.go:23 +0x14d
github.com/chrislusf/seaweedfs/weed/util.Retry({0x2221a29, 0xa}, 0xc0006936b0)
        /github/workspace/weed/util/retry.go:16 +0xb1
github.com/chrislusf/seaweedfs/weed/mount.(*WFS).WithFilerClient(0xc0002e70c0?, 0x33?, 0xc0005cb5c0?)
        /github/workspace/weed/mount/wfs_filer_client.go:16 +0x66
github.com/chrislusf/seaweedfs/weed/mount.(*WFS).Rename(0xc000522900, 0x18?, 0xc0002e6ec0, {0xc00027aa30, 0x10}, {0xc00027aa05, 0xb})
        /github/workspace/weed/mount/weedfs_rename.go:166 +0x4cd
github.com/hanwen/go-fuse/v2/fuse.doRename(0xc000714420, 0xc000604000)
        /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.0/fuse/opcode.go:418 +0xf1
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc000714420, 0xc000604000)
        /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.0/fuse/server.go:483 +0x1f3
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc000714420, 0x20?)
        /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.0/fuse/server.go:456 +0x108
github.com/hanwen/go-fuse/v2/fuse.(*Server).Serve(0xc000714420)
        /go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.0/fuse/server.go:378 +0x35
github.com/chrislusf/seaweedfs/weed/command.RunMount(0x389eb40, 0x12)
        /github/workspace/weed/command/mount_std.go:260 +0x1416
github.com/chrislusf/seaweedfs/weed/command.runMount(0x3881ef8?, {0xc000128090?, 0x0, 0x8?})
        /github/workspace/weed/command/mount_std.go:55 +0x165
main.main()
        /github/workspace/weed/weed.go:81 +0x383

**Comment by shapememory** [comment]
I checked everything several times and I even restarted from zero. it's not working. in my opinion it's not stable.

**Comment by chrislusf** [comment]
the trace showed the failure is when renaming on the `weed mount`. Not related to `volume.fix.replication`.

**Comment by shapememory** [comment]
Well. I just mounted it and led it run without doing any operation at all on the mount.

It just crashes. Dovecot is running of course. So seems like it has problems with this.

May 11, 2022 21:07:54 Chris Lu ***@***.***>:

**Comment by chrislusf** [comment]
it seems doing a rename when it crashes.

**Comment by shapememory** [comment]
I will make a test tomorrow morning. I will stop dovecot completely and see what happens then.

**Comment by chrislusf** [comment]
@shapememory any updates?

**Comment by shapememory** [comment]
Hello, 

 �

I think it had something to do with the fact that I was using NAS mounted directories for the storage part. 

 �

I will retest seaweedfs on SSD storage to cluster a /var/www directory. 


 �
