### ISSUE TITLE
Filer cache lead to OOM

### ISSUE THREAD

**Issue by geekboood** [chrislusf/seaweedfs#3193]
When using fuse mount and reading large files, sometimes OOM happened

```
fatal error: runtime: out of memory

runtime stack:
runtime.throw({0x22a902f?, 0x4e2800000?})
	/usr/local/go/src/runtime/panic.go:992 +0x71
runtime.sysMap(0xc013800000, 0xc0005d7e90?, 0xc0005d7ef8?)
	/usr/local/go/src/runtime/mem_linux.go:189 +0x11b
runtime.(*mheap).grow(0x3964040, 0x271300?)
	/usr/local/go/src/runtime/mheap.go:1404 +0x225
runtime.(*mheap).allocSpan(0x3964040, 0x271300, 0x0, 0x1)
	/usr/local/go/src/runtime/mheap.go:1170 +0x171
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:912 +0x65
runtime.systemstack()
	/usr/local/go/src/runtime/asm_amd64.s:469 +0x49

goroutine 3089 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:436 fp=0xc007385d40 sp=0xc007385d38 pc=0x469dc0
runtime.(*mheap).alloc(0x4e2600000?, 0x271300?, 0x80?)
	/usr/local/go/src/runtime/mheap.go:906 +0x65 fp=0xc007385d88 sp=0xc007385d40 pc=0x428de5
runtime.(*mcache).allocLarge(0x469e0e?, 0x4e2600000, 0x1)
	/usr/local/go/src/runtime/mcache.go:213 +0x85 fp=0xc007385dd8 sp=0xc007385d88 pc=0x417105
runtime.mallocgc(0x4e2600000, 0x1e0e800, 0x1)
	/usr/local/go/src/runtime/malloc.go:1096 +0x5a5 fp=0xc007385e50 sp=0xc007385dd8 pc=0x40d505
runtime.makeslice(0x1e0e580?, 0xc0053b2f50?, 0xf91920?)
	/usr/local/go/src/runtime/slice.go:103 +0x52 fp=0xc007385e78 sp=0xc007385e50 pc=0x44ffd2
github.com/chrislusf/seaweedfs/weed/util/mem.Allocate(0xc000836960?)
	/github/workspace/weed/util/mem/slot_pool.go:54 +0x125 fp=0xc007385ef0 sp=0xc007385e78 pc=0x9fa085
github.com/chrislusf/seaweedfs/weed/filer.(*SingleChunkCacher).startCaching(0xc0006d0bb0)
	/github/workspace/weed/filer/reader_cache.go:158 +0x1cd fp=0xc007385fc8 sp=0xc007385ef0 pc=0xf93c8d
github.com/chrislusf/seaweedfs/weed/filer.(*ReaderCache).ReadChunkAt.func2()
	/github/workspace/weed/filer/reader_cache.go:107 +0x26 fp=0xc007385fe0 sp=0xc007385fc8 pc=0xf93666
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc007385fe8 sp=0xc007385fe0 pc=0x46bea1
created by github.com/chrislusf/seaweedfs/weed/filer.(*ReaderCache).ReadChunkAt
	/github/workspace/weed/filer/reader_cache.go:107 +0x436
```

I have looked into the code, the cache allocate part seems fine. Maybe it is some corrupted filer chunk size? Could you add some option to disable the filer cache, or add if statement to avoid allocate too large cache?

**Comment by chrislusf** [comment]
How large is the file and how much memory there is? And is it random read or sequential read?

**Comment by geekboood** [comment]
The file is larger than 100GB, and it is random read. And fuse mount memory usage is steady (around 300MB) during the read process but have a sudden peak then OOM. 
Also I see the cache is based on chunks, so the file size and read pattern should be inconsequential?

**Comment by chrislusf** [comment]
It is related to the read process. Seems the "rc.downloaders" has too many downloaders working at the same time.

Is it possible to reproduce the the read process?

**Comment by geekboood** [comment]
OK, it is my bad...
I looked into the file meta, it has a 20GB large chunk, which caused the OOM. Maybe this was introduced during my initial test. 
However, could we add some limitation to the cache mechanism? Like some size filter?

**Comment by chrislusf** [comment]
can you share the metadata?

**Comment by geekboood** [comment]
Yeah, the manifest data shows that the needle is a manifest... This is problematic. 

```
I0619 15:27:25 30531 filehandle_read.go:73]   read /file1 [108827508736,108829605888) from chunk 370,018b84d0aac13847
I0619 15:27:25 30531 filehandle_read.go:73]   read /file1 [108829605888,108831703040) from chunk 370,018b84d113cdb915
I0619 15:27:25 30531 filehandle_read.go:73]   read /file1 [108831703040,108833800192) from chunk 371,018b84d22145ba2e
I0619 15:27:25 30531 filehandle_read.go:73]   read /file1 [108833800192,108835798910) from chunk 371,018b84d335ed6fce
I0619 15:27:25 30531 reader_cache.go:159] start caching 20975714304 371,018b84d48774b58c
fatal error: runtime: out of memory
```


```
file /file1 file_size:108835798910 mtime:1639929988 file_mode:384 gid:100 crtime:1639928469
  chunk: 1 file_id:"370,018b7d6d8656b863" offset:104861794304 size:2097152 mtime:1639929952412497186 e_tag:"ic+t9eETspHyEPKEjFLbOw==" fid:{volume_id:370 file_key:25918829 cookie:2253830243} 370,18b7d6d8656b863
  chunk: 2 file_id:"370,018b7d703a4e3fce" offset:104868085760 size:2097152 mtime:1639929952444293599 e_tag:"MNNBtGNzTvuNbV4LoP3K7Q==" fid:{volume_id:370 file_key:25918832 cookie:978206670} 370,18b7d703a4e3fce
  chunk: 3 file_id:"370,018b7d6e69149774" offset:104863891456 size:2097152 mtime:1639929952420785377 e_tag:"oZHVZmdyoTdrW0ZCuz9Lnw==" fid:{volume_id:370 file_key:25918830 cookie:1762957172} 370,18b7d6e69149774
  chunk: 4 file_id:"371,018b7d6f8c4e325b" offset:104865988608 size:2097152 mtime:1639929952426495681 e_tag:"MVeWziK1HrBDBvE+5treaw==" fid:{volume_id:371 file_key:25918831 cookie:2353934939} 371,18b7d6f8c4e325b

a lot of lines

  chunk: 1896 file_id:"371,018b84d22145ba2e" offset:108831703040 size:2097152 mtime:1639929984809607228 e_tag:"w1ZNbJFxNoRj7kuyPK1VVw==" fid:{volume_id:371 file_key:25920722 cookie:558217774} 371,18b84d22145ba2e
  chunk: 1897 file_id:"370,018b84d0aac13847" offset:108827508736 size:2097152 mtime:1639929984768356244 e_tag:"UHoh++Ny+jMh6XyK5X9vEQ==" fid:{volume_id:370 file_key:25920720 cookie:2864789575} 370,18b84d0aac13847
  chunk: 1898 file_id:"371,018b84d48774b58c" size:20975714304 mtime:1639929988477066194 e_tag:"50qiSL66eCN7h8MN69wHIQ==" fid:{volume_id:371 file_key:25920724 cookie:2272572812} is_chunk_manifest:true 371,18b84d48774b58c
  chunk: 1899 file_id:"370,018b84d5d24c13ae" offset:20961034240 size:20986200064 mtime:1639929988491572302 e_tag:"AoofenGnLivLRLikp3FTwg==" fid:{volume_id:370 file_key:25920725 cookie:3528201134} is_chunk_manifest:true 370,18b84d5d24c13ae
  chunk: 1900 file_id:"370,018b84d620ff7f7d" offset:41936748544 size:20984102912 mtime:1639929988505451436 e_tag:"La8mq3wQ3vkNvwviSsCuHw==" fid:{volume_id:370 file_key:25920726 cookie:553615229} is_chunk_manifest:true 370,18b84d620ff7f7d
  chunk: 1901 file_id:"371,018b84d72db02d48" offset:62904074240 size:20988297216 mtime:1639929988518579788 e_tag:"qlWzGTImQySmUVXJrf5t6Q==" fid:{volume_id:371 file_key:25920727 cookie:766520648} is_chunk_manifest:true 371,18b84d72db02d48
  chunk: 1902 file_id:"371,018b84d88b2776d7" offset:83869302784 size:20988297216 mtime:1639929988532860063 e_tag:"6bPM4JnYqNOgtF0NVzz+7w==" fid:{volume_id:371 file_key:25920728 cookie:2334619351} is_chunk_manifest:true 371,18b84d88b2776d7

```

**Comment by geekboood** [comment]
OK, I figured it out..

In filer/filechunk_manifest.go, when reading sub manifest failed, the function should return dataChunks instead of chunks, which contains manifest chunks. 

```
func ResolveChunkManifest(lookupFileIdFn wdclient.LookupFileIdFunctionType, chunks []*filer_pb.FileChunk, startOffset, stopOffset int64) (dataChunks, manifestChunks []*filer_pb.FileChunk, manifestResolveErr error) {
	// TODO maybe parallel this
	for _, chunk := range chunks {

		if max(chunk.Offset, startOffset) >= min(chunk.Offset+int64(chunk.Size), stopOffset) {
			continue
		}

		if !chunk.IsChunkManifest {
			dataChunks = append(dataChunks, chunk)
			continue
		}

		resolvedChunks, err := ResolveOneChunkManifest(lookupFileIdFn, chunk)
		if err != nil {
			return dataChunks, nil, err
		}

		manifestChunks = append(manifestChunks, chunk)
		// recursive
		subDataChunks, subManifestChunks, subErr := ResolveChunkManifest(lookupFileIdFn, resolvedChunks, startOffset, stopOffset)
		if subErr != nil {
			return dataChunks, nil, subErr
		}
		dataChunks = append(dataChunks, subDataChunks...)
		manifestChunks = append(manifestChunks, subManifestChunks...)
	}
	return
}
```

**Comment by geekboood** [comment]
#3195 https://github.com/chrislusf/seaweedfs/pull/3195
