### ISSUE TITLE
panic: assertion failed: leader.elected.at.same.term.0

### ISSUE THREAD

**Issue by shichanglin5** [chrislusf/seaweedfs#3236]
**Describe the bug**
I tested locally, started three master nodes, and sometimes the following panic log appears and program exit, which seems to be from raft：

`panic: assertion failed: leader.elected.at.same.term.0

goroutine 88 [running]:
github.com/chrislusf/raft._assert(...)
        /Users/lhhdz/wd/projects/go/pkg/mod/github.com/chrislusf/raft@v1.0.9/util.go:60
github.com/chrislusf/raft.(*server).processAppendEntriesRequest(0x14000932240, 0x1400087c6e0)
        /Users/lhhdz/wd/projects/go/pkg/mod/github.com/chrislusf/raft@v1.0.9/server.go:983 +0x74c
github.com/chrislusf/raft.(*server).leaderLoop(0x14000932240)
        /Users/lhhdz/wd/projects/go/pkg/mod/github.com/chrislusf/raft@v1.0.9/server.go:884 +0x324
github.com/chrislusf/raft.(*server).loop(0x14000932240)
        /Users/lhhdz/wd/projects/go/pkg/mod/github.com/chrislusf/raft@v1.0.9/server.go:609 +0x144
github.com/chrislusf/raft.(*server).Start.func1()
        /Users/lhhdz/wd/projects/go/pkg/mod/github.com/chrislusf/raft@v1.0.9/server.go:470 +0x58
created by github.com/chrislusf/raft.(*server).Start
        /Users/lhhdz/wd/projects/go/pkg/mod/github.com/chrislusf/raft@v1.0.9/server.go:468 +0x1a8
`

**Comment by chrislusf** [comment]
how to reproduce?

**Comment by shichanglin5** [comment]
> how to reproduce?

Start three node masters locally at the same time, I guess this is caused by the raft mechanism, it may not be a bug

**Comment by kmlebedev** [comment]
his is a double, I decided to switch to hashicorp raft https://github.com/chrislusf/seaweedfs/issues/2833
```
weed master -raftHashicorp
```
Since this is not the only problem
https://github.com/chrislusf/seaweedfs/issues/2804

**Comment by shichanglin5** [comment]
thx, i replaced it with raftHashicorp
