### ISSUE TITLE
Problem with uploading (Java library)

### ISSUE THREAD

**Issue by maxcom1** [chrislusf/seaweedfs#3292]
Hi, I have set up a seaweedfs server locally according to the instructions and I'm trying to use the client for Java to upload a file, however there is an error.

**Describe the bug**
When I run the attached below code, I get this error:
```
Copying 'testfile.txt' file..
Exception in thread "main" java.io.IOException: java.util.concurrent.ExecutionException: org.apache.http.client.ClientProtocolException: URI does not specify a valid host name: http:///7,0f709db88e
	at seaweedfs.client.SeaweedOutputStream.flushWrittenBytesToService(SeaweedOutputStream.java:300)
	at seaweedfs.client.SeaweedOutputStream.flushInternal(SeaweedOutputStream.java:286)
	at seaweedfs.client.SeaweedOutputStream.close(SeaweedOutputStream.java:192)
	at pl.maxcom1.weedtest.Main.main(Main.java:25)
Caused by: java.util.concurrent.ExecutionException: org.apache.http.client.ClientProtocolException: URI does not specify a valid host name: http:///7,0f709db88e
Caused by: java.util.concurrent.ExecutionException: org.apache.http.client.ClientProtocolException: URI does not specify a valid host name: http:///7,0f709db88e

	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at seaweedfs.client.SeaweedOutputStream.flushWrittenBytesToService(SeaweedOutputStream.java:298)
	... 3 more
Caused by: org.apache.http.client.ClientProtocolException: URI does not specify a valid host name: http:///7,0f709db88e
	at org.apache.http.impl.client.CloseableHttpClient.determineTarget(CloseableHttpClient.java:95)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
Caused by: org.apache.http.client.ClientProtocolException: URI does not specify a valid host name: http:///7,0f709db88e

	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at seaweedfs.client.SeaweedWrite.multipartUpload(SeaweedWrite.java:123)
	at seaweedfs.client.SeaweedWrite.writeChunk(SeaweedWrite.java:65)
	at seaweedfs.client.SeaweedWrite.writeData(SeaweedWrite.java:31)
	at seaweedfs.client.SeaweedOutputStream.lambda$submitWriteBufferToService$0(SeaweedOutputStream.java:229)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

Whole code:
```
package pl.maxcom1.weedtest;

import seaweedfs.client.FilerClient;
import seaweedfs.client.SeaweedOutputStream;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;

public class Main {

    public static void main(String[] args) throws IOException {
        FilerClient filerClient = new FilerClient("localhost", 18888);

        File localFile = new File("testfile.txt");

        filerClient.mkdirs("/testmkdir", 0);

        SeaweedOutputStream outputStream = new SeaweedOutputStream(filerClient, "/minifiles/" + localFile.getName());
        long startTime = System.currentTimeMillis();
        System.out.println("Copying 'testfile.txt' file..");
        Files.copy(localFile.toPath(), outputStream);

        outputStream.flush();
        outputStream.close();
        System.out.println("Sent file in " + (System.currentTimeMillis() - startTime) / 1000f + "s.");
    }
    
}
```

Directory is created successfully (line 17)

**System Setup**
- Start command: `.\weed.exe server -dir=storage/data -s3`
- Gradle dependency: `implementation 'com.github.chrislusf:seaweedfs-client:1.6.4'` (from java client description)
- OS version: `Windows 10.0.19044`
- output of `weed version`: `version 30GB 3.14 3c79c770562ef4f7c0d4e57a88f616eb3671b9cd windows amd64`

**Expected behavior**
I want to upload a file to the server to the given path (/minifiles/)

**Screenshots**
![image](https://user-images.githubusercontent.com/46265094/178145794-64edf730-7e31-4353-a316-cc2c9c337cfc.png)
![image](https://user-images.githubusercontent.com/46265094/178145856-61dfcd00-7f1c-432c-99c4-a12e0a14312a.png)

**Comment by maxcom1** [comment]
Successfully solved, the version in the documentation was out of date.

**Comment by zcw5116** [comment]
> Successfully solved, the version in the documentation was out of date.

How solved， I meet the same question?
Thank you.
