### ISSUE TITLE
[BUG] hudi hdfs write error

### ISSUE THREAD

**Issue by waywtdcc** [chrislusf/seaweedfs#3294]
Replace seaweedfs with hdfs interface, write with hudi flink, and report an error

**log**
```
Caused by: java.io.IOException: java.util.concurrent.ExecutionException: shaded.org.apache.http.client.ClientProtocolException: URI does not specify a valid host name: http:///285,40d610859cab
	at seaweedfs.client.SeaweedOutputStream.flushWrittenBytesToService(SeaweedOutputStream.java:300)
	at seaweedfs.client.SeaweedOutputStream.flushInternal(SeaweedOutputStream.java:286)
	at seaweedfs.client.SeaweedOutputStream.close(SeaweedOutputStream.java:192)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:101)
	at org.apache.hudi.common.table.HoodieTableConfig.create(HoodieTableConfig.java:438)
	at org.apache.hudi.common.table.HoodieTableMetaClient.initTableAndGetMetaClient(HoodieTableMetaClient.java:441)
	at org.apache.hudi.common.table.HoodieTableMetaClient$PropertyBuilder.initTable(HoodieTableMetaClient.java:1044)
	at org.apache.hudi.util.StreamerUtil.initTableIfNotExists(StreamerUtil.java:272)
	at org.apache.hudi.table.catalog.HoodieCatalog.createTable(HoodieCatalog.java:279)
	... 30 more
Caused by: java.util.concurrent.ExecutionException: shaded.org.apache.http.client.ClientProtocolException: URI does not specify a valid host name: http:///285,40d610859cab
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at seaweedfs.client.SeaweedOutputStream.flushWrittenBytesToService(SeaweedOutputStream.java:298)
	... 39 more
Caused by: shaded.org.apache.http.client.ClientProtocolException: URI does not specify a valid host name: http:///285,40d610859cab
	at shaded.org.apache.http.impl.client.CloseableHttpClient.determineTarget(CloseableHttpClient.java:94)
	at shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at seaweedfs.client.SeaweedWrite.multipartUpload(SeaweedWrite.java:149)
	at seaweedfs.client.SeaweedWrite.writeChunk(SeaweedWrite.java:91)
	at seaweedfs.client.SeaweedWrite.writeData(SeaweedWrite.java:36)
	at seaweedfs.client.SeaweedOutputStream.lambda$submitWriteBufferToService$0(SeaweedOutputStream.java:229)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**config**

```
        configuration.setString("flink.hadoop.fs.seaweedfs.impl", "seaweed.hdfs.SeaweedFileSystem");
        configuration.setString("flink.hadoop.fs.defaultFS", "seaweedfs://10.2.5.3:9283");
        configuration.setString("flink.hadoop.fs.AbstractFileSystem.seaweedfs.impl", "seaweed.hdfs.SeaweedAbstractFileSystem");
        configuration.setString("flink.hadoop.fs.seaweed.buffer.size", "4194304");
        configuration.setString("flink.hadoop.fs.seaweed.volume.server.access", "direct");
```

**code**
```

set parallelism.default = 1;
CREATE CATALOG myhudi WITH(
    'type' = 'hudi',
    'default-database' = 'test',
    'catalog.path' = 'seaweedfs://10.2.5.3:9283/buckets/bk001/hudi_test'
);

use catalog myhudi;
show databases;
use test;

show tables;

drop table if exists test_catalog_c4;
create table test_catalog_c4
(id int,
name string,
primary key(id) NOT ENFORCED  )
with('connector'= 'hudi', 'table.type' = 'COPY_ON_WRITE');

show create table test_catalog_c4;

insert into test_catalog_c4
values
(1, '12312');

select *
from test.test_catalog_c4;

```

**Comment by waywtdcc** [comment]
@chrislusf  hello

**Comment by chrislusf** [comment]
What is the SeaweedFS Java client library version?

**Comment by waywtdcc** [comment]
This one has created a part of the directory. But an error is reported midway, and there is no data.
![image](https://user-images.githubusercontent.com/59957056/178181722-55874f2a-3769-4478-b139-1f86d3840ccd.png)

**Comment by chrislusf** [comment]
what is the output of `volume.list` in `weed shell`?

**Comment by waywtdcc** [comment]
config error,seaweed.volume.server.access should be filerProxy

**Comment by waywtdcc** [comment]
Does seaweedfs support file append?
