### ISSUE TITLE
panic when execute "weed export"

### ISSUE THREAD

**Issue by rockiee281** [chrislusf/seaweedfs#566]
When execute "weed export -dir /home/q/data  -volumeId 51 -collection my_collection", got error like bellow:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x89c1fa]

goroutine 1 [running]:
os.(*File).Name(...)
	/home/travis/.gimme/versions/go/src/os/file.go:47
github.com/chrislusf/seaweedfs/weed/storage.(*Volume).readSuperBlock(0xc4201fe000, 0xc4201f2210, 0x1)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/storage/volume_super_block.go:64 +0x7a
github.com/chrislusf/seaweedfs/weed/storage.(*Volume).load(0xc4201fe000, 0xc4201f0000, 0x0, 0x0, 0xb424a0, 0xc4201e87d0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/storage/volume_loading.go:50 +0x164c
github.com/chrislusf/seaweedfs/weed/storage.loadVolumeWithoutIndex(0x7fff796435c4, 0xc, 0x7fff796435ea, 0x9, 0x33, 0x0, 0xc4201e87e0, 0x7fd048720500, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/storage/volume_loading.go:15 +0xdc
github.com/chrislusf/seaweedfs/weed/storage.ScanVolumeFile(0x7fff796435c4, 0xc, 0x7fff796435ea, 0x9, 0xc400000033, 0x0, 0xc4201fdce0, 0xc4201b5b01, 0xc4201fdd68, 0xc4201eaf70, ...)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/storage/volume_read_write.go:185 +0x82
github.com/chrislusf/seaweedfs/weed/command.runExport(0x10c1480, 0xc4200100f0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/export.go:128 +0x6ff
main.main()
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/weed.go:64 +0x3f6
```

**Comment by rockiee281** [comment]
Got the reason, I need to execute this cmd with sudo, cause weed run as sudo
