### ISSUE TITLE
volumeServer进程异常停止

### ISSUE THREAD

**Issue by linxiaobai** [chrislusf/seaweedfs#597]
volumeServer报了个一个异常后就停止了，异常栈我看不懂。。能帮忙看看吗。
版本0.70 正式版。
```
fatal error: concurrent map read and map write

goroutine 17100465 [running]:
runtime.throw(0xde9dc0, 0x21)
        /home/chris/apps/go/src/runtime/panic.go:530 +0x90 fp=0xc82013d280 sp=0xc82013d268
runtime.mapaccess2_fast64(0xaa7a40, 0xc831dbcc00, 0x1829cc6, 0x453146, 0xc820026a0c)

 runtime.throw(0xde9dc0, 0x21)
        /home/chris/apps/go/src/runtime/panic.go:530 +0x90 fp=0xc82013d280 sp=0xc82013d268
runtime.mapaccess2_fast64(0xaa7a40, 0xc831dbcc00, 0x1829cc6, 0x453146, 0xc820026a0c)
        /home/chris/apps/go/src/runtime/hashmap_fast.go:157 +0x5a fp=0xc82013d2a0 sp=0xc82013d280
github.com/chrislusf/seaweedfs/go/storage.(*CompactSection).Get(0xc83c209fc0, 0x1829cc6, 0x2, 0x0)
        /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/storage/compact_map.go:82 +0x59 fp=0xc82013d2d8 sp=0xc82013d2a0
github.com/chrislusf/seaweedfs/go/storage.(*CompactMap).Get(0xc83e561260, 0x1829cc6, 0xea0b59, 0xc800000000)
        /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/storage/compact_map.go:150 +0x91 fp=0xc82013d318 sp=0xc82013d2d8
github.com/chrislusf/seaweedfs/go/storage.(*NeedleMap).Get(0xc83e561260, 0x1829cc6, 0x0, 0x42eef7)
        /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/storage/needle_map_memory.go:92 +0x32 fp=0xc82013d340 sp=0xc82013d318
github.com/chrislusf/seaweedfs/go/storage.(*Volume).readNeedle(0xc83655a780, 0xc82921b0e0, 0xc83655a780, 0x0, 0x0)
        /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/storage/volume.go:285 +0x76 fp=0xc82013d408 sp=0xc82013d340
github.com/chrislusf/seaweedfs/go/storage.(*Store).ReadVolumeNeedle(0xc82000a300, 0xc800000027, 0xc82921b0e0, 0x4, 0x0, 0x0)
        /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/storage/store.go:378 +0x67 fp=0xc82013d488 sp=0xc82013d408
github.com/chrislusf/seaweedfs/go/weed/weed_server.(*VolumeServer).GetOrHeadHandler(0xc8200781c0, 0x7f458315d030, 0xc836190dd0, 0xc835c06ee0)
        /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/volume_server_handlers_read.go:67 +0x1740 fp=0xc82013da88 sp=0xc82013d488
github.com/chrislusf/seaweedfs/go/weed/weed_server.(*VolumeServer).privateStoreHandler(0xc8200781c0, 0x7f458315d030, 0xc836190dd0, 0xc835c06ee0)
        /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/volume_server_handlers.go:28 +0xf6 fp=0xc82013dad0 sp=0xc82013da88
github.com/chrislusf/seaweedfs/go/weed/weed_server.(*VolumeServer).(github.com/chrislusf/seaweedfs/go/weed/weed_server.privateStoreHandler)-fm(0x7f458315d030, 0xc836190dd0, 0xc835c06ee0)
        /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/weed_server/volume_server.go:64 +0x3e fp=0xc82013daf8 sp=0xc82013dad0
net/http.HandlerFunc.ServeHTTP(0xc820010960, 0x7f458315d030, 0xc836190dd0, 0xc835c06ee0)
        /home/chris/apps/go/src/net/http/server.go:1618 +0x3a fp=0xc82013db18 sp=0xc82013daf8
net/http.(*ServeMux).ServeHTTP(0xc82000f410, 0x7f458315d030, 0xc836190dd0, 0xc835c06ee0)

 net/http.HandlerFunc.ServeHTTP(0xc820010960, 0x7f458315d030, 0xc836190dd0, 0xc835c06ee0)
        /home/chris/apps/go/src/net/http/server.go:1618 +0x3a fp=0xc82013db18 sp=0xc82013daf8
net/http.(*ServeMux).ServeHTTP(0xc82000f410, 0x7f458315d030, 0xc836190dd0, 0xc835c06ee0)
        /home/chris/apps/go/src/net/http/server.go:1910 +0x17d fp=0xc82013db70 sp=0xc82013db18
net/http.serverHandler.ServeHTTP(0xc8200aa100, 0x7f458315d030, 0xc836190dd0, 0xc835c06ee0)
        /home/chris/apps/go/src/net/http/server.go:2081 +0x19e fp=0xc82013dbd0 sp=0xc82013db70
net/http.(*conn).serve(0xc847eb2180)
        /home/chris/apps/go/src/net/http/server.go:1472 +0xf2e fp=0xc82013df98 sp=0xc82013dbd0
runtime.goexit()
        /home/chris/apps/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82013dfa0 sp=0xc82013df98
created by net/http.(*Server).Serve
        /home/chris/apps/go/src/net/http/server.go:2137 +0x44e

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7f458315cae8, 0x72, 0x0)
        /home/chris/apps/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8200781b0, 0x72, 0x0, 0x0)
        /home/chris/apps/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200781b0, 0x0, 0x0)
        /home/chris/apps/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820078150, 0x0, 0x7f458315cc08, 0xc828a83e80)
        /home/chris/apps/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc8200bc090, 0x1, 0x0, 0x0)
        /home/chris/apps/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc8200bc090, 0x0, 0x0, 0x0, 0x0)
        /home/chris/apps/go/src/net/tcpsock_posix.go:264 +0x3d
github.com/chrislusf/seaweedfs/go/util.(*Listener).Accept(0xc8200b01c0, 0x0, 0x0, 0x0, 0x0)
        /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/util/net_timeout.go:19 +0x5f
net/http.(*Server).Serve(0xc8200aa100, 0x7f458315cba8, 0xc8200b01c0, 0x0, 0x0)
        /home/chris/apps/go/src/net/http/server.go:2117 +0x129
net/http.Serve(0x7f458315cba8, 0xc8200b01c0, 0x7f458315cbe0, 0xc82000f410, 0x0, 0x0)
        /home/chris/apps/go/src/net/http/server.go:1976 +0x8e
main.runVolume(0x115a080, 0xc82000a0f0, 0x0, 0x0, 0x0)
        /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/volume.go:161 +0x1530
main.main()
        /home/chris/dev/workspace/home/gopath/src/github.com/chrislusf/seaweedfs/go/weed/weed.go:78 +0x68d
```

**Comment by chrislusf** [comment]
Need to use the latest version.

**Comment by linxiaobai** [comment]
具体原因能解释一下吗？为何要升到最新版。因为我看了新版的代码，通信改用grpc了，如果要升级的话，需要整个集群全部停止重启了，我们目前不太好停旧的服务。

**Comment by linxiaobai** [comment]
https://github.com/chrislusf/seaweedfs/commit/36f96332238a37cb659bb3ff27d82febb1b22c91
是并发问题吗？在这个代码中加锁修复的？
