### ISSUE TITLE
Can not start filer: structure needs cleaning

### ISSUE THREAD

**Issue by ijunaid8989** [chrislusf/seaweedfs#600]
```
I1121 16:48:14   894 volume.go:110] loading index file /storage/1050.idx readonly false
x�$ebb7555c19�*�Q>P61/1�-�$f36137886eA99���qYaA�*����M�$c92c9ed6c8!A9��
                                                    cf60�r9�'>P$296c6971012 
��$cda7ae6b49��yq-1�7ef1�- 0f115b03d0c0�                                (
(5A,d79bf8fba},�(Ѧ 9303cc401!9�+1�M94f2d633b4ba0*�!��\9�2c��( has LxM�(f50c64043102�
line �
(Q�$fafaa17733(9���M�8cbdf9acad8e29��B!a6a814c5A�9� has ��	(50	(8e1dced48e33P�(4	(8dee4cf1aaa4(��
                                                               :��C�� �>�40_01_000.jpg.�149,0200af344a1bad12_(r�!
�8d636dfa5e9239��Q!fcac9e0482*b1>( 54ea6456e�9�dbc54.*��-!c�3a35092��
(Q� f279adea6x!y4�-#1�$d776a53c19�69���c99b2bad55Py,�(3fac91989�|1�-�0d4a004ccce=��
(P$727352f0ba6�!>�27c2b21a� has 9�p
P1$ce9b36aa8a!�2y*î:j3a4944f5A99��(�&$cc1ee5de67a�9��(�v$cb734c9d2aa�9��
)� f5c76ea71:2�(f5a21Y95b88869�_P1I 56a7cc8a0��9�WP�t��%$e1ebbe0bf3�9��P��(ed8e38fc8ab2�	P
               9��>� d987065acA9�k(��
                                       d6a0�
P$f1930cc3a5A   9�c>(6�                     09!9��1�� 04c7d9eb8A�y*�
P1$ce9b36aa8a!�2y*î:j3a4944f5A99��(�&$cc1ee5de67a�9��(�v$cb734c9d2aa�9��
                       $bffcec86fa�1_2��>0 0dc7104a9a�9�t��%$e1ebbe0bf3�9��P��(ed8e38fc8ab2�!
line �
Px8dcf5c5c90a229�>�$132d0a55c42*XQ1q 5ab97bbe4��9��B�b594fa29P9��> ff2623101A�9�6(mR e3ce8d910x9�}>� 788ef5724!i��WPy1I f53d29328��9�� has �q adcc01f3d!q�^�1qMb(cec83f590052^R
                        ;��R!� �>�41_41_000.jpg>�148,0200af48018ebfb2_(+�!
I1121 16:48:14   894 disk_location.go:38] data file /storage/1050.dat, replicaPlacement=000 v=2 size=23536316144 ttl=
I1121 16:48:14   894 volume.go:110] loading index file /storage/1051.idx readonly false
I1121 16:48:15   894 disk_location.go:38] data file /storage/1051.dat, replicaPlacement=000 v=2 size=31460089776 ttl=
I1121 16:48:15   894 volume.go:110] loading index file /storage/1052.idx readonly false
F1121 16:48:15   894 filer_server.go:53] Can not start filer in dir /storage/filer : open /storage/filer/CURRENT.3380234: structure needs cleaning
goroutine 36 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0x1214600, 0x0, 0x0, 0x0)
	/root/go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0xb8
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x11f59e0, 0xc800000003, 0xc8201a6c00, 0x11cb17f, 0xf, 0x35, 0x0)
	/root/go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:718 +0x259
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x11f59e0, 0xc800000003, 0xe57d80, 0x22, 0xc86ccc7d00, 0x2, 0x2)
	/root/go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:656 +0x1d4
github.com/chrislusf/seaweedfs/weed/glog.Fatalf(0xe57d80, 0x22, 0xc86ccc7d00, 0x2, 0x2)
	/root/go/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:1149 +0x5d
github.com/chrislusf/seaweedfs/weed/server.NewFilerServer(0xc82016d950, 0xd8b9b0, 0x7, 0x22b8, 0xc8201923c0, 0x13, 0xc820185390, 0xe, 0x0, 0x0, ...)
	/root/go/src/github.com/chrislusf/seaweedfs/weed/server/filer_server.go:53 +0xbbe
```

Master server was running smoothly, all of a sudden we got such crash and it start restarting again. any clue about this? where things got wrong?

**Comment by chrislusf** [comment]
The error says 
 open /storage/filer/CURRENT.3380234: structure needs cleaning

The filer db files are wrong.

**Comment by ijunaid8989** [comment]
They were correct for last 3 weeks, after repairing, is there any
possibility that they got wrong again by themselves?



Junaid Farooq

**Comment by chrislusf** [comment]
The problem maybe was there but not showing up until sstable compaction.

**Comment by ijunaid8989** [comment]
Is there anyway, we can stop stable compaction to happen? we don't need
anything on that master now, Its totally read-only now.

Vacuuming is fine, but is there any possibility to stop compaction all
together?



Junaid Farooq

**Comment by chrislusf** [comment]
The file is generated via goleveldb. 

Needs to recover the db file with this goleveldb RecoverFile() function:

https://github.com/syndtr/goleveldb/blob/34011bf325bce385408353a30b101fe5e923eb6e/leveldb/db.go#L263
