### ISSUE TITLE
0.5% save ConnectionClosedException

### ISSUE THREAD

**Issue by twosunnus** [chrislusf/seaweedfs#653]
保存请求量为150qps，请求中有0.5%的量失败，报下面的异常信息，这个是不是weed服务端的问题？
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 149; received: 0
        at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:180) ~[httpcore-4.3.jar:4.3]
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137) ~[httpclient-4.3.1.jar:4.3.1]
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[na:1.8.0_60]
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[na:1.8.0_60]
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[na:1.8.0_60]
        at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[na:1.8.0_60]
        at java.io.Reader.read(Reader.java:140) ~[na:1.8.0_60]
        at org.apache.http.util.EntityUtils.toString(EntityUtils.java:244) ~[httpcore-4.3.jar:4.3]
        at org.apache.http.util.EntityUtils.toString(EntityUtils.java:288) ~[httpcore-4.3.jar:4.3]
        at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:70) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:52) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:218) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:136) ~[httpclient-4.3.1.jar:4.3.1]
        at com.xxxx.service.FileOperatorServiceImpl.saveFile(FileOperatorServiceImpl.java:139) ~[FileOperatorServiceImpl.class:na]

**Comment by chrislusf** [comment]
May need to change the "weed volume" option for large files.
  -idleTimeout int
    	connection idle seconds (default 30)

**Comment by twosunnus** [comment]
The configuration is already -idleTimeout=120

**Comment by twosunnus** [comment]
The configuration is already -idleTimeout=120

2018-05-17 16:37 GMT+08:00 Chris Lu <notifications@github.com>:
