### ISSUE TITLE
weed volume segfaults on github.com/chrislusf/seaweedfs/weed/util.BytesToUint32

### ISSUE THREAD

**Issue by ingardm** [chrislusf/seaweedfs#656]
We've seen this same crash now 3 times over the course of 5 days on 2 different servers.

The same stack trace apart from memaddresses on all three crashes:
```
   unexpected fault address 0x7f5bb4014448
   fatal error: fault
   [signal SIGSEGV: segmentation violation code=0x1 addr=0x7f5bb4014448 pc=0x70a9f0]
   goroutine 14412585 [running]:
   runtime.throw(0xcb2e1e, 0x5)
           /usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc42142f8c8 sp=0xc42142f8a8 pc=0x42cf35
   runtime.sigpanic()
           /usr/local/go/src/runtime/signal_unix.go:374 +0x227 fp=0xc42142f918 sp=0xc42142f8c8 pc=0x443c17
   github.com/chrislusf/seaweedfs/weed/util.BytesToUint32(0x7f5bb4014448, 0x4, 0x8, 0x0)
           /go/src/github.com/chrislusf/seaweedfs/weed/util/bytes.go:17 +0x20 fp=0xc42142f928 sp=0xc42142f918 pc=0x70a9f0
   github.com/chrislusf/seaweedfs/weed/storage.(*BoltDbNeedleMap).Get(0xc421a7e0c0, 0x21aef365, 0xc42023f3a0, 0xc42142fa08)
           /go/src/github.com/chrislusf/seaweedfs/weed/storage/needle_map_boltdb.go:93 +0x144 fp=0xc42142f9a8 sp=0xc42142f928 pc=0x8b7004
   github.com/chrislusf/seaweedfs/weed/storage.(*Volume).readNeedle(0xc420599ef0, 0xc42161c3c0, 0xc420599ef0, 0xc42142fa68, 0x54cb60)
           /go/src/github.com/chrislusf/seaweedfs/weed/storage/volume_read_write.go:149 +0x46 fp=0xc42142fa18 sp=0xc42142f9a8 pc=0x8c57f6
   github.com/chrislusf/seaweedfs/weed/storage.(*Store).ReadVolumeNeedle(0xc420252000, 0xc400001276, 0xc42161c3c0, 0x2, 0x0, 0x10)
           /go/src/github.com/chrislusf/seaweedfs/weed/storage/store.go:302 +0x54 fp=0xc42142fa78 sp=0xc42142fa18 pc=0x8bee94
   github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).DeleteHandler(0xc4201f8380, 0x10dfb80, 0xc420011500, 0xc4209f5100)
           /go/src/github.com/chrislusf/seaweedfs/weed/server/volume_server_handlers_write.go:60 +0x199 fp=0xc42142fbf0 sp=0xc42142fa78 pc=0xa9cee9
   github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).DeleteHandler-fm(0x10dfb80, 0xc420011500, 0xc4209f5100)
           /go/src/github.com/chrislusf/seaweedfs/weed/server/volume_server_handlers.go:34 +0x48 fp=0xc42142fc20 sp=0xc42142fbf0 pc=0xaa08f8
   github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).privateStoreHandler(0xc4201f8380, 0x10dfb80, 0xc420011500, 0xc4209f5100)
           /go/src/github.com/chrislusf/seaweedfs/weed/server/volume_server_handlers.go:34 +0x220 fp=0xc42142fc80 sp=0xc42142fc20 pc=0xa94250
   github.com/chrislusf/seaweedfs/weed/server.(*VolumeServer).(github.com/chrislusf/seaweedfs/weed/server.privateStoreHandler)-fm(0x10dfb80, 0xc420011500, 0xc4209f5100)
           /go/src/github.com/chrislusf/seaweedfs/weed/server/volume_server.go:67 +0x48 fp=0xc42142fcb0 sp=0xc42142fc80 pc=0xaa07d8
   net/http.HandlerFunc.ServeHTTP(0xc421861800, 0x10dfb80, 0xc420011500, 0xc4209f5100)
           /usr/local/go/src/net/http/server.go:1918 +0x44 fp=0xc42142fcd8 sp=0xc42142fcb0 pc=0x6caa04
   net/http.(*ServeMux).ServeHTTP(0xc4201e5ce0, 0x10dfb80, 0xc420011500, 0xc4209f5100)
           /usr/local/go/src/net/http/server.go:2254 +0x130 fp=0xc42142fd18 sp=0xc42142fcd8 pc=0x6cc0b0
   net/http.serverHandler.ServeHTTP(0xc42021e000, 0x10dfb80, 0xc420011500, 0xc4209f5100)
           /usr/local/go/src/net/http/server.go:2619 +0xb4 fp=0xc42142fd48 sp=0xc42142fd18 pc=0x6cd674
   net/http.(*conn).serve(0xc4200cf5e0, 0x10e0680, 0xc420a86680)
           /usr/local/go/src/net/http/server.go:1801 +0x71d fp=0xc42142ffc8 sp=0xc42142fd48 pc=0x6c98dd
   runtime.goexit()
```

**Comment by chrislusf** [comment]
What's the golang version?

**Comment by ingardm** [comment]
1.9.3
