### ISSUE TITLE
Read through fuse points to incorrect URL

### ISSUE THREAD

**Issue by Eloahman** [chrislusf/seaweedfs#721]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
Using `weed mount` command to mount a directory. Directory tree can be listed but failed when try to achieve an object

**System Setup**
* In server 172.27.221.2
```
nohup ./weed master -mdir="./mdata" > master.log 2>&1 &
nohup ./weed volume -mserver="localhost:9333" -port=8081 -dir="./data" -publicUrl="172.27.221.2:8081" > volume.log 2>&1 &
nohup ./weed filer > filer.log 2>&1 &
```
* In client 172.28.43.46
```
nohup ./weed mount -filer=172.27.221.2:8888 -dir=rdir -filer.path=/ 2>&1 &
```
**Expected behavior**
Achieve files as local storagement.

**Screenshots**
Some log related.

```
➜  rdir ls -l
total 0
-rw-rw----. 1 scper scper 143028 Sep  4 10:51 162d749c1064bac28.jpg
-rw-rw-r--. 1 root  root       0 Sep  4 11:02 bug.txt
-rw-rw-r--. 1 root  root       0 Sep  4 11:48 docker-compose.yml
-rw-r--r--. 1 root  root    5380 Sep  4 11:03 kubecfg-kube-admin.yaml
-rw-rw----. 1 scper scper  45056 Sep  4 11:31 test
drwxrwx---. 1 scper scper      0 Sep  4 11:46 test1
-rw-rw----. 1 scper scper   2007 Sep  4 10:50 youtube_with_pyspider.py
➜  rdir cat kubecfg-kube-admin.yaml 
cat: kubecfg-kube-admin.yaml: Input/output error
➜  rdir stat .
  File: .
  Size: 0               Blocks: 0          IO Block: 4096   directory
Device: 100022h/1048610d        Inode: 1           Links: 1
Access: (0777/drwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Context: system_u:object_r:fusefs_t:s0
Access: 2018-09-04 11:35:16.332740191 +0800
Modify: 2018-09-04 11:35:16.332740191 +0800
Change: 2018-09-04 11:35:16.332740191 +0800
```

* Log of mount process
```
I0904 12:26:16 32361 filehandle.go:115] //kubecfg-kube-admin.yaml read http://127.0.0.1:8081/1,0f2510b483 0 bytes: Get http://127.0.0.1:8081/1,0f2510b483: dial tcp 127.0.0.1:8081: connect: connection refused
```

**Additional context**
I think the problem is mainly the filer doesn't use the public URL to access volume server.

Another situation may be help show below
```
➜  rdir ll
total 0
-rw-rw----. 1 scper scper 140K Sep  4 10:51 162d749c1064bac28.jpg
-rw-rw-r--. 1 root  root     0 Sep  4 11:02 bug.txt
-rw-rw-r--. 1 root  root     0 Sep  4 11:48 docker-compose.yml
-rw-r--r--. 1 root  root  5.3K Sep  4 11:03 kubecfg-kube-admin.yaml
-rw-rw-r--. 1 root  root   158 Sep  4 14:40 Pipfile
-rw-rw----. 1 scper scper  44K Sep  4 11:31 test
drwxrwx---. 1 scper scper    0 Sep  4 11:46 test1
-rw-rw----. 1 scper scper 2.0K Sep  4 10:50 youtube_with_pyspider.py
➜  rdir cp ~/hello.exs . 
cp: failed to close './hello.exs': Input/output error
➜  rdir ll
total 0
-rw-rw----. 1 scper scper 140K Sep  4 10:51 162d749c1064bac28.jpg
-rw-rw-r--. 1 root  root     0 Sep  4 11:02 bug.txt
-rw-rw-r--. 1 root  root     0 Sep  4 11:48 docker-compose.yml
----------. 1 root  root    34 Sep  4 14:41 hello.exs
-rw-r--r--. 1 root  root  5.3K Sep  4 11:03 kubecfg-kube-admin.yaml
-rw-rw-r--. 1 root  root   158 Sep  4 14:40 Pipfile
-rw-rw----. 1 scper scper  44K Sep  4 11:31 test
drwxrwx---. 1 scper scper    0 Sep  4 11:46 test1
-rw-rw----. 1 scper scper 2.0K Sep  4 10:50 youtube_with_pyspider.py
```
And the log of the mount process is
```
I0904 14:41:05 32361 upload_content.go:89] failing to upload to http://127.0.0.1:8081/1,15329ff42d Post http://127.0.0.1:8081/1,15329ff42d: dial tcp 127.0.0.1:8081: connect: connection refused
I0904 14:41:05 32361 dirty_page.go:145] upload data hello.exs to http://127.0.0.1:8081/1,15329ff42d: Post http://127.0.0.1:8081/1,15329ff42d: dial tcp 127.0.0.1:8081: connect: connection refused
2018/09/04 14:41:05 fuse: panic in handler for Flush [ID=0xe7c Node=0x3 Uid=1000 Gid=1000 Pid=14931] 0x1 fl=0x0 lk=0xb6a74297c26d5718: runtime error: invalid memory address or nil pointer dereference
goroutine 12406 [running]:
bazil.org/fuse/fs.(*Server).serve.func2(0x10d3860, 0xc0000dc0a0, 0xc00044def8, 0xc00044de77)
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:857 +0x1ac
panic(0xe2d080, 0x17f6260)
        /home/travis/.gimme/versions/go/src/runtime/panic.go:513 +0x1b9
github.com/chrislusf/seaweedfs/weed/filesys.(*FileHandle).Flush(0xc0000300f0, 0x10d7ba0, 0xc00049e080, 0xc0000dc0a0, 0xc0000300f0, 0x47fa01)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filesys/filehandle.go:182 +0x4a9
bazil.org/fuse/fs.(*Server).handleRequest(0xc0003760c0, 0x10d7ba0, 0xc00049e080, 0x10cb020, 0xc0000300a0, 0xc00023c040, 0x10d3860, 0xc0000dc0a0, 0xc00044def8, 0x10ca6a0, ...)
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:1282 +0x2bec
bazil.org/fuse/fs.(*Server).serve(0xc0003760c0, 0x10d3860, 0xc0000dc0a0)
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:878 +0x410
bazil.org/fuse/fs.(*Server).Serve.func1(0xc0003760c0, 0x10d3860, 0xc0000dc0a0)
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:425 +0x6e
created by bazil.org/fuse/fs.(*Server).Serve
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:423 +0x321
```

**Comment by chrislusf** [comment]
set your ip when starting volume server
 "./weed volume -ip=172.27.221.2 ...."
