### ISSUE TITLE
Seaweedfs failed to start with -ip param v96

### ISSUE THREAD

**Issue by ijunaid8989** [chrislusf/seaweedfs#737]
I started seaweedfs with no ip first to localhost. It worked fine. After that I started it with -ip param

```
root@evercam-release-test:~# ./weed -v=0 server -filer=true -dir=storage -pulseSeconds=1 -volume.images.fix.orientation=false -ip=95.216.167.191
I0925 10:34:33 12534 file_util.go:19] Folder storage Permission: -rwxr-xr-x
I0925 10:34:33 12534 file_util.go:19] Folder storage Permission: -rwxr-xr-x
I0925 10:34:33 12534 master_server.go:68] Volume Size Limit is 30000 MB
I0925 10:34:33 12534 server.go:186] Start Seaweed Master 0.96 at 95.216.167.191:9333
I0925 10:34:33 12534 raft_server.go:47] Starting RaftServer with 95.216.167.191:9333
I0925 10:34:34 12534 filer_server.go:80] Reading filer.toml from 
I0925 10:34:34 12534 masterclient.go:43] filer bootstraps with masters [localhost:9333]
I0925 10:34:34 12534 masterclient.go:52] Connecting to localhost:9333
I0925 10:34:34 12534 file_util.go:19] Folder storage/filer Permission: -rwxr-xr-x
I0925 10:34:34 12534 masterclient.go:67] failed to receive from localhost:9333: rpc error: code = Unknown desc = raft.Server: Not current leader
I0925 10:34:34 12534 configuration.go:24] Configure filer for leveldb
I0925 10:34:34 12534 filer.go:120] Start Seaweed Filer 0.96 at port 8888
I0925 10:34:34 12534 raft_server.go:88] current cluster leader: 95.216.167.191:9333
I0925 10:34:34 12534 master_server.go:103] [ 95.216.167.191:9333 ] I am the leader!
I0925 10:34:34 12534 disk_location.go:106] Store started on dir: storage with 0 volumes max 7
I0925 10:34:34 12534 server.go:256] Start Seaweed volume server 0.96 at 95.216.167.191:8080
I0925 10:34:34 12534 volume_grpc_client.go:19] Volume server start with masters: [95.216.167.191:9333]
I0925 10:34:34 12534 volume_grpc_client.go:53] Heartbeat to: 95.216.167.191:9333
I0925 10:34:34 12534 node.go:223] topo adds child DefaultDataCenter
I0925 10:34:34 12534 node.go:223] topo:DefaultDataCenter adds child DefaultRack
I0925 10:34:34 12534 node.go:223] topo:DefaultDataCenter:DefaultRack adds child 95.216.167.191:8080
I0925 10:34:34 12534 master_grpc_server.go:66] added volume server 95.216.167.191:8080
panic: assertion failed: leader.elected.at.same.term.2


goroutine 36 [running]:
github.com/chrislusf/raft._assert(0xde2b00, 0xfa1a50, 0x1f, 0xc00006fce0, 0x1, 0x1)
    /home/travis/gopath/src/github.com/chrislusf/raft/util.go:60 +0xf6
github.com/chrislusf/raft.(*server).processAppendEntriesRequest(0xc0001d6480, 0xc0000ca2d0, 0xc0000ca2d0, 0x0)
    /home/travis/gopath/src/github.com/chrislusf/raft/server.go:948 +0x171
github.com/chrislusf/raft.(*server).leaderLoop(0xc0001d6480)
    /home/travis/gopath/src/github.com/chrislusf/raft/server.go:849 +0x3c2
github.com/chrislusf/raft.(*server).loop(0xc0001d6480)
    /home/travis/gopath/src/github.com/chrislusf/raft/server.go:609 +0x1e3
github.com/chrislusf/raft.(*server).Start.func1(0xc0001d6480)
    /home/travis/gopath/src/github.com/chrislusf/raft/server.go:470 +0x5a
created by github.com/chrislusf/raft.(*server).Start
    /home/travis/gopath/src/github.com/chrislusf/raft/server.go:468 +0x1fc
root@evercam-release-test:~# 
root@evercam-release-test:~# ./weed -v=0 server -filer=true -dir=storage -pulseSeconds=1 -volume.images.fix.orientation=false -ip=95.216.167.191
I0925 10:35:08 12555 file_util.go:19] Folder storage Permission: -rwxr-xr-x
I0925 10:35:08 12555 file_util.go:19] Folder storage Permission: -rwxr-xr-x
```

It got failed but after a minute I started with the same command and it worked?

**Comment by chrislusf** [comment]
known data racing issue and only happens on the first run with a new IP.

**Comment by ijunaid8989** [comment]
Okay thanks.
