### ISSUE TITLE
weed filer.replicate command failed with invalid memory address v 0.99

### ISSUE THREAD

**Issue by ijunaid8989** [chrislusf/seaweedfs#757]
**Describe the bug**
Weed replicate command failed to start..
Command: `/opt/go/bin/weed filer.replicate`
Error: 
```
I1030 08:40:43  5127 filer_server.go:81] Reading replication.toml from 
I1030 08:40:43  5127 filer_replication.go:73] Configure sink to s3
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xeafd4b]

goroutine 1 [running]:
github.com/chrislusf/seaweedfs/weed/command.runFilerReplicate(0x1e93b60, 0xc0000be010, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/filer_replication.go:90 +0x31b
main.main()
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/weed.go:67 +0x2b6
```

**System Setup**
Ubuntu 18.04
Weed 0.99 amd64
weed startup command withing systemD service
```
[Unit]
Description=SeaweedFS Master
After=network.target

[Service]
Type=simple
User=root
Group=root
LimitNOFILE=1000000
Environment=HOME=/home/root
Environment=LANGUAGE=en_US:en
Environment=LS_ALL=en_US.UTF-8

ExecStart=/opt/go/bin/weed -v=0 server -filer=true -ip=159.xx.xxx.xx -dir=/storage/new_master -volume.max=3000 -volume.images.fix.orientation=false -pulseSeconds=5
Restart=always
RestartSec=5
Environment=LANG=en_US.UTF-8
SyslogIdentifier=seaweedfs

[Install]
WantedBy=multi-user.target
```
Foiler.toml file in /etc/seaweedfs/filer.toml

```
[memory]
# local in memory, mostly for testing purpose
enabled = false

[leveldb]
# local on disk, mostly for simple single-machine setup, fairly scalable
enabled = true
dir = "/storage/new_master/filer"
```
Replication file in /etc/seaweedfs/replication.toml

```
[source.filer]
enabled = true
grpcAddress = "localhost:18888" # I had tried to change it to only 8888 as well , as my filer is running at 8888 nothing worked
directory = "/storage/new_master/filer"    # all files under this directory tree are replicated

topic = "seaweedfs_filer_to_s3"

[sink.s3]
# read credentials doc at https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/sessions.html
# default loads credentials from the shared credentials file (~/.aws/credentials). 
enabled = true
aws_access_key_id     = "AKd---------------"     # if empty, loads from the shared credentials file (~/.aws/credentials).
aws_secret_access_key = "d+-----------------"     # if empty, loads from the shared credentials file (~/.aws/credentials).
region = "eu-west-1"
bucket = "seaweedfs-filer-backup"    # an existing bucket
directory = "filer"                 # destination directory (do not prefix or suffix with "/")

[sink.google_cloud_storage]
# read credentials doc at https://cloud.google.com/docs/authentication/getting-started
enabled = false
google_application_credentials = "/path/to/x.json" # path to json credential file
bucket = "your_bucket_seaweedfs"    # an existing bucket
directory = "/"                     # destination directory

[sink.azure]
# experimental
enabled = false
account_name = ""
account_key  = ""
container = "mycontainer"      # an existing container
directory = ""                 # destination directory (do not prefix or suffix with "/")

```

**Expected behavior**
Seaweedfs is running and saving files but `/opt/go/bin/weed filer.replicate` failed with above error.

**Screenshots**
![image](https://user-images.githubusercontent.com/13561999/47704172-8b6f1580-dc44-11e8-8775-01be3dc47855.png)

**Additional context**
Is this process is continues? for example once we run the command through systemdD job, and we need to start it again and again or it will be unbreakable?

**Comment by chrislusf** [comment]
Need to add a section in replication.toml. 

[notification.kafka]
enabled = false
hosts = [
  "localhost:9092"
]
topic = "seaweedfs_filer"
offsetFile = "./last.offset"
offsetSaveIntervalSeconds = 10

And correspondingly, need to add a section to filer.toml,
[notification.kafka]
enabled = false
hosts = [
  "localhost:9092"
]
topic = "seaweedfs_filer"

And I assume you have kafka running also.

As you can tell, the replication progress is saved in "offsetFile" every "offsetSaveIntervalSeconds".

**Comment by ijunaid8989** [comment]
Actually, we are not using Kafka for notification purposes, or either. Is there any possibility to use it without setting up kafka?

**Comment by chrislusf** [comment]
The design does need some message queue. Do you use https://github.com/nsqio/nsq ?

**Comment by ijunaid8989** [comment]
Okay, I have installed Kafka and started Kafka Zookeeper and Kafka as daemons and they are running now, on port 2182 Zookeeper and on port 9092 Kafka. also created a topic as 
```
root@Ubuntu-1804-bionic-64-minimal:/etc/seaweedfs# /opt/kafka/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic seaweedfs_filer_to_s3
WARNING: Due to limitations in metric names, topics with a period ('.') or underscore ('_') could collide. To avoid issues it is best to use either, but not both.
Created topic "seaweedfs_filer_to_s3".
```

and now I ran the replicate command as 

```
root@Ubuntu-1804-bionic-64-minimal:~# /opt/go/bin/weed filer.replicate
I1031 07:34:11 23511 filer_server.go:81] Reading replication.toml from 
I1031 07:34:11 23511 notification_kafka.go:32] replication.notification.kafka.hosts: [localhost:9092]
I1031 07:34:11 23511 notification_kafka.go:33] replication.notification.kafka.topic: seaweedfs_filer_to_s3
I1031 07:34:11 23511 notification_kafka.go:49] connected to [localhost:9092]
W1031 07:34:11 23511 notification_kafka.go:124] failed to read kafka progress file: 
I1031 07:34:11 23511 filer_replication.go:47] Configure notification input to kafka
I1031 07:34:11 23511 filer_replication.go:73] Configure sink to s3
```

It gave no error but the present files on `/storage/new_master/filer` didn't appear on S3.

filer.toml
```
[memory]
# local in memory, mostly for testing purpose
enabled = false

[leveldb]
# local on disk, mostly for simple single-machine setup, fairly scalable
enabled = true
dir = "/storage/new_master/filer"					# directory to store level db files
[notification.kafka]
enabled = true
hosts = [
"localhost:9092"
]
topic = "seaweedfs_filer_to_s3"
```

and  replication.toml

```
[source.filer]
enabled = true
grpcAddress = "localhost:8888"
directory = "/storage/new_master/filer"    # all files under this directory tree are replicated

[notification.kafka]
enabled = true
hosts = [
  "localhost:9092"
]
topic = "seaweedfs_filer_to_s3"

[sink.s3]
enabled = true
aws_access_key_id     = "A----------------------------"     # if empty, loads from the shared credentials file (~/.aws/credentials).
aws_secret_access_key = "d----------------------------"     # if empty, loads from the shared credentials file (~/.aws/credentials).
region = "eu-west-1"
bucket = "seaweedfs-filer-backup"    # an existing bucket
directory = "filer"
```
my filer is running at port 8888.

current files in `/storage/new_master/filer`

```
root@Ubuntu-1804-bionic-64-minimal:/storage/new_master/filer# ls
000002.ldb  000003.log	CURRENT  CURRENT.bak  LOCK  LOG  MANIFEST-000004
root@Ubuntu-1804-bionic-64-minimal:/storage/new_master/filer#
```

**Comment by ijunaid8989** [comment]
sorry but I think I misunderstood this whole feature.

its not for the filer files? as you can see I have started filer on `/storage/new_master/filer`, 
I think this feature is for user uploaded files to the filer? not the files being created during filer is running right?

**Comment by chrislusf** [comment]
see https://github.com/chrislusf/seaweedfs/wiki/Backup-to-Cloud

this is not to backup .dat, .idx files, but to backup each user file directly.

**Comment by ijunaid8989** [comment]
Okay with this the whole purpose of creating the issue is over. Thanks.
