### ISSUE TITLE
filer mode start error

### ISSUE THREAD

**Issue by srzyhead** [chrislusf/seaweedfs#885]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
when execute 
```
docker run --rm -it chrislusf/seaweedfs server -filer=true
```
there's an error occur
```
I0315 06:33:49     1 file_util.go:19] Folder /data Permission: -rwxr-xr-x
I0315 06:33:49     1 master_server.go:76] Volume Size Limit is 30000 MB
I0315 06:33:49     1 server.go:178] Start Seaweed Master 1.26 at 172.17.0.3:9333
I0315 06:33:49     1 raft_server.go:44] Starting RaftServer with 172.17.0.3:9333
I0315 06:33:49     1 raft_server.go:48] Peers Change: [] => []
I0315 06:33:49     1 raft_server.go:71] Initializing new cluster
I0315 06:33:49     1 raft_server.go:84] current cluster leader: 172.17.0.3:9333
I0315 06:33:49     1 master_server.go:115] [ 172.17.0.3:9333 ] I am the leader!
I0315 06:33:49     1 server.go:199] grpc config <nil>
I0315 06:33:49     1 server.go:205] Start Seaweed Master 1.26 grpc server at 172.17.0.3:19333
I0315 06:33:49     1 file_util.go:19] Folder /data Permission: -rwxr-xr-x
I0315 06:33:49     1 disk_location.go:106] Store started on dir: /data with 0 volumes max 7
I0315 06:33:49     1 volume.go:163] Start Seaweed volume server 1.26 at 0.0.0.0:8080
I0315 06:33:49     1 volume_grpc_client_to_master.go:21] Volume server start with masters: [172.17.0.3:9333]
I0315 06:33:49     1 volume_grpc_client_to_master.go:62] Heartbeat to: 172.17.0.3:9333
I0315 06:33:49     1 node.go:223] topo adds child DefaultDataCenter
I0315 06:33:49     1 node.go:223] topo:DefaultDataCenter adds child DefaultRack
I0315 06:33:49     1 node.go:223] topo:DefaultDataCenter:DefaultRack adds child 172.17.0.3:8080
I0315 06:33:49     1 master_grpc_server.go:67] added volume server 172.17.0.3:8080
I0315 06:33:50     1 masterclient.go:46] filer bootstraps with masters [localhost:9333]
I0315 06:33:50     1 masterclient.go:55] Connecting to master localhost:9333
I0315 06:33:50     1 leveldb_store.go:36] filer store dir: /data/filerdb
F0315 06:33:50     1 configuration.go:22] Failed to initialize store for leveldb: Check Level Folder /data/filerdb Writable:
    github.com/chrislusf/seaweedfs/weed/filer2/leveldb.(*LevelDBStore).initialize
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filer2/leveldb/leveldb_store.go:38
  - stat /data/filerdb: no such file or directory
goroutine 27 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0xc000395d00, 0xc000294000, 0x168, 0x285)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0xad
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x2193aa0, 0xc000000003, 0xc00047b3b0, 0x212c219, 0x10, 0x16, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:718 +0x351
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x2193aa0, 0x3, 0x1447eb5, 0x26, 0xc0003a9d18, 0x2, 0x2)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:656 +0x14e
github.com/chrislusf/seaweedfs/weed/glog.Fatalf(...)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:1149
github.com/chrislusf/seaweedfs/weed/filer2.(*Filer).LoadConfiguration(0xc0005984c0, 0xc000122200)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filer2/configuration.go:22 +0x48f
github.com/chrislusf/seaweedfs/weed/server.NewFilerServer(0xc000598400, 0xc000598400, 0xc0001360e0, 0x1, 0x0, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/server/filer_server.go:70 +0x1b2
github.com/chrislusf/seaweedfs/weed/command.(*FilerOptions).startFiler(0x21937e0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/filer.go:101 +0x21a
github.com/chrislusf/seaweedfs/weed/command.runServer.func1()
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/server.go:161 +0x3a
created by github.com/chrislusf/seaweedfs/weed/command.runServer
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/server.go:158 +0x4c9
```

**System Setup**
```
docker run --rm -it chrislusf/seaweedfs server -filer=true
```

**Expected behavior**
start normally

**Comment by chrislusf** [comment]
the fix is in. but because the docker image build has some lag, this command will be fixed when 1.27 is released

**Comment by chrislusf** [comment]
or wait for chrislusf/seaweedfs:dev when it is ready in 10 minutes. The docker image size is much larger though.

docker run --rm -it chrislusf/seaweedfs:dev server -filer

**Comment by srzyhead** [comment]
Thank you very much :)
