### ISSUE TITLE
filer use memdb panic

### ISSUE THREAD

**Issue by HZ89** [chrislusf/seaweedfs#930]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
start a cluster with a filer use memdb, then executing this command ` ./weed filer.copy -c 32 -master 172.16.10.60:9333 abc/* http://172.16.10.62:8888/abc/`, the filer server is panic.The panic output is below.

**System Setup**
* start master:
``` bash
root@172-16-10-60:~/seaweeedfs# ./weed master -ip.bind 0.0.0.0 -port 9333 -mdir /data/seaweedfs/meta -i172.17.10.60 -volumePreallocate

```

* start volume-1:
``` bash
root@172-16-10-60:~/seaweeedfs# ./weed volume -ip.bind 0.0.0.0 -mserver 172.17.10.60:9333 -port 8080 -dir /data/seaweedfs/data/ -max 10 -ip 172.17.10.60 -publicUrl http://172.16.10.60:8080 -port.public 8080
```

* start volume-2:
``` bash
root@172-16-10-62:~/seaweedfs# ./weed volume -ip.bind 0.0.0.0 -mserver 172.17.10.60:9333 -port 8080 -dir /data/seaweedfs/data/ -max 10 -ip 172.17.10.62 -publicUrl http://172.16.10.62:8080 -port.public 8080
```

* start filer:
``` bash
./weed filer -port 8888 -ip 0.0.0.0 -master 172.17.10.60:9333 -redirectOnRead
```

* filer.toml:
``` toml
# A sample TOML config file for SeaweedFS filer store
# Used with "weed filer" or "weed server -filer"
# Put this file to one of the location, with descending priority
#    ./filer.toml
#    $HOME/.seaweedfs/filer.toml
#    /etc/seaweedfs/filer.toml

[memory]
# local in memory, mostly for testing purpose
enabled = true

```

**Expected behavior**

**Screenshots**
* filer output:
``` bash
root@172-16-10-62:~/seaweedfs# ./weed filer -port 8888 -ip 0.0.0.0 -master 172.17.10.60:9333 -re[94/626]
Read
I0415 21:30:24 26437 configuration.go:26] Configure filer for memory
I0415 21:30:24 26437 filer.go:133] Start Seaweed Filer 30GB 1.30 at 0.0.0.0:8888
panic: interface conversion: btree.Item is nil, not memdb.entryItem

goroutine 1394 [running]:
github.com/chrislusf/seaweedfs/weed/filer2/memdb.entryItem.Less(0xc00082d340, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filer2/memdb/memdb_store.go:25 +0x10
0
github.com/google/btree.items.find.func1(0xe, 0xc0002eb400)
        /home/travis/gopath/src/github.com/google/btree/btree.go:189 +0x55
sort.Search(0xf, 0xc0002eb4a0, 0xffffffffffffffff)
        /home/travis/.gimme/versions/go1.12.4.linux.amd64/src/sort/search.go:66 +0x58
github.com/google/btree.items.find(0xc0007bb180, 0xf, 0x1c, 0x18f30c0, 0xc00082d340, 0xc, 0xe)
        /home/travis/gopath/src/github.com/google/btree/btree.go:188 +0x8a
github.com/google/btree.(*node).get(0xc000366bc0, 0x18f30c0, 0xc00082d340, 0x18f30c0, 0xc00082d340)
        /home/travis/gopath/src/github.com/google/btree/btree.go:337 +0x58
github.com/google/btree.(*node).get(0xc0007b5300, 0x18f30c0, 0xc00082d340, 0x18f30c0, 0xc00082d340)
        /home/travis/gopath/src/github.com/google/btree/btree.go:341 +0xcf
github.com/google/btree.(*node).get(0xc0004358c0, 0x18f30c0, 0xc00082d340, 0x18f30c0, 0xc00082d340)
        /home/travis/gopath/src/github.com/google/btree/btree.go:341 +0xcf
github.com/google/btree.(*node).get(0xc000435940, 0x18f30c0, 0xc00082d340, 0x5cb4877b, 0x1f606afbe51)
        /home/travis/gopath/src/github.com/google/btree/btree.go:341 +0xcf
github.com/google/btree.(*BTree).Get(...)
        /home/travis/gopath/src/github.com/google/btree/btree.go:822
github.com/chrislusf/seaweedfs/weed/filer2/memdb.(*MemDbStore).FindEntry(0xc000108130, 0x191a120, 0xc000
6c2cf0, 0xc000741c20, 0x49, 0xc0007506c0, 0x2b, 0x152e5e0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filer2/memdb/memdb_store.go:62 +0xe1
github.com/chrislusf/seaweedfs/weed/filer2.(*Filer).FindEntry(0xc0001a4ac0, 0x191a120, 0xc0006c2cf0, 0xc
000741c20, 0x49, 0xc0007506c0, 0x2b, 0x5)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filer2/filer.go:199 +0x87
github.com/chrislusf/seaweedfs/weed/filer2.(*Filer).CreateEntry(0xc0001a4ac0, 0x191a120, 0xc0006c2cf0, 0
xc00082d260, 0x0, 0xed4467e7b)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/filer2/filer.go:152 +0x9a9
github.com/chrislusf/seaweedfs/weed/server.(*FilerServer).CreateEntry(0xc0001a4a40, 0x191a120, 0xc0006c2
cf0, 0xc000763b40, 0xc0001a4a40, 0xc0006c2cf0, 0xc000627ba8)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/server/filer_grpc_server.go:123 +0x2
5e
github.com/chrislusf/seaweedfs/weed/pb/filer_pb._SeaweedFiler_CreateEntry_Handler(0x15e54c0, 0xc0001a4a4
0, 0x191a120, 0xc0006c2cf0, 0xc0007812c0, 0x0, 0x191a120, 0xc0006c2cf0, 0xc0006df860, 0x9a)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/pb/filer_pb/filer.pb.go:1065 +0x23e
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005f4900, 0x192f4a0, 0xc0005d4600, 0xc00073f500, 0x
c00041bd40, 0x2545610, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/google.golang.org/grpc/server.go:972 +0x470
google.golang.org/grpc.(*Server).handleStream(0xc0005f4900, 0x192f4a0, 0xc0005d4600, 0xc00073f500, 0x0)
        /home/travis/gopath/src/google.golang.org/grpc/server.go:1252 +0xda6
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0004aa060, 0xc0005f4900, 0x192f4a0, 0xc0005d460
0, 0xc00073f500)
        /home/travis/gopath/src/google.golang.org/grpc/server.go:691 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/travis/gopath/src/google.golang.org/grpc/server.go:689 +0xa1
```

**Comment by chrislusf** [comment]
First of all, do not use memory. It's only for testing.

**Comment by HZ89** [comment]
yes,but i am runing a test

**Comment by chrislusf** [comment]
"Write operations are not safe for concurrent mutation by multiple goroutines" see https://godoc.org/github.com/google/btree

If interested, you can send a PR to lock the writes in github.com/chrislusf/seaweedfs/weed/filer2/memdb/memdb_store.go
