### ISSUE TITLE
heartbeat error: rpc error: code = Unknown desc = Raft Server not initialized

### ISSUE THREAD

**Issue by patsevanton** [chrislusf/seaweedfs#932]
**Describe the bug**
heartbeat error: rpc error: code = Unknown desc = Raft Server not initialized

**System Setup**
I have 3 servers
dev-tools-postgresql-patroni-96-1 - 10.233.47.61
dev-tools-postgresql-patroni-96-2 - 10.233.47.59
dev-tools-postgresql-patroni-96-3 - 10.233.47.60
On dev-tools-postgresql-patroni-96-3 have 2 ip: 10.233.47.60 eth and 10.233.47.62 - keepalived

Every server run `mkdir -p /var/lib/pgsql/1`
On dev-tools-postgresql-patroni-96-1 run
`weed server -master.port=9333 -dir=/var/lib/pgsql/1 -volume.port=8080 -master.peers=localhost:9333,10.233.47.59:9333,10.233.47.60:9333`

On dev-tools-postgresql-patroni-96-2 run
`weed server -master.port=9333 -dir=/var/lib/pgsql/1 -volume.port=8081 -master.peers=localhost:9333,10.233.47.61:9333,10.233.47.60:9333`

On dev-tools-postgresql-patroni-96-3 run
`weed server -master.port=9333 -dir=/var/lib/pgsql/1 -volume.port=8082 -master.peers=localhost:9333,10.233.47.61:9333,10.233.47.59:9333`

But i see error
```
I0419 09:21:22  4192 volume_grpc_client_to_master.go:41] heartbeat error: rpc error: code = Unknown desc = Raft Server not initialized!
I0419 09:21:27  4192 volume_grpc_client_to_master.go:62] Heartbeat to: localhost:9333
I0419 09:21:27  4192 node.go:224] topo:DefaultDataCenter:DefaultRack adds child localhost:8080
I0419 09:21:27  4192 master_grpc_server.go:67] added volume server localhost:8080
I0419 09:21:27  4192 master_grpc_server.go:23] unregister disconnected volume server localhost:8080
I0419 09:21:27  4192 node.go:238] topo:DefaultDataCenter:DefaultRack removes localhost:8080
```
Every Server. 
May i run not correct run weed. Plz help.

**Comment by chrislusf** [comment]
for all servers, use
-master.peers=10.233.47.61:9333,10.233.47.59:9333,10.233.47.60:9333

do not use localhost.

**Comment by patsevanton** [comment]
If use real ip i get error Only odd number of masters are supported!

```
[root@dev-tools-postgresql-patroni-96-1 ~]# ip a | grep eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    inet 10.233.47.61/24 brd 10.233.47.255 scope global dynamic eth0
[root@dev-tools-postgresql-patroni-96-1 ~]# puppet agent -t^C
[root@dev-tools-postgresql-patroni-96-1 ~]# weed server -master.port=9333 -dir=/var/lib/pgsql/1 -volume.port=8080 -master.peers=10.233.47.61:9333,10.233.47.59:9333,10.233.47.60:9333
I0419 11:37:01 11417 file_util.go:19] Folder /var/lib/pgsql/1 Permission: -rwxr-xr-x
I0419 11:37:01 11417 master_server.go:76] Volume Size Limit is 30000 MB
I0419 11:37:01 11417 server.go:180] Start Seaweed Master 30GB 1.30 at localhost:9333
F0419 11:37:01 11417 master.go:146] Only odd number of masters are supported!
goroutine 15 [running]:
github.com/chrislusf/seaweedfs/weed/glog.stacks(0xc0003fc800, 0xc0003ca000, 0x4e, 0xaf)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:767 +0xb1
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).output(0x2557940, 0xc000000003, 0xc0002b48c0, 0x24d46de, 0x9, 0x92, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:718 +0x2d9
github.com/chrislusf/seaweedfs/weed/glog.(*loggingT).printf(0x2557940, 0x3, 0x165b8ca, 0x29, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:656 +0x14e
github.com/chrislusf/seaweedfs/weed/glog.Fatalf(...)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/glog/glog.go:1149
github.com/chrislusf/seaweedfs/weed/command.checkPeers(0x162871e, 0x9, 0x2475, 0x7ffd2d68773e, 0x35, 0x0, 0x0, 0xc00003a960, 0xc00005ee48, 0x1)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/master.go:146 +0x19d
github.com/chrislusf/seaweedfs/weed/command.runServer.func2.1(0xc0000c5860, 0xc0001180c0)
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/server.go:188 +0x75
created by github.com/chrislusf/seaweedfs/weed/command.runServer.func2
	/home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/command/server.go:186 +0x390

```

**Comment by chrislusf** [comment]
Try to set -ip for each server.

**Comment by patsevanton** [comment]
```
[root@dev-tools-postgresql-patroni-96-1 ~]# weed server -master.port=9333 -dir=/var/lib/pgsql/1 -volume.port=8080 -ip=10.233.47.61:9333 -ip=10.233.47.59:9333 -ip=10.233.47.60:9333
I0423 05:51:42  3709 file_util.go:19] Folder /var/lib/pgsql/1 Permission: -rwxr-xr-x
I0423 05:51:42  3709 master_server.go:76] Volume Size Limit is 30000 MB
I0423 05:51:42  3709 server.go:180] Start Seaweed Master 30GB 1.30 at 10.233.47.60:9333:9333
I0423 05:51:42  3709 raft_server.go:44] Starting RaftServer with 10.233.47.60:9333:9333
I0423 05:51:42  3709 raft_server.go:84] current cluster leader: 
F0423 05:51:42  3709 server.go:198] master failed to listen on grpc port 19333: listen tcp: address 10.233.47.60:9333:19333: too many colons in address
goroutine 28 [running]:
```

**Comment by patsevanton** [comment]
```
[root@dev-tools-postgresql-patroni-96-1 ~]# ip a | grep eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    inet 10.233.47.61/24 brd 10.233.47.255 scope global dynamic eth0

[root@dev-tools-postgresql-patroni-96-1 ~]# weed -v="3" master -mdir="/var/lib/pgsql/1" -ip="10.233.47.61" -port="9333" -peers="10.233.47.61:9333,10.233.47.59:9333,10.233.47.60:9333"
I0423 05:56:54  5113 filer_server.go:100] Reading security.toml from 
I0423 05:56:54  5113 filer_server.go:103] Reading : Config File "security" Not Found in "[/root /root/.seaweedfs /etc/seaweedfs]"
I0423 05:56:54  5113 file_util.go:19] Folder /var/lib/pgsql/1 Permission: -rwxr-xr-x
I0423 05:56:54  5113 master_server.go:76] Volume Size Limit is 30000 MB
I0423 05:56:54  5113 master.go:87] Start Seaweed Master 30GB 1.30 at 0.0.0.0:9333
I0423 05:56:54  5113 raft_server.go:44] Starting RaftServer with 10.233.47.61:9333
I0423 05:56:54  5113 raft_server.go:48] Peers Change: [] => [10.233.47.61:9333 10.233.47.59:9333 10.233.47.60:9333]
I0423 05:56:54  5113 raft_server.go:84] current cluster leader: 
I0423 05:56:54  5113 master.go:114] Start Seaweed Master 30GB 1.30 grpc server at 0.0.0.0:19333
```

```
[root@dev-tools-postgresql-patroni-96-2 ~]# ip a |grep eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    inet 10.233.47.59/24 brd 10.233.47.255 scope global dynamic eth0
[root@dev-tools-postgresql-patroni-96-2 ~]# weed -v="3" master -mdir="/var/lib/pgsql/1" -ip="10.233.47.59" -port="9333" -peers="10.233.47.61:9333,10.233.47.59:9333,10.233.47.60:9333"
I0423 05:56:55  1606 filer_server.go:100] Reading security.toml from 
I0423 05:56:55  1606 filer_server.go:103] Reading : Config File "security" Not Found in "[/root /root/.seaweedfs /etc/seaweedfs]"
I0423 05:56:55  1606 file_util.go:19] Folder /var/lib/pgsql/1 Permission: -rwxr-xr-x
I0423 05:56:55  1606 master_server.go:76] Volume Size Limit is 30000 MB
I0423 05:56:55  1606 master.go:87] Start Seaweed Master 30GB 1.30 at 0.0.0.0:9333
I0423 05:56:55  1606 raft_server.go:44] Starting RaftServer with 10.233.47.59:9333
I0423 05:56:55  1606 raft_server.go:48] Peers Change: [] => [10.233.47.61:9333 10.233.47.59:9333 10.233.47.60:9333]
I0423 05:56:55  1606 raft_server.go:71] Initializing new cluster
I0423 05:56:55  1606 raft_server.go:84] current cluster leader: 10.233.47.59:9333
I0423 05:56:55  1606 master_server.go:115] [ 10.233.47.59:9333 ] I am the leader!
I0423 05:56:55  1606 master.go:114] Start Seaweed Master 30GB 1.30 grpc server at 0.0.0.0:19333
```

```
[root@dev-tools-postgresql-patroni-96-3 ~]# ip a | grep eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    inet 10.233.47.60/24 brd 10.233.47.255 scope global dynamic eth0
    inet 10.233.47.62/24 scope global secondary eth0

[root@dev-tools-postgresql-patroni-96-3 ~]# weed -v="3" master -mdir="/var/lib/pgsql/1" -ip="10.233.47.60" -port="9333" -peers="10.233.47.61:9333,10.233.47.59:9333,10.233.47.60:9333"
I0423 05:56:58 31632 filer_server.go:100] Reading security.toml from 
I0423 05:56:58 31632 filer_server.go:103] Reading : Config File "security" Not Found in "[/root /root/.seaweedfs /etc/seaweedfs]"
I0423 05:56:58 31632 file_util.go:19] Folder /var/lib/pgsql/1 Permission: -rwxr-xr-x
I0423 05:56:58 31632 master_server.go:76] Volume Size Limit is 30000 MB
I0423 05:56:58 31632 master.go:87] Start Seaweed Master 30GB 1.30 at 0.0.0.0:9333
I0423 05:56:58 31632 raft_server.go:44] Starting RaftServer with 10.233.47.60:9333
I0423 05:56:58 31632 raft_server.go:48] Peers Change: [] => [10.233.47.61:9333 10.233.47.59:9333 10.233.47.60:9333]
I0423 05:56:58 31632 raft_server.go:84] current cluster leader: 
I0423 05:56:58 31632 master.go:114] Start Seaweed Master 30GB 1.30 grpc server at 0.0.0.0:19333
```

**Comment by chrislusf** [comment]
-ip="10.233.47.61" is correct. do not include port number.

**Comment by chrislusf** [comment]
btw: -v="3" should be -v=3

**Comment by chrislusf** [comment]
assume the problem is resolved.
